### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by vynsynt** [GoogleChrome/lighthouse#2536] opened 2017-06-19 15:40 UTC
**Initial URL**: about:blank
**Chrome Version**: 61.0.3135.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@a990af190304be5bf38b120799c594df5a293518/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@a990af190304be5bf38b120799c594df5a293518/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-06-19 16:07
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2362

**Closed by ebidel** 2017-06-19 16:07 UTC
