### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by tghelere** [GoogleChrome/lighthouse#3475] opened 2017-10-04 19:50 UTC
**Initial URL**: http://localhost:8080/top
**Chrome Version**: 61.0.3163.100
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-10-06 18:53
thanks for filing @tghelere! dupe of #2174

**Closed by patrickhulce** 2017-10-06 18:53 UTC
Labels: duplicate
