### ISSUE TITLE
Error: Unknown formatter: url-list

### ISSUE THREAD

**Issue by paulsmith** [GoogleChrome/lighthouse#2403] opened 2017-05-31 03:25 UTC
Ran lighthouse CLI (version 2.0.0) on https://www.adhocteam.us/ Output report as JSON, copy/paste as [Gist](https://gist.github.com/paulsmith/ee183b4b566a747d4f5ba63a9cca98e2).

Opened [Lighthouse report viewer](https://googlechrome.github.io/lighthouse/viewer/) (in Chrome Version 58.0.3029.110 (64-bit)
on macOS 10.12.5), pasted Gist URL, got following error message and stack trace:

``` 
⚠️ Error: Unknown formatter: url-list

Error: Unknown formatter: url-list
    at Function.t.getByName (https://googlechrome.github.io/lighthouse/viewer/src/main.js:2:9830)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12833
    at Array.forEach (native)
    at e._registerFormatters (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12753)
    at e.generateHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:13036)
    at t.replaceReportHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:25936)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:25301
    at anonymous

**Comment by ebidel** [comment] 2017-05-31 03:42
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2338

**Closed by ebidel** 2017-05-31 03:42 UTC
