### ISSUE TITLE
Lighthouse never finishes on Debian 4.9

### ISSUE THREAD

**Issue by Serkan-devel** [GoogleChrome/lighthouse#4834] opened 2018-03-21 16:14 UTC
Lighthouse only keeps loading and doesn't respond, no matter which setting was selected before and it's still loading without any indication of progress. How long does it usually take because I'm able to run Minecraft on this PC

![auswahl_039](https://user-images.githubusercontent.com/16866642/37721769-a8ebd6e4-2d2a-11e8-855c-cb32f8abd568.png)

Chromium version
<pre>
Chromium:	64.0.3282.119 (Entwickler-Build) built on Debian 9.3, running on Debian 9.4 (64-Bit)
Überarbeitung:	2ba93af511033c75c55cac08672b808e2c3fbe71-
Betriebssystem:	Linux
JavaScript:	V8 6.4.388.40
Flash:	(Deaktiviert)
User-Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
Befehlszeile	/usr/lib/chromium/chromium --show-component-extension-options --ignore-gpu-blacklist --no-default-browser-check --disable-pings --media-router=0 --enable-remote-extensions --flag-switches-begin --enable-tab-audio-muting --flag-switches-end
Ausführbarer Pfad:	/usr/lib/chromium/chromium
Profilpfad:	/home/user/.config/chromium/Default
</pre>

Linux version: Linux Kachel 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

**Comment by patrickhulce** [comment] 2018-03-21 16:18
Thanks for reporting @Serkan-devel! This looks like a dupe of #2627, we'll post updates there.

**Closed by patrickhulce** 2018-03-21 16:18 UTC
