### ISSUE TITLE
finalUrl is incorrect

### ISSUE THREAD

**Issue by justlauzadis** [GoogleChrome/lighthouse#13697] opened 2022-02-23 08:01 UTC
### What happened?

I am writting tests and I wanted to add assertion that finalUrl is as expected, i.e. no redirects happen and we are auditing the expected page. However, after running an audit in a page A which redirects to page B (due to missing/misconfigured authorization) it seems that both requestedUrl and finalUrl in audit result JSON return page A.

UPDATE:
Finally was able to reproduce using a sample from https://codesandbox.io/s/zealous-bird-qok15g?file=/src/App.tsx
Just run an audit for https://qok15g.csb.app/route-one - it redirects to https://qok15g.csb.app/route-two, but audit result still shows the following:

"requestedUrl": "https://qok15g.csb.app/route-one",
"finalUrl": "https://qok15g.csb.app/route-one",

### What did you expect?

I expected requestedUrl to refer to page A, and finalUrl - page B.

UPDATE:
Regarding example from https://qok15g.csb.app/route-one, I was expecting the following:

"requestedUrl": "https://qok15g.csb.app/route-one",
"finalUrl": "https://qok15g.csb.app/route-two",

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.4.0

### Chrome Version

98.0.4758.102

### Node Version

14.17.6

### OS

Windows

**Comment by adamraine** [comment] 2022-02-23 17:02
Are you able to provide the URLs where this is happening or maybe some example setup that can reproduce this?

**Comment by justlauzadis** [comment] 2022-02-24 10:02
Tried with on some public websites, but all of them resulted in expected behavior, i.e.:

  "requestedUrl": "https://www.imdb.com/registration/accountsettings",
  "finalUrl": "https://m.imdb.com/registration/signin?u=https%3A%2F%2Fm.imdb.com%2Fregistration%2Faccountsettings",
  
I cannot disclose the system we are developing, but it feels like it is related to the nature of single page application and how it changes route in application code once it recognizes that authorization is invalid/missing.

I will still try to find out or to compose some working example to reproduce the issue.

**Comment by adamraine** [comment] 2022-02-24 16:44
> However, after running an audit in a page A which redirects to page B

Is this a SPA redirect (e.g. using `history.pushState`)?

**Comment by justlauzadis** [comment] 2022-02-25 09:42
Finally was able to reproduce using a sample from https://codesandbox.io/s/zealous-bird-qok15g?file=/src/App.tsx
Just run an audit for https://qok15g.csb.app/route-one - it redirects to https://qok15g.csb.app/route-two, but audit result still shows the following:

  "requestedUrl": "https://qok15g.csb.app/route-one",
  "finalUrl": "https://qok15g.csb.app/route-one",

Updating the original issue details as well.

**Comment by adamraine** [comment] 2022-02-25 17:24
This is expected because the redirect is a "soft" redirect meaning the URL is updated with `history.pushState` instead of performing a "hard" navigation that actually makes a network request to the destination URL. Lighthouse only considers the latter type of navigation for `finalUrl`.

I don't think we need to keep it that way though. I'm going to close this as it's WAI, but I'm working on a proposal to change this.

**Closed by adamraine** 2022-02-25 17:24 UTC
Labels: bug, needs-more-info, needs-priority
