### ISSUE TITLE
First interactive and consistently interactive order of magnitude slower

### ISSUE THREAD

**Issue by rwwagner90** [GoogleChrome/lighthouse#3428] opened 2017-09-27 18:54 UTC
It seems that my site, which is an Ember app, all the sudden went from like 3-4 seconds first interactive to 10-15 seconds, which gives me an awful score. Any ideas why this is happening all the sudden? My site is https://shipshape.io

**Comment by patrickhulce** [comment] 2017-09-27 20:19
@rwwagner90 I'm unable to reproduce this 10-15 second time result for that site. How are you running Lighthouse? Can you capture a trace so we can take a look? Run the CLI with the `--save-assets` flag, the .trace.json file is of interest.

`lighthouse --save-assets https://shipshape.io`

**Comment by rwwagner90** [comment] 2017-09-28 19:55
@patrickhulce I'm just running it in my browser. In my last run first interactive was 11.3 seconds. Here is a screenshot:

<img width="843" alt="screen shot 2017-09-28 at 3 54 46 pm" src="https://user-images.githubusercontent.com/2640861/30987541-68c27242-a465-11e7-9455-c6d9e52c35f9.png">

**Comment by patrickhulce** [comment] 2017-09-28 19:59
Have you recently installed any extensions or antivirus that might be interfering with your pages? This is the most common case of unexplained increases in metric values. 

Again though, it's difficult to say more without a trace. If you're willing to install the CLI and gather a trace using the command above, we can offer more insight.

**Comment by rwwagner90** [comment] 2017-09-28 20:27
[shipshape.io_2017-09-28_16-16-59-0.trace.json.zip](https://github.com/GoogleChrome/lighthouse/files/1342228/shipshape.io_2017-09-28_16-16-59-0.trace.json.zip)

It does seem to be faster outside of my browser, but 7.4 seconds is still a pretty long first interactive time. I am pretty sure it used to be 3-4 seconds.

You mentioned some of the bottlenecks previously, any tips on improving them? I was okay with 3-4 seconds, but 7+ is too slow.

**Comment by patrickhulce** [comment] 2017-09-28 20:56
Ah! Yes, this trace lines up with what I saw as well so perhaps an extension is adding time in the DevTools case.

My specific advice for your site is to try and reduce the size of your initial `app-[hash].js` bundle. It's quite large and takes nearly ~3.6s to download and another ~1.8s to evaluate. To get this down you'll likely need to defer some of the work you're doing or at least try to limit it. This is a [good article](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-2-page-load-performance-33b932d97cf2) that talks about code splitting with React and Webpack. It's not all applicable since I assume you're using ember based on your site, but the general principles are all good lessons. I don't know much about ember, but it looks like there might be similar concepts available to you? https://github.com/duizendnegen/ember-cli-lazy-load

It also looks like your Google analytics script is added by your bundle which means it is discovered and downloaded fairly late. You might consider inlining the GA snippet in your HTML or [preloading](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) it instead to shave off ~1s.

**Comment by rwwagner90** [comment] 2017-09-29 18:55
@patrickhulce thanks for the tips! Removing ember-metrics and using GA manually myself did shave about 1 second off my load time, which is great 🎉 . I'm still around 6 seconds now though, which still seems pretty high. I'm not sure how much splitting up of the app.js I can actually do, so I may just need to look through my code and see if there are things I can cut down the size of to improve things.

**Comment by patrickhulce** [comment] 2017-09-29 19:19
Glad to hear it! 

I'm going to go ahead and close this issue for now, but if you find out what's causing any discrepancies feel free circle back around to let us know.

**Closed by patrickhulce** 2017-09-29 19:19 UTC
Labels: needs-more-info
