### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by laimonas** [GoogleChrome/lighthouse#2745] opened 2017-07-26 07:44 UTC
**Initial URL**: http://madingasvente.lt/
**Chrome Version**: 60.0.3112.78
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-07-26 19:14
dupe of #1091

**Closed by patrickhulce** 2017-07-26 19:14 UTC
