### ISSUE TITLE
GatherRunner:error no document request found <URL>

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3781] opened 2017-11-08 09:33 UTC
I run a simple test on my application from command prompt by the following query from the command prompt,
query :  lighthouse https://<url>/ims/#/login
Output :
C:\Users\jmallick>lighthouse https://<url>/ims/#/login
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +2ms
  ChromeLauncher Waiting for browser...√ +506ms
  status Initializing. +595ms
  status Loading page & waiting for onload URL, Viewport, ViewportDimensions, Th
emeColor, Manifest, ChromeConsoleMessages, ImageUsage, Accessibility, EventListe
ners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, Optimiz
edImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFir
stPaint, WebSQL +328ms
  statusEnd Loading page & waiting for onload +22s
  status Retrieving trace +1ms
  status Retrieving devtoolsLog and network records +5s
  status Retrieving: URL +15ms
  status Retrieving: Viewport +2ms
  status Retrieving: ViewportDimensions +2ms
  status Retrieving: ThemeColor +1ms
  status Retrieving: Manifest +2ms
  status Retrieving: ChromeConsoleMessages +0ms
  status Retrieving: ImageUsage +1ms
  status Retrieving: Accessibility +6ms
  status Retrieving: EventListeners +75ms
  status Retrieving: AnchorsWithNoRelNoopener +104ms
  status Retrieving: AppCacheManifest +1ms
  status Retrieving: DOMStats +2ms
  status Retrieving: JSLibraries +5ms
  status Retrieving: OptimizedImages +8ms
  status Retrieving: PasswordInputsWithPreventedPaste +328ms
  status Retrieving: ResponseCompression +2ms
  status Retrieving: TagsBlockingFirstPaint +4ms
  status Retrieving: WebSQL +3ms
  status Loading page & waiting for onload ServiceWorker, Offline, StartUrl +809
ms
  statusEnd Loading page & waiting for onload +67ms
  status Retrieving devtoolsLog and network records +20ms
  status Retrieving: ServiceWorker +2ms
  status Retrieving: Offline +1ms
  status Retrieving: StartUrl +6ms
  status Loading page & waiting for onload HTTPRedirect, HTMLWithoutJavaScript +
309ms
  Driver:warn Timed out waiting for page load. Moving on... +30s
  statusEnd Loading page & waiting for onload +2ms
  status Retrieving devtoolsLog and network records +0ms
  GatherRunner:error no document request found http://<url>/im
s/#/login +1ms
  status Disconnecting from browser... +0ms
  ChromeLauncher Killing Chrome instance 17184 +4ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)

C:\Users\jmallick>

**Comment by vinamratasingal** [comment] 2017-11-08 19:06
Hi Jyoti- this is a duplicate of #1978. Closing this out to carry over the discussion there :)

**Closed by vinamratasingal** 2017-11-08 19:06 UTC
