### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by w3review** [GoogleChrome/lighthouse#2834] opened 2017-08-03 04:51 UTC
**Lighthouse Version**: 2.3.0
**Chrome Version**: 59.0.3071.115
**Initial URL**: http://localhost:4200/assets/icons
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14109:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14534:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14559:25)
    at <anonymous>
```

**Comment by wardpeet** [comment] 2017-08-04 08:43
@w3review do you get this issue often?

Is there a way we can reproduce this bug?

**Comment by ebidel** [comment] 2017-08-08 21:29
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-08-08 21:29 UTC
