### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by adavis0000** [GoogleChrome/lighthouse#3266] opened 2017-09-06 18:47 UTC
**Initial URL**: https://vintageking.com/
**Chrome Version**: 60.0.3112.113
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@95c454326a7a3153e984e50a4719924968490717/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ev1stensberg** [comment] 2017-09-08 07:38
Thanks for submitting an issue @adavis0000 ! Duplicate of #1091, so let's nest the identical issues there!

**Comment by patrickhulce** [comment] 2017-09-08 16:11
@ev1stensberg thanks for being vigilant! We actually have a bot that can take care of these for us though if there is no additional information added after a few days :)

**Closed** 2017-09-08 16:12 UTC
Labels: duplicate

**Comment by ev1stensberg** [comment] 2017-09-09 08:08
@patrickhulce Gotcha! Nice with some human response too, once in a while :rocket:
