### ISSUE TITLE
[Question] Largest Contentful Paint element shows WRS Protocol error

### ISSUE THREAD

**Issue by Bizotics-Dev** [GoogleChrome/lighthouse#10958] opened 2020-06-14 17:29 UTC
![lcp-error](https://user-images.githubusercontent.com/34595045/84599837-9ebf0b00-ae92-11ea-8b75-21d48443ab5f.PNG)

In diagnostics section 
Largest Contentful Paint element shows WRS Protocol error: "DOM.resolveNode: No node with given id found" 

can you explain it why it occurs , and same error is given for Avoid large layout shifts

**Comment by connorjclark** [comment] 2020-06-14 19:11
We may have fixed this for next version. URL?

**Comment by patrickhulce** [comment] 2020-06-14 22:35
Ya, this is almost certainly a duplicate of #10893 fixed by #10877

**Comment by Bizotics-Dev** [comment] 2020-06-15 04:52
Thanks

**Closed** 2020-06-15 05:02 UTC
Labels: needs-priority
