### ISSUE TITLE
'Unable to retrieve manifest' when manifest file is available and valid

### ISSUE THREAD

**Issue by kimixu717** [GoogleChrome/lighthouse#2576] opened 2017-06-23 03:53 UTC
https://pwa.banggood.com/manifest.json
Audit error: Required StartUrl gatherer encountered an error: Unable to retrieve manifest at https://pwa.banggood.com/manifest.json.

Lighthouse shows this error, but this json file is avaliable and it is a valid json file. We can't fix this error ,so help me fix it.

**Comment by patrickhulce** [comment] 2017-06-23 18:04
This seems to happen because the manifest is not retrievable when there is no network connection.

@wardpeet this seems like a bug, but was this the intended behavior? I seem to remember a discussion around this

**Comment by kimixu717** [comment] 2017-06-26 02:52
@patrickhulce . Lighthouse report error is not because network error,  you can test www.pwa.banggood.com , it just report 'Unable to retrieve manifest', but you can open 'https://pwa.banggood.com/manifest.json' in the meantime

**Comment by patrickhulce** [comment] 2017-06-26 17:20
Yes, I understand @kimixu717, but Lighthouse turns off network connectivity during one of our loads of the page, and the manifest is not retrievable while we are offline (it does not appear to be cached by your service worker). This is likely our bug as it seems like we should try to fetch the manifest file while we are online.

**Comment by jeffposnick** [comment] 2018-02-27 19:31
Precaching `manifest.json` in a service worker amounts to wasted bytes, since browsers maintain their own cache of this metadata. 

Anecdotally, this is causing Lighthouse scores for web apps using [Workbox](https://developers.google.com/web/tools/workbox/) to generate their service worker to be artificially lower. Workbox takes steps to automatically exclude `manifest.json` from the list of URLs to precache, and an offline fetch for `manifest.json` will fail by default.

CC: @prateekbh @gauntface @addyosmani @owencm

**Comment by addyosmani** [comment] 2018-02-28 19:15
@wardpeet Could you spend some time investigating a fix for this? One possible solution would be requesting the manifest.json first and then taking the network offline. As it's impacting the score of any sites using Workbox, it would be great if we could get this addressed soon.

**Comment by gauntface** [comment] 2018-02-28 19:25
@prateekbh also mentioned this may be the cause of false negatives for lighthouse claiming the start url is no cached when it is

**Comment by prateekbh** [comment] 2018-02-28 19:32
Here are the repro URLs:

buggy app(without cached manifest.json): https://preact-cli-workbox-buggy.surge.sh/

with cached manifest.json: https://preact-cli-workbox.surge.sh/

the PWA report for both have a 9 point difference.

**Comment by wardpeet** [comment] 2018-02-28 19:37
Thanks for sharing I'll have a look!

**Comment by wardpeet** [comment] 2018-02-28 21:55
The issue is indeed that `Page.getAppManifest()` in the protocol doesn't return a manifest when it's not cached in offline mode. I can get an url of the manifest and fetch the url using nodejs and get manifest data. The sad part is this does not work in devtools and/or extension as devtools suffer from CORS and the extension doesn't get an manifest url.

Another approach i'll look at but haven't tested is just trying to do everything in the afterpass and try to enable the network, get the manifest and disable it again and do the rest of the logic. (might break other case 🙄 )

**Closed** 2018-03-22 01:39 UTC
Labels: P1, bug, needs-investigation

**Comment by nunoperalta** [comment] 2018-04-08 18:13
The same happening to me. Initially, I thought this would be because of "manifest.json" not being cached, but even after caching, I get the same error.

This issue thread was closed without being fixed..

**Comment by jannaee** [comment] 2018-08-08 18:38
So, what is the propose solution when encountering this issue? I'm working on a PWA and have created the manifest perfectly to the specs. What next?

**Comment by EddieOne** [comment] 2021-03-26 00:58
For me it works here https://nl.y8.com/ but not here https://www.y8.com/
