### ISSUE TITLE
Using specific Chrome profile

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#8957] opened 2019-05-15 02:30 UTC
Working on docs for authenticated usages of LH (#1418). Want to make sure I'm not overlooking something - unclear if this is meant to work already.

Looks like our usage of chrome-launcher always makes a new user data dir, and thus a new profile, and deletes it every run. To actually use an existing profile I think we need to pass "userDataDir: false" to ChromeLauncher.launch.

Was it expected that just using `chrome-flags="--profile-directory=..."` would work? With existing LH, I think you'd need to spin up Chrome yourself and pass a port to LH?

**Comment by patrickhulce** [comment] 2019-05-15 03:49
> With existing LH, I think you'd need to spin up Chrome yourself and pass a port to LH?

That's my understanding if you wanted to use your own Chrome profile, yes.

It's been optimized for the common cold load case for sure rather than the authenticated flow for sure, but the good news is we own both if that's something we wanted to change :) (i.e. if `--chrome-flags` has `--user-data-dir` pass the right chrome launcher flags)

**Comment by Hoten** [comment] 2019-05-15 17:36
Thanks for clearing that up.

> (i.e. if --chrome-flags has --user-data-dir pass the right chrome launcher flags)

I'll see if that works well.

**Comment by connorjclark** [comment] 2019-08-30 16:48
Opening because we should do what Patrick says.

**Comment by connorjclark** [comment] 2019-08-30 22:39
fyi finding the name of the profile directory is an annoying experience: https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/

must look at `chrome://version`.

**Comment by brendankenny** [comment] 2022-01-11 20:50
@connorjclark are you still interested in this? Should we move this to `chrome-launcher`?

**Comment by paulirish** [comment] 2022-08-23 19:37
dupe of https://github.com/GoogleChrome/chrome-launcher/issues/172

**Closed by paulirish** 2022-08-23 19:37 UTC
Labels: needs-priority
