### ISSUE TITLE
Lighthouse cannot audit SAP UI5 applications

### ISSUE THREAD

**Issue by xiaowang03** [GoogleChrome/lighthouse#10309] opened 2020-02-07 17:38 UTC
SAP UI5 is a library for building SAP Web applications. See: https://sapui5.hana.ondemand.com/.
When we try to audit SAP UI5 applicatiosn we always get the error: "Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)".
Example of SAP UI5 application: https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html

**Comment by connorjclark** [comment] 2020-02-07 18:17
Please fill out that form you deleted. Where / how are you running Lighthouse?

**Comment by xiaowang03** [comment] 2020-02-07 18:28
@connorjclark 
Sorry, where is the form?
Where: I use Audit directly in Chrome browser for Windows Version 80.0.3987.87.
How: I open the URL. I set the device mode to Desktop. I click in "Generate report".

**Comment by paulirish** [comment] 2020-02-07 18:28
I ran lighthouse against https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html and didn't get a NO_FCP error. 

Do you get an error when testing this page?

Also note that you can't change tabs while lighthouse is running. it needs to stay in the foreground.

**Comment by xiaowang03** [comment] 2020-02-07 19:05
@paulirish 
Which version of Chrome are you using? It is on Windows or Mac?
I don't change tab. I only have one tab. I click on "Generate Report" then wait.
I already checked many of SAP applications built with SAP UI5. 
It does not work, except for one.
Could you double check?

**Comment by paulirish** [comment] 2020-02-07 19:35
@xiaowang03 okay thanks for that information. :)

i'm on mac.

![image](https://user-images.githubusercontent.com/39191/74059679-58fead00-499d-11ea-8784-aebcff80c441.png)

I tested with both Chrome 79 and Chrome 80 and both look good here.

**Comment by xiaowang03** [comment] 2020-02-07 19:40
@paulirish 
I tried again.
- With Chrome 80 on Windows (laptop): it does not work.
- With Chrome 79.0.3945.130 on Windows (desktop): it works on Mobile mode. It does not work on Desktop mode.

**Comment by paulirish** [comment] 2020-02-07 19:49
@xiaowang03 this is interesting. thanks for all the info.

unfortunately we can't debug the situation much more from devtools, but we can from the Lighthouse CLI.

https://github.com/GoogleChrome/lighthouse#using-the-node-cli

basically. you need node installed, then you can run this command:

```sh
lighthouse https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html --only-categories=performance --emulated-form-factor=desktop --gather-mode
```

this will only collect necessary data from the browser, but not evaluate, so it shouldn't throw an error.  but the collected data is saved to a local `./latest-run` folder. I'm interested in the contents of those files. So perhaps you could zip them up and share them to me.

There shouldn't be anything personally identifying in there, especially since it's using a completely brand new chrome profile.

if you dont want to post the zip in github you can email it to me (paulirish @ google) 

this is a bit of work, but i appreciate you debugging this with me. :) thanks!

**Comment by xiaowang03** [comment] 2020-02-07 20:54
Sure, I'll try it asap.
BTW, Chrome on my desktop machine is upgraded to v80.
Still, the desktop mode does not work, but the mobile version works.
There is a different behavior on laptop and desktop...

**Comment by patrickhulce** [comment] 2020-02-25 21:39
Hey @xiaowang03 we're going to go ahead and close this since we can't reproduce or debug without additional data. Feel free to come back with the data to reopen.

**Closed by patrickhulce** 2020-02-25 21:39 UTC
Labels: needs-more-info
