### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by kgdev** [GoogleChrome/lighthouse#2316] opened 2017-05-19 22:52 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 58.0.3029.110
**URL**: https://connect-local.unity.com:8443/p
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13554:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14639:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14665:18)
    at <anonymous>```

**Comment by patrickhulce** [comment] 2017-05-20 00:04
dupe of #1834

**Closed by patrickhulce** 2017-05-20 00:04 UTC
Labels: duplicate
