### ISSUE TITLE
Extension Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/lighthouse#1215] opened 2016-12-21 16:56 UTC
**Lighthouse Version**: 1.3.0
**Chrome Version**: 56.0.2924.28
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.DateNowUse.usage.filter.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1046:39)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1045:48)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11365:20)```

**Comment by ebidel** [comment] 2016-12-21 17:52
Can you provide us what page you were testing and a list of installed chrome extensions? @wardpeet is investigating. Please report over on #1194 .

Dupe of #1194

**Closed by ebidel** 2016-12-21 17:52 UTC
Labels: duplicate
