### ISSUE TITLE
Ability to Change Lighthouse Settings -- Network & Device

### ISSUE THREAD

**Issue by dsills22** [GoogleChrome/lighthouse#2893] opened 2017-08-08 21:06 UTC
Lighthouse performance audit ran from the Lighthouse Chrome extension seems to only run with these settings for me: 

Device Emulation Nexus 5X: Enabled
Network Throttling 562.5ms RTT, 1.4Mbps down, 0.7Mbps up: Enabled
CPU Throttling 4x slowdown: Enabled

Can we not change these settings? Opening Chrome (60) development tools and changing the Network Throttling setting causes Lighthouse to complain: "You probably have DevTools open. Close DevTools to use Lighthouse". Then closing the developer tab and running the audit shows that it is using the same settings as shown above (re-opening the developer tab also indicates the Network Throttling setting was reverted to No Throttling). Clicking the Lighthouse Options button only lets me check which audits I want to run whereas I would like a way to change the runtime settings for an audit.

Similarly, running a performance audit in Chrome 60 from developer tools only runs with Nexus5X device simulation and seems to have the same Network Throttling. I don't see how to view the runtime settings from within the Chrome audit though.

**Comment by ebidel** [comment] 2017-08-08 21:21
This is something we need to support. Currently, there's no way to change the runtime settings in DevTools or the Chrome extension. Even if you set your own in DevTools, Lighthouse uses the Devtools Protocol to set [its defaults](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/emulation.js) before the run.

If you're using the CLI, you can disable emulation altogether (see https://github.com/GoogleChrome/lighthouse/issues/2864#issuecomment-320735994), but that's about it. 

Marking this as a dupe of https://github.com/GoogleChrome/lighthouse/issues/2838

**Closed by ebidel** 2017-08-08 21:21 UTC

**Comment by dsills22** [comment] 2017-08-08 21:38
Cool, thanks @ebidel
