### ISSUE TITLE
Cannot test a site that required login

### ISSUE THREAD

**Issue by woisme** [GoogleChrome/lighthouse#1994] opened 2017-04-11 10:19 UTC
Try to test my Polymer site after login. Just tests the login page.

**Comment by patrickhulce** [comment] 2017-04-11 16:04
dupe of #1418, feel free to add the specifics of your authentication situation there for us to consider. Also, looks like the original PR never got finished if you'd want to take a stab :)

**Closed by patrickhulce** 2017-04-11 16:04 UTC
