### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by qiyunbao** [GoogleChrome/lighthouse#2021] opened 2017-04-17 06:09 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: http://act.mogujie.com/hxzycx0412?acm=3.mce.1_10_1bn70.36344.0.kJzwdqh1XdY0h.m_271610-mf_4537_383670-idx_1-mfs_5

**Comment by ebidel** [comment] 2017-04-17 15:34
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-04-17 15:34 UTC
