### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by thangman22** [GoogleChrome/lighthouse#2384] opened 2017-05-29 08:09 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 60.0.3107.4
**URL**: https://pwa.online.hackathon.in.th/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11604:25)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)```

**Comment by ebidel** [comment] 2017-05-29 16:43
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-05-29 16:43 UTC
