### ISSUE TITLE
Extension Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by dharanee86** [GoogleChrome/lighthouse#2632] opened 2017-07-03 06:43 UTC
**Lighthouse Version**: 2.2.1
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://ilovecoding.org/
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9693:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment] 2017-07-05 05:06
dupe of #2174

**Closed by patrickhulce** 2017-07-05 05:06 UTC
