### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by TipuAliKhan** [GoogleChrome/lighthouse#4238] opened 2018-01-12 09:37 UTC
**Initial URL**: https://tipu.nowfloats.com/index.html?v=25
**Chrome Version**: 63.0.3239.132
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```

**Comment by ev1stensberg** [comment] 2018-01-13 18:41
This is a dupe of #2448, let's resume the discussion there!

**Closed** 2018-01-18 17:03 UTC
Labels: duplicate
