### ISSUE TITLE
Speed index does not match actual visual results

### ISSUE THREAD

**Issue by kkmuffme** [GoogleChrome/lighthouse#10079] opened 2019-12-08 11:13 UTC
#### Provide the steps to reproduce
1. Run LH on the destination url of: https://bit.ly/38imLrn
 

#### What is the current behavior?
You will get something like:
![image](https://user-images.githubusercontent.com/11071985/70388467-6eae2100-19b2-11ea-8140-23583b7a9efa.png)

Where the page is visibly rendered in the second screenshot and there is no change happening anymore until the last screenshot.
So where is it getting the 7.1s from?

#### What is the expected behavior?
fix that the Speed index matches the actual visual results the user can see (as it's supposed to be)
or more information on what exactly it has issues with in the speed index

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.2.0
* Chrome version: 78.0.3904.108
* Operating System: Win 10

**Comment by patrickhulce** [comment] 2019-12-08 14:49
Thanks for filing @kkmuffme! I'm not able to reproduce this issue though, anything else you might be able to share that could help? 

3/3 runs for me across different versions look more like...

![image](https://user-images.githubusercontent.com/2301202/70391120-554bab80-1997-11ea-99ce-376e6510e0ac.png)

**Comment by murali-krishnamoorthy** [comment] 2019-12-09 16:13
i have created somewhat related issues with regards to speed index - https://github.com/GoogleChrome/lighthouse/issues/10082

**Comment by kkmuffme** [comment] 2019-12-10 02:51
@patrickhulce 5 things come to my mind:
1) the numbers lighthouse reports are quite inconsistent (and are more like a lottery at this point it seems). I reran the test from various computers at the same location within a short timespan, as well as with some time difference and got vastly different results too.
So why your numbers are so different - only lighthouse knows (but check the points below)

E.g. exactly same screenshots completely different numbers:
![image](https://user-images.githubusercontent.com/11071985/70487412-8e9a2d80-1af5-11ea-84e6-08671ba252ff.png)

b) I used "Simulated Slow 4G, 4x CPU Slowdown" - perhaps the speed it "simulated" for you is different? Or my CPU (i5-7400, 4x 3.00GHz) is faster so the Slowdown doesn't match? 

2) it seems you are using a different lighthouse version? bc there is a "Largest Contentful Paint" in your screenshot, which doesn't exist for me.

3) perhaps some js/css was not in cache yet at the CDN from your location. Just open the page in private mode a 3-4 times to make sure it's (+js/css) is cached at a CDN location near you so we can compare

4) if you compare the numbers (e.g. First Contentful Paint/FCP) of Lighthouse 

Please let me know what I can contribute additionally (information you need, testing,...) to get this issue investigated & solved.

=== not sure if relevant ===

I am also consistently having an error for these 3 in the audit:
![image](https://user-images.githubusercontent.com/11071985/70487868-02890580-1af7-11ea-9903-356f430128b6.png)

**Comment by patrickhulce** [comment] 2019-12-10 16:09
Our two runs are very similar to each other, I'm just not sure how the first one in your original screenshot was produced.

> it seems you are using a different lighthouse version? bc there is a "Largest Contentful Paint" in your screenshot, which doesn't exist for me.

Yes that screenshot came from latest LH, but I also tested with the 5.2.0 and got a very similar result to your second screenshot there (which is also unlike that first screenshot).

> I am also consistently having an error for these 3 in the audit:

Chrome's internal tracing format changed which caused those errors, versions of LH 5.6.0+ should be fixed.

> Please let me know what I can contribute additionally (information you need, testing,...) to get this issue investigated & solved.

TBH, I'm not sure what there is here to fix yet. So far it seems as if that run in your first screenshot suffered from unfortunate [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md). If it's reproducible regularly for you, the only way forward would be collecting a trace of the run (produced by running Lighthouse from the command line with `--save-assets` flag or by click "View Trace" in DevTools and exporting the trace file from Performance panel). With comparison traces we can take a look at what's going on.

**Comment by kkmuffme** [comment] 2020-01-09 01:24
Sorry for the late reply, but the page had some major changes so I couldn't get a useful stable trace & also I wanted to check with the latest Chrome as that fixed some issues.
It seems the latest Chrome/lighthouse is a lot more reliable.

When clicking on the "View Trace" all numbers are showing for an unthrottled CPU, so it's hard to investigate what is slow when using the 4x CPU throttling.
Would it be possible to show the values Lighthouse had, instead of showing the unthrottled values?

**Comment by patrickhulce** [comment] 2020-01-09 03:48
> Would it be possible to show the values Lighthouse had, instead of showing the unthrottled values?

We've discussed this and intend to implement something along these lines, but tl;dr it's complicated (#9971)

**Comment by patrickhulce** [comment] 2020-04-28 20:19
We're deduping this into #9971 👍

**Closed by patrickhulce** 2020-04-28 20:19 UTC
Labels: needs-priority
