### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by jasonrhodes** [GoogleChrome/lighthouse#1961] opened 2017-04-04 02:34 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.98
**URL**: https://app.sparkpost.com/auth
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment] 2017-04-05 19:41
@jasonrhodes could you give us more feedback.

Did you run a trace and close it?

**Comment by jasonrhodes** [comment] 2017-04-07 02:09
Yes, I switched tabs originally and came back and it was still running, then it appeared to be running in all of my tabs, then I closed the window and now clicking the extension button gives me the error here.

**Comment by ebidel** [comment] 2017-04-07 16:15
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1961. @jasonrhodes I added that info over there. Thanks for reporting!

**Closed by ebidel** 2017-04-07 16:15 UTC
