### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by fullbacca** [GoogleChrome/lighthouse#2081] opened 2017-04-27 10:13 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: https://otakumode.com/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by stramel** [comment] 2017-04-27 12:34
Dupe of #1091

**Closed** 2017-04-27 14:43 UTC
