### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by kakyoin** [GoogleChrome/lighthouse#1478] opened 2017-01-17 01:51 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: http://quansou.demowx.uae.uc.cn/index.php
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11470:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12474:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12498:25)```

**Comment by ebidel** [comment] 2017-01-17 17:34
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2017-01-17 17:34 UTC
