### ISSUE TITLE
Check fail "Content not sized properly for the viewport" due to open dev tools

### ISSUE THREAD

**Issue by dcastil** [GoogleChrome/lighthouse#6095] opened 2018-09-23 14:27 UTC
#### Provide the steps to reproduce

1. Dock dev tools to side
2. Run LH on https://google.com
3. PWA check fail "Content not sized properly for the viewport" shows up
4. Dock dev tools to bottom
5. Rerun LH on same website
6. PWA check fail from step 3 disappears

Audit with dev tools docked to right side:
<img width="1920" alt="bildschirmfoto 2018-09-23 um 16 20 32" src="https://user-images.githubusercontent.com/31006608/45929115-833cff80-bf4d-11e8-9087-0728838628ac.png">

Audit with dev tools docked to bottom:
<img width="1920" alt="bildschirmfoto 2018-09-23 um 16 23 14" src="https://user-images.githubusercontent.com/31006608/45929120-8df79480-bf4d-11e8-88d5-16fe1c3bac29.png">

#### What is the expected behavior?

Audits shouldn't be dependent on the location of the dev tools and the check fail from step 3 shouldn't appear in this case.

#### Environment Information

* Affected Channels: DevTools
* Lighthouse version: 3.0.3
* Node.js version: 10.10.0
* Operating System: Mac OS High Sierra 10.13.6

**Comment by patrickhulce** [comment] 2018-09-23 15:11
Thanks for filing @dcastil! This is a dupe of #5558 and has a pending fix in #5893 :)

**Closed by patrickhulce** 2018-09-23 15:11 UTC

**Comment by Malvoz** [comment] 2019-03-08 16:50
@patrickhulce 

Unfortunately, this seems to be an issue again. I had devtools "docked to side" (while still having the device toolbar open), after running a desktop audit I recieved this warning:

![lighthouse-issue](https://user-images.githubusercontent.com/26493779/54042327-1c916280-41ca-11e9-9d63-5bf83379555c.png)

**Comment by patrickhulce** [comment] 2019-03-08 17:46
Thanks @Malvoz let's take this over to #5558.
