### ISSUE TITLE
Extension Error: No tabId set for sendCommand

### ISSUE THREAD

**Issue by Triverla** [GoogleChrome/lighthouse#5603] opened 2018-07-01 18:43 UTC
**Lighthouse Version**: 3.0.0
**Lighthouse Commit**: d6aa4416d7b60beb47207c476a674b0149e58675
**Chrome Version**: 69.0.3478.0
**Initial URL**: https://triverla.github.io/Currency-Converter/
**Error Message**: No tabId set for sendCommand
**Stack Trace**:
```
Error: No tabId set for sendCommand
    at Promise (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17254:15)
    at new Promise (<anonymous>)
    at ExtensionConnection._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17250:8)
    at Driver._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18585:25)
    at Object.clearAllNetworkEmulation (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:21414:15)
    at Driver.setThrottling (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18384:18)
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19011:14)
```

**Comment by patrickhulce** [comment] 2018-07-02 14:42
duplicate of #5595

**Closed by patrickhulce** 2018-07-02 14:42 UTC
