### ISSUE TITLE
plots: graph metrics over time (e.g. different lighthouse versions)

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#2413] opened 2017-05-31 22:54 UTC
The Lighthouse team wants to see how performance metrics have evolved over time as lighthouse has changed.

### Phase 1 - Plots over time locally
* This allows you to select multiple out folders and creates a comparison chart

### Phase 2 - Nightly plots
* Does a nightly run on master and records the artifacts (in Google Cloud Storage or GitHub gh-pages?)
* Link to a site that shows plots over time

Part of https://github.com/GoogleChrome/lighthouse/issues/1980

**Comment by patrickhulce** [comment] 2017-10-12 23:44
dupe of #3461

**Closed by patrickhulce** 2017-10-12 23:44 UTC
Labels: feature, P3
