### ISSUE TITLE
Offscreen image audit incorrectly reporting lazy-loaded images

### ISSUE THREAD

**Issue by mdiblasio** [GoogleChrome/lighthouse#6677] opened 2018-11-29 00:44 UTC
#### Provide the steps to reproduce

1. Run LH on https://oldnavy.gap.com/
2. View "Defer offscreen images" audit

#### What is the current behavior?
https://oldnavy.gap.com/ lazy-loads below-the-fold ("BTF") images ([example BTF image](https://oldnavy.gap.com/Asset_Archive/ONWeb/content/0016/352/058/assets/181126_013A_Gifting_mod8_S_US_image.jpg) that is lazy-loaded on homepage). 

The following LH reports incorrectly show lazy-loaded images in "defer offscreen images" audit. In addition, the above-the-fold images do not appear to render in timeline:

- [PageSpeed Insights (current version)](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Foldnavy.gap.com%2F)
- [web.dev (v4.0.0-alpha.1)](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://oldnavy.gap.com/#performance)

However, when run in CDT (v.3.0.3) and [via WebpageTest (v.4.0.0-alpha.2-3.2.1)](https://www.webpagetest.org/lighthouse.php?test=181129_WY_2d81dc8e63d6d6ab80ec91877eac229a&run=1#performance), this audit passes and ATF images render.

The same audit discrepancy exists for https://pwa.www.1800flowers.com/ when run from [web.dev](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://pwa.www.1800flowers.com/#performance) vs. [WPT](https://www.webpagetest.org/lighthouse.php?test=181127_RC_38adbd4e683517e11f8ff0e51ad8f82b&run=1#performance).

I did notice that [a change was made to offscreen images audit in v4.0.0-alpha.1](https://github.com/GoogleChrome/lighthouse/commit/71658c65a284a7fd954586d01b5be138811805d8#diff-a1f60c48a53d5112dca66b46c2de29d3). 

#### What is the expected behavior?
Offscreen images audit should pass as BTF images are lazy-loaded.

**Comment by h3d0** [comment] 2019-01-14 13:32
I'd like to confirm the problem.

The report ran for https://alpha.floralle.com.ua/: 
- https://builder-dot-lighthouse-ci.appspot.com/report.1547472388154.html

_Defer offscreen images_ lists a group of images. However when the same page is inspected using Chrome Dev Tools:

The only images that are loaded, are:

![image](https://user-images.githubusercontent.com/7346327/51115594-66387f00-1811-11e9-9009-d089a906481e.png)

The solution uses [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) and would not show any images until they emerge on the screen.

**Comment by bkowalk** [comment] 2019-07-09 20:07
Seeing the same Lighthouse issue on our site, and Pagespeed Insights won't recognize the lazy load as well, since it uses the same library. Definitely concerning since our Google AdWords rep is under the impression that Pagespeed Insights is now a weighted factor in search ranking! Hoping this can be fixed in Lighthouse as well as PI soon...

**Comment by andreasantonsson** [comment] 2019-07-12 10:19
I can confirm this as well. I've tried different solutions, both with and without `Intersection Observer`.

**Comment by johanlantz** [comment] 2019-08-01 16:15
I think I am seeing something similar. 
I have just updated a Prestashop store and the new theme is using lazy loading but lighthouse says  to defer images which are using lazy loading.

For instance, on [this page](https://givensa.com/es/escurridor-de-cubiertos-jumbo) there are 3 images in large format and 3 in small format and at least from what I can see in the code they are using a lazy loading plugin but Lighthouse says to defer them.

**Comment by ShacharAgam** [comment] 2019-09-02 08:39
currently still seeing it on a site im working on

**Comment by astolfivincent** [comment] 2019-10-08 20:27
Currently seeing this happening as well. Maybe my lazyloading scripts are loading/triggered before the `Time To Interactive (TTI)` event? https://developers.google.com/web/tools/lighthouse/audits/offscreen-images

**Comment by simonlayfield** [comment] 2019-11-01 09:38
I've stumbled across this issue too, and hoping for a solution.

**Comment by Julianatwave** [comment] 2019-11-04 14:58
Getting this on a WordPress site that uses WP Rocket plugin for lazy load. I can see that lazy load is working by looking in the Chrome Network tab, but Audit says no.

**Comment by rmertens** [comment] 2019-11-11 08:33
We're experiencing this as well.

**Comment by MatTeague** [comment] 2019-11-11 10:38
We are also having the same issue. I hope a fix will happen soon

**Comment by CKMacLeod** [comment] 2019-11-29 23:38
Yep - same here - still. Since this problem has been around for a year, I'm wondering if we'll just have to consider it may-never-fix and another thing to explain to clients inclined to treat Lighthouse/Page Speed Insights as definitive.

**Comment by tobidot** [comment] 2020-04-27 10:52
This is still the case, correct?
The test is mostly correct for me, but some images show up as failed seemingly randomly.
Restarting the test, 3 times out wich 1 time it showed an image that is lazy-loaded.

**Comment by patrickhulce** [comment] 2020-04-27 14:54
This is still the case in 5.6.0 but we intend to loosen this to 3 viewports in 6.0.0 (https://github.com/GoogleChrome/lighthouse/issues/10471)

**Comment by Monique011114** [comment] 2020-04-30 20:33
I'm seeing the same issue. Lighthouse is mostly correct for me too but this issue is giving me a bad performance score even though my images clearly are lazy-loaded. I wonder when this will be resolved.

**Comment by connorjclark** [comment] 2020-04-30 20:48
We're working on it. #10643

**Comment by jaxita47** [comment] 2020-05-04 18:36
That is great news this issue is being worked on! Do you have any idea yet as to when a fix might be released?

**Closed** 2020-05-07 22:38 UTC
Labels: P1.5, PSI/LR, bug, needs-investigation, web.dev

**Comment by rshackleton** [comment] 2020-05-11 10:59
Still seeing this issue on our site. An off-screen image is being reported, but only one of them, even though they're all deferred.

Has the #10643 PR been deployed so PSI is now using the updated checks or is it still in progress?

**Comment by patrickhulce** [comment] 2020-05-11 14:19
@rshackleton no it has not. Should happen later this month.

**Comment by rshackleton** [comment] 2020-05-12 11:42
@patrickhulce thanks for confirming, it will help us set expectations for clients on our side.

**Comment by panablue** [comment] 2020-05-13 18:09
Any good current examples of unrecognized lazy loading to see in action?

**Comment by GigaMick** [comment] 2020-05-13 21:09
> Any good current examples of unrecognized lazy loading to see in action?

@panablue - 2 images continue flagged on https://songbox.rocks despite them being appropriately setup for lazy loading.

**Comment by panablue** [comment] 2020-05-13 21:36
Thank you @GigaMick.

As established, PSI and the browser seem to disagree on the viewport threshold.

What's the relationship of this issue with `loading="lazy"` vs `IntersectionObserver` and `rootMargin` settings? Any current pure `IntersectionObserver` lazy loading setups with the same result to compare?

**Comment by Menark** [comment] 2020-05-19 14:02
@patrickhulce Has the #10643 PR been deployed so PSI is now using the updated checks or is it still in progress?

**Comment by patrickhulce** [comment] 2020-05-19 14:23
v6 with this fix is being officially released imminently. Keep your eye out for posts about the PSI deployment timeline :)

**Comment by violuke** [comment] 2020-05-26 11:59
@patrickhulce Do you know how imminently? We're still getting false positives on this. Thanks for your help.

**Comment by patrickhulce** [comment] 2020-05-26 15:25
It was released minutes after my comment.

PSI timeline is mentioned in the post https://web.dev/lighthouse-whats-new-6.0/

> Other Google services that leverage Lighthouse will get the update by the end of the month

**Comment by violuke** [comment] 2020-05-26 16:16
Thanks @patrickhulce, sorry I didn't know where to check the depoyment timeline. In that case:
1. There's still a pointer to this bug at https://web.dev/offscreen-images/ - just in case removing that has been forgotten.
2. When I check our [homepage](https://www.viovet.co.uk/) - I'm warned about some images which are lazy loaded via `loading="lazy"`. Can you help as to why? As an example `static2.viovet.co.uk/opt/s=kr,width=680,height=640/banners/1587565188-4463.png.webp` is listed on [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.viovet.co.uk%2F) but in the source of our page it does have the `loading="lazy"` tag. It's loaded via `srcset` so maybe that's related? Or maybe we're doing something wrong in which case any help you can offer would be very much appreciated. Here's the snippet as-per viewing source in a web browser:

```html
<img class="_desktop-visible _no-padding" loading="lazy" src="//static2.viovet.co.uk/opt/s=kr,width=340,height=320/banners/1587565188-4463.png.webp" srcset="//static2.viovet.co.uk/opt/s=kr,width=340,height=320/banners/1587565188-4463.png.webp 1x, //static2.viovet.co.uk/opt/s=kr,width=680,height=640/banners/1587565188-4463.png.webp 2x " alt="SL 25% off VioPet Food 2kg">
```

Thanks for your help.

**Comment by patrickhulce** [comment] 2020-05-26 16:23
PSI has not been updated yet.

> Other Google services that leverage Lighthouse will get the update by the end of the month

It's still May 26. If it's still happening June 1 feel free to bug the PSI team ;)

**Comment by violuke** [comment] 2020-05-26 16:26
Sorry for the misunderstanding. Thanks 👍

**Comment by johncarlson21** [comment] 2020-06-11 19:42
This is broken again, please re-open.

**Comment by patrickhulce** [comment] 2020-06-11 19:51
Please file a new bug report *with repro steps and environment information* then @johncarlson21. We have no idea if you're using the version of Lighthouse in which this should be fixed or if it's even the same root cause when that's all you say.
