### ISSUE TITLE
Audit reports post-decompression sizes for html documents.

### ISSUE THREAD

**Issue by mikesherov** [GoogleChrome/lighthouse#3588] opened 2017-10-17 16:13 UTC
Thanks for the great work on Lighthouse!

Running an audit inside Chrome, I see:

![image](https://user-images.githubusercontent.com/364532/31675790-aacdd578-b333-11e7-87ba-fc9b297d3bf6.png)

However, the actual transfer size of that html document was 55KB.

**Comment by mikesherov** [comment] 2017-10-17 16:20
I think this is actually a bug in devtools, see here: https://bugs.chromium.org/p/chromium/issues/detail?id=775540

Happy to keep open until that is confirmed. Thanks!

**Comment by patrickhulce** [comment] 2017-10-30 17:06
Thanks for tracking down root cause @mikesherov!

Confirmed we are awaiting a Chrome-side fix due to PlzNavigate changes 👍

**Comment by Hoten** [comment] 2018-11-26 21:15
@jakub-g Thanks for sharing that bug report. I did the repro steps in Chrome 70.0.3538.102 - the issue seems to still exist (even though the bug report says it was fixed in 63).

**Comment by Hoten** [comment] 2018-11-26 21:21
@mikesherov would you mind testing your site again with the newest Chrome?

**Comment by brendankenny** [comment] 2019-05-18 00:52
looks 👍 now

**Closed by brendankenny** 2019-05-18 00:52 UTC
Labels: DevTools, bug, chillin ❄
