### ISSUE TITLE
CSS Sprites did not need width and height

### ISSUE THREAD

**Issue by tobeana** [GoogleChrome/lighthouse#14407] opened 2022-09-23 12:58 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://analytik.news

### What happened?

The error message

"Image elements do not have explicit width and height"

is not relevant for pages using CSS sprites. It's impossible to do that.

### What did you expect?

This should not be an error

### What have you tried?

nothing

### How were you running Lighthouse?

web.dev

### Lighthouse Version

Emulated Moto G4 with Lighthouse 9.6.6

### Chrome Version

103

### Node Version

14.15.0

### OS

WIN 10

### Relevant log output

```shell
Image elements do not have explicit width and height
Set an explicit width and height on image elements to reduce layout shifts and improve CLS. Learn moreCLS
	
URL
Coherent Shared Services BV
<img src="/grafik/s265101014.png" alt="Coherent Shared Services BV" style="left:-0px;top:-0px;position:relative;">
```

**Comment by brendankenny** [comment] 2022-09-23 15:36
This isn't typically what's meant by "css sprite". This is a real image and (from what you've included from the report) appears that it can affect layout when the image loads. Is there a reason you don't have the width/height of the image or can explain more why it's not possible to include it?

**Comment by tobeana** [comment] 2022-09-23 15:49
For me a css sprite is a collection of images put into a single image: https://www.w3schools.com/css/css_image_sprites.asp

You then access the individual images via the coordinates.

We have implemented it some years ago to reduce the number of server hits. If you include width/height the layout of the page is completely destroyed.

**Comment by brendankenny** [comment] 2022-09-26 15:33
Right, but the copied log says the problem is

`<img src="/grafik/s265101014.png" alt="Coherent Shared Services BV" style="left:-0px;top:-0px;position:relative;">`

which would not be a css sprite? Unless there's additional CSS and the image element itself is not the problem.

However, CSS sprites (if we're talking `background-url` image with background positioning/clipping/etc) should always be excluded from that audit (see [audit source here](https://github.com/GoogleChrome/lighthouse/blob/da3c865d698abc9365fa7bb087a08ce8c89b0a05/core/audits/unsized-images.js#L119-L120)), so that shouldn't be the problem here unless there's a bug. If that is the issue and you have a way to reproduce, that would be greatly appreciated!

**Comment by connorjclark** [comment] 2022-10-24 21:50
Happy to look more with a repro. Closing for now.

**Closed by connorjclark** 2022-10-24 21:50 UTC
Labels: bug, needs-more-info, needs-priority

**Comment by connorjclark** [comment] 2022-10-24 22:00
BTW, our recommendation for css sprite is to _not_ use `img` elements. Use a div sized properly with css background-image ... or put each of those logos into a separate image resource and `<img>` then directly (combining into one request hasn't mattered for perf since h1)
