### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by azrahn** [GoogleChrome/lighthouse#6416] opened 2018-10-27 11:01 UTC
**Initial URL**: https://www.horizonhomes-samui.com/
**Chrome Version**: 70.0.3538.77
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:4878:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1405:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1384:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1394:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1397:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1397:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9/audits2_worker/audits2_worker_module.js:1087:163)
```

**Comment by patrickhulce** [comment] 2018-10-28 03:17
duplicate of #6145, fixed by  #6157 in next version

**Closed by patrickhulce** 2018-10-28 03:17 UTC
