### ISSUE TITLE
DevTools Error: Cannot read property 'navigate' of null

### ISSUE THREAD

**Issue by tomdw** [GoogleChrome/lighthouse#7544] opened 2019-03-16 15:03 UTC
**Initial URL**: http://localhost:4201/
**Chrome Version**: 73.0.3683.75
**Error Message**: Cannot read property 'navigate' of null
**Stack Trace**:
```
TypeError: Cannot read property 'navigate' of null
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:221:562)
    at async Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:214:126)
```

**Comment by patrickhulce** [comment] 2019-03-16 20:19
Interesting this is a new one. @tomdw any steps you took that might help us reproduce?

**Comment by tomdw** [comment] 2019-03-19 22:03
@patrickhulce I dont have specific steps. It happened suddenly.

**Comment by brendankenny** [comment] 2019-04-25 23:07
Closing since it's been a while without an update. If you run into this again, please comment and we can reopen.

**Closed by brendankenny** 2019-04-25 23:07 UTC
Labels: needs-more-info
