### ISSUE TITLE
Indexing check "Audit error: libUrl.parse is not a function"

### ISSUE THREAD

**Issue by Enalmada** [GoogleChrome/lighthouse#4852] opened 2018-03-22 19:34 UTC
I am running lighthouse extension 2.9.2 and under SEO > Crawling and Indexing > Page is blocked from indexing, I think there is an error in the plugin "Audit error: libUrl.parse is not a function":

![image](https://user-images.githubusercontent.com/1892132/37793822-f846f80c-2dcc-11e8-9cc8-ccedee309c47.png)

Also, when I click that Learn More link I get a 404
https://developers.google.com/lighthouse/audits/indexing

**Comment by patrickhulce** [comment] 2018-03-22 20:01
Thanks for reporting @Enalmada! duplicate of #4794, fixed in 2.9.3

**Closed by patrickhulce** 2018-03-22 20:01 UTC

**Comment by Enalmada** [comment] 2018-03-22 20:02
Ah sorry...I should have looked harder for dupe.

**Comment by patrickhulce** [comment] 2018-03-22 20:19
no worries, appreciate the effort! :)
