### ISSUE TITLE
Extension Error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by fes300** [GoogleChrome/lighthouse#1490] opened 2017-01-18 16:17 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: https://www.chiarezza.it/preventivo-assicurazione/rc-auto-1
**Error Message**: Cannot read property 'children' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:560:62)```

**Comment by ebidel** [comment] 2017-01-18 17:59
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1427

**Closed by ebidel** 2017-01-18 17:59 UTC
Labels: duplicate
