### ISSUE TITLE
Launching Chrome with launcher in non headless mode

### ISSUE THREAD

**Issue by janbaer** [GoogleChrome/lighthouse#2292] opened 2017-05-17 15:23 UTC
I'm trying to start Chrome Canary 60 just for manual testing in a non headless mode from my Node.js script which is using the Lighthouse ChromeLauncher. But Chrome will always started in the headless mode in this mode and I'm wondering about this.

These flags will be used to spawn the new process with a running Chrome instance: 

'--remote-debugging-port=9222',
  '--disable-translate',
  '--disable-extensions',
  '--disable-background-networking',
  '--safebrowsing-disable-auto-update',
  '--disable-sync',
  '--metrics-recording-only',
  '--disable-default-apps',
  '--no-first-run',
  '--user-data-dir=/var/folders/pr/11rp2g1s3vjcn48gxy2sqzdw0000gr/T/lighthouse.XXXXXXX.aR37Ho4Y',
  'about:blank'

Is there any explanation for this behaviour? Thanks!

**Comment by paulirish** [comment] 2017-05-17 15:48
it doesn't make obvious sense to me! very weird. 

Is it any different with a fresh user-data-dir?

can you manage to launch chrome from cmd line as non-headless at all?

**Comment by janbaer** [comment] 2017-05-18 07:29
Yes Chrome is starting from the commandline in the headless mode and also in the normal mode. The userdata dir was empty when I started it. So directly from the commandline it's working perfectly. And yes, it sounds weird since I saw the command line args and spawn should do nothing different then I would do in the manual mode.

**Comment by janbaer** [comment] 2017-05-18 09:19
It seems that on the Computer of my colleague it's working, but he's using the Chrome 59 Beta on Linux and I've Chrome Canary on MacOS.

**Comment by wardpeet** [comment] 2017-05-23 20:17
@janbaer node & npm version are the same? i'll give it a go somewhere this week

**Comment by janbaer** [comment] 2017-05-24 06:25
Yes, it's the same. I always install Node.js and NPM together with using nvm and never update NPM manually.

**Comment by samccone** [comment] 2017-05-24 17:41
Can you share your script? Right now I can not reproduce your bug case.

**Comment by samccone** [comment] 2017-05-25 03:21
Closing as unable to reproduce. Let me know if you have a test case and we can reopen.

Thanks!

**Closed by samccone** 2017-05-25 03:21 UTC
Labels: cli

**Comment by tomasbatto** [comment] 2017-06-21 14:27
Hi! I don't know if my issue belongs here, but I'm having a similar issue. 
When I don't set the --no-headless flag, a Chrome window opens but it's not possible to actually view the navigation inside it. I'm connecting to it using https://github.com/cyrus-and/chrome-remote-interface and navigating to different websites using the protocol, but All I can see is the "about:blank" page while the navigation is only happening in the background.

The weird thing is that when I run EXACTLY the same code on an older Mac or any other computer, it works perfectly. Both computers have the same Google Chrome, Node and NPM versions. 

Any ideas?
Thanks!

**Comment by samccone** [comment] 2017-06-21 14:47
@tomasbatto would you be able to post an example of your code to reproduce this?
