### ISSUE TITLE
Flakiness with "Registers a service worker" audit

### ISSUE THREAD

**Issue by AswathyNath** [GoogleChrome/lighthouse#1815] opened 2017-03-04 08:26 UTC
We have installed service worker, but lighthouse report saying service worker not installed. 
Site URL : https://fuzecaresystem.com/

Please check screenshot:
![capture](https://cloud.githubusercontent.com/assets/26127819/23575243/168a48c8-00b0-11e7-9361-388d87cda24d.PNG)

**Comment by wardpeet** [comment] 2017-03-04 19:37
can you tell us what version of lighthouse and what browser you are running it on?
Do you run it through lighthouse-cli or lighthouse browser extension?

I could not reproduce it.

**Comment by AswathyNath** [comment] 2017-03-05 05:45
Chrome Version 56.0.2924.87
lighthouse browser extension version 1.6.0

**Comment by wardpeet** [comment] 2017-03-05 12:19
@AswathyNath do you have it every time or does it pass sometimes?

**Comment by AswathyNath** [comment] 2017-03-06 05:34
Yes, Sometimes this test pass with score 89/100

**Comment by wardpeet** [comment] 2017-03-14 22:04
Looks like a duplicate of #1111
I will have a look into this

**Comment by stramel** [comment] 2017-03-23 18:11
I'm also getting this issue.

**Comment by wardpeet** [comment] 2017-03-25 12:49
I have a fix ready but needs to be reviewed.
can you give us your url :)

**Comment by AswathyNath** [comment] 2017-03-25 13:29
Our url:
https://www.fuzecaresystem.com/

**Comment by sskhera** [comment] 2017-03-29 08:20
Hi,
Is the issue resolved. We are also facing the same issue on our test environment. Want to make sure everything is fine before pushing the changes to Prod.
test environment link https://test.cilory.com/

**Comment by AswathyNath** [comment] 2017-03-29 13:37
when switching network panel to offline
 https://test.cilory.com/ showing offline TREX

**Comment by stramel** [comment] 2017-04-14 15:40
I think I figured out why my site is showing no service worker.

I have jQuery (trying to get my company to get rid of it) and an adobe analytics script both fetch from CDNs. 

Without them, the checks pass. With either script referencing the CDN, the audit fails both registering a service worker and returning a 200 when offline. 

However, it does run offline when manually testing.

**Comment by ebidel** [comment] 2017-04-14 15:57
@stramel can you provide the URL of that site?

**Comment by stramel** [comment] 2017-04-14 16:14
@ebidel https://d-citrix.salesnext.com

**Comment by ebidel** [comment] 2017-04-15 17:39
@stramel I was able to look a bit at your site yesterday. It looked like the sw registration never happened because the function was returning before it gets to `navigator.serviceWorker.register`. You're hitting this line:

```
if (window.Polymer)
   return void console.error("Polymer already initialized!");
```

I also noticed waiting to register the sw until after `window.onload`. That could explain the timing differences with/without the CDN resources.

**Comment by stramel** [comment] 2017-04-15 17:46
@ebidel Thanks for taking a look!

**Comment by ebidel** [comment] 2017-04-15 18:32
I was also unable to repo on https://www.fuzecaresystem.com/ using LH's default throttling settings. However, the using Network Link Conditioner to throttle to DSL or lower does the trick!

You can also repo on WPT when running EM throttling. I just ran the easy setting: https://www.webpagetest.org/lighthouse.php?test=170415_YJ_ZMZ&run=2.

**Comment by stramel** [comment] 2017-04-15 19:36
@ebidel Is loading the service worker after `window.onload` a bad thing? The PSK has it setup that way.

**Comment by ebidel** [comment] 2017-04-15 19:40
No, not a bad thing. I expect many sites to do similar lazy loading techniques. For example, the new mobile.twitter.com PWA delays their registration even after page load. 

We need to handle these cases better within LH :)

**Closed** 2017-04-26 01:49 UTC
Labels: audit, bug

**Comment by AswathyNath** [comment] 2017-04-29 07:44
https://d-and-b.in/ showing serive worker not installed

**Comment by wardpeet** [comment] 2017-04-29 10:13
@AswathyNath it's not yet available in the latest npm. It only works if you run from master but that might give other issues as we are heavily developing for a new release.
