### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by pushkar0108** [GoogleChrome/lighthouse#1993] opened 2017-04-11 09:55 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.98
**URL**: https://paytm.com/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2017-04-11 19:32
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1984

**Closed by ebidel** 2017-04-11 19:32 UTC
