### ISSUE TITLE
Passive Event Listeners Detection Error

### ISSUE THREAD

**Issue by KingSora** [GoogleChrome/lighthouse#9315] opened 2019-06-30 20:18 UTC
Good day!

#### Provide the steps to reproduce
If I add a `touchevent` with a callback which is calling `preventDefault()`, lighthouse will still report a `Best Practices` error, which is telling me to use `passive event listeners`.

I've uploaded a example which confirms this bug:
[passive.zip](https://github.com/GoogleChrome/lighthouse/files/3343298/passive.zip)

#### What is the current behavior?
Lighthouse reports a `Best Practices` error, which is telling me to use `passive event listeners` even if a event calls `preventDefault()` inside.

#### What is the expected behavior?
Lighthouse should act like described: [https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners)
> Filter out listeners that call preventDefault().

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.1.0.1
* Node.js version: -
* Operating System: Windows 10

**Comment by patrickhulce** [comment] 2019-07-01 05:08
Thanks for filing @KingSora! While the audit did used to work as described, when Chrome's violation policy changed to warn on *any* `touchevent` with a non-passive listener, Lighthouse changed to match this behavior as well.

The docs need to be updated to reflect this.

**Comment by exterkamp** [comment] 2019-07-23 20:54
@mfriesenhahn would you mind including this in the https://web.dev docs?

**Comment by patrickhulce** [comment] 2021-06-21 21:55
Dupe of #11100, follow that issue for updates.

**Closed by patrickhulce** 2021-06-21 21:55 UTC
Labels: P1.5, docs
