### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by Ralf8686** [GoogleChrome/lighthouse#2930] opened 2017-08-10 14:47 UTC
**Initial URL**: http://localhost:8080/
**Chrome Version**: 60.0.3112.90
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-08-10 17:15
dupe of #1685

**Closed by patrickhulce** 2017-08-10 17:15 UTC
