### ISSUE TITLE
Page Speed Insight scores do not match Lighthouse scores in chrome dev tools

### ISSUE THREAD

**Issue by nragan34** [GoogleChrome/lighthouse#9286] opened 2019-06-26 03:38 UTC
Page Speed Insight scores do not match Lighthouse scores in chrome dev tools - https://cavanalchiropractic.com . Mobile scores are all I am concerned with and reflect the reason for this issue.

**Comment by ueltonVeslei** [comment] 2019-07-02 14:27
Duplicate from #8997

**Comment by exterkamp** [comment] 2019-07-08 17:05
Duplicate of #6708

**Closed by exterkamp** 2019-07-08 17:05 UTC
