### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by blastseld** [GoogleChrome/lighthouse#2446] opened 2017-06-06 15:42 UTC
**Initial URL**: about:blank
**Chrome Version**: 61.0.3119.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@177b9b934d8398dfb0d17b88fd9ff00f3291cca5/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@177b9b934d8398dfb0d17b88fd9ff00f3291cca5/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-06 17:09
dupe of #2362

**Closed by patrickhulce** 2017-06-06 17:09 UTC
