### ISSUE TITLE
Web page crashes when using lighthouse from devtools

### ISSUE THREAD

**Issue by Jaspreet-diff** [GoogleChrome/lighthouse#12123] opened 2021-02-22 20:19 UTC
**Describe the bug**
-Lighthouse crashes my web page every-time when I try to generate report 

**To Reproduce**
1. Go to https://www.fashionnova.com/ (Open in incognito window)
2. Click on inspect element, go to lighthouse tab
3. Generate report

**Expected behavior**
Should generate report without crashing the page.

**Logs/Screenshots**
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: https://www.fashionnova.com/
Chrome Version: 88.0.4324.182
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:456:814)
    at async Driver.evaluateAsync (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:455:491)
    at async Function.afterPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:479:1)
    at async Function.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:483:430)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:481:730)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:607:184)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:605:118)
```
<img width="1340" alt="Screen Shot 2021-02-22 at 3 19 11 PM" src="https://user-images.githubusercontent.com/63602760/108765039-54ae1f00-7521-11eb-8619-c58b62968288.png">

<img width="945" alt="Screen Shot 2021-02-22 at 3 08 44 PM" src="https://user-images.githubusercontent.com/63602760/108764912-29c3cb00-7521-11eb-8864-5da21d7d7c9f.png">

**Comment by adamraine** [comment] 2021-02-23 00:10
I can reproduce this. Looks like Chrome is crashing and DT gets disconnected from the page. We should file upstream but figure out what stage is causing this to fail first.

**Comment by patrickhulce** [comment] 2021-02-23 03:19
Oh shoot, sorry @adamraine I forgot to update this, but I did file a crash report with this (https://bugs.chromium.org/p/chromium/issues/detail?id=1181049)

**Comment by patrickhulce** [comment] 2021-02-23 17:58
@Jaspreet-diff this appears to be fixed in today's Chrome Canary. Could you give it a try and let us know if it's resolved for you too?

**Comment by Jaspreet-diff** [comment] 2021-02-23 18:14
> Chrome Canary

@patrickhulce  Yes it worked on Chrome Canary but why not on google chrome Version 88.0.4324.192 (Official Build) (x86_64) for Mac os??
Is there any reason behind which disconnect DT and does not load page automatically. I see this was not the issue with older version of chrome.

**Comment by patrickhulce** [comment] 2021-02-23 18:32
> but why not on google chrome Version 88.0.4324.192 (Official Build) (x86_64) for Mac os??

Because there was a bug in Chromium that caused the page to crash, and then Chrome engineers fixed the bug after version 88.

**Comment by patrickhulce** [comment] 2021-02-23 18:32
Glad to hear it was fixed @Jaspreet-diff that's great news! We'll go ahead and close this one then.

**Closed by patrickhulce** 2021-02-23 18:32 UTC
Labels: needs-priority, waiting-on-upstream

**Comment by StefsterNYC** [comment] 2024-04-26 17:38
Wow this happened back in 2021 and is happening again in 2024. Nice!
