### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by Jeezman** [GoogleChrome/lighthouse#2069] opened 2017-04-26 10:13 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: http://localhost:5050/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13554:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14639:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14665:18)```

**Comment by wardpeet** [comment] 2017-04-26 15:07
Dupe of #1834

**Closed by wardpeet** 2017-04-26 15:07 UTC
