### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by gamesbyfrenzy** [GoogleChrome/lighthouse#6414] opened 2018-10-27 02:42 UTC
**Initial URL**: http://127.0.0.1:8887/
**Chrome Version**: 72.0.3592.0
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:85:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:490:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:182:241)
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:206:381)
```

**Comment by patrickhulce** [comment] 2018-10-28 03:16
duplicate of #4330

**Closed by patrickhulce** 2018-10-28 03:16 UTC
