### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by SrSandeepKumar** [GoogleChrome/lighthouse#1909] opened 2017-03-25 02:36 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 56.0.2924.87
**URL**: https://www.flipkart.com/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment] 2017-03-25 12:40
Do you still have this issue after the latest update?

**Comment by SrSandeepKumar** [comment] 2017-03-25 16:45
yes, remove the extension and re-installed it.
when i click on **generate report**, it tries to test the site and page would directed to **about:blank**
_Protocol error (Tracing.start): Tracing is already startedReport Error_
P.S. How do i stop tracing before clicking on _generate report_  again?

**Comment by SrSandeepKumar** [comment] 2017-03-26 23:50
@wardpeet it worked fine now.

**Comment by ebidel** [comment] 2017-03-27 16:44
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-03-27 16:44 UTC
