### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by bebensiganteng** [GoogleChrome/lighthouse#1354] opened 2016-12-29 12:58 UTC
**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.95
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7382:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7532:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2016-12-29 17:55
@bebensiganteng can you let us know how to reproduce and what page you were testing against?

**Comment by bebensiganteng** [comment] 2016-12-30 04:48
@ebidel 

1. Start Lighthouse (on google.com).
2. Took too long ( > 10 minutes).
3. Cancel the process, the dialog window went away.
4. Restart the process, then the error appeared.

**Comment by wardpeet** [comment] 2016-12-30 06:38
will have to check but I'm pretty sure we have a dupe of this with some more information.

**Comment by ebidel** [comment] 2016-12-30 17:05
Right you are. Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2016-12-30 17:05 UTC
