### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by web20opensource** [GoogleChrome/lighthouse#5908] opened 2018-08-25 00:10 UTC
**Initial URL**: http://localhost:8000/
**Chrome Version**: 68.0.3425.0
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:90:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:489:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:187:241)
    at Audits2.Audits2Dialog._stopAndReattach (chrome-devtools://devtools/bundled/audits2/audits2_module.js:226:374)
```

**Comment by paulirish** [comment] 2018-08-27 17:27
dupe of #4330

**Comment by paulirish** [comment] 2018-08-27 17:27
thx for reporting

**Closed by paulirish** 2018-08-27 17:27 UTC
Labels: needs-priority
