### ISSUE TITLE
Bug last declaration font-display without semicolon

### ISSUE THREAD

**Issue by romanmarkelov** [GoogleChrome/lighthouse#7559] opened 2019-03-18 10:31 UTC
#### Provide the steps to reproduce
https://github.com/google/fonts/issues/1883

Audit fails  "Ensure text remains visible during webfont load"

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: 73.0.3683.75 
* Node.js version: v11.9.0
* Operating System: MacOS

**Comment by patrickhulce** [comment] 2019-03-18 14:12
Thanks @romanmarkelov! This is a duplicate of #6628 and fixed by #7191, should be out in the next few Chrome versions.

**Closed by patrickhulce** 2019-03-18 14:12 UTC
