### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by gbowman2013** [GoogleChrome/lighthouse#1310] opened 2016-12-25 16:27 UTC
I had just closed a tab after being warned that the url was open in another tab. I then clicked 'Generate report' button and this error was generated.

**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.87
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11251:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12218:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12231:25)```

**Comment by ebidel** [comment] 2016-12-25 18:34
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2016-12-25 18:34 UTC
