### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by LETUONGNHAN** [GoogleChrome/lighthouse#4570] opened 2018-02-17 01:00 UTC
**Initial URL**: https://payment.napas.com.vn/gateway/message?referenceId=1518827161865
**Chrome Version**: 60.0.3112.101
**Error Message**: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by LETUONGNHAN** [comment] 2018-02-17 01:01
https://payment.napas.com.vn/gateway/message?referenceId=1518827161865

**Comment by wardpeet** [comment] 2018-02-17 22:37
@LETUONGNHAN could you test your page on the latest chrome (63)? I could run lighthouse just fine.

**Comment by LETUONGNHAN** [comment] 2018-02-17 23:24
hien thi ma the

**Comment by patrickhulce** [comment] 2018-02-20 16:51
hey there @LETUONGNHAN this is a duplicate of #2784, so take a look at the descriptions there and let us know if your situation is missing. thanks!

**Closed by patrickhulce** 2018-02-20 16:51 UTC
