### ISSUE TITLE
Image Aspect Ratio Audit failed despite no images

### ISSUE THREAD

**Issue by iamedwardwall** [GoogleChrome/lighthouse#4619] opened 2018-02-26 02:35 UTC
The page on which I am running the audit has no images but the "Does not use images with appropriate aspect ratio" audit in Best Practices still fails

**Comment by patrickhulce** [comment] 2018-02-27 17:26
This is a duplicate of #3551 that was fixed in v2.6. Update to latest (v2.9.1), use the extension, or CLI.

**Closed by patrickhulce** 2018-02-27 17:26 UTC
Labels: duplicate
