### ISSUE TITLE
DevTools Error: Unable to load the page: 

### ISSUE THREAD

**Issue by SteveGuluk** [GoogleChrome/lighthouse#3549] opened 2017-10-13 14:14 UTC
**Initial URL**: http://www.islandwaterpark.com/wp-content/uploads/2015/05/Island-Waterpark-Memorial-Day-Weekend-2017-103.jpg
**Chrome Version**: 61.0.3163.100
**Error Message**: Unable to load the page: 
**Stack Trace**:
```
Error: Unable to load the page: 
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by SteveGuluk** [comment] 2017-10-13 14:15
Page Audit error

**Comment by vinamratasingal** [comment] 2017-10-13 20:07
Hi- I'm able to run the report through DevTools, can you update with reproduction steps and an update on the error if you're still facing this problem?

**Comment by patrickhulce** [comment] 2018-03-08 23:40
dupe of #2784

**Closed by patrickhulce** 2018-03-08 23:40 UTC
Labels: pending-close
