### ISSUE TITLE
PageSpeed Insights Failed: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Fudoshiki** [GoogleChrome/lighthouse#16168] opened 2024-08-24 13:52 UTC
https://pagespeed.web.dev doesn't support `wss` requests, `user-agent` now useless for detection

How can I avoid error messages

![Снимок экрана 2024-08-26 в 18 50 23](https://github.com/user-attachments/assets/6cc5e190-4fd1-408f-8acb-7fef0307e939)

**Comment by rsmything** [comment] 2024-08-24 13:53
The same issue

**Comment by adamraine** [comment] 2024-08-28 19:25
Merging as duplicate of https://github.com/GoogleChrome/lighthouse/issues/12459

**Closed by adamraine** 2024-08-28 19:25 UTC
