### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by xtianares** [GoogleChrome/lighthouse#2442] opened 2017-06-05 21:41 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 58.0.3029.110
**URL**: https://localhost:8000/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:16039:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:17124:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:17149:25)
    at <anonymous>```

**Comment by ebidel** [comment] 2017-06-05 21:55
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-06-05 21:55 UTC
