### ISSUE TITLE
Incorrect CSS selector when running lighthouse through CLI or Node.

### ISSUE THREAD

**Issue by adelavegaf** [GoogleChrome/lighthouse#5415] opened 2018-06-03 23:55 UTC
## Bug report
Sometimes the CSS selector returned by running lighthouse through the CLI or Node returns a different and incorrect value than if it is ran through Chrome devtools.

#### Provide the steps to reproduce
1. Run LH on https://www.washington.edu/accesscomputing/AU/before.html through the CLI or Node.
`
$ lighthouse https://www.washington.edu/accesscomputing/AU/before.html --output json
`
#### What is the current behavior?

The color-contrast audit result obtained through the CLI or Node returns incorrect selectors for the four failing elements. Here we can see that the selector ":root" was assigned to all four elements.

<img width="327" alt="screen shot 2018-06-03 at 6 40 27 pm" src="https://user-images.githubusercontent.com/5798535/40892507-c32d6d5c-675d-11e8-92a2-f2b4d9b16656.png">

If we call document.querySelector(':root') the whole document is returned and not the particular failing elements as shown in the next image.

<img width="1680" alt="screen shot 2018-06-03 at 6 46 14 pm" src="https://user-images.githubusercontent.com/5798535/40892554-6c254d80-675e-11e8-84e1-7b67246fdf01.png">

#### What is the expected behavior?

Running the same audit through Chrome devtools renders the following selectors:

<img width="328" alt="screen shot 2018-06-03 at 6 40 40 pm" src="https://user-images.githubusercontent.com/5798535/40892525-09f7f0c2-675e-11e8-915a-d41bb1541353.png">

These selectors do work as expected as shown in the following image:

<img width="1680" alt="screen shot 2018-06-03 at 6 51 37 pm" src="https://user-images.githubusercontent.com/5798535/40892624-2c2cfce0-675f-11e8-9586-ca66fc99853a.png">

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: 2.9.4
* Node.js version: 9.0.0
* Operating System: MacOS High Sierra 10.13.4

**Related issues**

None

**Comment by patrickhulce** [comment] 2018-06-04 17:18
Thanks for reporting @adelavegaf I can reproduce this as well! We'll have to look into what's going on with axe here.

**Comment by paulirish** [comment] 2018-08-29 19:44
@adelavegaf can you reproduce this with the aXe extension? We should report it upstream to axe-core.

**Comment by brendankenny** [comment] 2019-04-25 22:46
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen, but hopefully axe updates have fixed this in the meantime.

**Closed by brendankenny** 2019-04-25 22:46 UTC
Labels: P2, bug, cli, extension, needs-more-info
