### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by SerkanSipahi** [GoogleChrome/lighthouse#4682] opened 2018-03-03 22:03 UTC
**Initial URL**: http://localhost:4200/
**Chrome Version**: 64.0.3282.186
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```

This happens when i start lighthouse over chrome dev audits! The application what i want to testing is, is a running angular app in dev prod (`ng serve --prod`)!
Yesterday everything works fine but today not. Is this a bug?

**Comment by SerkanSipahi** [comment] 2018-03-03 22:04
Update: it occurs (the error) on each webpage!

**Comment by SerkanSipahi** [comment] 2018-03-03 22:05
Update: after restarting chrome everything works fine :)

**Comment by patrickhulce** [comment] 2018-03-05 16:39
you've figured out the only fix @SerkanSipahi :)

duplicate of #1091

**Closed by patrickhulce** 2018-03-05 16:39 UTC
