### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by Catelepsy** [GoogleChrome/lighthouse#3083] opened 2017-08-22 21:07 UTC
**Initial URL**: https://www.drakemoon.com/
**Chrome Version**: 60.0.3112.101
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-09-01 16:00
dupe of #1733

**Closed by patrickhulce** 2017-09-01 16:00 UTC
