### ISSUE TITLE
Anchors with no href fail AnchorsWithNoRelOpener Audit

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1233] opened 2016-12-22 02:45 UTC
Testing https://www.seamless.com/, we get:

<img width="1042" alt="screen shot 2016-12-21 at 4 14 34 pm" src="https://cloud.githubusercontent.com/assets/238208/21413625/8b698b54-c7ad-11e6-96ad-7fd104b78974.png">

@brendankenny giving this to you since you already started investigating.

**Comment by brendankenny** [comment] 2016-12-22 06:11
The underlying issue here is `new URL('')`, which isn't valid, which happens when you use an anchor tag without an `href` attribute.

The issue is that many web apps use anchors with no `href` for app purposes (e.g. the seamless example has `<a class="app-download-appsStore-link" ng-click="::$ctrl.goToUrl($ctrl.appleUrl)" target="_blank">...</a>`). However angular, at least, still honors the `target` attribute (and `window.opener` is available in the new tab). If it honors `rel` as well we should probably still warn on these links, so we shouldn't just strip them out in the audit.

**Comment by wardpeet** [comment] 2016-12-22 12:09
issue got fixed on master

**Closed by wardpeet** 2016-12-22 12:09 UTC
Labels: audit bug
