### ISSUE TITLE
Extension Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by ZigZagIL** [GoogleChrome/lighthouse#1255] opened 2016-12-22 20:35 UTC
**Lighthouse Version**: 1.3.0
**Chrome Version**: 55.0.2883.87
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.AnchorsWithNoRelNoopener.usages.filter.anchor (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:689:25)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:689:8)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11365:20)```

**Comment by ebidel** [comment] 2016-12-22 20:56
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1200. Will be fixed soon in the next release!

**Closed by ebidel** 2016-12-22 20:56 UTC
Labels: duplicate
