### ISSUE TITLE
Self closing <meta charset> isn't detected

### ISSUE THREAD

**Issue by Zoltanpetrik** [GoogleChrome/lighthouse#11956] opened 2021-01-14 16:52 UTC
#### Provide the steps to reproduce

1. Run LH on a page which contains a self closing meta charset tag:
  `<meta charset="utf-8" />`

Why would I use this in my code? Because: *Prettier defaults to producing this output when beautifying html.*

#### What is the current behavior?

The page scores "?" for "Best Practices".

Error: Browser compatibility: Properly defines charset: Error!

#### What is the expected behavior?

Self closing meta tags are valid HTML5, so this shouldn't be an issue.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 6.4.0
* Chrome version: Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
* Operating System: Windows 10 OS Version 2004 (Build 19041.746)

**Comment by patrickhulce** [comment] 2021-01-14 23:41
Thanks for filing @Zoltanpetrik! I can't reproduce though (http://melodic-class.glitch.me/meta-selfclosing.html)

![image](https://user-images.githubusercontent.com/2301202/104662122-b6ac7680-568f-11eb-9d9b-02567f12cead.png)


The "Error!" you're describing doesn't mean that Lighthouse is failing the page, it means an exception was thrown and Lighthouse couldn't finish. If you mouse over the Error the underlying exception details should be revealed. Would you be able to provide that message and/or provide more detailed reproduction steps on a public URL?

**Comment by Zoltanpetrik** [comment] 2021-01-17 18:52
@patrickhulce Since then I discovered; this issue has more prerequisites to be triggered, I'm working on isolating the issue, and will share a POC in the next couple of days.

**Comment by brendankenny** [comment] 2021-04-06 20:00
Going to close this for now, but if you do get a repro, please share are we can reopen.

**Closed by brendankenny** 2021-04-06 20:00 UTC
Labels: needs-more-info, needs-priority
