### ISSUE TITLE
Auditing LocalHost not working with lighthouse

### ISSUE THREAD

**Issue by Des-Hussain** [GoogleChrome/lighthouse#9444] opened 2019-07-24 07:54 UTC
![image](https://user-images.githubusercontent.com/33750071/61930827-67085580-af98-11e9-9c7b-98f931aeb555.png)

NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:4200/
Chrome Version: 75.0.3770.142
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@8d93477bd18154c67a70a67019cb8032382c55dd/audits2_worker/audits2_worker_module.js:1219:206)
```

i am trying to audit my angular 6 web app at localhost but it is showing the error above, meanwhile when i am auditing it on live server it is working fine.

**Comment by patrickhulce** [comment] 2019-07-24 14:40
It looks like a substantial portion of the error is missing from your comment. I'm only seeing a single line of the stack trace instead without the actual error message.

**Comment by maksof-Hussain** [comment] 2019-07-26 06:29
@patrickhulce i have updated my issue.

**Comment by patrickhulce** [comment] 2019-07-26 14:46
Ah thanks! `NO_FCP` means that the page did not paint any content. Lighthouse cannot audit a page that has no content.

**Comment by ebabel-eu** [comment] 2019-08-06 09:15
I'm also getting NO_FCP but the page is painting content (it's a WebGL Canvas)

**Comment by maksof-Hussain** [comment] 2019-08-06 10:17
> Ah thanks! `NO_FCP` means that the page did not paint any content. Lighthouse cannot audit a page that has no content.

lighthouse is auditing my page when its live and but when i am trying with the same code on local its shows error.

**Comment by patrickhulce** [comment] 2019-08-06 14:59
@ebabel-eu a canvas should [count as content](https://w3c.github.io/paint-timing/#first-contentful-paint), do you have a URL for your page?

**Comment by patrickhulce** [comment] 2019-08-06 15:00
@maksof-Hussain is the window obscured for your page? The screenshot has the window for your audit backgrounded. Your page has to be visible in order for Chrome to paint.

**Comment by ebabel-eu** [comment] 2019-08-06 15:38
> @ebabel-eu do you have a URL for your page?

Sure, here it is: https://d1vn0ri7r15fzf.cloudfront.net/

I get NO_FCP in both localhost and production. I'm using Chrome Version 76.0.3809.87 (Official Build) (64-bit) on macOS Mojave version 10.14.6

**Comment by patrickhulce** [comment] 2019-08-06 16:25
@ebabel-eu I can confirm yours is a bug in Chrome and filed https://bugs.chromium.org/p/chromium/issues/detail?id=991228.

**Comment by paulirish** [comment] 2020-05-26 20:12
closing since this is an upstream chrome issue.

**Closed by paulirish** 2020-05-26 20:12 UTC
Labels: needs-priority, waiting-on-upstream

**Comment by tryhardest** [comment] 2020-06-23 18:42
@paulirish can lighthouse work with Cordova (localhost) from debug console? Keeps crashing on audits.

**Comment by Kamilius** [comment] 2022-08-23 09:21
> @paulirish can lighthouse work with Cordova (localhost) from debug console? Keeps crashing on audits.

Actually seems like it doesn't crash but rather closes your app, as Lighthouse tries opening `about:blank` first, which can be prohibited by your Cordova configuration
