### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by Davidoseq** [GoogleChrome/lighthouse#1707] opened 2017-02-13 12:47 UTC
**Lighthouse Version**: 1.5.1
**Chrome Version**: 56.0.2924.87
**URL**: http://www.topdrogerie.cz/letaky/akcni-letak
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12963:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14040:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14066:25)```

**Comment by ebidel** [comment] 2017-02-13 17:25
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2017-02-13 17:25 UTC
