### ISSUE TITLE
picture srcset not loaded correctly on mobile report

### ISSUE THREAD

**Issue by Jehfen** [GoogleChrome/lighthouse#11251] opened 2020-08-11 10:16 UTC
#### Provide the steps to reproduce
1. Run LH on any url
  

#### What is the current behavior?
When performing a mobile report, a 'picture' tag with subtags 'source' and 'img', LH loads both sources, resulting in bigger total  image transfer size.

#### What is the expected behavior?
LH should just load the most appropriate element source, depending on the provided media query; either the 'source' tag or the 'img' tag, but not both. This is the standard behavior in Chrome.

#### Environment Information
* Lighthouse version: 6
* Chrome version: 84
* Operating System: Windows 10

**Related issues**

**Comment by patrickhulce** [comment] 2020-08-11 14:36
Thanks for filing @Jehfen!

I can't reproduce this though. See http://melodic-class.glitch.me/image-picture-duplicate.html

![image](https://user-images.githubusercontent.com/2301202/89910660-1faa3280-dbb6-11ea-898c-fb417a9088d5.png)


> Run LH on any url

You'll need to be more specific ;)

**Comment by patrickhulce** [comment] 2020-09-29 20:28
We're going to go ahead and close this, but if you're still seeing this and willing to provide more reproduction information feel free to comment back and we'll reopen :)

**Closed by patrickhulce** 2020-09-29 20:28 UTC
Labels: needs-more-info, needs-priority
