### ISSUE TITLE
Extension Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by 1003865572** [GoogleChrome/lighthouse#4097] opened 2017-12-20 03:25 UTC
**Lighthouse Version**: 2.7.0
**Lighthouse Commit**: dd13fbdb4a646660867b43bb8b02b1c083546793
**Chrome Version**: 60.0.3112.113
**Initial URL**: https://qbweb.idbhost.com/bond?bondkey=G0001242017FINPBB10&listedmarket=CIB
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13166:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by vinamratasingal** [comment] 2017-12-21 20:21
Hi! This issue is a dupe of #2448 so let's migrate all the discussion over there- closing this issue out for now :)

**Closed by vinamratasingal** 2017-12-21 20:21 UTC
