### ISSUE TITLE
Performance issues with the new Lighthouse 3.0

### ISSUE THREAD

**Issue by afanjul** [GoogleChrome/lighthouse#5776] opened 2018-08-03 15:28 UTC
#### Provide the steps to reproduce
1. Run LH on https://www.tiradelamanta.com/c1869-mantas.html

#### What is the current behavior?
![screen shot 2018-08-03 at 17 24 23](https://user-images.githubusercontent.com/2046424/43651220-15b7925a-9742-11e8-9406-4ce5715cffa0.jpg)

#### What is the expected behavior?
In the homepage of the same site all seems to work fine, and with the Lighthouse 2.x all worked fine too.

#### Environment Information
* Affected Channels: Chrome Versión 68.0.3440.84 (Build oficial) (64 bits)

* Lighthouse version: 3.0
* Node.js version:
* Operating System: MacOs 10.13.4

**Related issues**

**Comment by daviddahl** [comment] 2018-08-05 00:34
Do you see: ```"first-contentful-paint" : -{

    "scoreDisplayMode" : error,
    "errorMessage" : Audit error: Graph creation failed, depth exceeded,
    "id" : first-contentful-paint,
    "title" : First Contentful Paint,
    "description" : First contentful paint marks the time at which the first text/image is painted. [Learn more](https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics#first_paint_and_first_contentful_paint).,
    "score" : null,
    "rawValue" : null 

},
"aria-required-parent" : +{ ... },
"speed-index" : -{

    "scoreDisplayMode" : error,
    "errorMessage" : Audit error: Graph creation failed, depth exceeded,
    "id" : speed-index,
    "title" : Speed Index,
    "description" : Speed Index shows how quickly the contents of a page are visibly populated. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/speed-index).,
    "score" : null```
 in the json report output?

**Comment by brendankenny** [comment] 2018-08-10 18:00
Hmm, I'm not seeing this issue. @afanjul are you seeing the issue using the CLI, extension, and/or devtools?

**Comment by paulirish** [comment] 2018-08-27 18:27
@daviddahl do you also get SUPER long metric values?

**Comment by paulirish** [comment] 2018-08-27 18:28
@afanjul what is your locale btw?

**Comment by paulirish** [comment] 2018-08-27 18:29
@wardpeet wanna try reproing on https://www.tiradelamanta.com/c1869-mantas.html with ES-es  ?

**Comment by afanjul** [comment] 2018-08-27 18:30
sorry for the delay @paulirish , I'm using the devtool, and my local is Spain/Spanish

**Comment by afanjul** [comment] 2018-08-27 18:42
I have re-ran the test again, and while the results are not suuuper long, they seems preeetttyyy bad when comparing with LH 2.x. We can assure this because we are the SaaS e-commerce CMS www.palbin.com and we have hundreds of online stores, and the resources, javascript, etc. are pretty optimized... (except perhaps some resources you cannot get rid of...like jquery, etc.)

![screen shot 2018-08-27 at 20 37 03](https://user-images.githubusercontent.com/2046424/44678748-650cde00-aa39-11e8-9479-ab529dbb3c6f.jpg)

**Comment by afanjul** [comment] 2018-08-27 18:49
We are getting pretty "bad/low" metrics in our own proprietary CMS, but if you ran it on a "typical" prestashop online store, the things get nasty worst ^_^. I think that the threshold of the new LH is not balanced. With our CMS, we **used to get a performance of 85+ in LH 2.x** (depending of the settings of the online store), and now it's half the number at his best.

![screen shot 2018-08-27 at 20 44 23](https://user-images.githubusercontent.com/2046424/44679173-7efaf080-aa3a-11e8-83a7-f1fc319ef927.jpg)

**Comment by daviddahl** [comment] 2018-08-27 18:54
@paulirish my errors were due to badly-formed performance/bandwidth simulation configuration. All was well, my earlier comments can be ignored.

**Comment by wardpeet** [comment] 2018-10-09 22:29
Ok I did the test and could not reproduce this issue but as @afanjul it seems to be fixed. There are quite some blocking scripts inside head which block rendering and that's why your score is lower. On lighthouse 2.9.1 (cli) I get pretty bad results too. Are you sure it's not just the calculations of the score that's affecting you?

**Comment by afanjul** [comment] 2018-10-09 23:50
Ok, I just did another test again and WITH the same site, the same page, nothing touched, now the report throws a "more used to" score of 81 in performance... (probably close to the performance score LH 2.x throwed in the past). So it's a bit inconsistent... isn't it? (remember, same web, same url, nothing touched in html, resources, etc.)

![screen shot 2018-10-10 at 01 47 28](https://user-images.githubusercontent.com/2046424/46705215-d641d280-cc2e-11e8-9c8a-89c2b4429ad0.jpg)

**Comment by afanjul** [comment] 2018-10-09 23:54
Another test, this time for a typical prestashop e-commerce, and now it goes from 14 (as you saw in my last report) to 80. 

Sorry guys, I don't pretend to be annoying, just trying to help you with my tests...

![screen shot 2018-10-10 at 01 53 11](https://user-images.githubusercontent.com/2046424/46705336-5a945580-cc2f-11e8-8b15-3a991fea1504.jpg)

**Comment by wardpeet** [comment] 2018-10-10 07:00
@afanjul don't worry about 👍

Could you maybe share the full report with us through a gist or whatever so I can see the differences with my runs.

**Comment by brendankenny** [comment] 2019-04-25 22:42
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.

We also have some new variability docs that could be helpful when encountering these issues: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Closed by brendankenny** 2019-04-25 22:42 UTC
Labels: P1.5, needs-investigation, needs-more-info
