### ISSUE TITLE
this tool say allway 'error javascript' , but no one byte of js is write here

### ISSUE THREAD

**Issue by jcrm70** [GoogleChrome/lighthouse#9544] opened 2019-08-09 11:07 UTC
&lt;!DOCTYPE html&gt;
&lt;html&gt;
	&lt;head&gt;
		&lt;meta charset="UTF-8"/&gt;
		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0"/&gt;
		&lt;meta name="apple-mobile-web-app-capable" content="yes"/&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black"/&gt;
		&lt;meta name="apple-mobile-web-app-title" content="My PWA"/&gt;
		&lt;meta name="theme-color" content="#2F3BA2" /&gt;
		&lt;meta name="description" lang="en" content="The content of this site"/&gt;
		&lt;meta name="keywords" lang="en" content="key, words, is, here"/&gt;
		&lt;meta name="author" content="jcr"/&gt;
		&lt;base href="./" /&gt;
		&lt;link rel="manifest" href="manifest.json"/&gt;
		&lt;link rel="apple-touch-icon" href="images/web/192x192.ico.png"/&gt;
		&lt;link rel="shortcut icon" href="favicon.ico"/&gt;
		&lt;title&gt;
			This is my title text
		&lt;/title&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;img alt="wallpaper" width="1152" height="720" src="wallpaper.jpg" /&gt;
	&lt;/body&gt;
&lt;/html&gt;

------------------------

When lighthouse audits the above code, it says 'js error', and they taken their bothers self,  to advise the user to look for good js codes, because the ones he has are not good ...

This is lamerlandia ?. There is not a single byte of js.

A bug is possible and understandable, but it is better not to give erroneous advice how that beginner software does.

(excuse my bad english)

**Comment by patrickhulce** [comment] 2019-08-09 14:43
Thanks for filing!

Would you be able to share a screenshot of the "js error" you are talking about? I'm not sure what you mean.

**Comment by jcrm70** [comment] 2019-08-09 15:29
Yes, i can do this.

![google devtool error js](https://user-images.githubusercontent.com/53938793/62790367-45948700-bacb-11e9-8ca7-4b50714703de.jpg)

Thanks for your attention

**Comment by patrickhulce** [comment] 2019-08-09 15:59
Thanks for the screenshot! That is a bug in Lighthouse. If you hover on the "Error!" it should display the actual error message.

Would you be willing to upload this site somewhere publicly with all the assets so we could reproduce? Perhaps http://surge.sh?

**Comment by jcrm70** [comment] 2019-08-09 21:09
The hovermessage say: 'Fatal trace logic error - expected start event, got X'. and both cases of js error.

My intention is to warn of this error, and I do not understand that I am asked for absurd things in return. You ask me to install things that I don't want to know, I like asm and hex more.

The code I have put is very simple, but if you do not have a simple localhost to run the code, it is not my problem. Do not send me to absurd and unnecessary places.

I may not be very nice, but I think I don't lie.

**Comment by jcrm70** [comment] 2019-08-09 21:31
now I think .. why don't you run the code yourself in, maybe http://surge.sh ?. Sure you don't need me

**Comment by patrickhulce** [comment] 2019-08-09 22:01
You're right, we don't need any of that! :) Duplicate of #7764. 

Something must have gotten lost in translation @jcrm70 I never asked you to install anything. I was only trying to suggest a convenient way to share the resources of your page. The code alone does not have the other assets you reference and does not reproduce the issue for me. We already know this issue though, so we do not need anything from you.

**Closed by patrickhulce** 2019-08-09 22:01 UTC
Labels: needs-more-info

**Comment by jcrm70** [comment] 2019-08-09 23:01
excuse me, I thought you had not started the code.  Thank you for your quick responses.
