### ISSUE TITLE
Lighthouse not working on local instance of a website.

### ISSUE THREAD

**Issue by pereiraryan** [GoogleChrome/lighthouse#4156] opened 2018-01-02 06:48 UTC
While trying to run audits on a local instance of a website the Lighthouse audit block goes for a infinite loop of loading, The audit goes on forever. 
Here is the screen 
![image](https://user-images.githubusercontent.com/12751557/34476468-0438629e-efb7-11e7-92e1-782262043df2.png)

**Comment by vinamratasingal** [comment] 2018-01-02 18:09
Hi pererayan- thanks for writing in! Are you running this on ChromeOS? If so, there is a known issue (#2627 and #4132) that we can fold this into.

**Comment by nikssardana** [comment] 2018-03-22 06:46
I am experiencing a similar issue on Chromium Ubuntu.

This is the version of Chrome and Ubuntu that I am using:-
`Chromium 64.0.3282.167 Built on Ubuntu , running on Ubuntu 16.04`

**Comment by paulirish** [comment] 2019-04-25 22:27
Probably a dupe of https://github.com/ChromeDevTools/devtools-frontend/issues/69 and https://github.com/ChromeDevTools/devtools-frontend/issues/76

**Closed by paulirish** 2019-04-25 22:27 UTC
Labels: needs-more-info, needs-priority
