### ISSUE TITLE
Extension Error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by raviahuja4u** [GoogleChrome/lighthouse#1595] opened 2017-02-01 07:04 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 56.0.2924.76
**URL**: https://www.google.com.au/
**Error Message**: Cannot read property 'children' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:560:62)```

**Comment by alvaropinot** [comment] 2017-02-01 07:09
Dupe of #1427

**Closed** 2017-02-01 17:03 UTC
