### ISSUE TITLE
Lighthouse on web.dev fails to download robots.txt due to CSP violation

### ISSUE THREAD

**Issue by jplejacq-quoininc-com** [GoogleChrome/lighthouse#13394] opened 2021-11-18 03:00 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://ettyproject.org/

### What happened?

When using https://web.dev/measure I receive an error message under Best Practices:

```
Issues logged to the `Issues` panel in Chrome Devtools indicate unresolved problems. They can come from network request failures, insufficient security controls, and other browser concerns. Open up the Issues panel in Chrome DevTools for more details on each issue.

Issue type
--
Content security policy
/robots.txt(ettyproject.org)

```
This does not occur with LightHouse in Chrome DevTools.

The referenced website does not have any JavaScript. Normally loading in a browser does not show any CSP violation either in the browser console or on the server. The robots.txt file can be download as you can easily test.

### What did you expect?

Able to download the robots.txt file.

### What have you tried?

* Downloaded robots.txt with curl and chrome. No problems.
* No CSP violations reported in Chrome console.
* No CSP violations reported on server.
* Checked for other related bugs - see issues 4386 and 10225.

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

9.0.0

### Chrome Version

96

### OS

Linux

### Relevant log output

```shell
Issues logged to the `Issues` panel in Chrome Devtools indicate unresolved problems. They can come from network request failures, insufficient security controls, and other browser concerns. Open up the Issues panel in Chrome DevTools for more details on each issue.

Issue type
--
Content security policy
/robots.txt(ettyproject.org)

```
```

**Comment by adamraine** [comment] 2021-11-18 16:29
The in-page legacy robots.txt fetcher is used for Lightrider, but it can get blocked by CSPs. When running Lighthouse in DevTools/CLI, we use the DevTools protocol to fetch the robots.txt.

Unfortunately, the new protocol fetcher fails most (100%?) of the time in Lightrider (https://github.com/GoogleChrome/lighthouse/issues/12936).

Relevant fork:
https://github.com/GoogleChrome/lighthouse/blob/fe3daf0b8c760d1144ecc336e5206133adfa1ae0/lighthouse-core/gather/fetcher.js#L95-L106

Have there been any updates on using the protocol fetcher since https://github.com/GoogleChrome/lighthouse/issues/12936?

**Comment by connorjclark** [comment] 2021-11-18 21:18
b/199294474

**Comment by connorjclark** [comment] 2021-11-20 00:58
Update: https://chromium-review.googlesource.com/c/chromium/src/+/3291970 just landed, but we need to wait for it to hit stable channel before using. That is ~Feb 1.

**Comment by davidmurdoch** [comment] 2023-01-29 16:32
This is still an issue on Page Speed Insights.

**Comment by connorjclark** [comment] 2023-01-29 21:09
Above I mentioned that it will be at least until February 1st before this can be fixed.

**Comment by davidmurdoch** [comment] 2023-01-30 01:22
That comment is dated 2021, did you mean Feb 2023 at that time?

**Comment by connorjclark** [comment] 2023-01-31 20:59
Sorry @davidmurdoch, I was a bit hasty in my reply and overlooked the dates here. We've got a fix for this in a staging environment, so this should be resolved with our 10.0 release to PSI within the coming weeks.

**Closed** 2023-08-17 23:15 UTC
Labels: bug, P1.5, PSI/LR

**Comment by beatquantum** [comment] 2023-08-27 17:33
As of today (27 August 2023) it seems the issue that Lighthouse being unable to access robots.txt has not been properly fixed. However, the workaround is very easy. In your Content-Security-Policy header, you can include the following:

connect-src 'self';

After that use :
nginx -t

If there no errors
systemctl restart nginx

Good luck!

**Comment by adamraine** [comment] 2023-08-28 17:14
@beatquantum can you provide a site that reproduces this problem?

**Comment by beatquantum** [comment] 2023-08-28 18:50
@adamraine - I have included the "connect-src 'self' as the workaround for https://hard.email without which Lighthouse did not find "robots.txt".

If you wish, we can coordinate and I can remove "connect-src" and share with you Nginx log entries. 

Happy to help to make this work.

(JP - You are right. I wish I did not have to create this workaround. But the developers seem to be a nice bunch.)

**Comment by adamraine** [comment] 2023-08-28 19:44
If you updated https://hard.email/ with a workaround can you please share a version of this site that reproduces this problem? There isn't much we can do without a repro case.

I can't reproduce this problem on other sites that use `connect-src 'none'` in PSI or Lighthouse.
