### ISSUE TITLE
Way to surface non-critical errors in the report

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1512] opened 2017-01-23 20:35 UTC
From https://github.com/GoogleChrome/lighthouse/pull/1492#pullrequestreview-17592494

For individual gatherers/audit errors, we surface `debugString`.

Right now, fatal errors stop the extension from running and we show a "report error" button. However, for non-fatal errors that happen outside of the gatherer -> audit -> report pipeline, we don't have a way to surface those errors to extension users.

Without analytics, we don't know about non-fatal errors. The HTML report could have a section where users see overall LH non-fatal errors and file bugs against us.

**Comment by brendankenny** [comment] 2017-01-23 20:43
It seems this could be broken down into
- a general system for logging or capturing errors in Lighthouse
- having those errors available for output in some way: surfacing in the report, error reporting if that's enabled, etc

**Comment by brendankenny** [comment] 2017-02-03 00:23
after #1591, we probably want to add the errors in the gatherer -> audit -> report pipeline to this as well. Some things might not make sense, but e.g. if we couldn't find FCP and didn't calculate a bunch of perf metrics it should probably be called out at the top as well (this was the spirit of @addyosmani's original #812)

We may want a better icon to mark them in the report as well :)

**Comment by brendankenny** [comment] 2017-02-03 02:54
one more thought for the CLI: as @patrickhulce notes in https://github.com/GoogleChrome/lighthouse/pull/1605#issue-204981590, if something gets logged at the beginning of the LH run, it probably won't get noticed. If we figure out a nice way to pipe errors to the report (or whatever), we could also drop them in the log at the end of the CLI run so they're very visible there too.

**Comment by brendankenny** [comment] 2017-09-26 21:39
yet another warning in the report issue. dupe of #1825 (or the other way around)

**Comment by brendankenny** [comment] 2017-09-28 22:53
List of things to warn on:
- Run on `localhost`, so `is-on-https` warning (amongst others?) might not be representative of when site moves to production/real server - (formerly #3228)
- redirected from HTTP to HTTPS (should only happen in the CLI), so `is-on-https` passes (after #3417) but risk of downgrade attack and performance impact of redirect (details in #3417)

**Comment by patrickhulce** [comment] 2017-11-13 18:57
addressed by #3692

**Closed by patrickhulce** 2017-11-13 18:57 UTC
Labels: feature, P1, report
