### ISSUE TITLE
Lighthouse doen't generate audit report

### ISSUE THREAD

**Issue by jirkapinus** [GoogleChrome/lighthouse#13437] opened 2021-11-26 11:57 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.slunecno.cz

### What happened?

Lighthouse on my webpage doesn't generate audit report. 
Audit stop before end on Chrome and doesn't begin auditing on Edge. 

Probably due to some changes in html code on my website but I don't have any clue what's the reason why Lighthouse doen't work.

Best regards,
Jiri Kapinus
Slunecno.cz

### What did you expect?

Finish audit report

### What have you tried?

Start audit repo
<img width="960" alt="1" src="https://user-images.githubusercontent.com/75752573/143577389-ccbd8148-d9b4-49d6-ab94-758e682a502e.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/75752573/143577394-7356d322-7cf9-4783-a5f7-3f417c7b1002.png">
rt

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

idn

**Comment by adamraine** [comment] 2021-11-29 16:58
https://github.com/GoogleChrome/lighthouse/issues/13396. Looks like it works in the latest Chrome Canary.

**Comment by jirkapinus** [comment] 2021-11-30 09:50
> #13396. Looks like it works in the latest Chrome Canary.

me not :( 

on google canary this error:
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.slunecno.cz/
Chrome Version: 98.0.4738.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:58
    at new Promise (<anonymous>)
    at Driver$1.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:10)
    at Driver$1.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:257)
    at ExecutionContext$2._evaluateInContext (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:108:795)
    at ExecutionContext$2.evaluateAsync (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:109:403)
    at ExecutionContext$2.evaluate (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:109:772)
    at getBenchmarkIndex$2 (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:98:32)
    at Function.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:212:827)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:358:413)
```

**Comment by krissastrabudi** [comment] 2021-12-01 09:35
I'm using chrome 96 version. Some of my friends and I also stuck with that error and stuck. my temporary solution is downgrading chrome. but i hope there's a fix for this problem. But for some friends also working with the 96 version

**Comment by adamraine** [comment] 2021-12-01 18:18
Looks like this might be a different issue than https://github.com/GoogleChrome/lighthouse/issues/13396. I can reproduce a `PROTOCOL_TIMEOUT` in Chrome Dev on Linux, but it happens in a different place:

```
LH:GatherRunner InstallabilityErrors:error LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:58
    at new Promise (<anonymous>)
    at Driver$1.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:10)
    at Driver$1.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:146:257)
    at Function.getInstallabilityErrors (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:200:350)
    at Function.populateBaseArtifacts (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:212:141)
    at async Function.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:213:281)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:358:413)
    at async Function.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:356:146)
    at async o (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4094e13ce4e84c33bff7d6f27d4b9d170483e0afa4%2F:1:1225) +0ms
```
Chrome: 98.0.4736.0

**Comment by mpiorowski** [comment] 2021-12-03 10:04
I have the same problem, lighthouse is stuck on "Auditing...." and not finishing. And it's not the html changes to my page, cos it was working in previous version.

Edge, Version 96.0.1054.43

**Comment by adamraine** [comment] 2021-12-03 17:02
@mpiorowski @krissastrabudi can you try on Chrome Canary (M98) with the flag `--disable-features=PlzServiceWorker`? Could you also provide URLs that are experiencing this?

@jirkapinus the `PROTOCOL_TIMEOUT` I was experiencing was fixed by `--disable-features=PlzServiceWorker`, but it's interesting because we typically see that timeout on sites with a service worker, and https://www.slunecno.cz/ doesn't have one. The `PROTOCOL_TIMEOUT` you are experiencing looks unrelated to service workers, but could you try `--disable-features=PlzServiceWorker` just in case?

**Comment by adamraine** [comment] 2021-12-03 20:02
Note: make sure to verify the flag is being used in `chrome://version`.

![Screen Shot 2021-12-03 at 3 01 22 PM](https://user-images.githubusercontent.com/6752989/144665504-d2fc2b82-0698-4f85-b9d0-89930ac53458.png)

**Comment by mpiorowski** [comment] 2021-12-03 21:10
@adamraine not working on the newest chrome canary, BUT WORKING with the flag :)

Is this a problem on my website or with the lighthouse?

**Comment by adamraine** [comment] 2021-12-03 21:20
> Is this a problem on my website or with the lighthouse?

It's an issue with Lighthouse/Chrome being tracked in https://github.com/GoogleChrome/lighthouse/issues/13396.

**Comment by mpiorowski** [comment] 2021-12-03 21:22
@adamraine Thank You for the help then :)

If it helps You in any way, my webpage is test.homeit.app, build using svelte.

**Comment by connorjclark** [comment] 2021-12-06 22:42
We think this is #6512, so we will close this issue.

**Closed by connorjclark** 2021-12-06 22:42 UTC
Labels: bug, needs-investigation, P1.5

**Comment by jirkapinus** [comment] 2021-12-07 05:30
Service Worker on Chrome stops work if cannot read some file and then isnt register (any error message). I changed serviceworker.js, repair my error in code and now Service Worker works and webpage can be install as PWA from Chrome. When I start generate lighthouse report, registration of Service Worker still doesnt happend but not it returns error message
 _No it didn't. This happened: DOMException: Failed to register a ServiceWorker for scope ('https://www.slunecno.cz/') with script ('https://www.slunecno.cz/service-worker.js'): Operation has been aborted_

**Comment by connorjclark** [comment] 2021-12-09 02:12
that is #13396
