### ISSUE TITLE
Extension Error: Cannot access contents of the page. Extension manifest mu...

### ISSUE THREAD

**Issue by meruggles** [GoogleChrome/lighthouse#2388] opened 2017-05-29 23:40 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 58.0.3029.110
**URL**: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/6678982e-6f14-42b5-96fb-b109dc97558f
**Error Message**: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
**Stack Trace**:
 ```Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at Object.chrome.debugger.attach._ [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11548:29)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by wardpeet** [comment] 2017-05-30 04:32
This is a duplicate of #1863.

Thanks for filing this bug

**Closed by wardpeet** 2017-05-30 04:32 UTC
