### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by IshaiA** [GoogleChrome/lighthouse#2494] opened 2017-06-13 08:44 UTC
**Lighthouse Version**: 2.1.0
**Chrome Version**: 58.0.3029.110
**Initial URL**: https://cpms.pointgrab.com/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14050:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14505:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14530:18)
    at <anonymous>
```

**Comment by wardpeet** [comment] 2017-06-13 20:24
dupe of #1834 can you try the CLI?

**Closed by wardpeet** 2017-06-13 20:24 UTC
Labels: duplicate, extension
