### ISSUE TITLE
INFO Error: not opened at WebSocket.send (/var/task/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:344:18)

### ISSUE THREAD

**Issue by Deepikajain77** [GoogleChrome/lighthouse#12153] opened 2021-03-01 08:41 UTC
Hi ,
 I have an application for fetching lighthouse score for multiple site using node module.But its always failing for 1 site and give INFO Error: not opened at WebSocket.send (/var/task/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:344:18).
the website provide score using chrome extn properly but not on node_module code.
"lighthouse": "^6.1.1",
Any pointer will be helpful

**Comment by adamraine** [comment] 2021-03-01 18:41
Can you share a URL for the site causing this failure?

**Comment by Deepikajain77** [comment] 2021-03-02 04:22
Hi,
This is happening at walls Indonesia.
For e.g.
https://www.wallsicecream.com/id/home.html
https://www.wallsicecream.com/id/brand-kami/viennetta.html

Thanks
Deepika

**Comment by adamraine** [comment] 2021-03-02 16:18
I am able to reproduce this in stable, but the crash appears to be fixed in M90. Possibly related to https://github.com/GoogleChrome/lighthouse/issues/12123.

Are you using stable Chrome to test LH? If you need this to work immediately, Canary and Dev channels should work.

**Comment by Deepikajain77** [comment] 2021-03-03 04:18
Could you lease check that for https://www.suave.com/us/en/kids/shampoo-conditioners.html as well

**Comment by connorjclark** [comment] 2021-03-03 04:34
Try upgrading from LH 6.1.1 to 7.2.0.

**Comment by Deepikajain77** [comment] 2021-03-03 11:08
Hi @connorjclark : i tried with v7.2.0 but its giving same error for  https://www.suave.com/us/en/kids/shampoo-conditioners.html 
@adamraine : we are using  "chrome-aws-lambda": "^3.1.1", which is seperate node module that contains the chromium.

**Comment by adamraine** [comment] 2021-03-03 16:06
https://github.com/alixaxel/chrome-aws-lambda#versioning

Looks like chrome-aws-lambda version 3.1.1 uses M83. The first version of that package to use M90 is 7.0.0.

**Comment by connorjclark** [comment] 2021-03-03 18:41
Should we catch the error when connecting to Chrome and print a friendlier message? "Check that Chrome is running and that the version is recent" or something.

**Comment by Deepikajain77** [comment] 2021-03-05 07:13
@adamraine we tried with chrome-aws-lambda v7.0.0 ,launch 72.0 and pupeteer 7.0.0 version but its still not working of that link.Weird issue is launch is working fine on at all 100+ sites except this one. Any other suggestion?

**Comment by adamraine** [comment] 2021-03-05 16:43
Are you referring to https://www.suave.com/us/en/kids/shampoo-conditioners.html? Unfortunately, I can't reproduce the failure on that site with the latest chrome and LH 7.2.0.

**Comment by paulirish** [comment] 2021-04-06 19:11
Unfortunately we don't support running Lighthouse on AWS. The websocket problem is certainly unexpected, especially for a single site.  

Best of luck.

**Closed by paulirish** 2021-04-06 19:11 UTC
Labels: needs-priority, pending-close
