### ISSUE TITLE
DevTools Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by alexfromgeneva** [GoogleChrome/lighthouse#2912] opened 2017-08-09 14:01 UTC
**Initial URL**: https://www.youtube.com/embed/7GhS7PNOSkQ?hl=EN

**Comment by ebidel** [comment] 2017-08-09 17:21
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2866

**Closed by ebidel** 2017-08-09 17:21 UTC
