### ISSUE TITLE
Issue with Google Tag Manager <noscript>

### ISSUE THREAD

**Issue by alanablett** [GoogleChrome/lighthouse#9748] opened 2019-09-27 11:16 UTC
#### Provide the steps to reproduce
Run LH on https://wd40.ca/

#### What is the current behavior?
Lighthouse reports PWA Issues

* Redirects HTTP traffic to HTTPS
* Contains some content when JavaScript is not available

#### What is the expected behavior?

Lighthouse does not report those issues

#### Resolution

It seems that the behaviour is related to the existence of the google tag manager `<noscript><iframe>` element on the page. Upon removing that element we see that both of the errors reported below disappear.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 5.2.0

**Comment by patrickhulce** [comment] 2019-09-27 15:07
Thanks for filing @alanablett! I'm not able to able to reproduce this issue though, everything passes on my end :/ 

Anything else about the repro steps might be relevant? Relevant settings or geo required to reproduce perhaps?

![image](https://user-images.githubusercontent.com/2301202/65780050-847bac00-e10e-11e9-9e91-d662e893dc20.png)

**Comment by alanablett** [comment] 2019-09-27 16:06
Thanks for your swift response @patrickhulce 

There should be no difference in terms of geo or set up.

I actually just ran the test via the CLI instead, using `lighthouse https://wd40.ca/` and `lighthouse https://wd40.ca/ --chrome-flags="--headless"` Seems that the headless browser doesn't have the issue. Screenshots below show the results. Any ideas what might be going on? Thanks

![STANDARD-wd40 ca_2019-09-27_16-42-31 report html](https://user-images.githubusercontent.com/1838355/65783916-c75a7580-e148-11e9-810b-ae35ebaf0179.png)
![HEADLESS-wd40 ca_2019-09-27_16-54-38 report html](https://user-images.githubusercontent.com/1838355/65783917-c75a7580-e148-11e9-8c49-549384d172ee.png)

**Comment by patrickhulce** [comment] 2019-09-27 16:25
Ah thanks for the screenshots!

Do you see the warning message about the interstitial and the question mark in place of the PWA score? Those indicate that something went wrong while loading the page. In your case with the iframe, it's a root cause of #9562 and fixed in 5.4.0 which was just released. If you update LH, it should go away 👍 

Going to close for now, but if latest LH doesn't fix the issue, feel free to chime back in :)

**Closed by patrickhulce** 2019-09-27 16:25 UTC
Labels: needs-more-info

**Comment by alanablett** [comment] 2019-09-27 21:47
I can confirm that updating to 5.4.0 fixed the "issue". Many thanks for your help @patrickhulce
