### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by theWando** [GoogleChrome/lighthouse#2778] opened 2017-07-28 14:33 UTC
**Initial URL**: https://roraimadelsur.com/
**Chrome Version**: 60.0.3112.78
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-09-26 22:55
dupe of #2174

**Closed by patrickhulce** 2017-09-26 22:55 UTC
Labels: pending-close
