### ISSUE TITLE
Lighthouse is warming up...

### ISSUE THREAD

**Issue by camakin** [GoogleChrome/lighthouse#13154] opened 2021-10-01 13:02 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.doorhandlecompany.co.uk/

### What happened?

When Genarating a report the Auditing your web page... Lighthouse is warming up ... just hangs.

Is this URL blocked now from receiving reports, I had been testing the site successfully over the last couple of days but now nothing. 

### What did you expect?

A report to appear

### What have you tried?

Other sites Lighthouse audit runs successfully.
Any site on this server will now not run a report tried on 2 separate systems.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

Lighthouse 8.3.0

### Chrome Version

Version 94.0.4606.61 (Official Build) (x86_64)

**Comment by patrickhulce** [comment] 2021-10-01 14:37
Thanks for filing @camakin! I can reproduce this issue.

Heads up team this appears to be a bug in DevTools. [When we evaluate `window.location.href`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/lighthouse/LighthouseController.ts;l=275-290?q=f:devtools%20%22window.location.href%22%20-f:out&ss=chromium) we get `undefined` even though the `window.location.href` is definitely defined. 
![image](https://user-images.githubusercontent.com/2301202/135638101-bfbc9fb8-fd7d-41fb-b80e-97537e0a7ec5.png)

It's currently unclear why it is undefined. The target appears to be correct and evaluating `window.location.href` in the console returns the correct result. I tested in M93 and this did not happen, so it's possible it's a chrome-side bug/change.

Possible fix: check that `result.object.value` is a valid URL before setting `inspectedURL` to it.

**Comment by patrickhulce** [comment] 2021-10-01 14:39
Oh dang, it's not just this URL, *every* URL fails with this 😱

**Comment by patrickhulce** [comment] 2021-10-01 15:23
Bisect is... 

You are probably looking for a change made after 908353 (known good), but no later than 908365 (first known bad).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/7227dbaa1316b93f4b5c7112f0e0b32c39ca90ac..067706859478f20ddec492715b5fc6592e791da7

Suspecting https://chromium.googlesource.com/chromium/src/+/2a4d05dea58d1a561f880e523abff7188095d69e ?

**Comment by patrickhulce** [comment] 2021-10-01 15:46
OK some more debugging along with a theory:

I opened DevTools on DevTools and explored some of the targets and execution contexts. Scripts provided below.

<details>
<summary>Debugging Scripts</summary>

```js
console.log(await (async() => {
    const mainTarget = SDK.TargetManager.instance().targets()[0];
    const runtimeModel = mainTarget.model(SDK.RuntimeModel);
    const executionContext = runtimeModel && runtimeModel.defaultExecutionContext();
    let inspectedURL = mainTarget.inspectedURL();
    if (!executionContext) {
      return inspectedURL;
    }

console.log(mainTarget)
    // Evaluate location.href for a more specific URL than inspectedURL provides so that SPA hash navigation routes
    // will be respected and audited.
    try {
      const result = await executionContext.evaluate(
          {
            expression: 'window.location.href',
            objectGroup: 'lighthouse',
            includeCommandLineAPI: false,
            silent: false,
            returnByValue: true,
            generatePreview: false,
            allowUnsafeEvalBlockedByCSP: undefined,
            disableBreaks: undefined,
            replMode: undefined,
            throwOnSideEffect: undefined,
            timeout: undefined,
          },
          /* userGesture */ false, /* awaitPromise */ false);

          console.log(result, executionContext)
      if ((!('exceptionDetails' in result) || !result.exceptionDetails) && 'object' in result && result.object) {
        inspectedURL = result.object.value;
        result.object.release();
      }
    } catch (err) {
      console.error(err);
    }

    return inspectedURL;

})());

Array.from(runtimeModel.executionContextById.values()).forEach(ec => ec.evaluate(
          {
            expression: 'window.location.href',
            objectGroup: 'lighthouse',
            includeCommandLineAPI: false,
            silent: false,
            returnByValue: true,
            generatePreview: false,
            allowUnsafeEvalBlockedByCSP: undefined,
            disableBreaks: undefined,
            replMode: undefined,
            throwOnSideEffect: undefined,
            timeout: undefined,
          },
          /* userGesture */ false, /* awaitPromise */ false).then(x => console.log(x.object.value, ec)))
```

</details>

The core issue is that `.defaultExecutionContext()` of the main target is returning an execution context that is *NOT* the main target's current execution context. My suspicion is that the CL is keeping around a zombie execution context that is no longer active.

![image](https://user-images.githubusercontent.com/2301202/135649519-a9f70e18-0954-4200-9614-2f65aab7315a.png)

True fix is using the correct execution context (which `defaultExecutionContext` should return), and Lighthouse stopgap for future regressions should be checking that window.location.href is a valid URL.

**Comment by Mbellsudteen** [comment] 2021-10-02 05:13
ในวันที่ ศ. 1 ต.ค. 2021 20:03 น. camakin ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment] 2021-10-02 05:44
ในวันที่ ศ. 1 ต.ค. 2021 22:47 น. Patrick Hulce ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment] 2021-10-02 05:47
ในวันที่ ศ. 1 ต.ค. 2021 22:24 น. Patrick Hulce ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment] 2021-10-02 05:48
ในวันที่ ศ. 1 ต.ค. 2021 21:40 น. Patrick Hulce ***@***.***>
เขียนว่า:

**Comment by Mbellsudteen** [comment] 2021-10-02 05:49
ในวันที่ ศ. 1 ต.ค. 2021 21:38 น. Patrick Hulce ***@***.***>
เขียนว่า:

**Comment by paulirish** [comment] 2021-10-05 19:14
Two relevant CLs from long ago:

1. [DevTools: Audits2 use location.href when available - Code Review](https://codereview.chromium.org/2895913003)
1. [DevTools: return the correct defaultExecutionContext (I56a1ebd0) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/570921/)

I've put up  https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3206615 for review. it uses `mainTarget.inspectedURL()` if the `location.href` evaluate comes back undefined. also we know that `mainTarget.inspectedURL()` is a valid URL cuz its only set [if the URL is valid](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/sdk/Target.ts;l=171;drc=f290aeebbcf4f9e5662a184a9c6afc964f4a602a).

**Comment by connorjclark** [comment] 2021-10-05 23:31
related https://bugs.chromium.org/p/chromium/issues/detail?id=1252014

**Comment by tblakers** [comment] 2021-10-22 03:34
I downloaded the latest Canary, and it no longer gets stuck "warming up". However, it doesn't ultimately go on to complete on the pages which are not working on stable.

For example:

https://restaurantguru.com/

Other pages continue to work correctly.

**Comment by lewisgauss** [comment] 2021-10-30 06:02
> Could you also try in latest Chrome Canary? We merged a fix ~10 days ago so it should be fine now.
> 
> > works for the first run after application restart and freezes on subsequent runs ... I feel like this assessment from 10 days ago might not be correct.
> 
> Indeed, my testing was automated and restarted Chrome every time, so your experience gives some insight.

Is this fixed on Chrome Version 97.0.4686.0 (Official Build) canary (64-bit)? I just tested it on both my own website and the sample https://www.doorhandlecompany.co.uk/, it's not working. The test is stuck at "lighthouse is warming up".

**Comment by connorjclark** [comment] 2021-11-01 19:44
We're experiencing multiple issues/root causes here and #13237, it seems. We need some time to sift through the bug reports. In the meantime, please ensure you've provided the following to help us resolve this:

1) URL
2) Details on what Chrome version you are using (`chrome://version`)
3) If you can, running on latest Canary (and providing the Chrome version too)

**Comment by fraitag** [comment] 2021-11-03 11:54
1. https://www.onet.pl/

2. Google Chrome	95.0.4638.69 (Official Build) (64-bit) (cohort: Stable)
Revision	6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS	Windows 10 Version 21H1 (Build 19043.1288)
3. 
Google Chrome	97.0.4690.0 (Oficjalna wersja) canary (64-bitowa) (cohort: Clang-64)
Revision	dbf04dbd0a62049e8a1b67d268918afc12c48c6b-refs/branch-heads/4690@{#1}

**Comment by kevinebaugh** [comment] 2021-11-12 18:38
1. https://ifttt.com
1. 👎 in 95.0.4638.69 (Official Build) (arm64)
1. 👍 in Canary 98.0.4701.0 (Official Build) canary (arm64)

**Comment by connorjclark** [comment] 2021-11-19 00:43
The issue for the original url https://www.doorhandlecompany.co.uk/ was solved by https://chromiumdash.appspot.com/commit/7e11a25ec77fc1a579a09195263f9902e06ae1bf and will is fixed in Chrome 97.

All other issues about a report hanging are likely related to SW/installability checks. Tracking those in #13396, please follow there.

**Closed by connorjclark** 2021-11-19 00:43 UTC
Labels: bug, DevTools, P1

**Comment by nhoizey** [comment] 2023-04-13 09:00
I currently have this issue with `Chrome 112.0.5615.49 (Build officiel) (arm64)`.

I tried on several sites including google.com, restarted Chrome, it hangs with `warming up`…

**Comment by thetalesofj** [comment] 2023-04-16 14:42
> I currently have this issue with `Chrome 112.0.5615.49 (Build officiel) (arm64)`.
> 
> I tried on several sites including google.com, restarted Chrome, it hangs with `warming up`…

I'm having the same issue on several sites too.

**Comment by adamraine** [comment] 2023-04-17 15:55
Hi folks, this issue is very old and is probably caused by something different than what you are experiencing. Please fill out a new bug report.
