### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by pfernandom** [GoogleChrome/lighthouse#2564] opened 2017-06-22 05:48 UTC
**Lighthouse Version**: 2.1.0
**Chrome Version**: 59.0.3071.104
**Initial URL**: http://localhost:8080/#/
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10812:17)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-22 17:43
dupe of #1685

**Closed by patrickhulce** 2017-06-22 17:43 UTC
