### ISSUE TITLE
Bring "Download as PDF"/"Print to PDF" to DevTools

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3601] opened 2017-10-17 23:30 UTC
Sales team would love to have a way for them to share and save reports to send out. I think this is worth doing. 

------

EDIT: it appears that printing to PDF is supported across mac & linux. yay.

**Comment by patrickhulce** [comment] 2017-11-01 20:57
dupe of #3564

**Closed by patrickhulce** 2017-11-01 20:57 UTC
Labels: DevTools, P1
