### ISSUE TITLE
Lighthouse doesn't run in DevTools on Chromium Linux

### ISSUE THREAD

**Issue by stramel** [GoogleChrome/lighthouse#2627] opened 2017-06-30 20:30 UTC
EDIT: All chromium users with a non-matching git hash don't get the audits2 remote module. Unfortunately a diff bug than the chromeOS one.

---------

I'm running a Asus Chromebook C302CA on the Beta Channel. 

Chromium 60

When I go to my website and try to run the lighthouse audit on it, it just spins and never does anything other than switch to a mobile view.

**Comment by patrickhulce** [comment] 2017-06-30 20:34
@stramel got a URL for us?

**Comment by stramel** [comment] 2017-06-30 21:23
It was https://d-citrix.salesnext.com/login but it did work using the extension.

**Comment by patrickhulce** [comment] 2017-06-30 21:24
Hm yeah seems to be working fine in Canary as well

**Comment by stramel** [comment] 2017-06-30 21:56
@patrickhulce it was only with the audit through dev tools on my Chromebook. I didn't get any error messages either. I ended up having to close the tab to kill the audit.

**Comment by patrickhulce** [comment] 2017-09-28 22:23
We're unable to reproduce with latest version, please re-comment if you're still experiencing this to re-open!

**Comment by stramel** [comment] 2017-11-18 20:41
@patrickhulce I am still able to reproduce this.

Chromium Version 62.0.3202.89 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Lighthouse 2.6.0


Works with the Chrome Extension doesn't work with the DevTools.

Can you please re-open?

**Comment by patrickhulce** [comment] 2017-11-20 17:10
@stramel I'm able to audit that page in both Chrome Stable and Canary DevTools on both OS X and Ubuntu. Can you provide more information on steps you take and precisely what behavior you observe?

**Comment by stramel** [comment] 2017-11-20 17:36
@patrickhulce I don't think my steps are that abnormal...

### Steps to Reproduce w/ Extension

1. Open **Chromium** 62
1. Check Extension settings, Ensure Lighthouse is allowed to run in incognito
1. Open an incognito tab
1. Navigate to https://d-demo-ci.salesnext.com/login
1. Click the lighthouse extension icon
1. Click "Generate Report"
1. Wait for successful finish

Works as Expected

### Steps to Reproduce w/ Dev Tools

1. Open **Chromium** 62
1. Open an incognito tab
1. Navigate to https://d-demo-ci.salesnext.com/login
1. Open Dev Tools
1. Click the "Audits" tab
1. Click "Perform an audit..."
1. Click "Run audit"

**Expected:** Same results as extension
**Actual**

**Comment by patrickhulce** [comment] 2017-11-20 18:00
Hm, strange. I cannot reproduce on this new URL either, but the behavior you're describing seems like DevTools has lost its connection to the tab and not actually started Lighthouse at all. "Loading" should almost immediately be replaced by "Loading page & waiting for onload..." in normal operation.

Are you able to successfully audit *any* page in DevTools?

**Comment by stramel** [comment] 2017-11-20 18:11
@patrickhulce I am **not** able to successfully audit any page using the DevTools.

Tested usatoday.com and github.com

**Comment by stramel** [comment] 2017-11-20 18:19
@patrickhulce The issue is directly an issue with using **Chromium** not Chrome. I downloaded Google Chrome (stable) and ran the audit using DevTools, everything worked as expected.

**Comment by patrickhulce** [comment] 2017-11-20 18:22
Ahhhh thanks for identifying @stramel! We'll have to explore this. Could you provide steps for how you're installing/building Chromium?

**Comment by stramel** [comment] 2017-11-20 18:51
Mine comes with my OS, Gallium OS, which is specifically built for Chromebooks. It is listed as `chromium-browser` recommended under `galliumos-desktop` package.

**Comment by devsware** [comment] 2017-12-15 15:11
If this can help, the same issue (as explained and documented by @stramel ) happens running Lighthouse via **Chromium 63** Developers Tools on **Linux Mint** (installed via apt). 

On the same PC, Lighthouse on Google Chrome Version 63.0.3239.84 (Official Build) (64-bit) works as expected and completes the audits.

This is the "About Chromium" content:
Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

**Comment by hhofstaetter** [comment] 2017-12-18 13:15
The same issue happens on Chromium 63 under Ubuntu installed from official apt repos:
> Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by paulirish** [comment] 2018-01-02 20:43
I'm guessing the remote module download fails due to an unmatched git hash. 

see also #4132, which has an upstream bug at https://crbug.com/747349

**Comment by nzhuk98** [comment] 2018-02-10 08:57
I can consistently reproduce the same exact issue described in https://github.com/GoogleChrome/lighthouse/issues/2627#issuecomment-345770177 in Debian 9.3 Stretch.

Installed from stretch/updates/main:
> Version 64.0.3282.119 (Developer Build) built on Debian 9.3, running on Debian 9.3 (64-bit)

Version 62 from stretch/main doesn't work either:
> Version 62.0.3202.89 (Developer Build) built on Debian 9.1, running on Debian 9.3 (64-bit)

**Comment by jasomdotnet** [comment] 2018-02-14 07:17
I confirm this issue too:

> Version 64.0.3282.119 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (32-bit)

Lighthouse never finish the loading. Long live to [Webpagetest](https://www.webpagetest.org/) :-)

**Comment by N0ps32** [comment] 2018-03-09 12:16
I have the same issue on

> Version 64.0.3282.186 (Official Build) (64-bit)

On
> Version 65.0.3325.106 (Official Build) beta (64-bit)

Lighthouse does finally start running tests. but after it finishes no report is being generated.

OS: Arch Linux

**Comment by Serkan-devel** [comment] 2018-03-21 16:23
Same on 
`Chromium:	64.0.3282.119 (Entwickler-Build) built on Debian 9.3, running on Debian 9.4 (64-Bit)`

**Comment by Serkan-devel** [comment] 2018-03-21 16:45
Has the reason why it's happening already been found?

**Comment by patrickhulce** [comment] 2018-03-21 17:32
@Serkan-devel Yes remote modules are not supported on all Chrome versions, see [root cause crbug](https://crbug.com/747349) for discussion

**Comment by Serkan-devel** [comment] 2018-03-21 19:48
the link isn't viewable on my end, even when logged in

**Comment by patrickhulce** [comment] 2018-03-21 20:07
Ah, apologies didn't realize it's restricted. 

Summary: remote devtools modules (such as audits/a11y/device frames/network "product" labels/etc) are not supported for some Chrome build processes, Chrome OS and Chromium Linux for example. Fix has landed in ToT for Chrome OS.

**Comment by Serkan-devel** [comment] 2018-04-24 19:16
How far is it for the fix to to be ported from ChromiumOS to other Linux distros?

**Comment by mnalis** [comment] 2018-05-16 18:17
Chromium also hang here after displaying "Lighthouse is warming up..."
on Version 66.0.3359.117 (Developer Build) built on Debian 9.4, running on Debian 9.4 (64-bit)

in console there is error:
[`8627:8627:0516/201607.774326:ERROR:CONSOLE(1)] "Uncaught (in promise) SyntaxError: Invalid or unexpected token", source: chrome-devtools://devtools/bundled/audits2_worker.js?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@1634af79e3bf0d6f0178a5fdb8829b059ead4b26/ (1)
`

**Comment by stefanmaric** [comment] 2018-06-04 13:09
For me it also hangs on "Lighthouse is warming up..." using stable build:

```
Version 66.0.3359.181 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
```

**Comment by Serkan-devel** [comment] 2018-06-04 14:04
Is there any progress

**Comment by patrickhulce** [comment] 2018-06-04 16:57
Yes there's been plenty of discussion on the already referenced CR bug, if you're interested in following along. The fix is in Chromium and is tracked by [that bug](https://bugs.chromium.org/p/chromium/issues/detail?id=747349)

**Comment by patrickhulce** [comment] 2018-06-04 17:10
There has been some progress, yes. Chrome OS is now bundled directly and should work in m69.

Chromium builds are still blocked, but there's a proposed approach that might work in most cases. Likely 1-2 releases out still.

**Comment by devsware** [comment] 2018-07-26 13:43
It's a good news for Debian users, but unfortunately it still freezes on `Version 67.0.3396.99 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)`

**Comment by Serkan-devel** [comment] 2018-07-26 13:48
@devsware your version looks a little newer than mine. And isn't there a significant difference between debian and debian based distros, like ubuntu/mint?

**Comment by N0ps32** [comment] 2018-07-27 12:47
Also works on Arch Linux now!

**Comment by jasonworden** [comment] 2018-12-18 04:39
Does Lighthouse's Chrome Launcher support Chromium by default, if Chrome or Chrome Canary are not installed?

Would I need to specify the Chromium path by the ` CHROME_PATH` flag? (looking at https://www.npmjs.com/package/lighthouse)

**Comment by patrickhulce** [comment] 2018-12-19 01:36
@jasonworden if it's on your path already and you're on linux, yes!

https://github.com/GoogleChrome/chrome-launcher/blob/6316362c585ad1dfd85562d488d0f2644fcdca15/src/chrome-finder.ts#L111-L117

**Comment by brendankenny** [comment] 2019-04-30 22:38
Looks like this is more or less fixed now that the remote module bug is fixed and released.

**Closed by brendankenny** 2019-04-30 22:38 UTC
Labels: DevTools, P2, bug, needs-investigation

**Comment by RogerBytes** [comment] 2023-10-06 07:08
Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)
