### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by lpongetti** [GoogleChrome/lighthouse#1899] opened 2017-03-24 09:23 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.98
**URL**: https://visidev.test.namirialtsp.com/demo/conference/?id=1234567891234567
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13600:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14685:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14711:18)```

**Comment by ebidel** [comment] 2017-03-27 05:46
Dupe of #1819

**Closed by ebidel** 2017-03-27 05:46 UTC
