### ISSUE TITLE
Extension should run without pollution from other extension/content scripts.

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1289] opened 2016-12-24 00:30 UTC
As discovered in https://github.com/GoogleChrome/lighthouse/issues/1282, many extensions inject content scripts and do other funky things to the page. When we run our audits, we quickly bump into issues on page that call `Date.now()`, overwrite apis, etc.

Running lighthouse on the CLI also produces different perf results than the crx. We're in a clean env without extensions :)

**Comment by wardpeet** [comment] 2016-12-26 21:17
Would be nice to find out contentScripts like devtools does so we can warn the user
![image](https://cloud.githubusercontent.com/assets/1120926/21486696/10ebf564-cbb9-11e6-9318-616ca2fd1b4e.png)

**Comment by brendankenny** [comment] 2017-09-26 21:54
dupe of #1689?

**Comment by paulirish** [comment] 2018-01-16 23:54
We moved to use an isolatedWorld. So this is fixed!

**Closed by paulirish** 2018-01-16 23:54 UTC
Labels: needs-priority
