### ISSUE TITLE
Extension Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by SeriousM** [GoogleChrome/lighthouse#1397] opened 2017-01-04 16:56 UTC
**Lighthouse Version**: 1.3.2
**Chrome Version**: 56.0.2924.28
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.DateNowUse.usage.filter.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1054:24)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1050:48)```

This error happens when generating an report for https://www.reddit.com/r/personalfinance/

**Comment by wardpeet** [comment] 2017-01-04 17:13
Dupe of #1282.

**Closed by wardpeet** 2017-01-04 17:13 UTC
