### ISSUE TITLE
"properly size images" advises 100% potential savings

### ISSUE THREAD

**Issue by GuillaumeRossolini** [GoogleChrome/lighthouse#4402] opened 2018-01-31 16:11 UTC
Hi,

While trying out Lighthouse in Chrome's DevTools, the report tells us we should be able to reduce global download by properly sizing images to save celllular data. However, the report then provides a list of images with potential savings of 100%. Image compression can usually be improved upon, but this seems to be a tad optimistic.

Here is an example of Lighthouse's output reporting this:
https://drive.google.com/open?id=1nDpR007OREh9frIg2GvlNa7EEB7S6ZU5

I thought this was due to missing `height`/`width` attributes on some `<img>` tags, but that's not the case. It might however be due to image visibility.

I am currently using: Chrome version 66.0.3335.0 (Build officiel) canary (64 bits) on Windows 10 v1709 b16299.192

**Comment by vinamratasingal** [comment] 2018-02-01 17:36
Hi- what version of Lighthouse are you using? Is this 2.8?

**Comment by midzer** [comment] 2018-02-01 17:53
Probably dupe of https://github.com/GoogleChrome/lighthouse/issues/3508

**Comment by GuillaumeRossolini** [comment] 2018-02-01 18:39
@vinamratasingal I didn't check- it's the version that ships with Chrome, of which I provided the version number (canary channel and up to date so I'd say probably one of the most recent versions of LH)
@midzer yes probably, my bad if I didn't use the right search terms; the example I provided is from InstantLuxe.com where images are indeed lazy-loaded most of the time

**Comment by vinamratasingal** [comment] 2018-02-01 18:42
If this is a dupe of #3508, then I propose closing this bug in favor of the other one. If not, feel fre to reopen and we can take a deeper look.

**Closed by vinamratasingal** 2018-02-01 18:42 UTC
Labels: needs-investigation, needs-more-info
