### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by hanjeahwan** [GoogleChrome/lighthouse#2656] opened 2017-07-08 09:20 UTC
**Initial URL**: https://www.jobstore.com/
**Chrome Version**: 61.0.3141.7
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@d5df4ad8983872374dad86bee9d1fa31299114f7/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ev1stensberg** [comment] 2017-07-08 16:30
Dupe of #1091, let's stack the similar issues up there.

**Closed** 2017-07-10 17:22 UTC
Labels: duplicate
