### ISSUE TITLE
Service worker does not successfully serve the manifest's start_url

### ISSUE THREAD

**Issue by frvge** [GoogleChrome/lighthouse#5828] opened 2018-08-13 13:47 UTC
#### Provide the steps to reproduce
1. Run LH on https://www.trivago.nl

#### What is the current behavior?
Failed PWA audit of:
```
User will not be prompted to Install the Web App
Failures: Service worker does not successfully serve the manifest's start_url, Timed out waiting for fetched start_url.
```

#### What is the expected behavior?
Passed audit.

Our QA department is able to add it to the home screen of Android.

#### Environment Information
* Affected Channels: Chrome Extension / CLI
* Lighthouse version: 3.0.3
* Node.js version: N/A for extension   / v8.11.3 based on https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile
* Operating System: MacOS / Debian host OS for Docker

**Related issues**
#4541
#4261

**Comment by patrickhulce** [comment] 2018-08-14 05:56
Thanks for reporting @frvge I can reproduce this! I'm seeing a sizeable delay to serve the primary document of your page, it's possible that the service worker isn't able to cache the resources in time before we move on. Are you also getting ~1s+ download times for your primary document even on fast connections?

**Comment by patrickhulce** [comment] 2018-08-14 05:57
cc @wardpeet in case you've got ideas from your recent debugging of start URL :)

**Comment by frvge** [comment] 2018-08-14 07:49
For cross-continent connections, it can take a bit more than 1 sec. If you want you can test with https://www.trivago.com . During my last run of that, I saw that it hit our start_url and still failed the audit.

**Comment by wardpeet** [comment] 2018-08-16 20:57
I'm from belgium so .nl should be fast enough. Even when moving the threshold to 30s it still returns `Timed out waiting for fetched start_url`

When running lighthouse on trivage it starts to reload the page every x time, not sure why this only happens on lighthouse run. @frvge is this something you can help us with?
I ran `node lighthouse-cli/index.js https://www.trivago.nl/`

![trivago - reload](https://user-images.githubusercontent.com/1120926/44234797-c0241280-a1a7-11e8-99b3-24b1784bfe5e.gif)

**Comment by frvge** [comment] 2018-08-16 22:26
I haven't seen that behavior yet. I will try to reproduce it and get back to you with the results.

**Comment by wardpeet** [comment] 2018-09-09 17:51
@frvge could you explain what's happening here? 😀 Maybe we can add something to lighthouse to make it more robust

**Comment by tomdwyer** [comment] 2018-09-10 09:14
Hey @wardpeet. We suspect the issue may be down to a redirect in our start_url that lighthouse may have some troubles with. The two components that are flashing are both client-side rendered and are naturally flashing because the page seems to be constantly reloading. We're now trying to confirm if it's reloading because of the redirect.

**Comment by wardpeet** [comment] 2018-09-17 19:27
ok i'm going to close this as it seems like trivago is the only one having this issue if it's an issue on our side or something we can fix please create a new issue.

**Closed by wardpeet** 2018-09-17 19:27 UTC
Labels: P1.5, needs-investigation, needs-more-info, pwa

**Comment by rbjarnason** [comment] 2019-01-10 16:20
@wardpeet We are also having this issue, getting this same error but the app installs and works correctly on iPhone and Android.

We are using:
"start_url": "/?utm_source=web_app_manifest"

have also tried (which also works for install Android):
"start_url": "./?utm_source=web_app_manifest"

If we change it the URL below the error in Lighthouse disappears but the app does not work after install as this path is not available, the only valid paths in our app are "/" and then dynamically generated paths:
"start_url": "./index.html?utm_source=web_app_manifest"

We do "internal app" redirect quickly in the app when it loads from "/" to for example "/domain/1" or other paths based on the hostname, could also go to "/community/123".

I've Google for hours before writing a comment to this ticket but have not found any solutions. The only thing I can think of is to support "/html.index" in the PWA routing and have that path redirect to "/" but that would just be a hack to get Lighthouse working and not might even work if there is a bug in Lighthouse that fails to deal with PWA routing.

Here is our sw config: https://github.com/CitizensFoundation/your-priorities-app/blob/master/client_app/sw-precache-config.js

Here is the manifest starturl generated: https://github.com/CitizensFoundation/your-priorities-app/blob/master/server_api/utils/manifest_generator.js#L51 

Here is the live app: https://yrpri.org/

**Comment by rbjarnason** [comment] 2019-01-10 17:53
@wardpeet Never mind, I found something that had changed since I had a 100% PWA score.

We were adding video support to our platform and I changed the regex not to cache any media and when I changed to back to caching everything then I'm back to 100% PWA score :) I just hope there will be no issues regarding caching videos in the ServiceWorker.

So I changed the sw config regex runtimeCaching from:
urlPattern: /(.html|.js|.json|\/api\/)/,

back to:
urlPattern: /\/(.*)/

**Comment by bobmcgurk** [comment] 2020-02-21 23:05
Need to add code to your /index.html file:

`<link rel="manifest" href="manifest.json">`

Also helpful to include:

`<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="application-name" content="yourtitlename">
<meta name="apple-mobile-web-app-title" content="yourtitlename">
<meta name="theme-color" content="#343a40">
<meta name="msapplication-navbutton-color" content="#343a40">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="msapplication-starturl" content="/https://yoururl.com">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="icon" type="image/png" sizes="192x192" href="img/homescreen192.png">
<link rel="apple-touch-icon" type="image/png" sizes="192x192" href="img/homescreen192.png">
<link rel="icon" type="image/png" sizes="512x512" href="img/homescreen512.png">
<link rel="apple-touch-icon" type="image/png" sizes="512x512" href="img/homescreen512.png">`
