### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by gcornhill** [GoogleChrome/lighthouse#2149] opened 2017-05-04 16:37 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 56.0.2924.87
**URL**: https://www.oppenheimerfunds.com/advisors/events
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by stramel** [comment] 2017-05-04 16:56
Maybe dupe of #1091

**Closed** 2017-05-04 16:59 UTC
Labels: duplicate
