### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by rmorales2016** [GoogleChrome/lighthouse#2302] opened 2017-05-18 16:18 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 58.0.3029.110
**URL**: https://ivf-dev.com/trending/deals
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by patrickhulce** [comment] 2017-05-18 16:22
dupe of #1091

**Closed by patrickhulce** 2017-05-18 16:22 UTC
Labels: duplicate
