### ISSUE TITLE
lighthouse Report: PWA - Report save option popup not working.

### ISSUE THREAD

**Issue by SWGeekPD** [GoogleChrome/lighthouse#9742] opened 2019-09-26 11:31 UTC
After running the lighthouse report by selecting all the below option I am able to click on 3 dots to save the report in any format like Html, JSON.
1. Performance
2. Progressive Web App
3. Best Practices
4. Accessibility
5. SSO

But If I unselct any of above option for lighthouse report than  click on 3 dots is not showing any option.

**Comment by exterkamp** [comment] 2019-09-26 16:02
What method are you using to get these reports, then view them? CLI, DevTools, Extension, LH Viewer?

**Comment by SWGeekPD** [comment] 2019-09-29 07:08
@exterkamp  I am simply doing F12 (Dev Tool) and than selecting the option of Audits.

**Comment by exterkamp** [comment] 2019-09-30 05:31
I ran it without A11y, and got all the options, do you have a screenshot? What Chrome version is it, and what browser version, and what OS?
![image](https://user-images.githubusercontent.com/6392995/65851694-ab053700-e308-11e9-9335-5e69f0916965.png)

**Comment by SWGeekPD** [comment] 2019-10-01 16:45
@exterkamp  You skip the accessibility option from the Audit.
I am using below versions.
Chrome 77 
Windows 10
<img width="506" alt="lightHouseBug" src="https://user-images.githubusercontent.com/33997468/65982230-77591700-e498-11e9-8a38-2b28f85ae038.PNG">

I unselected performance option in the audit.
And I can see the result but after unselecting any of the option as mentioned in the bug I am not able to download it.
As you can see in below image now I selected all 5 option for Audit so download option is coming.

<img width="482" alt="lightHouseBug1" src="https://user-images.githubusercontent.com/33997468/65982369-d159dc80-e498-11e9-8416-99cc080b3291.PNG">

**Comment by connorjclark** [comment] 2019-10-01 17:27
root cause was fixed for chrome 78: https://chromium-review.googlesource.com/c/chromium/src/+/1745287

**Comment by exterkamp** [comment] 2019-10-01 17:28
> @exterkamp You skip the accessibility option from the Audit.

You said "unselect any" 😉

But upon unselecting the "performance" category this has a repro. As @connorjclark said, it should be fixed in Chrome M78+.

**Comment by connorjclark** [comment] 2019-10-01 19:04
You can use Chrome Canary (or Beta) to work around this for now.

**Closed by connorjclark** 2019-10-01 19:04 UTC
