### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by xereda** [GoogleChrome/lighthouse#1751] opened 2017-02-18 14:35 UTC
**Lighthouse Version**: 1.5.2
**Chrome Version**: 56.0.2924.87
**URL**: http://homologa.docmob.com.br/

**Comment by ebidel** [comment] 2017-02-18 18:53
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2017-02-18 18:53 UTC
Labels: duplicate
