### ISSUE TITLE
'Speed Index' breaks when going too fast ;)

### ISSUE THREAD

**Issue by alystair** [GoogleChrome/lighthouse#10959] opened 2020-06-15 01:08 UTC
#### Provide the steps to reproduce
1. Run LH 'Performance' category on https://pagedriver.org, under 'Desktop' device.

#### What is the current behavior?

Speed index breaks when a site is... very fast 🔥

![image](https://user-images.githubusercontent.com/159109/84608985-eb024f00-ae82-11ea-9b86-4b03be195294.png)

#### What is the expected behavior?

An actual number :D

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:  Whatever's in latest Canary
* Chrome version: 85.0.4172.0 (Official Build) canary (64-bit) (cohort: Clang-64)
* Node.js version:
* Operating System: Win 10 Pro x64

**Related issues**

**Comment by alystair** [comment] 2020-06-15 02:12
Also ended up breaking on a non-static page which I guess was pretty optimized
![image](https://user-images.githubusercontent.com/159109/84611485-058cf600-ae8c-11ea-96c2-cf29c7d3ec67.png)

**Comment by connorjclark** [comment] 2020-06-15 05:01
Doesn't seem to happen in 5.6.0, I wonder what changed in 6.0.

@paulirish this does remind me of when we dug into the SI calculation and noticed a bad edge case. don't recall the specifics.

**Comment by alystair** [comment] 2020-06-15 05:20
Also happening in 84.0.4147.45 (Official Build) beta (64-bit) (cohort: Beta) - For personal reference, how do I find out the version of Lighthouse within DevTools?

**Comment by connorjclark** [comment] 2020-06-15 06:28
It's at the bottom of the report.

**Comment by patrickhulce** [comment] 2020-06-15 15:53
Hm, extra DevTools-specific too! What's even weirder is that when I take the trace from a devtools run and use it in a local `-A` run I get a valid speed index, no problems...

**Comment by paulirish** [comment] 2020-10-19 21:45
dupe of #11154 

> Yes it should be fixed in Chrome Canary and is part of Chrome 86 (becomes stable in October).

**Closed by paulirish** 2020-10-19 21:45 UTC
Labels: DevTools, needs-investigation, needs-priority
