### ISSUE TITLE
https://www.rateablevaluations.com/

### ISSUE THREAD

**Issue by RateableValuations** [GoogleChrome/lighthouse#9571] opened 2019-08-17 11:14 UTC
I am reporting a bug with PageSpeed Insights as it returns a score of 0 for https://www.rateablevaluations.com/ please look into this?

**Comment by RateableValuations** [comment] 2019-08-17 11:15
You can contact us at info@rateablevaluations.com

**Comment by patrickhulce** [comment] 2019-08-17 13:34
This is not a bug. The performance metrics for this page are very, very bad. There is over 5MB of uncompressed, render-blocking script that should be fixed.

**Closed by patrickhulce** 2019-08-17 13:34 UTC
