### ISSUE TITLE
Performance Audit also include the chrome extensions as the JavaScript boot-up time

### ISSUE THREAD

**Issue by wahyubucil** [GoogleChrome/lighthouse#4733] opened 2018-03-12 15:08 UTC
![capture](https://user-images.githubusercontent.com/30768993/37291476-ad426196-2649-11e8-8243-21dc2def01f4.PNG)

I just do the performance audit and confused with my JavaScript boot-up time because the audit said is too high. After i check it. It's all because my extension from Google Chrome. The extension is Wappalyzer. Wappalyzer is extension for seeing the technology behind website. I hope script from extension not include in JavaScript boot-up time performance audit. Thank You!

**Comment by addyosmani** [comment] 2018-03-12 20:28
Two things off the top of my mind:

1. I wonder if we can distinguish better between boot-up time introduced from an extension vs. the site itself so those content_script.js entries are clearer. I could imagine someone unfamiliar with them to be pretty surprised an otherwise well performing site has those entries. At minimum, maybe some additional warning text for this audit?

2. Curious if it makes sense to detect the presence of extensions (other than Lighthouse) running and provide some sort of top-level message encouraging folks to disable them or run in a cleaner profile if they want accurate performance results. Comes back to https://developer.chrome.com/devtools/docs/clean-testing-environment

**Comment by paulirish** [comment] 2018-03-12 22:00
Our challenge is that we can't report accurate performance numbers since we know a chrome extension is on the page and can be affecting performance quite a bit.

We can hypothetically remove it from JS Bootup Time, but we can't model how the performance metrics would be adjusted if the extension weren't present. So we'd rather take the approach of summarize ALL the costs and let you handle them.

Incognito is a quick way to test things without extensions getting in the way.

cc #3776, #4013 #3600

Current proposal is:

1. we visually annotate rows in the report where the named resource is from a chrome extension. 
   - v2: we do the same for 3rd party domains
2. We look at the bootup-time audit and if there are chrome extensions spending "lots of" main thread time, then we add a topLevelWarning in the report for the user, including a recommendation to use incognito. 


closing as a dupe of #4013 but please tell me how that sounds!

**Closed by paulirish** 2018-03-12 22:00 UTC

**Comment by huuthang1993** [comment] 2018-10-02 07:43
Incognito tab is nice

**Comment by UisgeBeatha436** [comment] 2019-03-02 14:07
> Incognito is a quick way to test things without extensions getting in the way.

How to start lighthouse when in incognito mode? The icon-extension in the browser is only visible when one is not in incognito mode.
