### ISSUE TITLE
Issue building v1.6.5 CLI

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/lighthouse#2134] opened 2017-05-03 16:41 UTC
I am getting the following problem when building v1.6.5 CLI:

> lighthouse-cli@ build /lighthouse/lighthouse-cli
> tsc

bin.ts(215,12): error TS2345: Argument of type '() => Promise<any[]> | undefined' is not assignable to parameter of type '((reason: any) => any[] | PromiseLike<any[]>) | null | undefined'.
  Type '() => Promise<any[]> | undefined' is not assignable to type '(reason: any) => any[] | PromiseLike<any[]>'.
    Type 'Promise<any[]> | undefined' is not assignable to type 'any[] | PromiseLike<any[]>'.
      Type 'undefined' is not assignable to type 'any[] | PromiseLike<any[]>'.

npm ERR! Linux 4.9.13-moby
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lighthouse-cli@ build: `tsc`
npm ERR! Exit status 2

**Comment by paulirish** [comment] 2017-05-03 17:40
a guess: perhaps the dependency versions are different if things were installed with npm. (looks like you're doing `npm run`.) did you install via yarn?

**Comment by juliantoledo** [comment] 2017-05-03 19:18
I didn't use yarn, I did:
`git clone https://github.com/GoogleChrome/lighthouse.git`
`cd lighthouse/`
`git checkout tags/v1.6.5`
`npm install`
`npm run install-all`
`cd lighthouse-cli/`

Then I tried `npm run build` and `npm run dev` 

I am using node v6.8.1

**Comment by juliantoledo** [comment] 2017-05-03 19:19
@patrickhulce yes, 3828c17a15b5cfb0eeac6ae2fb887a4e4e5e82fd.

**Comment by patrickhulce** [comment] 2017-05-03 20:21
> I also tried, yarn install-all for all 1.6.X tagged version and I could only build it at v1.5.2

Unfortunately `install-all` on `v1.6.5` explicitly calls `npm install` in each repo instead of `yarn` 😆 (fixed in master). I can repro your issue though and looks like the problem is typescript 2.3.2 vs. 2.2 in our yarn.lock. 

I could fix the problem by running `cd lighthouse-cli && yarn` or manually installing version 2.2 `cd lighthouse-cli && npm install typescript@2.2.0`.

**Comment by juliantoledo** [comment] 2017-05-04 07:56
@patrickhulce good catch! That fixed it, thank you!

**Comment by patrickhulce** [comment] 2017-05-04 16:46
Great! Let us know if you run into any other squirrely typescript issues :)

**Closed by patrickhulce** 2017-05-04 16:46 UTC
