### ISSUE TITLE
DevTools Error: The asynchronous expression exceeded the allotted time of 60

### ISSUE THREAD

**Issue by paidfocusgroups** [GoogleChrome/lighthouse#7198] opened 2019-02-09 22:19 UTC
**Initial URL**: https://www.paidfocusgroup.net/nationwide-paid-focus-groups/nationwide-100-paid-online-focus-group-snack-foods
**Chrome Version**: 72.0.3626.81
**Error Message**: The asynchronous expression exceeded the allotted time of 60s
**Stack Trace**:
```
Error: The asynchronous expression exceeded the allotted time of 60s
    at _ (chrome-devtools://devtools/remote/serve_file/@ac8b982e05014492d1bd7d317628a4f22a97ffa0/audits2_worker/audits2_worker_module.js:1034:120)
```

**Comment by patrickhulce** [comment] 2019-02-11 15:29
Thanks for filing @paidfocusgroups! I'm not able to reproduce this error though. Any additional info or repro steps you might have for us?

**Comment by brendankenny** [comment] 2019-04-25 23:07
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.

**Closed by brendankenny** 2019-04-25 23:07 UTC
Labels: needs-more-info
