### ISSUE TITLE
No short_name but name is already short

### ISSUE THREAD

**Issue by camsteffen** [GoogleChrome/lighthouse#5259] opened 2018-05-18 03:59 UTC
This [page](https://developers.google.com/web/fundamentals/web-app-manifest/#short_name_andor_name) says

> You must provide at least the `short_name` or `name` property...

...but lighthouse shows a warning when I have a `name` property less than 12 characters and no `short_name`.

> Maniifest's short_name will be truncated when displayed on homescreen
> ...
> No short_name found in manifest.

1. The first sentence shown in the failed audit is incorrect.
1. Is this a false audit failure?

**Comment by patrickhulce** [comment] 2018-05-18 16:13
Thanks for filing @camsteffen you are correct LH needs some updating! :)

I believe this is a duplicate of #2698 and a PR is in progress to fix it #4860, so we'll go ahead and close this one. Feel free to subscribe to the referenced issues to track progress!

**Closed by patrickhulce** 2018-05-18 16:13 UTC
Labels: bug, duplicate
