### ISSUE TITLE
Chrome DevTools and PageSpeed Insights give extremely different results on COBE demo

### ISSUE THREAD

**Issue by benmccann** [GoogleChrome/lighthouse#14301] opened 2022-08-18 16:04 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://cobe.vercel.app/

### What happened?

Running Lighthouse in Chrome always gives a score close to 100
Running on PageSpeed Insights always gives a score less than 50: https://pagespeed.web.dev/report?url=https%3A%2F%2Fcobe.vercel.app%2F&form_factor=mobile

This has been confirmed both by myself and the library's author

### What did you expect?

Lighthouse and PageSpeed insights should be giving relatively similar results

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

9.6.1

### Chrome Version

Version 103.0.5060.134 (Official Build) (64-bit)

### OS

Ubuntu

**Comment by connorjclark** [comment] 2022-08-18 17:33
PSI doesn't support hardware WebGL (falling back to software rendering), and unfortunately there's nothing we can do about this today.

closing as duplicate of #8557

**Closed by connorjclark** 2022-08-18 17:33 UTC
Labels: bug
