### ISSUE TITLE
rel="canonical" different domain false negative

### ISSUE THREAD

**Issue by callmenicholi** [GoogleChrome/lighthouse#4440] opened 2018-02-06 20:41 UTC
States "Document does not have a valid rel=canonical. Points to a different domain."

This is not true for the sites I ran it for.

There appears to be a bug.

**Comment by rviscomi** [comment] 2018-02-06 21:14
Hi @callmenicholi thanks for your bug report! Can you provide the URLs of the pages you tested so we can reproduce the issue?

**Comment by callmenicholi** [comment] 2018-02-06 22:13
You can use site https://www.thehangoutrestaurant.com/ for testing.

**Comment by rviscomi** [comment] 2018-02-06 22:26
Thanks! Here's the result of my test run: https://googlechrome.github.io/lighthouse/viewer/?gist=646764b85fff44a845944b905fe26dd8

It does seem like a bug that the error message is that the domains are different, when the canonical URL is the same as the base URL. Assigning to Konrad to investigate further.

**Comment by kdzwinel** [comment] 2018-02-07 15:01
I did couple of runs using extension, DevTools panel and console and only managed to reproduce it once at the very beginning. The issue was, that the main resource was not identified correctly because main HTML page was returning HTTP 304. Instead, font was identified as a main resource causing canonical audit to fail:

<img width="369" alt="screen shot 2018-02-07 at 15 21 49" src="https://user-images.githubusercontent.com/985504/35923183-cce80f8a-0c1f-11e8-8527-2db60cc20cab.png">

Can anyone still reproduce it? @callmenicholi have you, by any chance, changed something on that page in the meantime?

**Comment by callmenicholi** [comment] 2018-02-07 18:11
I have made no changes. It’s in your hands.

**Closed** 2018-02-15 17:26 UTC
Labels: P1, bug, seo
