### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by andrewluetgers** [GoogleChrome/lighthouse#2657] opened 2017-07-08 14:46 UTC
**Lighthouse Version**: 2.2.1
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://localhost:8443/top
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13890:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14315:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14340:18)
    at <anonymous>
```

**Comment by ev1stensberg** [comment] 2017-07-08 16:29
FYI this happens if your initial URL fails and you try to rerun the extension straight away. Currently, "roundtrip" test also fails at my build. 
![skjermbilde 2017-07-08 kl 18 28 39](https://user-images.githubusercontent.com/16735925/27987284-52bd5e8e-640b-11e7-996d-5b6a4a7a3959.png)

**Comment by patrickhulce** [comment] 2017-07-10 17:20
> FYI this happens if your initial URL fails and you try to rerun the extension straight away.

Ahhhh thank you for finding the repro conditions @ev1stensberg this is huge! :D 

dupe of #1834

**Closed by patrickhulce** 2017-07-10 17:20 UTC
