### ISSUE TITLE
audit: no plugins

### ISSUE THREAD

**Issue by igrigorik** [GoogleChrome/lighthouse#101] opened 2016-03-29 19:10 UTC
Should we have an audit to discourage use of plugins? E.g. we already list use of Flash as a [common mistake](https://developers.google.com/webmasters/mobile-sites/mobile-seo/common-mistakes#blocked-resources) in our "mobile friendly documentation"

> Some types of videos or content are not playable on mobile devices, such as license-constrained media or experiences that require Flash or other players that are not broadly supported on mobile devices. Unplayable content, when featured on a page of any website can be very frustrating for users. 

A "simple" way to ensure that this is the case: 
- check that the site's CSP policy sets `object-src 'none'`
- check that iframes have a [sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute

**Comment by samccone** [comment] 2016-03-29 19:29
:+1: I like this idea

**Comment by paullewis** [comment] 2016-04-04 11:08
Definitely like this idea. Looking into CSP stuff to see what we can do.

**Comment by paullewis** [comment] 2016-04-04 11:16
Okay, so @mikewest says in the longer term we may have https://w3c.github.io/webappsec-csp/api/ to play with, for now I'll roll with checking the headers. Which I _think_ we should be able to do from the existing Network records gather.

**Comment by paulirish** [comment] 2017-09-26 21:57
dupe of #3180 now.

**Closed by paulirish** 2017-09-26 21:57 UTC
Labels: audit, chillin ❄, enhancement
