### ISSUE TITLE
Service worker offline problem !

### ISSUE THREAD

**Issue by imothep85** [GoogleChrome/lighthouse#10262] opened 2020-01-24 16:32 UTC
when i test my website with lighthouse, i get this error:

start_url does not respond with a 200 when offlineThe start_url did respond, but not via a service worker.
![error_lighthouse](https://user-images.githubusercontent.com/8946215/73085758-82b0d200-3ecf-11ea-916f-7d29f265cd51.jpg)

**Comment by Malvoz** [comment] 2020-01-24 21:53
This is effectively a dupe of https://github.com/GoogleChrome/lighthouse/issues/10237.

**Comment by patrickhulce** [comment] 2020-02-25 21:56
We'll leave tracking at #10237 thanks for filing @imothep85 and thanks for the ref @Malvoz!

**Closed by patrickhulce** 2020-02-25 21:56 UTC
Labels: needs-priority
