### ISSUE TITLE
Can't run cli on linux: Error: Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by crhym3** [GoogleChrome/lighthouse#503] opened 2016-07-11 10:39 UTC
$ npm install -g googlechrome/lighthouse
    /usr/local/nodejs/bin/lighthouse -> /usr/local/nodejs/lib/node_modules/lighthouse/lighthouse-cli/index.js
    ...

```
$ lighthouse --help
module.js:442
    throw err;
    ^

Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/nodejs/lib/node_modules/lighthouse/lighthouse-core/report/report-generator.js:22:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Running on a 64bit linux 4.2.0-38-generic:

```
$ node --version
v6.3.0

$ npm --version
3.10.3
```

FWIW the same thing was happening on node v4.

**Comment by paullewis** [comment] 2016-07-11 11:21
Looks like a dupe of #486?

**Comment by paullewis** [comment] 2016-07-11 12:30
With this one did node _install_deps.js run? It doesn't look like it.

**Comment by wardpeet** [comment] 2016-07-18 07:09
@paulirish can I give it a try?

**Comment by wardpeet** [comment] 2016-07-25 20:27
PR #526 should fix this

**Comment by wardpeet** [comment] 2016-07-27 17:59
This one can be closed @paullewis @paulirish

**Comment by paulirish** [comment] 2016-07-27 19:51
cheers. thanks ward

**Closed** 2016-07-27 19:51 UTC
