### ISSUE TITLE
test-legacy-javascript improvements

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#10566] opened 2020-04-09 15:57 UTC
Right now @connorjclark is the `test-legacy-javascript` whisperer, but it would be good to spread that ability :) Some possible improvements:

- [ ] **lock test dependencies to a specific version**. It appears deps updates are the cause of changes like in https://github.com/GoogleChrome/lighthouse/pull/10555#issuecomment-611586368 and https://github.com/GoogleChrome/lighthouse/pull/10469#discussion_r393901338, which block landing a PR (and Travis may have different cached dependencies than the local machine, so re-running and pushing may not fix CI)
- [ ] **speed up the initial run(?)** It's not that common to touch something in `**/legacy-javascript/**`, but since Travis starts fresh every time it's a +6minute hit to CI when you do
- [ ] **improve interpretability of results** by the average contributor. Maybe readme explanation, simpler logged output, and specific assertions on top of the `git diff`?
  - e.g. for `sample_v2_round_trip.json` you know the diff should match `sample_v2.json`, and there are [unit tests](https://github.com/GoogleChrome/lighthouse/blob/a6fd756c991c425dc3f59deb9c75eda0af7c9bdb/lighthouse-core/test/report/proto-test.js) checking specific aspects of the generated json to call out the important parts. While if something goes `-3567 total` to `+4121 total` in `test-legacy-javascript`, it's unclear if committing the new count is going to cause an issue.
  - maybe this means separating the diagnostic tool(s) from the CI check? The diagnostic would still log lots of information, while the CI check would be more like, are some number of bytes found (or something more specific, not sure :)

**Comment by connorjclark** [comment] 2020-04-09 20:56
> It appears deps updates are the cause of changes like ...

I confirmed this by checking out the original commit that added this test, clearing my local yarn.lock and seeing that the numbers returned are different.

Seems like the variant w/ babel preset set to false (heavy transpilation and polyfilling) got much bigger. I don't see individual polyfill variants changing sizes, seems some transforms got worse ... interesting, might look into that later.

![image](https://user-images.githubusercontent.com/4071474/78938145-8e3f7e00-7a66-11ea-97aa-a4b42e6e0b29.png)

(yes, we should check in the lockfile)

> speed up the initial run

We could store the "variants" (the long part of run.js) in a folder that is name-cached by the md5sum of `cat yarn.lock run.js` (`variants/abcded1234/...`), and then add `variants` to the CI cache.

> improve interpretability of results ...

As I think you've determined with your suggestion of separating diagnostics from the CI check, `summary-signals.json` >>> `summary-sizes.txt` in terms of how this test prevents regressions.

I'd be okay with removing the sizes check from CI if we couldn't find a way to stop insignificant byte changes (since the signals check will catch non-trivial changes), but if checking in the yarn.lock is all it takes to stop this noise I would prefer to keep it around.

I like `summary-sizes.txt` being checked in because whenever we purposefully update this yarn.lock file it tells us unexpected things like transforms are seemingly getting worse(!). And it is a quick reference for the relative weight of each of these transform/polyfills.

But more to your point- since summary signals is the important bit, let's talk about interpreting changes to that file. #10564 introduces a second signal file, one for using maps and the pattern heuristic, and one using just the patterns. 

For `variantsMissingSignals `, I would expect the former to only have the `babel-preset-env=true` variant (since this whole test is about finding signals when babel-preset-env is NOT used). The latter should also have that, but may having more missing variants since it's just a heuristic. A codified check that these files have the `babel-preset-env=true` variant seems good to me.

For the signals of each variant, across both signal files, the expectation is that the number of them only goes up. I think the diff is enough for interpreting that.

___

I also noticed that the whitespace is different for update-sizes.sh output. There's an extra space on every line. Not sure why - I see there is [a difference in OSX for wc behavior](https://unix.stackexchange.com/questions/205906/extra-space-with-counted-line-number), but I am pretty sure I originally ran this test on my mac ... Should probably just replace update-sizes.sh (as nice as it is...) with some JS

**Comment by brendankenny** [comment] 2020-04-09 21:43
I think the yarn.lock file will help a lot (hopefully eliminating unrelated changes causing test changes) and then I guess we can see the frequency of people needing to interpret the output.

Re: keeping the `summary-sizes.txt` diff, that may be a case when beefing up the readme (and maybe tweaking the summary format) would help. Some level of jargon and insider knowledge is inevitable when looking at failing tests, but in an ideal world test results are at least somewhat self documenting, but e.g.

```
variants/core-js-2-only-polyfill
1482778 total
  47738 variants/core-js-2-only-polyfill/es6-typed-uint8-clamped-array/main.bundle.min.js
  47718 variants/core-js-2-only-polyfill/es6-typed-float64-array/main.bundle.min.js
```
is currently pretty impenetrable :)

**Closed** 2020-04-22 23:35 UTC
Labels: needs-priority
