### ISSUE TITLE
Page crash in Puppeteer >= 2.6.0

### ISSUE THREAD

**Issue by LegitTrevorTiernan** [GoogleChrome/lighthouse#16243] opened 2024-11-05 20:07 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

cnn.com

### What happened?

I was attempting to use puppeteer 23.6.0+ and the latest lighthouse 12.2.1
I ran into an issue where I was getting 
```
page errored! Error: Page crashed!
--
  | 2024-11-05T19:15:18.618Z | at #onTargetCrashed (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:384:50)
```
If I do not run lighthouse, the process is ok with Puppeteer 2.7.0.  Although this error does not happen with lighthouse if puppeteer < 23.6.0. 
When I did a deeper debug, I got an error similar to 
https://stackoverflow.com/questions/49386692/aw-snap-and-asr-no-room-in-socket-buffer-errors-in-chrome
However, I'm using the flag. "--disable-dev-shm-usage",

### What did you expect?

I expected the lighthouse audit to complete correctly without a puppeteer page crash. 

### What have you tried?

I tried running the process without lighthouse, and it worked. 
I also tried running with an earlier version of Puppeteer, which did work with a lighthouse. 

### How were you running Lighthouse?

node

### Lighthouse Version

12.2.1

### Chrome Version

130.0.6723.58+

### Node Version

20

### OS

Linux (Amazon ECS task)

### Relevant log output

```sh
Page errored! Error: Page crashed!
2024-11-05T19:46:33.223Z
at #onTargetCrashed (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:379:50)
2024-11-05T19:46:33.223Z
at /node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
2024-11-05T19:46:33.223Z
at Array.map (<anonymous>)
2024-11-05T19:46:33.223Z
at Object.emit (/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
2024-11-05T19:46:33.223Z
at CdpCDPSession.emit (/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
2024-11-05T19:46:33.223Z
at CdpCDPSession._onMessage (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:82:18)
2024-11-05T19:46:33.223Z
at Connection.onMessage (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:143:25)
2024-11-05T19:46:33.223Z
at WebSocket.<anonymous> (/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:44:32)
2024-11-05T19:46:33.223Z
at callListener (/node_modules/ws/lib/event-target.js:290:14)
2024-11-05T19:46:33.223Z
at WebSocket.onMessage (/node_modules/ws/lib/event-target.js:209:9)

Error! TargetCloseError: Protocol error (Emulation.setTouchEmulationEnabled): Target closed
at CallbackRegistry.clear (/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:73:36)
at CdpCDPSession._onClosed (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:101:25)
at #onClose (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:167:21)
at WebSocket.<anonymous> (/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
at callListener (/node_modules/ws/lib/event-target.js:290:14)
at WebSocket.onClose (/node_modules/ws/lib/event-target.js:220:9)
at WebSocket.emit (node:events:519:28)
at WebSocket.emitClose (/node_modules/ws/lib/websocket.js:272:10)
at Socket.socketOnClose (/node_modules/ws/lib/websocket.js:1341:15)
at Socket.emit (node:events:519:28) {
cause: ProtocolError
at <instance_members_initializer> (/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
at new Callback (/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
at CallbackRegistry.create (/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
at Connection._rawSend (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
at CdpCDPSession.send (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
at next (/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
at CdpCDPSession.send (/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
at #applyViewport (/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/EmulationManager.js:147:32)
at EmulatedState.<anonymous> (/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:154:23)
at /node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/EmulationManager.js:69:33
}
content types: text/html video/mp4
TargetCloseError: Protocol error (Emulation.setTouchEmulationEnabled): Target closed
```

**Comment by adamraine** [comment] 2024-11-05 23:06
Can you please provide a minimum script or other repro steps for this issue

**Comment by LegitTrevorTiernan** [comment] 2024-11-19 17:29
Sorry it took so long. The bug was in production code, and I needed to boil it down to a much smaller example. 
[minimal.txt](https://github.com/user-attachments/files/17819063/minimal.txt)
[package.json](https://github.com/user-attachments/files/17819064/package.json)

**Comment by LegitTrevorTiernan** [comment] 2024-11-22 17:59
I was researching Chrome and Chromium and stumbled upon more information about this bug. 
The bug is reproducible using Puppeteer 23.5.3 IF you do not use the built-in Chrome (which does not crash) but instead specify an executable path to a later Chrome (in my case, chrome for Mac 131).

**Comment by LegitTrevorTiernan** [comment] 2024-11-26 17:19
Well, I just installed Chromium (133) via homebrew on my Mac and no crash there, either. 
Maybe this is a chrome issue?

```
  "devDependencies": {
    "lighthouse": "12.2.2",
    "puppeteer": "23.9.0"
  },
```

**Comment by adamraine** [comment] 2024-12-20 18:37
Yeah I can reproduce this on 132.0.6834.57 but not 133.0.6907.0. This looks like a Chrome bug that was fixed recently, I will see if I can confirm anything.

**Comment by adamraine** [comment] 2024-12-20 19:24
Ok I did some bisecting and I think I found the patch which fixed it:
https://chromium.googlesource.com/chromium/src/+/f4b301d60033d304154df5a7e29afcb2edc76464

Since this appears to be fixed in the latest Chrome I'm going to close this.

**Closed by adamraine** 2024-12-20 19:24 UTC
Labels: bug, needs-priority, needs-investigation
