### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by Chiqui1234** [GoogleChrome/lighthouse#7859] opened 2019-03-31 14:46 UTC
**Initial URL**: http://localhost/holanerd/Forum
**Chrome Version**: 72.0.3626.109
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by Chiqui1234** [comment] 2019-03-31 14:47
Debian Buster (Clean install) + LXQt
AMD Phenom II X6 1055T + 2x2GB DDR2 + AMD RX Vega 56

**Comment by patrickhulce** [comment] 2019-03-31 15:10
Thanks @Chiqui1234! This is a dupe of #7246, debian removes critical Chromium pieces in their distribution that Lighthouse needs. The workaround is to install regular Chrome.

**Closed by patrickhulce** 2019-03-31 15:10 UTC
