### ISSUE TITLE
Timespan Third Party Filtering

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14268] opened 2022-08-08 21:23 UTC
In our report we use the origin of `finalUrl`/`finalDisplayedUrl` to determine what is third party.

In timespan mode this origin can change so some URLs might get incorrectly categorized as third party or first party.

We should either design a better way to determine third party requests, or disable the third party filtering in timespan.

**Comment by connorjclark** [comment] 2022-08-09 02:53
The obvious solution is to just consider a URL to be first party if any of the URLs match in origin, and third party otherwise. Any downsides there?

**Comment by adamraine** [comment] 2022-08-11 17:26
> any of the URLs

We would need a `visitedUrls` list or something.

> Any downsides there?

During a timespan, if the usr goes from originA to originB, and originB requests some resources under originA, are those resources considered third party? From originB's perspective they are but from the users perspective they might not be.

It's would be better than what we have now though.

**Comment by alexnj** [comment] 2022-12-12 22:58
I just ran into this issue while implementing entity-classification into third-party-summary audit. The issue I'm seeing with timespan is that it allows cross-origin navigations. Eg., I could do a timespan of navigating to `paulirish.com` and then click on the Twitter link on the right rail, navigating to `twitter.com` origin. In this case, a report is still generated, but third-party and first-party doesn't make much sense in that context. 

We could either,
(1) restrict timespan to same origin navigations, or
(2) treat each navigation as independent (`navigations[]`) without squishing everything as one `trace`/`devtoolsLogs`/score, i.e., giving each navigation its own first party and a set of third parties.

The more I think about it, the more I'm leaning towards option 1.

**Comment by alexnj** [comment] 2022-12-13 20:19
Alternatively, we could implicitly create multiple timespans each time origin changes — so each timespan would still make sense and the overall report still usable. This should also work with Flows better, and we're neither restricting timespans to an origin, or abruptly ending a timespan when a new origin navigation is detected.

**Comment by paulirish** [comment] 2023-03-13 22:51
Dupe of https://github.com/GoogleChrome/lighthouse/issues/14775

**Closed by paulirish** 2023-03-13 22:51 UTC
Labels: P2, third-party
