### ISSUE TITLE
Preload key requests

### ISSUE THREAD

**Issue by wildpow** [GoogleChrome/lighthouse#5471] opened 2018-06-11 19:53 UTC
Light House is suggesting that I preload key requests, specifically the two google fonts that I'm using in my React app. Currently I'm just importing them like this:
 `@import url('https://fonts.googleapis.com/css?family=Open+Sans|Roboto:700')`
I've been looking for an example of how to do this but, everything I've tried doesn't seem to work. Any suggestions would be much appreciated.

**Comment by patrickhulce** [comment] 2018-06-11 20:25
This audit will actually change a bit for 3rd party requests in future version of LH, but basically you want

```html
<link rel="preload" as="style" href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:700" crossorigin>
```

for extra good bonus points you can also preconnect to the origin *it's* going to connect to :)

```html
<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
```

**Comment by wildpow** [comment] 2018-06-11 22:32
Thank you for such a quick response! Unfortunately I've tried this but, I figured I was doing something wrong because the fonts now don't display. I know it's making the request because I see it in the waterfall and I get this console warning: 

"The resource https://fonts.googleapis.com/css?family=Open+Sans|Roboto:700 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."
   
I apologize for getting a little off topic but, do I need to define these font-families in my CSS with `@font-face` or something before use? Also, thank you again

**Comment by wildpow** [comment] 2018-06-12 21:34
Well I got it to work with this bit of code:
```<link rel="preload" as="style" href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:700" crossorigin>```
```<link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:700" rel="stylesheet" crossorigin>```
Without adding the crossorgin property to the second link tag I get a render blocking stylesheet warning from LightHouse but, this whole endeavor to preload font fonts per Light House's suggestion as upped my first meaningful paint to 3620ms from 2650ms and lower my lighthouse score from 88 to 79. Not sure if the preload suggestion is general and doesn't work with the way Google serves their fonts or if I'm still doing something wrong. Just frustrating to follow these optimization guide-lines and end up with a slower product.

**Comment by patrickhulce** [comment] 2018-06-12 21:52
This should definitely not make your page slower if it's being done correctly. From your steps it sounds like there's some confusion about how preload works. You might find [this article on preload](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/) helpful.

**Comment by wildpow** [comment] 2018-06-12 22:43
That's true I may not fully understand preload and thank you for the link. Here are two screenshots of the lighthouse audits and the zip contains both reports. The only changes to my code was adding those 3 link tags and removed the font `@import` in my CSS.
![screen shot 2018-06-12 at 3 36 44 pm](https://user-images.githubusercontent.com/17464319/41320906-8164118c-6e56-11e8-8543-52638d627808.png)
VS
![screen shot 2018-06-12 at 3 35 34 pm](https://user-images.githubusercontent.com/17464319/41320941-9dd54976-6e56-11e8-8724-46885bf38d28.png)
Here is the two reports

[Archive.zip](https://github.com/GoogleChrome/lighthouse/files/2096025/Archive.zip)

**Comment by patrickhulce** [comment] 2018-08-27 20:50
Sorry I missed this reply @wildpow thanks for sending over the reports! 

This is a very interesting case, the successful preloading improves First Contentful Paint as expected, but First Meaningful Paint gets worse because of a quirk in its implementation (the same quirks that were the rationale for decreasing its priority/weight in v3 and promotion of FCP in its place). The regression in the other metrics seems to be unrelated to the preload change and looks like natural variance. If we had been tracking FCP in v2, the incremental improvement from preloading would have been reflected there.

Thanks for bringing this up and sorry for the confusion! Hopefully these cases are addressed in v3 with the new prioritization/metrics :)

**Closed by patrickhulce** 2018-08-27 20:50 UTC
Labels: needs-more-info, needs-priority, question
