### ISSUE TITLE
start_url fetched via an "offline" SW not considered good enough

### ISSUE THREAD

**Issue by ondras** [GoogleChrome/lighthouse#10237] opened 2020-01-17 10:41 UTC
#### Provide the steps to reproduce
1. Run LH on https://ondras.github.io/sw/
  
#### What is the current behavior?
`start_url does not respond with a 200 when offline. The start_url did respond, but not via a service worker.`

#### What is the expected behavior?
This configuration shall be considered okay.

The problem is related to the SW's caching strategy. The current worker works online-first, i.e. it always [tries to fetch the resource](https://github.com/ondras/sw/blob/master/sw.js#L9). It looks like it succeeds, even when "simulating offline in Lighthouse", so the reply is not considered *via a service worker*.

If I change the `if (cached)` implementation to simply `return cached` (not trying any network interatction), Lighthouse works correctly.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.5, 5.7
* Chrome version: 79, 81
* Operating System: Linux

**Comment by patrickhulce** [comment] 2020-01-17 13:59
Thanks for filing @ondras! I'm able to reproduce this in DevTools as well (though everything seems to work fine from CLI)

Related #709

**Comment by paulirish** [comment] 2020-02-25 21:57
another repro from #102622 https://www.stop-it.be/

**Comment by hdlion** [comment] 2020-07-20 09:12
I'm also facing same problem? Any solution ?

**Comment by derykmarl** [comment] 2020-07-29 15:44
Same in gatsby-plugin-offline / gatsby-plugin-manifest

The generated manifest file contains start_url of '/' and on most pages it passes, but on the home page it fails.

**Comment by surajtambe** [comment] 2020-10-15 05:12
"files": [
					"/",
					"*.html",
					"/favicon.png",
					"/manifest.json",
					"/*.css",
					"/*.js"
				]


my configuration
 "/" is not being cache in service worker cache causes no offline application.

**Comment by SimonHogstromRonbol** [comment] 2020-10-15 11:01
i've made a minimal example in AMP, that has the same issue:
https://www.pwamp.dk/

**Comment by psabharwal123** [comment] 2020-10-23 20:53
same issue with https://preactjs.com/repl/

**Comment by psabharwal123** [comment] 2020-10-23 20:58
strange thing is, it is actually being served by service worker, bug in chrome?

**Comment by Jimmydalecleveland** [comment] 2020-11-10 21:41
I've been fighting this same problem for over a week. My problem is similar to what @derykmarl described, except reversed: My sites homepage passes the check, but all other pages do not. I have an older Gatsby site that is passing this check, but despite the many combinations of code and package version changes I cannot get any other site using `gatsby-plugin-manifest` and `gatsby-plugin-offline` to pass this check.

**Comment by akrmontoya** [comment] 2020-11-15 14:01
> I've been fighting this same problem for over a week. My problem is similar to what @derykmarl described, except reversed: My sites homepage passes the check, but all other pages do not. I have an older Gatsby site that is passing this check, but despite the many combinations of code and package version changes I cannot get any other site using `gatsby-plugin-manifest` and `gatsby-plugin-offline` to pass this check.

I have the same problem

**Comment by JacobDB** [comment] 2020-11-17 19:51
I believe I'm having the same issue – Lighthouse in Chrome's dev tools reports that `start_url` isn't available offline, but Chrome on Android still displays the "Add to home screen" prompt just fine, and the app does function offline after a second page load. I think the issue is that the service worker can't cache the current page until the second load because it's not installed until the initial load finishes (and thus cannot intercept the loading to cache it).

Very frustrating, it's preventing me from achieving a perfect score... would love a resolution.

**Comment by garygreen** [comment] 2020-11-23 02:33
Having the same issue. So it looks like it's failing for everyone who basically uses a "Network First" then fallback to "Cache" approach? 

Kinda suprising there's not more attention on this tbh.

**Comment by patrickhulce** [comment] 2020-11-23 03:14
> Kinda suprising there's not more attention on this tbh.

FYI everyone there's not much public attention here because the intent is to loosen the strictness of this check to match browser checks rather than fix it :)

The primary question is around the timeline which requires coordinating with many consumers and stakeholders of the PWA category, which is where we're currently held up.

**Comment by SalahAdDin** [comment] 2020-12-03 20:48
Here, me too, using `next-offline`.

**Comment by kkoss89** [comment] 2020-12-07 16:20
same here https://impulsioneme.com

**Comment by brendankenny** [comment] 2020-12-15 16:01
fixed in #11745

**Closed by brendankenny** 2020-12-15 16:01 UTC
Labels: 7.0, DevTools, P2, bug, needs-investigation, pwa

**Comment by JacobDB** [comment] 2020-12-15 16:23
Fantastic news! Any idea when this will be integrated in to Chrome?
