### ISSUE TITLE
DevTools Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by maverickash8889** [GoogleChrome/lighthouse#2897] opened 2017-08-09 02:51 UTC
**Initial URL**: https://mcare.siriusxm.com/#_frmLogin ( URL under observation is : https://mcare.siriusxm.com/#_frmLogin and in the responsive mode for mobile through emulator). 
**Chrome Version**: 60.0.3112.90
**Error Message**: You must provide a url to the runner 
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:848:659)
    at window.runLighthouseForConnection (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:873:288)
    at window.runLighthouseInWorker (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:873:1013)
    at Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:4735:117)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-08-09 17:26
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-08-09 17:26 UTC
