### ISSUE TITLE
Can't see the results of the Lighthouse analysis 

### ISSUE THREAD

**Issue by leandroaps** [GoogleChrome/lighthouse#11589] opened 2020-10-22 22:32 UTC
#### Provide the steps to reproduce
1. Run LH on <affected url>
https://conta.uol.com.br/login?t=default

#### What is the current behavior?
Open DevTools, runs Lighthouse, can't see the results.

#### What is the expected behavior?
See the results of the analisys

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by oxy-32** [comment] 2020-10-22 23:38
Hello,
I've have the same problem for a while. For example, if I test the following website: https://www.oxyitservices.com/  

my google chrome version is :  Versie 86.0.4240.111 (Officiële build) (64-bits) on windows ten 64 bit. 

I have always used this tool very often. And from one day to the next I kept getting the message:

There were issues affecting this run of Lighthouse:

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

I've already tried the following things: delete cookies, disable extensions and even delete them. and in incognito mode it doesn't work either.  nothing helps. and i have this with Every site i test. not only the oxyitservices.com
I also send a print screen.
![2020-10-23_013444](https://user-images.githubusercontent.com/63825526/96940422-f835e700-14cf-11eb-8cdb-e4af367435da.png)
 Thanks in advance!

**Comment by patrickhulce** [comment] 2020-10-22 23:44
Thanks for filing @leandroaps! I can reproduce this on stable, but in Chrome Canary the issue appears to be fixed. Are you able to confirm the same?

@oxy-32 that is a different issue, but has to do with the page itself. Also make sure you're never backgrounding the window while Lighthouse is running.

**Comment by oxy-32** [comment] 2020-10-22 23:48
ow ok sorry i thought he had the same problem as me. what do you mean by: "Also make sure you're never backgrounding the window while Lighthouse is running." ?

thx

**Comment by patrickhulce** [comment] 2020-10-23 01:22
> what do you mean by: "Also make sure you're never backgrounding the window while Lighthouse is running." ? i have this problem with evvery website i want to test.

If the page isn't visible and right in front of you as it audits, you will receive this error.

**Comment by oxy-32** [comment] 2020-10-25 20:19
Ok thx this whas the problem! omg this solution whas so simpel :-) thank you verry mutch !

**Comment by BerenOneHand** [comment] 2020-10-27 08:01
Hello, running lighthouse with the chrome devtools popped out of the chrome window causes this behavior.

**Comment by patrickhulce** [comment] 2020-10-27 14:45
Thanks for chiming in @BerenOneHand! I can't reproduce that behavior unless the tab itself is backgrounded (in which case the fact that DevTools is undocked doesn't have an effect). Any other details you have?

**Comment by BerenOneHand** [comment] 2020-10-28 06:33
Hey @patrickhulce ,
Well my laptop screen resolution is pretty small. I simply undocked the dev tools and maximised it. The window that contains the web site is now behind my dev tools. Running lighthouse at this point causes it to fail with ? on all categories after taking a lot longer than normal.

**Comment by patrickhulce** [comment] 2020-10-28 14:54
>  Maybe possibly add a warning about this to the screen?

Already on it :) https://github.com/GoogleChrome/lighthouse/pull/11579

**Comment by nickgriffiths** [comment] 2020-10-29 12:53
> Thanks for filing @leandroaps! I can reproduce this on stable, but in Chrome Canary the issue appears to be fixed. Are you able to confirm the same?

I also experience the same issue as @leandroaps when I use Chrome 86.0.4240.111. That is, I run Lighthouse from within Chrome and I see this:

<img width="1259" alt="lighthouse-blank" src="https://user-images.githubusercontent.com/1266682/97576160-b502d900-19e5-11eb-9053-48fe98fc9d65.png">

@patrickhulce I can confirm that I do _not_ experience it when using Chrome Canary 88.0.4307.0.

**Comment by patrickhulce** [comment] 2020-10-29 14:55
Glad it seems to be fixed already in Canary for others as well, we'll go ahead and close this then! 👍

**Closed by patrickhulce** 2020-10-29 14:55 UTC
Labels: needs-more-info, needs-priority
