### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by camsong** [GoogleChrome/lighthouse#1006] opened 2016-11-22 05:40 UTC
**Lighthouse Version**: 1.2.0
**Chrome Version**: 55.0.2883.52
**Error Message**: listeners.filter is not a function
**Stack Trace**:
 ```TypeError: listeners.filter is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1044:31)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10959:24)```

**Comment by brendankenny** [comment] 2016-11-22 06:12
duplicate of #975

**Closed by brendankenny** 2016-11-22 06:12 UTC
