### ISSUE TITLE
Throttling options other than simulated were not working

### ISSUE THREAD

**Issue by manojkumar542** [GoogleChrome/lighthouse#6924] opened 2019-01-04 06:50 UTC
Eventhough i select No throttling and run the audit it gives me with output with simulated throttling as below

![audit issue](https://user-images.githubusercontent.com/40314203/50676582-273d4900-101b-11e9-86ec-c04025aecbd7.png)

**Comment by patrickhulce** [comment] 2019-01-04 15:49
Thanks for filing @manojkumar542! This is a duplicate of #6772 and should be fixed in newer versions of Chrome.

**Closed** 2019-01-04 16:06 UTC
