### ISSUE TITLE
[Discussion] Longer-term doc strategy

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#758] opened 2016-10-10 19:37 UTC
I get the sense that there's a strong longer-term goal to make it easy for the community to create their own LH audits. 

With this in mind, we may be best off providing a well-lit path for including the reference documentation within the audit source, using JSDoc.

This maximizes the chances that docs stay in sync with the audits. The current doc system is too-far-removed. Somebody updating an audit likely won't want / won't know how to go over to the other system (i.e. the web fundamentals repo) to update a doc. And vice versa, as a writer I'm likely to miss updates to the audits.

I would personally like to impose some validation on the docs. I.e. each doc should have three sections, using JSDoc tags like `@section how` to represent the "how it works" section of the doc. But that may be too strict... But on the other hand LH can use this to vet the quality of the docs. If a doc doesn't have all of the required sections, then LH won't show it. 

In terms of user experience, to access the doc I'm thinking:
- (Chrome Extension) You click a "more help" button, and LH opens up the doc in a new tab.
- (CLI) `lighthouse help <audit-name>` and you view the doc, man-page-style.
- We'll have to handle other manifestations of LH on a case-by-case basis.

**Comment by paulirish** [comment] 2018-03-09 00:12
dupe of #3603

**Closed by paulirish** 2018-03-09 00:12 UTC
Labels: needs-priority
