### ISSUE TITLE
waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.clearBrowserCache)

### ISSUE THREAD

**Issue by lvorcool** [GoogleChrome/lighthouse#10996] opened 2020-06-19 06:52 UTC
**Summary**
hi，my issue: [#10987](https://github.com/GoogleChrome/lighthouse/issues/10987) 

I see this [#6450](https://github.com/GoogleChrome/lighthouse/issues/6450)

I tried to modify what you said，as shown, 
![image](https://user-images.githubusercontent.com/21286480/85104510-5198bb80-b23b-11ea-81f0-389f7d672b87.png)

I modified:
![image](https://user-images.githubusercontent.com/21286480/85104861-f7e4c100-b23b-11ea-9397-f87c9049312b.png)

but still report an error:
![image](https://user-images.githubusercontent.com/21286480/85105050-5873fe00-b23c-11ea-9a5e-bacc899b7a1e.png)

### machine
os : centos Red Hat 4.8.5-36
lighthouse： 6.0.0
node: v12.18.0
npm: 6.14.4

### my problem:

1. How do I determine if I can successfully connect to Chrome DevTools protocol？

**Comment by patrickhulce** [comment] 2020-06-19 13:13
Since you're using the CLI that starts with a clean Chrome anyway I would just use `--disable-storage-reset` to skip this step entirely.

What version of Chrome were you using here? The specific problem you're running into should've been fixed in one of the recent stable versions.

Sorry, but we'll have to close this as a duplicate of #6512 to keep the tracking in one place.

**Closed by patrickhulce** 2020-06-19 13:13 UTC
Labels: needs-priority

**Comment by lvorcool** [comment] 2020-06-20 08:48
Based on what you said ，Add to the command `--disable-storage-reset` skip the step of clearing the cache .  but report other error:
![image](https://user-images.githubusercontent.com/21286480/85197738-92650300-b315-11ea-8e2e-f025bbe5c02a.png)
How can this problem be solved?

In addition, skip the step of clearing the cache. My script needs to execute multiple URLs in a loop. Will it be affected by the cache, and the performance index is not allowed to be evaluated?

Looking forward for your response, thank you~

**Comment by patrickhulce** [comment] 2020-06-20 15:58
> but report other error:

That is unrelated and is an expected occurrence on some pages. Some scripts will be evicted from the memory cache if the page uses too many. This doesn't require any action on your part and won't affect performance score in any way.

> My script needs to execute multiple URLs in a loop. Will it be affected by the cache, and the performance index is not allowed to be evaluated?

Just ensure that you're not sharing the Chrome profile between runs which from your previous example you were using the CLI without the `port` option which will create a fresh Chrome for you between each run.

**Comment by lvorcool** [comment] 2020-06-21 01:36
Thank you for your patient and meticulous answers😁
