### ISSUE TITLE
Even a simple html page gives the "Content Sized Correctly for Viewport" error

### ISSUE THREAD

**Issue by camillo777** [GoogleChrome/lighthouse#9777] opened 2019-10-03 10:46 UTC
Error message is:
Content is not sized correctly for the viewportThe viewport size is 412px, whereas the window size is 1437px.
If the width of your app's content doesn't match the width of the viewport, your app might not be optimized for mobile screens. Learn more.

windows size is not the actual html windows size, but the Chrome app window size that obviously is never matching the html window size.

#### Provide the steps to reproduce
1. Run LH on <affected url>
  

Check with this simple HTML:

```
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Food Ninja</title>
  <link rel="manifest" href="/manifest.json">
  <meta name="theme-color" content="#fff">
  <link rel="apple-touch-icon" href="public/icons/icon-192x192.png">
</head>
<body>
  ciao
</body>
</html>
```

#### What is the current behavior?
Lighthouse gives error:
Content is not sized correctly for the viewportThe viewport size is 412px, whereas the window size is 1437px.

#### What is the expected behavior?
There is no error.
At least the 1437px size is the HTML size not the Chrome app size

#### Environment Information
* Affected Channels: 
Dev Tools on Chrome Version 77.0.3865.90 (Official Build) (64-bit)

* Lighthouse version: Lighthouse 5.2.0
* Node.js version:
* Operating System: OSX 10.12.6

**Related issues**

**Comment by camillo777** [comment] 2019-10-03 10:51
Tried with the node.js Lighthouse app on the same page: test is passed.
Version is 5.5.0

M0010218224:~ camillo$ lighthouse --version
5.5.0

So it can be related to lighthouse 5.2.0 on Chrome

**Comment by patrickhulce** [comment] 2019-10-03 15:30
Thanks for filing @camillo777! This was a bug in Chrome 77 that was fixed in Chrome 78 due out in a few weeks. 

See https://github.com/GoogleChrome/lighthouse/issues/9476#issuecomment-524424060

**Closed by patrickhulce** 2019-10-03 15:30 UTC

**Comment by connorjclark** [comment] 2019-10-03 18:13
Yup, you can use a fixed version in Chrome Beta today. But thanks for using our tool and caring enough to report a bug :)

**Comment by Malvoz** [comment] 2020-10-14 13:53
I'm getting the same issue with this minimum viable HTML:

```html
<!doctype html>
<h1>test</h1>
```

using Chrome v86.0.4240.75, however I don't see it in Canary 88.0.4292.0, can I assume it'll be fixed in a future Chrome version? Or should I open a Chromium bug?

**Comment by patrickhulce** [comment] 2020-10-14 14:44
@Malvoz that would be working as intended as there is no meta viewport declaration on that snippet you provided.

**Comment by patrickhulce** [comment] 2020-10-14 15:42
I can't reproduce that in stable or canary :/

http://melodic-class.glitch.me/meta-viewport.html

![image](https://user-images.githubusercontent.com/2301202/96012375-a921ef00-0e09-11eb-8792-b431be9f25f5.png)
![image](https://user-images.githubusercontent.com/2301202/96012514-cc4c9e80-0e09-11eb-9602-685cfa503fdc.png)


Either way if it's fixed for you in Chrome Canary then there's no action for anyone to take outside of waiting :)

**Comment by Malvoz** [comment] 2020-10-14 15:55
> http://melodic-class.glitch.me/meta-viewport.html

<img width="600" src="https://user-images.githubusercontent.com/26493779/96013881-0dfb3a80-0e46-11eb-9eb7-2a95355a0be9.png" alt="Incorrect audit failure">

Guess there's nothing TBD then. Thank you for your time @patrickhulce. :)
