### ISSUE TITLE
Lighthouse generation error.

### ISSUE THREAD

**Issue by bhaskar3112** [GoogleChrome/lighthouse#14429] opened 2022-10-05 10:01 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://mail.google.com/mail/u/0/#inbox

### What happened?

Hi team,
I would like to inform you that while using dev tools in google chrome, I summoned a bug related to generation of lighthouse in Gmail. 

### What did you expect?

I was expecting a lighthouse generated instead i got a error and a note saying 'if the issue is reproduceable than report it to lighthouse repo. GitHub.' 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.14.2 13

### OS

Windows 11

**Comment by connorjclark** [comment] 2022-10-06 23:31
I'm not seeing any error. Can you provide any more information?

**Comment by bhaskar3112** [comment] 2022-10-07 11:14
![light house github](https://user-images.githubusercontent.com/107243739/194540648-8c6c7418-5a11-4d64-a717-442d2cc6a945.jpg)

**Comment by bhaskar3112** [comment] 2022-10-07 12:26
This was reproduceable so I reported it. I have more proofs if you need.

**Comment by connorjclark** [comment] 2022-10-07 16:21
I need that text, can you copy/paste it.

**Comment by bhaskar3112** [comment] 2022-10-08 12:33
Channel: DevTools
Initial URL: https://mail.google.com/mail/u/0/#inbox/FMfcgzGqQmbBXPRKtdkXdglfrMJwMGrQ
Chrome Version: 106.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

**Comment by connorjclark** [comment] 2022-10-08 16:02
As a workaround for now, in the lighthouse panel setting try disabling clear storage. That may work for you

**Comment by bhaskar3112** [comment] 2022-10-09 09:48
It works but if someone wants it in clear storage enabled. then its a bug i think.

**Comment by bhaskar3112** [comment] 2022-10-10 11:38
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://mail.google.com/mail/u/0/#inbox
Chrome Version: 106.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1203:929
    at new Promise (<anonymous>)
    at ProtocolSession$1.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1203:881)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async _setupNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1222:504)
    at async _navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1224:716)
    at async _navigations (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1225:458)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1226:406
```

**Comment by bhaskar3112** [comment] 2022-10-10 11:40
<img width="559" alt="image" src="https://user-images.githubusercontent.com/107243739/194858175-eeced850-f43f-4545-8ac7-37cf5758ef33.png">

**Comment by bhaskar3112** [comment] 2022-10-13 10:30
Hi, 
Any updates?

**Comment by connorjclark** [comment] 2022-10-13 17:42
I can't reproduce this on my end. And it's the same issue as #6512 so I'm gonna close this particular issue.

I think you're best option here is to disable clear storage when this happens.

**Closed by connorjclark** 2022-10-13 17:42 UTC
Labels: bug, needs-more-info, needs-priority

**Comment by bhaskar3112** [comment] 2022-10-14 12:39
It is reproduceable many times on my side in many devices, I suggest you to look into the backend JavaScript coding, there is an error in the coding only in the clear storage option.
The error must be between the intersection of C programming and Javascript.

**Comment by bhaskar3112** [comment] 2022-10-19 09:35
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.youtube.com/
Chrome Version: 106.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1203:929
    at new Promise (<anonymous>)
    at ProtocolSession$1.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1203:881)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async _setupNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1222:504)
    at async _navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1224:716)
    at async _navigations (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1225:458)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:1226:406
```

**Comment by bhaskar3112** [comment] 2022-10-19 09:37
the issue is not only in in mail.google.com it is there on any http or https site and now it does not even works in clear storage disabled function.
