### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by lesukk** [GoogleChrome/lighthouse#1774] opened 2017-02-24 12:17 UTC
**Lighthouse Version**: 1.5.2
**Chrome Version**: 56.0.2924.87
**URL**: http://test.vuukle.com/comments/
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12958:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14035:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14061:25)```

**Comment by wardpeet** [comment] 2017-02-26 19:03
do you see an url when you click on the lighthouse extension?
![image](https://cloud.githubusercontent.com/assets/1120926/23342652/a1b66c5c-fc5e-11e6-947f-bc4b3f465dd3.png)

Any extensions running? Do you have it all the time? Could you test on a clean profile?

**Comment by ebidel** [comment] 2017-03-08 19:05
This is an older version of LH, but looks like this can still happen for 1.6.0.

Marking as a dupe of https://github.com/GoogleChrome/lighthouse/issues/1774

**Closed by ebidel** 2017-03-08 19:05 UTC
Labels: bug, extension
