### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started [does not go away]

### ISSUE THREAD

**Issue by benjaminr177** [GoogleChrome/lighthouse#2083] opened 2017-04-27 11:54 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: http://benjaminhr.com/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by benjaminr177** [comment] 2017-04-27 11:55
Important to note that this does not go away - after refreshing page, etc. still continues to do this.

**Comment by stramel** [comment] 2017-04-27 12:33
Dupe of #1091

**Closed** 2017-04-27 14:43 UTC
