### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by pierrechoffe** [GoogleChrome/lighthouse#1300] opened 2016-12-24 18:44 UTC
**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.95
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11251:29)```

**Comment by ebidel** [comment] 2016-12-25 00:47
This is a dupe of https://github.com/GoogleChrome/lighthouse/issues/1119. Can you add the URL you were testing against, any reliable repro steps, and chrome extensions you have installed (dev tools, etc.) that may affect the page.

**Closed by ebidel** 2016-12-25 00:47 UTC
