### ISSUE TITLE
Javascript boot time from Chrome's extensions should be ignored

### ISSUE THREAD

**Issue by Magissia** [GoogleChrome/lighthouse#5630] opened 2018-07-08 01:23 UTC
#### Provide the steps to reproduce
1. Install some extensions that inject JS in pages in Google Chrome
2. Run LH on any site that doesn't have any JavaScript

#### What is the current behavior?
If an injected JS takes too long to load, Lighthouse says the website is too slow to load it's JavaScript

#### What is the expected behavior?
JS not provided by website, not requested by page that are purely local should be ignored, lighthouse shouldn't try to load them at all.

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version:2.9.1
* Node.js version:Didn't install nodejs
* Operating System: 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fchristant** [comment] 2018-07-18 11:29
I had the same issue: boot-up time of 3.6s whilst the page had almost no JS. All caused by extensions. It's true that incognito mode solves this, but you don't see that recommendation anywhere as part of the standard experience. So extensions strongly skew results as per default. 

It would be interesting to know how many users run an audit in normal vs incognito mode, perhaps you have those numbers?

Don't know about the internal complexities of disabling extensions, but if incognito mode can do it fine, why not during an audit?

**Comment by paulirish** [comment] 2018-08-27 18:41
resolved with #5666

**Closed by paulirish** 2018-08-27 18:41 UTC
Labels: needs-discussion, needs-priority
