### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by AlphaWong** [GoogleChrome/lighthouse#1984] opened 2017-04-09 13:55 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 59.0.3066.0
**URL**: http://rushplace.com/shop/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)```

**Comment by ebidel** [comment] 2017-04-11 19:33
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-04-11 19:33 UTC
