### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by shafeeqonline** [GoogleChrome/lighthouse#2633] opened 2017-07-03 19:58 UTC
**Lighthouse Version**: 2.2.1
**Chrome Version**: 59.0.3071.104
**Initial URL**: https://localhost/bookit/cars/us/en/find-cars/car/list
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13890:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14315:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14340:18)
    at <anonymous>
```

Even though, the test start running fine, midway it starts failing with this error. happen both on CLI as well as extension.

**Comment by wardpeet** [comment] 2017-07-04 04:45
do you get the exact same issue on the cli? Is it possible to put the site public so we can have a look at it ourselves?

**Comment by mindon** [comment] 2017-07-04 09:35
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/http-redirect.js

```
  beforePass(options) {
    this._preRedirectURL = options.url;
    options.url = this._preRedirectURL.replace(/^https/, 'http');
  }
```
find this code which making an https:// into an http://... causing failed (the same in cli)

**Comment by wardpeet** [comment] 2017-07-04 21:15
Than it's probably a dupe of #2363

**Closed by wardpeet** 2017-07-04 21:15 UTC
