### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by sridharAJ** [GoogleChrome/lighthouse#2488] opened 2017-06-12 20:33 UTC
**Lighthouse Version**: 2.1.0
**Chrome Version**: 59.0.3071.86
**Initial URL**: https://udp-test.mynt.myntra.com/udp/home
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9893:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by patrickhulce** [comment] 2017-06-12 21:32
dupe of #1091

**Closed by patrickhulce** 2017-06-12 21:32 UTC
