### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by alipattsev** [GoogleChrome/lighthouse#2566] opened 2017-06-22 09:54 UTC
**Lighthouse Version**: 2.1.0
**Chrome Version**: 59.0.3071.104
**Initial URL**: https://lenta.ru/
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10812:17)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-06-22 16:26
Hi, I wasn't able to repro this using Lighthouse 2.1 from the CLI or the extension. Can you help us with steps to reproduce the error?

**Comment by alipattsev** [comment] 2017-06-22 16:34
The usual:
1) Open page
2) Launch "Generate report" through Chrome extension
3) Get error

I can't repro it now either, so it looks like a one-off, but no idea what caused it.

**Comment by patrickhulce** [comment] 2017-06-22 17:44
likely happened on a run that was particularly long/slow, dupe of #1685

**Closed by patrickhulce** 2017-06-22 17:44 UTC
