### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by FabiodeBorba** [GoogleChrome/lighthouse#2422] opened 2017-06-02 13:49 UTC
**Initial URL**: https://stackoverflow.com/
**Chrome Version**: 61.0.3118.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@e7b341c528a738a53a71ce8f3090f82805557dcc/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by stramel** [comment] 2017-06-02 15:57
Dupe of #1091

**Closed** 2017-06-05 13:44 UTC
Labels: duplicate
