### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by vin14976** [GoogleChrome/lighthouse#2493] opened 2017-06-13 07:37 UTC
**Initial URL**: https://localhost:8084/dashboard
**Chrome Version**: 60.0.3112.24
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@16a564bd7c034b8f6e008d0887fc46c7aae48488/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@16a564bd7c034b8f6e008d0887fc46c7aae48488/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-13 15:01
possible dupe of #1978?

**Comment by patrickhulce** [comment] 2017-08-22 16:55
See #2784 for further questions.

**Closed by patrickhulce** 2017-08-22 16:55 UTC
Labels: duplicate
