### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by shuraki** [GoogleChrome/lighthouse#2460] opened 2017-06-07 09:47 UTC
**Initial URL**: about:blank
**Chrome Version**: 61.0.3122.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@234ec23e9f56bb01af5c59922681b114da3aa540/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@234ec23e9f56bb01af5c59922681b114da3aa540/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-07 17:03
dupe of #2362

**Closed by patrickhulce** 2017-06-07 17:03 UTC
