### ISSUE TITLE
Color Contrast Error: "Element midpoint exceeds the grid bounds"

### ISSUE THREAD

**Issue by FelipeFama** [GoogleChrome/lighthouse#15619] opened 2023-11-17 02:10 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://nefa-crypto-page.vercel.app

### What happened?

When I run Lighthouse to test my web page, my accessibility score does not appear in the browser, instead, an exclamation mark appears.

### What did you expect?

That the score would appear, normally without any type of problem.

### What have you tried?

1 - I tested on Opera and Chrome on Ubuntu and tested on Windows.
2 - In Windows, only Opera worked normally.
3 - I noticed that the ones that didn't work had this version Using Chromium 119.0.0.0 with devtools.
4 - Opera on Windows has a version earlier than this.
5 - I tested the lighthouse extension and it worked normally too, but it has this version Using HeadlessChromium 119.0.6045.105 with lr.

![image-lighthouse-error](https://github.com/GoogleChrome/lighthouse/assets/91050670/963b2ab6-d1d9-42a7-bb2a-1850ae447376)

![image-lighthouse-error-2](https://github.com/GoogleChrome/lighthouse/assets/91050670/57514588-eaa3-4d25-9ca0-2c4b2a67375b)

### How were you running Lighthouse?

Chrome DevTools, WebPageTest

### Lighthouse Version

11.0.0

### Chrome Version

119.0.6045.159

### Node Version

18.16.0

### OS

Windows/Linux

**Comment by adamraine** [comment] 2023-11-17 19:30
I can't repro, it's possible that some Chrome extension is adding content that causes this error. Can you try running Lighthouse from an incognito window in Chrome?

**Comment by FelipeFama** [comment] 2023-11-20 23:41
I tested it but it didn't work.

**Comment by adamraine** [comment] 2023-11-20 23:47
Sorry, missed that you mentioned this was only for desktop. I can repro with this command `lighthouse https://nefa-crypto-page.vercel.app/ --preset=desktop`. Most likely an issue in Axe, I will investigate.

**Comment by adamraine** [comment] 2023-11-21 00:04
https://github.com/dequelabs/axe-core/issues/4253

**Comment by adamraine** [comment] 2023-11-21 20:46
@FelipeFama this is no longer reproducible for me. Has the content on the page changed at all? Are you still able to reproduce this?

**Comment by FelipeFama** [comment] 2023-11-23 01:03
Yes, I can still believe it is something related to axe-core or some version of chromium.

**Comment by clouddevloper** [comment] 2024-01-12 05:19
@adamraine I am still not able to understand how to resolve this. It will be relally helpful  if you can explain.

**Comment by adamraine** [comment] 2024-01-12 05:24
The issue has not been resolved, please see the upstream bug https://github.com/dequelabs/axe-core/issues/4253 for more info.

**Comment by chmerk** [comment] 2024-01-23 09:09
We have the same issue, just on mobile. I added a comment in https://github.com/dequelabs/axe-core/issues/4253

**Comment by kmurugulla** [comment] 2024-02-05 16:04
@adamraine - I am observing the similar issue "axe-core Error: Element midpoint exceeds the grid bounds" for "Mobile" on https://www.ust.com/en/insights . Tried on incognito window but seeing the same error. Appreciate any inputs

![image](https://github.com/GoogleChrome/lighthouse/assets/7944122/dc999d30-ea4a-42de-959a-0f172f54f352)

**Comment by clouddevloper** [comment] 2024-02-06 05:45
Still not able to resolve this issue yet. https://github.com/GoogleChrome/lighthouse/issues/15750

Let me know if any one can help here. 

Thanks

**Comment by chmerk** [comment] 2024-02-06 09:20
@clouddevloper @kmurugulla 
Please add this to the issue https://github.com/dequelabs/axe-core/issues/4253
So the axe developers can prioritize the issue accordingly. :)

**Comment by aprzygocki** [comment] 2024-02-09 01:16
I have the same issue

**Comment by neronim1141** [comment] 2024-02-11 00:33
I can report the same issue

**Comment by dylanrihan** [comment] 2024-02-12 04:28
I have the same issue, any suggestions?

**Comment by TutorFx** [comment] 2024-02-19 21:38
I'm having this same issue on https://github.com/TutorFx/vs-contabil

**Comment by TutorFx** [comment] 2024-02-20 20:03
> @aprzygocki @neronim1141 @dylanrihan @TutorFx Could you please also report the issue at [dequelabs/axe-core#4253](https://github.com/dequelabs/axe-core/issues/4253) to make them aware, that there are more people/sites affected. So far there seems to be little activity :( Thanks! :)

Thanks for moving the thread @chmerk, I was able to uncover the root cause of the issue and described a workaround in the discussion [there](https://github.com/dequelabs/axe-core/issues/4253).

**Comment by adamraine** [comment] 2024-03-27 16:14
Resolved by https://github.com/GoogleChrome/lighthouse/pull/15887, this will ship in the next Lighthouse release.

**Closed by adamraine** 2024-03-27 16:14 UTC
Labels: bug, P1, upstream-action-required
