### ISSUE TITLE
Lighthouse unable to recognize service worker

### ISSUE THREAD

**Issue by AKPMultimedia** [GoogleChrome/lighthouse#6935] opened 2019-01-06 14:49 UTC
Google Lighthose is sometimes unable to recognize the properly installed Service Worker. Sometimes it works and sometimes it doesn't.

https://www.ackeller.ch/

**Comment by patrickhulce** [comment] 2019-01-06 18:50
Thanks for filing @AKPMultimedia! Any details on how you're running Lighthouse? DevTools? Extension? Node CLI? What's your environment?

If you could fill out the environment questionnaire in our [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) that'd be great!

**Comment by AKPMultimedia** [comment] 2019-01-06 21:10
1. Run LH on 
Google Chrome Lighthouse Extension
#### What is the current behavior?
Sometimes: Does not register a service worker
#### What is the expected behavior?

#### Environment Information
* Affected Channels: 
* Lighthouse version: 3.3.0.4001
* Node.js version: 10.15.0 LTS
* Operating System: W10

**Comment by pairmix** [comment] 2019-02-18 13:17
I've got the same issue.

**Comment by exterkamp** [comment] 2019-02-22 06:18
I think this is a duplicate of #6342 the bug behavior seems quite similar and they seem related.

**Closed** 2019-04-25 21:13 UTC
Labels: needs-more-info, pending-close
