### ISSUE TITLE
I want the Old chrome Audit Back

### ISSUE THREAD

**Issue by dryleaf** [GoogleChrome/lighthouse#5807] opened 2018-08-08 01:32 UTC
## Summary
- The new Chrome audit declined its usability.
- Lots of features have been removed from the old Audit.
  - The FMP and TI, CI are very hard to read, the graph and other detailed information has been removed and seriously! Why use it in the first place?
- **Defer unused CSS**
  - In the new version of the chrome audit, no matter whether you follow the suggestion by google [OptimizeCSSDelivery](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery) or not, this field always fires as *failed*.

**Comment by brendankenny** [comment] 2018-08-10 17:34
Sorry to hear the 3.0 release has been a downgrade for you. Note that the 2.9 branch is still on npm if you can run Lighthouse from the command line.

> The FMP and TI, CI are very hard to read, the graph and other detailed information has been removed and seriously! Why use it in the first place?

We found that the graph was actually pretty confusing to many users, and what's worse, they didn't realize they were interpreting it differently than was intended. That's just bad design on our part :)

We'e been kicking around ideas for a replacement and would love specific suggestions, e.g. what about the old graph you found useful, what you'd like to see improved or added, etc.

> In the new version of the chrome audit, no matter whether you follow the suggestion by google OptimizeCSSDelivery or not, this field always fires as failed.

This definitely shouldn't be happening. Do you have a URL available to test to see what's going wrong?

**Comment by paulirish** [comment] 2018-08-27 18:07
ping @dryleaf to see if you have a URL we can test this CSS issue with. thanks!

**Comment by brendankenny** [comment] 2018-09-08 00:26
Closing for now. If you want to keep digging into this, please comment and we can reopen

**Closed by brendankenny** 2018-09-08 00:26 UTC
Labels: needs-more-info, pending-close
