### ISSUE TITLE
Unused CSS reports confusing numbers

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9614] opened 2019-08-26 22:15 UTC
https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.gatsbyjs.org%2F&tab=mobile

![image](https://user-images.githubusercontent.com/4071474/63727128-3d02b700-c814-11e9-9dac-48526eff392c.png)

.... (tons of rules)

![image](https://user-images.githubusercontent.com/4071474/63727141-468c1f00-c814-11e9-8aa5-2e10a3cd6ce2.png)

Potential savings 0 kb, but sum of the columns is 6kb. what?

**Comment by patrickhulce** [comment] 2019-09-24 22:35
Nostradamus @connorjclark! Filing issues before your time 😆 

turns out this is an exact dupe of the root of https://github.com/GoogleChrome/lighthouse/issues/9684 rearing its head in PSI, we'll track over there but fix incoming 👍

**Closed by patrickhulce** 2019-09-24 22:35 UTC
Labels: P1.5, needs-investigation
