### ISSUE TITLE
Adsense Anchor Ads Causes CLS

### ISSUE THREAD

**Issue by b21946606** [GoogleChrome/lighthouse#11724] opened 2020-11-29 13:20 UTC
Hey, I am preparing my site for Core Web Vitals. I am using Adsense for monetizing my site. But Adsense's automatic anchor ads causes CLS in mobile pages. You can find an example of anchor ads; with this link:
https://support.google.com/adsense/answer/9748090?hl=en

Reason Of Increment Of CLS Score: When user starts to scroll, anchor ads show and Adsense add style="padding: 124px 0px 0px;" in body tag. This is increasing CLS score. Only that's issue that i cant fix because Adsense ads is dynamically inserting it.

Similar Topic About Same Issue: https://github.com/GoogleChrome/lighthouse/issues/11004

Note: I know its not about Lighthouse, its about Adsense. I searched all around web but i haven't find any solutions or topics about that yet (except link at top). I just want to talk about possible JavaScript or CSS solutions for that.

**Comment by patrickhulce** [comment] 2020-11-30 16:15
Thanks for filing @b21946606! As stated in https://github.com/GoogleChrome/lighthouse/issues/11004#issuecomment-648895965 though, this forum is for issues with Lighthouse. Since this is a field data issue caused by adsense we're not really able to help much here.

If you haven't already, read through ads published [best practices for minimizing layout shift](https://developers.google.com/publisher-tag/guides/minimize-layout-shift), and maybe you can try contacting Adsense to get through to the [known issues](https://support.google.com/adsense/answer/1067521?hl=en)?

We're going to close this as there's no action for Lighthouse to take with regard to reporting CLS. Best of luck to you though!

**Closed by patrickhulce** 2020-11-30 16:15 UTC
Labels: needs-priority
