### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by qobitech** [GoogleChrome/lighthouse#15399] opened 2023-08-23 12:24 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://edekobi.com

### What happened?

I clicked on the button titled "Analyze page state" and it returned the error "Cannot read properties of null"
<img width="504" alt="Screen Shot 2023-08-23 at 1 11 38 PM" src="https://github.com/GoogleChrome/lighthouse/assets/45414030/dbdbcdee-369e-4287-a0a3-b03994c7a9ab">

### What did you expect?

I expected it to audit the page and show results of the audit

### What have you tried?

I refreshed the page and tried inspecting the page again, same result

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

100.0.0.0

### Chrome Version

Version 116.0.5845.96 (Official Build) (arm64)

### Node Version

v14.17.0

### OS

Mac OS

**Comment by adamraine** [comment] 2023-08-23 17:16
I think this has the same root cause as #15300. The error message is different because you are using snapshot mode instead of navigation mode. Closing as duplicate.

**Closed by adamraine** 2023-08-23 17:16 UTC
Labels: bug
