### ISSUE TITLE
PSI isn't requesting all referenced images

### ISSUE THREAD

**Issue by Lofesa** [GoogleChrome/lighthouse#10390] opened 2020-02-27 11:45 UTC
Hi
Maybe is a dumb question, but....
Regarding to native lazyload images in chrome, the viewport is spanded depending on the connection speed. So whats happens when the throttling is "simulated"?
Thats is that I can see:
In a chrome version 80 with Nexus 5x emulation:
Whit native lazy load disbled, only the suplied ([lazysizes](https://github.com/aFarkas/lazysizes)) lazyload works, so in my site, only 3 images are loaded until you scroll down. When do the audit, only these 3 images are loaded.
When native lazyload is enabled, 7 images are loaded, no matter if in performance panel I set network and cpu throttled or not.

In PSI or web.dev the behaviour changes, same on WPT:
Some times it load 3 images, some times the 7 ones.

These behaviour changes the timming for tests?  At least the onLoad event is at a diferent time.....

EDIT: I´m using a WP plugin that uses lazysizes but put the `loading=lazy` label and a js snippet that bypass the lazysizes if native lazyload is in place.

Images, the same url, 2 times PSI run:
![tempsnip](https://user-images.githubusercontent.com/22342793/75442678-481fd680-5960-11ea-9662-144ab8897722.jpg)

![tempsnip1](https://user-images.githubusercontent.com/22342793/75442691-4e15b780-5960-11ea-9e75-4e1ab565d14f.jpg)

**Comment by patrickhulce** [comment] 2020-02-27 15:48
Thanks for filing @Lofesa!

The native image lazy loading has a very large radius for what it will eagerly load (within ~3000px of the viewport) so this is probably why you're seeing the different in behavior if I understand your question correctly. We recently adjusted the offscreen images audit to manually accept native lazily loaded images (see #10053) as well.

**Comment by Lofesa** [comment] 2020-02-27 17:33
Ummm the issue you refereced is about if `loading=some thing` must be considered a valid label to pass the test.
I´m talking about other thing. If you run 2 times LH in PSI or web.dev you can spect that the behaviour be the same, timming may differ between each run cause the variabilty, yes, but the radius where the images get loaded must be the same. Maybe the issue is how chrome himself do the lazyload.

Think about this with an extreme (and maybe riduculous) example:
Pages are loaded, normally, in the order html, then css and last js, but this order get changed between LH runs, and in the 2 the order become js, css and html... surely the score changes, and you can´t compare the 1st. run with the 2nd. one.

If the 1st. run have 3000px of radius over the viewport, the 2nd must have the same radius, not 200px and then you can compare between runs or pages.

Hope I well expresed my question cause my english is so bad. But at last it can be resumed in Loading X images, timmings are the same that loading X+N imaages? If the response is no, then the question is Why LH loads diferent number of images between runs in the same url?

**Comment by patrickhulce** [comment] 2020-02-27 17:41
Hm I'm not sure I totally understand then. Let me try to clarify.

When you said...

> Whit native lazy load disbled, only the suplied (lazysizes) lazyload works, so in my site, only 3 images are loaded until you scroll down. When do the audit, only these 3 images are loaded.
When native lazyload is enabled, 7 images are loaded, no matter if in performance panel I set network and cpu throttled or not.

I interpreted that to mean the site is changing its use of native `loading=lazy` vs. a library to lazy load. If that's true, then that is what is causing the change in the number of images to be loaded.

But when you say...

> If you run 2 times LH in PSI or web.dev you can spect that the behaviour be the same, timming may differ between each run cause the variabilty, yes, but the radius where the images get loaded must be the sam

It sounds like there is nothing changing with the page?

Do you have a URL where we can reproduce this issue if that's the case?

**Comment by Lofesa** [comment] 2020-02-27 18:46
> When you said...
> 
> > Whit native lazy load disbled, only the suplied (lazysizes) lazyload works, so in my site, only 3 images are loaded until you scroll down. When do the audit, only these 3 images are loaded.
> > When native lazyload is enabled, 7 images are loaded, no matter if in performance panel I set network and cpu throttled or not.
> 
> I interpreted that to mean the site is changing its use of native `loading=lazy` vs. a library to lazy load. If that's true, then that is what is causing the change in the number of images to be loaded.

The use case is: 

A web that uses a WP plugin that uses lazysizes and put the native loading label, so images have all the data-src, data-srcset stuff and the loading=lazy  label, so both are present, stuff for lazysizes and stuff for native lazyload.  This plugin add a js file with the logic to detect native lazyload, so if it is detected, then lazysises do nothing and images are natively lazyloaded.

If you disable native lazyload in the browser (with the chrome://flags stuff) then you get only 3 images loaded, cause the lazysizes has a short radius. If you enable the native lazyload in the browser, the you got 6-7 images loaded. All this emulating Nexus-5X, with desktop the number of images changes.

> 
> But when you say...
> 
> > If you run 2 times LH in PSI or web.dev you can spect that the behaviour be the same, timming may differ between each run cause the variabilty, yes, but the radius where the images get loaded must be the sam
> 
> It sounds like there is nothing changing with the page?

Yes, is all time the same page content.
> 
> Do you have a URL where we can reproduce this issue if that's the case?

Off course: https://intersindicalrm.org/

But you need to hit the page with LH some number of times, don´t work 1 yes, 1 not. Is a random thing, maybe 4 times load 3 images and then 1 load 7, maybe 2 times load 3 images and then load 7.... a very ramdom stuff.

**Comment by patrickhulce** [comment] 2020-02-27 19:04
Got it! Yes, I see now. 

10/10 runs from the CLI all have 7 Images requested, so this seems to be PSI-specific behavior (first two I ran were 3 and then 7)

@exterkamp any ideas here?

**Comment by Lofesa** [comment] 2020-02-27 20:29
Well, native lazyload makes their radius in function of network speed, so
we can spect a variable number of loaded images if the network speed is
about any of the limits.
I will say, if a 1Mb speed the radius is 3000px, if you get a little bit of
speed the the radius maybe...2500px, same for upper speeds.
But load only these 3 images, make me think that native lazyload don't work
or is disabled for these request.
If Google take these measures as a signal for any purpuse, these measures
must be accurated, predectibles....

**Comment by connorjclark** [comment] 2020-03-20 21:48
Simulated throttling means we don't throttle as the page is loading, we only throttle in our analysis step. However, I could see that our backend services have a varying amount of connection type. Lazy loading radius is based on [ECT](https://developer.mozilla.org/en-US/docs/Glossary/Effective_connection_type).

@exterkamp

We use a brand new chrome profile for each run. We don't understand exactly when ECT is determined. Ideally we should emulate this behavior. To investigate, we should log out ECT in both environments and see what the difference is.

**Comment by patrickhulce** [comment] 2020-04-28 20:10
p1.5 because this seems like a legit PSI infra issue to investigate

**Comment by TheDutchCoder** [comment] 2020-05-29 15:12
In the latest version of Lighthouse in Chrome devtools, this report is currently bugged/broken it seems.

All our images have the `loading="lazy"`attribute, yet only some of them are showing up in the report as not being deferred.

All of these reported images are 3000px+ off-screen, yet the images NOT reported are close to the viewport or already in it:
![image](https://user-images.githubusercontent.com/1668207/83275498-3804d680-a19d-11ea-94f7-3912ec9df64c.png)

It's almost as if the results are inverted somehow. But besides that, it seems to fully ignore the loading attribute altogether.

**Comment by patrickhulce** [comment] 2020-05-29 15:40
> in Chrome devtools

That's a separate issue fixed in 6.0 (available in Chrome Canary), see #6677 for more on that.

This is about issues specific to PageSpeed Insights.

**Comment by TheDutchCoder** [comment] 2020-05-29 15:47
Ah okay, thanks

**Comment by johncarlson21** [comment] 2020-06-11 19:41
This is broken again.. it was fixed like 2 weeks ago.. and now today I'm getting issues.. I think this actually broke yesterday as I have different results from yesterday.
This is broken in Page Speed Insights, LightHouse in Chrome and Chrome Browser itself seems to not be adhering to lazyload

**Comment by patrickhulce** [comment] 2020-06-11 19:49
This issue is very specific to the *number of requested images in PSI being different from the number of requested images in every other channel*. 

If you have a reproducible bug report about lazily loaded images not being respected *in Chrome Canary*, then a separate issue with reproduction steps and a URL would be very much appreciated.

**Comment by adrianaixba** [comment] 2020-10-06 16:53
Closing this issue for now, since we're unable to reproduce it with https://intersindicalrm.org/. But, will open it if there is a follow up url that responds the same!

**Closed by adrianaixba** 2020-10-06 16:53 UTC
Labels: P1.5, PSI/LR, needs-investigation, variability

**Comment by adrianaixba** [comment] 2020-10-06 23:09
Update: @paulirish and I took a quick look at this earlier. We logged out the network information on both PSI (tti: 0ms, 4g, downlink: ~10Mbps) and the CI (tti: ~150ms, 4g, downlink: ~1.75Mbps). Seems like the problem might not be there, since faster speeds are supposed to yield the larger lazy loading radius, which is not happening for this PSI case. Might have to take a different direction.

**Comment by Lofesa** [comment] 2020-10-07 10:40
> Closing this issue for now, since we're unable to reproduce it with https://intersindicalrm.org/. But, will open it if there is a follow up url that responds the same!

In this url the issue is not reproducible as far as I disabled the native lazyload in the lazysizes plugin.
I will try to enable it again to check if the issue still here and  inform the results. If needed I can let it enabled.

**Comment by Lofesa** [comment] 2020-10-07 12:01
In the same run PSI show 5 images loaded in mobil emulation and only 2 on desktop

![Captura](https://user-images.githubusercontent.com/22342793/95326238-8c823600-08a2-11eb-8441-124c9dbd04d4.jpg)

![Captura1](https://user-images.githubusercontent.com/22342793/95326289-9efc6f80-08a2-11eb-8523-8fbf38c45206.JPG)

In others runs it show 2 images for both devices, mobil and desktop. In chrome devtools LH desktop, same... some times show 2, some times 5 and some times 6... In mobil seems that consistently only show 2 images
Dev Tools LH 6.4.0

![Captura](https://user-images.githubusercontent.com/22342793/95328073-4aa6bf00-08a5-11eb-91b1-fe0822b40ee4.jpg)

Dev Tools LH 6.0.0

![Captura1](https://user-images.githubusercontent.com/22342793/95328092-509ca000-08a5-11eb-9ee1-21c0f04da996.JPG)
