### ISSUE TITLE
Generating Results Doesn't Stop Running

### ISSUE THREAD

**Issue by scotburns** [GoogleChrome/lighthouse#4453] opened 2018-02-07 17:45 UTC
As the title says, the "Generating Results" operation won't finish. It just keeps on running.

**Comment by patrickhulce** [comment] 2018-02-13 22:06
@scotburns do you have a reproducible case with a public URL you'd be willing to give us? Is this with extension, DevTools, or CLI?

**Comment by scotburns** [comment] 2018-02-15 18:36
Hi - I'm no developer, so I'll try my best to explain....

I installed the app into my Chrome browser. If I run it on any site, www.drthomasmustoe.com for example, it runs and then generates a report, but the window in the upper RH corner under the Lighthouse icon remains open and still says "Generating Report" once the report is generated. It seems as there is no signal for the app window to stop running and close. 

Hope that helps.

**Comment by stefanos82** [comment] 2018-03-17 11:35
I have the same issue as @scotburns, if not worse.

It's being more than 10 minutes now and all I see is this:

![image](https://user-images.githubusercontent.com/1777466/37554906-fe225994-29e7-11e8-8919-b6a2ef84b100.png)

My Chromium version is `Version 62.0.3202.89 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`.

The website I'm trying to audit is [philenews](http://www.philenews.com), a Greek-Cypriot online newspaper.

**Comment by patrickhulce** [comment] 2018-03-19 16:19
@stefanos82 your issues is actually a different root cause #2627, you'll need to use Chrome extension of official stable to get DevTools version.

Thanks for the additional info @scotburns as we can't seem to observe this ourselves, we'll need additional cases before we can investigate a fix. Appreciate your patience!

**Comment by stefanos82** [comment] 2018-03-19 21:47
Cheers @patrickhulce for letting me know.

**Comment by Serkan-devel** [comment] 2018-03-21 16:24
But on debian stable the same issue is still there

**Comment by patrickhulce** [comment] 2018-03-21 16:42
@Serkan-devel this issue is different. "Generating Results" is a different phase than "Loading" stuck you experienced and is tracked by #2627, let's keep that discussion there please.

**Comment by wardpeet** [comment] 2018-08-20 20:42
closing as I see the discussion is being done on #2627.

Thank you @Serkan-devel

**Closed by wardpeet** 2018-08-20 20:42 UTC
Labels: bug, chillin ❄, extension, needs-more-info
