### ISSUE TITLE
lighthouse top part where you close or kill the results after running lighthouse

### ISSUE THREAD

**Issue by ilgizpg** [GoogleChrome/lighthouse#15185] opened 2023-06-19 12:43 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

local host 

### What happened?

After running lighthouse, if I scroll down and go back to top, the top part disappears where you have the option to close or kill the lighthouse results. I'm not bale to rerun the lighthouse until I completely close the inspect window and reopen it. It started to happen only recently I believe after my last chrome update. Thanks

### What did you expect?

I was excepting to see everything I saw at the first place where you can close the results and rerun the lighthouse

### How were you running Lighthouse?

WebPageTest

### Lighthouse Version

the latest

**Comment by adamraine** [comment] 2023-06-20 19:23
Can you please fill out the entire bug report. It sounds like you are using Lighthouse in Chrome DevTools however you filled out the form saying you were using [WebPageTest](https://github.com/WPO-Foundation/webpagetest/).

I cannot reproduce this so could you also provide more specific repro steps and/or screenshots of what you are referring to.

**Comment by adamraine** [comment] 2023-06-20 21:05
Moving to #15190

**Closed by adamraine** 2023-06-20 21:05 UTC
Labels: bug, needs-more-info, needs-priority
