### ISSUE TITLE
Extension Error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by yoanmarchal** [GoogleChrome/lighthouse#1165] opened 2016-12-15 23:30 UTC
**Lighthouse Version**: 1.2.2
**Chrome Version**: 57.0.2952.0
**Error Message**: Cannot read property 'message' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'message' of undefined
    at collectUsage.then.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:4444:23)```

**Comment by ebidel** [comment] 2016-12-16 01:27
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1147

**Closed by ebidel** 2016-12-16 01:27 UTC
