### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by vijaycapita** [GoogleChrome/lighthouse#1119] opened 2016-12-07 06:32 UTC
**Lighthouse Version**: 1.2.2
**Chrome Version**: 55.0.2883.75
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11095:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:38340:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:38353:25)```

**Comment by wardpeet** [comment] 2016-12-07 08:34
do you get this each time?
And would you be able to provide an url.

**Comment by ebidel** [comment] 2016-12-30 17:04
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2016-12-30 17:04 UTC
