### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by rharmse** [GoogleChrome/lighthouse#2636] opened 2017-07-04 12:54 UTC
**Lighthouse Version**: 2.2.1
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://myvodacomqa1.secure.vodacom.co.za/vodacom/home
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13890:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14315:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14340:18)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-07-05 05:07
dupe of #1834

**Closed by patrickhulce** 2017-07-05 05:07 UTC
