### ISSUE TITLE
Consider resources being fetched after service worker install not critical

### ISSUE THREAD

**Issue by midzer** [GoogleChrome/lighthouse#6011] opened 2018-09-12 20:01 UTC
Using latest `master`, searching in issues and some diggin in code beforehand.

**Feature request summary**

I wonder whether it's a good idea to relax LH `isCritical()` function in `critical-request-chains.js` for use case described below.

Yeah, I can further investigate and open a PR once there's some progress.

**What is the motivation or use case for changing this?**
In one of my projects I experiment with lazy loading small `.css` files on demand **after** service worker has been installed successfully. Right now LH argues there is an opportunity to preload this (key) request as `<link rel='stylesheet'> elements are high priority for any browser.

People might use `importScript()` in their service worker file. Fetching additional resources with those scripts might happen, see https://github.com/GoogleChromeLabs/sw-precache#importscripts-arraystring

**How is this beneficial to Ligthhouse?**
More accurate opportunities whether preloading resources is an option to improve the application

**Possible ways of implementation**
a) check respective file if it's fetch start time > service worker install time
b) somehow use `DOMContentLoaded` or `Interactive` time
c) your idea :)

**Comment by paulirish** [comment] 2020-01-28 21:29
@midzer do you know if this is still a thing?   We can definitely consider doing this but a lot has changed so I'm curious...

Also, got a repro URL? thanks

**Comment by midzer** [comment] 2020-01-28 21:55
@paulirish Thanks for bringing this back up. Too bad I've patched this "load CSS after service worker registration" mechanism https://github.com/midzer/eisolzried/blob/e647f34613e0e67cf3e278282c0d85d3cc851958/_assets/js/vendor/service-worker-registration.js#L46 out of live code summer last year.

If it helps you, I can restore this code the next days.

**Comment by patrickhulce** [comment] 2020-09-15 20:15
Duplicate of #11408

**Closed by patrickhulce** 2020-09-15 20:15 UTC
Labels: needs-discussion, needs-priority
