### ISSUE TITLE
Errors looks bad in Audits

### ISSUE THREAD

**Issue by xuxinya** [GoogleChrome/lighthouse#9300] opened 2019-06-28 01:59 UTC
Run LH on chrome Audits,It is expected to be not overflow

  
![image](https://user-images.githubusercontent.com/7734509/60311720-17c80880-998b-11e9-8152-75561e463aae.png)

**Comment by patrickhulce** [comment] 2019-06-28 12:27
Thanks @xuxinya! Duplicate of #8974, we'll track over there.

**Closed by patrickhulce** 2019-06-28 12:27 UTC
