### ISSUE TITLE
Audits no longer runs in Desktop device test mode

### ISSUE THREAD

**Issue by drpixel9400** [GoogleChrome/lighthouse#6808] opened 2018-12-14 12:26 UTC
Running Audits i DevTools has suddenly changed to only mobile tests. I still have the two radio buttons (Mobile / Desktop) but they do the same: only mobile. The title-text (for mouse-hover) also states that there is only a mobile test available, although it's hovered above the label 'Desktop'. It changed to this "double mobile" three days ago. I even ran a Chrome update, but still the same issue. 
![image](https://user-images.githubusercontent.com/45875252/50003434-e3b76800-ffa3-11e8-8552-dd2d77585d26.png)

**Comment by patrickhulce** [comment] 2018-12-14 15:10
Thanks for filing @drpixel9400! This is a duplicate of #6772, so feel free to follow along there.

**Closed by patrickhulce** 2018-12-14 15:10 UTC

**Comment by Hoten** [comment] 2018-12-14 23:05
Fixed in Canary Chrome.
