### ISSUE TITLE
Pwa check does not check "start_url"

### ISSUE THREAD

**Issue by atar-axis** [GoogleChrome/lighthouse#11716] opened 2020-11-26 01:20 UTC
#### Provide the steps to reproduce
1. Run LH on a page with a manifest without `start_url`
2. Check the PWA test

#### What is the current behavior?
LH says the website is installable

#### What is the expected behavior?
LH should Check if there is a `start_url` defined. Even `"start_url": "."` works, but it isn't installable without.

**Comment by patrickhulce** [comment] 2020-11-26 04:10
Thanks for filing @atar-axis!

I can repro the installability errors in Chrome when start_url is missing entirely. The issue is that we observe the manifest parsing spec which instructs user agents to use the document URL as the default value.

Unfortunately, [Chrome doesn't actually seem to do this](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/manifest/manifest_parser.cc;l=301?q=start_url%20lang:cpp%20-f:out%20-f:test&ss=chromium) *when considering if a manifest has a valid start URL* instead using [the value as defaults for other internal manifest validations](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/manifest/manifest_parser.cc;l=310-313?q=start_url%20lang:cpp%20-f:out%20-f:test&ss=chromium) and this behavior appears to be [slated for removal](https://github.com/w3c/manifest/issues/668) at some point in the future. Docs are also inconsistent on this point, saying [Chrome requires it but Firefox doesn't](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#How_do_you_make_an_app_A2HS-ready), and then also saying that [it's "required" but immediately contradicting](https://web.dev/add-manifest/#start-url) by saying the page the user was on when installing will be used if it's not set...

In any case, matching the installability errors shown in DevTools and encouraging a best practice in Lighthouse SGTM 👍

**Comment by paulirish** [comment] 2020-12-17 09:05
yup devtools does catch this.

![image](https://user-images.githubusercontent.com/39191/102466345-c3439d80-4003-11eb-8567-bdc2ecc8175a.png)


![image](https://user-images.githubusercontent.com/39191/102466197-8bd4f100-4003-11eb-99a0-0ab203ba248b.png)


but, good news! as of our master branch, we now reflect this as well. 

![image](https://user-images.githubusercontent.com/39191/102466318-b8890880-4003-11eb-8889-c37f56b1b020.png)

this will be in our 7.0 release.


fixed by #10515

**Closed by paulirish** 2020-12-17 09:05 UTC
Labels: needs-discussion, needs-priority
