### ISSUE TITLE
Accessibility has error message.

### ISSUE THREAD

**Issue by shuhang-eb** [GoogleChrome/lighthouse#10969] opened 2020-06-16 05:51 UTC
#### Provide the steps to reproduce
1. Run LH on <https://rescuemyresumes.com/resumes/edit/>
  

#### What is the current behavior?

The background and foreground color... has 'error!' which leads to '?' in Accessibility.

#### What is the expected behavior?

Accessibility has normal ratings

#### Environment Information
* Affected Channels: 
* Lighthouse version: latest
* Chrome version: 
* Node.js version:
* Operating System: Ubuntu

**Related issues**

**Comment by patrickhulce** [comment] 2020-06-16 16:15
Thanks for filing @shuhang-eb! This is a duplicate of #10908 and is being worked on.

**Closed by patrickhulce** 2020-06-16 16:15 UTC
Labels: needs-priority
