### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by ErstwhileWork** [GoogleChrome/lighthouse#2329] opened 2017-05-22 15:38 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 59.0.3071.61
**URL**: http://mcdcc.org/
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12538:27)
    at <anonymous>```

Error easily reproducible by adding LightHouse extension to Chrome Beta .. still occurs consistently

**Comment by wardpeet** [comment] 2017-05-22 20:13
is there any reason you are testing on Chrome Beta and not chrome canary?

**Comment by paulirish** [comment] 2017-05-22 21:52
dupe of #1685

**Closed by paulirish** 2017-05-22 21:52 UTC

**Comment by ev1stensberg** [comment] 2017-05-22 23:01
Working on a fix on this.

**Comment by ErstwhileWork** [comment] 2017-05-23 18:41
Even -- when recently tested it appears that the google extension updated
to v 2.0.0 .. and the site in question (mcdcc.org) did successfully
complete.

FYI!

Thanks for your help!
Joseph
