### ISSUE TITLE
Improve lighthouse results `extendedInfo` structure guarantee

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1981] opened 2017-04-07 23:34 UTC
Lighthouse results `extendedInfo` property tree is sometimes not defined. I came across this issue when working on plots, and I created a `safeGet` function as a workaround: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/traces/pwmetrics-events.js.

As @brendankenny is working on re-enabling closure compiler, we'll want to have a less hacky way of dealing this issue and still be type-checking friendly.

**Comment by paulirish** [comment] 2017-09-26 21:36
dupe of #2165 basicallly

**Closed** 2017-09-26 22:40 UTC
Labels: pending-close
