### ISSUE TITLE
Bug with Compression/GZIP

### ISSUE THREAD

**Issue by Onore** [GoogleChrome/lighthouse#7095] opened 2019-01-26 09:43 UTC
Hello.

1. Lighthouse
Chrome version says Text Compression  is disable
PageSpeed version says Text Compression  is enable
Example url: https://techhome.kiev.ua
Latest Chrome.

2. https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css
DevTools Network download without compression 150 Kb
PageSpeed Lighthouse -- 20Kb

2.1 https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css
DevTools Network download -- 20 Kb
PageSpeed Lighthouse -- 20Kb

**Comment by patrickhulce** [comment] 2019-01-26 18:43
Thanks for filing @Onore!

I'm not able to reproduce this.

That URL (https://techhome.kiev.ua) passes the "Enable text compression" audit in PageSpeed Insights, Chrome DevTools, CLI, and Chrome Extension. 

Are the other URLs you reference what the audit is flagging for you?

**Comment by exterkamp** [comment] 2019-02-05 18:05
This is probably a duplicate of #7141.  Which has been fixed 😄

**Closed** 2019-02-05 18:05 UTC
Labels: needs-more-info
