### ISSUE TITLE
Extension Error: Invalid string length

### ISSUE THREAD

**Issue by BenjaminWalsh** [GoogleChrome/lighthouse#2421] opened 2017-06-02 08:48 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 58.0.3029.110
**URL**: http://www.diy.com/departments/outdoor-garden/barbecues/DIY780334.cat
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12538:27)
    at <anonymous>```

**Comment by patrickhulce** [comment] 2017-06-22 17:43
dupe of #1685

**Closed by patrickhulce** 2017-06-22 17:43 UTC
