### ISSUE TITLE
pages the modify fetch mess with gathering

### ISSUE THREAD

**Issue by parmalarm** [GoogleChrome/lighthouse#10065] opened 2019-12-03 23:05 UTC
#### **Provide the steps to reproduce**
1. Run LH on <affected url>
- Go to https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.tiffany.com and the page speed score does not load. 
  

#### **What is the current behavior**?
I'm trying to pull lighthouse scores for www.tiffany.com but every time i do i receive a "backend error" message. This issue started around Sep 4th, prior to that date, i was able to pull lighthouse KPI's however the SEO score has never been able to populate.

**Today i get the following message:** Lighthouse returned error: generic::internal: Extension result empty. Lighthouse calling Page.navigate with https://www.tiffany.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5525:13) at http://ghost-rider/devtools_script_api.js:708:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:707:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:689:65) at <anonymous>:1:40 Dismiss

#### **What is the expected behavior?**
I expect to see a desktop and mobile speed scores pulled i from lighthouse. 

#### **Environment Information**
* Affected Channels:  All channels
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System: windows & mac

**Related issues**

**Comment by exterkamp** [comment] 2019-12-19 21:19
This is failing in PSI, DevTools, and CLI because of

```
Runtime error encountered: Protocol error (Runtime.evaluate): Promise was collected
```

I'll look more into this, but might be a duplicate of: #5973

**Comment by exterkamp** [comment] 2019-12-19 21:53
Seems like `https://www.tiffanys.com/` is consuming our `fetch()` functions and erroring on them?

See:
![image](https://user-images.githubusercontent.com/6392995/71211763-6d63da80-2275-11ea-8d56-d94959a36f02.png)

```javascript
function a(e, t) {
    return new Promise(function(n, r) {
        var i = e.clone(); // death here with: TypeError: e.clone is not a function
        "POST" === e.method ? e.json().then(function(r) {
            ...
```

This is killing the Lighthouse run on the `robots.txt` gatherer when we try to fetch the `robots.txt` page from what I can see.

**Comment by connorjclark** [comment] 2019-12-19 22:12
Yup, this page is intercepting the fetch command. Since this page is minified and does not have source maps, we can't investigate further.

My first inclination is that we should cache the native `fetch` (just like we do for other things that developers like to override ... see https://github.com/GoogleChrome/lighthouse/blob/648248e270deeef33e1b16b3420b43cc97230a97/lighthouse-core/gather/driver.js#L1472 ). `https://www.tiffanys.com/` keeps timing out so I can't confirm this will fix it right now.

**Comment by patrickhulce** [comment] 2019-12-19 23:19
Seems like the better fix is to have the robots txt gatherer `useIsolation` instead. At some point we should probably make that the default and force gatherers to opt-in to page context if they absolutely need it.

**Comment by exterkamp** [comment] 2019-12-20 17:50
This is happening in `lighthouse/lighthouse-core/lib/stack-collector.js` as well, and similarly needs to run in isolation.

**Comment by jmartinezpoq** [comment] 2020-02-13 07:37
Hi, i have the same problem to this URL, **https://www.lladro.com/es_es/escultura-gondola-en-venecia-serie-limitada-es-es-01002014.html**

This is happening from API
![image](https://user-images.githubusercontent.com/47970682/74411606-f5acc900-4e3b-11ea-807f-0b01578d23f2.png)

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.lladro.com%2Fes_es%2Fescultura-gondola-en-venecia-serie-limitada-es-es-01002014.html

**Comment by gsuberland** [comment] 2020-04-03 02:10
If an additional data point helps, I am also running into this bug on https://poly.nomial.co.uk/

**Comment by philkrie** [comment] 2020-05-27 17:06
@patrickhulce testing in Chrome Canary 85, I'm stilling getting this issue for tiffany.com (confirmed using LH v6.0.0), so it looks like #10133 didn't completely fix it

This is the message provided in Dev Tools; it's a different message so perhaps a different issue

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.tiffany.com/
Chrome Version: 85.0.4157.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@a4f2f880e7da1a083b75ee48b665dc2e2aa22840/lighthouse_worker/lighthouse_worker_module.js:1453:229)
```

**Comment by patrickhulce** [comment] 2020-05-27 17:27
@philkrie that is #6512, very unrelated but even more annoying because we can't really do anything about it :)

**Comment by connorjclark** [comment] 2020-06-09 19:50
We should modify the stack collector code we inject to use a window.___LH_FETCH native global.

**Closed** 2021-12-10 15:29 UTC
Labels: bug, P1.5
