### ISSUE TITLE
Extension Error: Protocol error (Debugger.enable): Script execution is pro...

### ISSUE THREAD

**Issue by gitty8** [GoogleChrome/lighthouse#1530] opened 2017-01-25 10:22 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: https://www.otto.de/p/miele-waschmaschine-wdb030wcs-d-lw-eco-aplusplusplus-7-kg-1400-u-min-571296502/

**Comment by brendankenny** [comment] 2017-01-25 23:12
duplicate of #1465. Looks like you've disabled JS execution; see discussion in that issue.

**Closed by brendankenny** 2017-01-25 23:12 UTC
