### ISSUE TITLE
'Unable to retrieve manifest' when manifest file is available but invalid

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2348] opened 2017-05-24 01:08 UTC
The manifest for my site was actually invalid, but the Lighthouse report looks as if the manifest file couldn't be retrieved:

![image](https://cloud.githubusercontent.com/assets/205226/26382613/4367964a-3fe2-11e7-85f2-ceb58deef6b1.png)

**Comment by brendankenny** [comment] 2017-05-24 01:13
do you have a test url/can you leave it invalid so we can debug it? :)

Lighthouse uses the debugger protocol to retrieve the manifest and it's possible it's dropping an error message being passed over.

**Comment by samdutton** [comment] 2017-05-24 01:29
Sure :). 

I just broke it again for you: 

https://apprtc-pwa.appspot.com

**Comment by paulirish** [comment] 2017-05-24 01:33
I added this:
![image](https://cloud.githubusercontent.com/assets/39191/26383135/087cd65e-3fe6-11e7-97cb-64bd4da98139.png)

and got this:
![image](https://cloud.githubusercontent.com/assets/39191/26383139/0f8584e6-3fe6-11e7-89fb-ddc672bc2c5f.png)

**Comment by paulirish** [comment] 2017-05-24 01:43
@samdutton would this work for you?

![image](https://cloud.githubusercontent.com/assets/39191/26383472/c11a3bb0-3fe7-11e7-83c9-416fea59862f.png)

**Comment by paulirish** [comment] 2017-05-24 01:53
PR up at #2349

**Comment by samdutton** [comment] 2017-05-24 04:55
That was quick :). Perfect — thanks.

**Comment by paulirish** [comment] 2019-04-25 22:00
We never surface `response.errors`. We should.

https://github.com/GoogleChrome/lighthouse/blob/d9e1a325e4f0b118d5ea586152abbefd2d3e2acb/lighthouse-core/gather/driver.js#L552-L554

These errors may be included in https://github.com/GoogleChrome/lighthouse/issues/8223 .. Not 100% sure.

**Comment by wardpeet** [comment] 2019-09-03 20:38
I'm closing this one as a duplicate of https://github.com/GoogleChrome/lighthouse/issues/1666.

**Closed by wardpeet** 2019-09-03 20:38 UTC
Labels: P2, pwa
