### ISSUE TITLE
Performance not getting evaluated due to speed index (NAN)

### ISSUE THREAD

**Issue by anandgupta193** [GoogleChrome/lighthouse#11173] opened 2020-07-28 18:23 UTC
Run LH on https://reactenterprisestarterkit.netlify.app/

Current Behaviour: 
<img width="259" alt="Screenshot 2020-07-28 at 11 36 56 PM" src="https://user-images.githubusercontent.com/24511864/88704254-72520c00-d12b-11ea-84f3-534d693fb659.png">

Performance getting evaluated successfully in below-mentioned links:

> https://developers.google.com/speed/pagespeed/insights/
> https://web.dev/measure/

Expected to calculate performance results in chrome dev-tools lighthouse tab.

#### Environment Information
* Affected Channels: Webapp
* Chrome version: Version 84.0.4147.89 (Official Build) (64-bit)
* Node.js version: v12.16.1
* Operating System: macos Catalina 10.15.6

**Comment by patrickhulce** [comment] 2020-07-28 18:33
Thanks for filing @anandgupta193! Duplicate of #11154

**Closed by patrickhulce** 2020-07-28 18:33 UTC
Labels: needs-priority
