### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by epcars** [GoogleChrome/lighthouse#3905] opened 2017-11-24 14:03 UTC
**Initial URL**: https://www.agerpres.ro/
**Chrome Version**: 62.0.3202.94
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:797:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3335:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3355:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3353:49)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:2201:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:2199:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3347:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:800:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:635:8)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-11-27 04:01
thanks for filing @epcars! this looks like a dupe of #3306, so we'll close this but feel free to add more info there if you have more to share!

**Closed by patrickhulce** 2017-11-27 04:01 UTC
