### ISSUE TITLE
lighthouse on display less systems

### ISSUE THREAD

**Issue by pulkitnandan** [GoogleChrome/lighthouse#1970] opened 2017-04-06 14:01 UTC
Hi,

I'm trying to benchmark few famous pwa frameworks and I like this task to be automated on cloud.
I have choosen amazon ec2 instance.
The issue I'm facing is 
`[20610:20610:0406/140026.530032:ERROR:browser_main_loop.cc(279)] Gtk: cannot open display:`

Is chrome's gui really needed for lighthouse to work, or am I missing something?

**Comment by pedro93** [comment] 2017-04-06 14:31
To run lighthouse you need chrome which as of right now has a few unsolved bugs with running in a headless mode so you need an interface or atleast xvfb. 

As an alternitive you may want to try running lighthouse in a container if its possible from an amazon ec2 instance, see this issue for some useful links to dockerfiles which enable that. https://github.com/GoogleChrome/lighthouse/issues/1932

**Comment by ebidel** [comment] 2017-04-07 16:11
What @pedro93 said :) 

Last time I checked, Chrome headless has bugs that causes LH audits to unexpected fail. Performance numbers also tend to be way off.

That said, if you modify this script:
https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md#running-headless-chrome-for-lighthouse

to use headless:

```
chromium-browser --headless --disable-gpu --user-data-dir=$TMP_PROFILE_DIR --remote-debugging-port=9222 'about:blank'
```

You might be able to get things cooking. 

Note: LH also uses a [bunch of other flags](https://github.com/GoogleChrome/lighthouse/blob/fbd88ad8b2531c252723f86f0c71d5d422d0a40f/lighthouse-cli/chrome-launcher.ts#L63) to launch Chrome.

**Comment by ebidel** [comment] 2017-06-21 23:51
Marking as a dupe of https://github.com/GoogleChrome/lighthouse/issues/2008

**Closed by ebidel** 2017-06-21 23:51 UTC
Labels: ci
