### ISSUE TITLE
Should detect manifests that have start_url parameters that are not on the same origin

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#4896] opened 2018-03-30 16:45 UTC
Essentially add the check described in https://github.com/mounirlamouri/manifest-validator/issues/43 by @adewale.

**Comment by brendankenny** [comment] 2018-03-30 16:53
In theory we added that check after we forked from manifest-validator: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/manifest-parser.js#L127

Are there cases where it's buggy?

**Comment by tomayac** [comment] 2018-03-30 18:19
The code suggests the check is there indeed, the results ([sample for Google Keep](https://builder-dot-lighthouse-ci.appspot.com/report.1522433832808.html)) don’t seem to communicate what the issue was.

**Comment by tomayac** [comment] 2018-03-30 18:27
The spec [says](https://www.w3.org/TR/appmanifest/#dfn-processing-the-start_url-member):

If start URL is not same origin as document URL:
- Issue a developer warning that the start_url needs to be same-origin as Document of the top-level browsing context.
- Return document URL.

Lighthouse could warn the user clearly about the issue.

**Comment by brendankenny** [comment] 2018-03-30 18:32
If there's not a bug, Lighthouse should be warning in this case. That sample report looks like it's testing the google log in page, not Keep.

Unfortunately our story for testing a site behind authentication is a bit of work (has to be done locally): https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#testing-on-a-site-with-authentication

(it'll be a little easier from DevTools at least when we implement the "don't clear cookies" option: https://github.com/GoogleChrome/lighthouse/issues/4419)

**Comment by brendankenny** [comment] 2018-03-30 18:43
actually, strike that, should be testable from DevTools or the extension :)

**Comment by brendankenny** [comment] 2018-04-11 21:48
Closing this bug for the reasons I noted in https://github.com/mounirlamouri/manifest-validator/issues/43: `start_url` is *parsed* relative to the manifest URL, but only needs to be same origin with the URL of the current document, not the manifest.

For a relative `start_url` that's the same as requiring it to be same origin as the manifest, but if the `start_url` is an absolute URL then the manifest can be on a different origin in this scenario.

The confusing parts of our warning and the `start_url` failure on Keep are indeed issues, though, and are tracked in #4898

**Closed by brendankenny** 2018-04-11 21:48 UTC
Labels: needs-priority
