### ISSUE TITLE
Service worker does not successfully serve the manifest's start_url.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#4541] opened 2018-02-14 22:30 UTC
This error is actually pretty hard to fix if you think you are.

At the moment I'm caching the index.html page and I've set the start_url to index.html and I still get this error. 

I can even go from `DevTools > Application > Manifest > start_url` link to the page, switch to offline in network panel and reload the page and get the full page from the service worker.

Any ideas how to debug this?

**Comment by patrickhulce** [comment] 2018-02-14 22:42
Potentially a case of #2688?

**Comment by gauntface** [comment] 2018-02-14 23:17
The project is the `wsk-next` branch of web-starter-kit https://github.com/google/web-starter-kit/tree/wsk-next 

in the directory run:

1. npm install
1. gulp prod

**Comment by icyJoseph** [comment] 2018-02-19 11:30
Hi,

I have encountered the same issue, when using create-react-app, out of the box because the service worker fails to serve the start_url, as you can see in this image:

![start_url fail](https://user-images.githubusercontent.com/21013447/36374854-23f3987a-156d-11e8-807f-28db787f9a60.PNG)

In order to fix this, I've fetched a service worker script from: http://www.manifoldjs.com/ using the Service Worker for offline pages.

``` javascript
self.addEventListener("fetch", function(event) {
  event.respondWith(
    fetch(event.request).catch(function(error) {
      console.log(
        "[Service Worker] Network request Failed. Serving content from cache: " +
          error
      );
      //Check to see if you have it in the cache
      //Return response
      //If not in the cache, then return error page
      return caches
        .open(
          "sw-precache-v3-sw-precache-webpack-plugin-https://silent-things.surge.sh"
        )
        .then(function(cache) {
          return cache.match(event.request).then(function(matching) {
            var report =
              !matching || matching.status == 404
                ? Promise.reject("no-match")
                : matching;
            return report;
          });
        });
    })
  );
});
```
Then I use [cra-append-sw](https://github.com/bbhlondon/cra-append-sw) to append this code to the Create-React-App default Service Worker. Set start_url in manifest to "./index.html" and it passes the audit. Note that the index.html is server anyway, so this might just be a Lighthouse bug.

Hope this hopes with the investigation. I have made a repo with the code that should work here: https://github.com/icyJoseph/test-worker/blob/master/src/service-worker.js

**Comment by JustFly1984** [comment] 2018-02-19 15:59
I'm not using CRA, but I've copied whole code concerning SW to my project based on `react-static`

Can you please explain the meaning of `"sw-precache-v3-sw-precache-webpack-plugin-https://silent-things.surge.sh"` string?

Can I copy this code to my register service worker file safely?

**Comment by JustFly1984** [comment] 2018-02-19 16:01
I've navigated to https://silent-things.surge.sh/, used Audit, and get the same `Service worker does not successfully serve the manifest's start_url.` error

**Comment by icyJoseph** [comment] 2018-02-19 16:02
Hej,

That's the name of the cache, aka cacheName, replace it with yours, that string i the url of project I used to test CRA.  

And yes, silent-things is not using this code yet, I'll deploy when I get home :)

**Comment by JustFly1984** [comment] 2018-02-20 14:28
Ok, so as I understand, this peace of code has no real value, except making lighthouse to stop false negative warning?

**Comment by icyJoseph** [comment] 2018-02-20 15:05
I could of course be wrong, but yes. There seems to be a false negative. Please refer to:

- https://developers.google.com/web/tools/lighthouse/audits/cache-contains-start_url
- https://github.com/GoogleChrome/lighthouse/issues/4312
- https://stackoverflow.com/questions/45330087/manifest-start-url-is-not-cached-by-a-service-worker

The blame seems to come from: 
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/webapp-install-banner.js

In line 78, 

``` javascript
static assessOfflineStartUrl(artifacts, result) {
    const hasOfflineStartUrl = artifacts.StartUrl.statusCode === 200;

    if (!hasOfflineStartUrl) {
      result.failures.push('Service worker does not successfully serve the manifest\'s start_url');
      if (artifacts.StartUrl.debugString) result.failures.push(artifacts.StartUrl.debugString);
    }

    if (artifacts.StartUrl.debugString) {
      result.warnings.push(artifacts.StartUrl.debugString);
    }
  }
```

Hopefully this gives you more insight on to how to fix your problem. For me this is as far as I go to jump over a false negative.

**Comment by mclamanna** [comment] 2018-03-19 16:03
Yeah I've pretty much given up on fixing this error:
Service worker does not successfully serve the manifest's start_url.

When you view my site [www.mlamannadev.com](url) from an android device a banner does pop up so iI don't know why I'm still getting this error in lighthouse.

**Comment by nunoperalta** [comment] 2018-04-08 18:16
The same happening to me. Initially, I thought this would be because of "manifest.json" not being cached, but even after caching, I get the same error.

Seems that issue #2576 was closed without being fixed..

**Comment by JosefJezek** [comment] 2018-04-09 11:16
I have the same problem. :-( I am using polymer cli and sw-precache.

**Comment by Stefany93** [comment] 2018-04-14 20:05
Same here. The banner does pop up on android device but the stupid error makes my Lighthouse has 82 points.

**Comment by stefanklokgieters** [comment] 2018-04-20 10:02
@Stefany93 same thing here... I assume that Google Lighthouse is not their top priority looking at the speed of development and improvement :shipit:

**Comment by corysimmons** [comment] 2018-04-22 07:40
@icyJoseph seems to have pinpointed the piece of code responsible for this pretty serious bug https://github.com/GoogleChrome/lighthouse/issues/4541#issuecomment-367006053

@patrickhulce @wardpeet @paulirish @karolklp Could one of you review and confirm if he's correct (that it's a false positive)?

It's causing fresh create-react-app projects to fail—as well as fresh Google projects.

**Comment by patrickhulce** [comment] 2018-04-23 16:09
The piece of code that @icyJoseph pinpointed is where the display string is being added to the set of errors but not the cause of the bug. 

@brendankenny didn't you recently discover something w.r.t manifest parsing that might help here?

**Comment by corysimmons** [comment] 2018-04-23 16:11
Thanks for the info @patrickhulce and helping move this along.

**Comment by wardpeet** [comment] 2018-04-23 17:17
The service worker issue got resolved here #4070

it more or less comes to this bug #4898 i'll try to figure something out somewhere this week.

**Comment by wardpeet** [comment] 2018-04-29 21:16
does this work for you guys? #5067 
Honestly it just gives a better error message. If not could you give me a good test url that's still broken with the #5067 patch.

**Comment by corysimmons** [comment] 2018-04-30 09:43
The user _is_ prompted to install the PWA though.

The problem, for me anyway, is I ran Lighthouse with a fresh CRA app, and this error made me think it wouldn't install a PWA. When I opened the url on Android, it _did_ prompt to install...

**Comment by wardpeet** [comment] 2018-04-30 09:44
going to try a fresh CRA, thanks for the feedback

**Comment by wardpeet** [comment] 2018-05-16 19:55
I tested this one and seems to be good.
wdyt @patrickhulce @patrickhulce  @gauntface ?

yarn start (dev mode) - no Service Worker
![image](https://user-images.githubusercontent.com/1120926/40140591-a38a9776-5953-11e8-8c78-99f6e26f4e6b.png)

yarn build (prod mode) - with Service Worker
![image](https://user-images.githubusercontent.com/1120926/40140681-cf40cc78-5953-11e8-9169-c400c633e33f.png)

**Comment by patrickhulce** [comment] 2018-05-16 19:58
@wardpeet out of curiosity wanna test real quick with/without https://github.com/GoogleChrome/lighthouse/commit/30eb6cee6790877c2d3e6991e9ef911e9a298e00? I'm wondering if that fixed things by chance

**Comment by wardpeet** [comment] 2018-05-16 20:32
@patrickhulce it's the same result with just fetch. The fix was actually the one #5067 as the messages were just messed up as the service worker is not registered on `yarn start`

you can test it here https://build-zzbfraodkg.now.sh/

**Comment by patrickhulce** [comment] 2018-05-16 20:43
Oooooooh, gotcha so it was always working with CRA then?

**Comment by wardpeet** [comment] 2018-05-16 20:47
Not entirely 😛 

the bug was fixed when #4710 landed as there was a race condition when the manifest wasn't cached on time. After that one it was just a wording error in the audit.

**Comment by patrickhulce** [comment] 2018-05-18 16:39
@frlinw on latest LH I don't see any of those issues on your site 👍 

![image](https://user-images.githubusercontent.com/2301202/40246909-5f604924-5a7f-11e8-8679-32c09d849e08.png)

**Comment by frlinw** [comment] 2018-05-18 17:04
@patrickhulce thanks ! I ran the audit on canary (v68) because I tought it was the latest lighthouse version but with the chrome extension it's all good.

**Comment by patrickhulce** [comment] 2018-05-18 17:05
we're rolling the latest lighthouse to canary as we speak, look out for it next week :)

**Comment by mrtnmgs** [comment] 2018-06-12 00:08
I'm still having this issue in Chrome 67.0.3396.79. (it seems to be the same issue, as my app passes the Lighthouse audit in Chrome Canary 69.0.3455.0). Is there any workaround?

**Comment by wdiechmann** [comment] 2018-06-12 17:04
hmmm - I get the `Service worker does not successfully serve...` when auditing, but from the Application tab, with Manifest selected, I am able to `Add to Homescreen` then select Service Workers and go Offline, then select Manifest and click the start_url and see the browser window flicker just noticeable (which I guess will equal a '200') 

This happens in Chrome (Version 66.0.3359.181 (Officiel version) (64-bit)) and Chrome Canary (Version 69.0.3455.0 (Officiel version) canary (64-bit)) on macOS

**Comment by fry2k** [comment] 2018-06-13 07:33
It depends on the Lighthouse version and not at the Chrome version. Just a short overview from myself with my website:
* Integrated Lighthouse 2.9.1 from Chrome 67.0.3396.79 (Windows) shows the error
* Lighthouse extension 3.0.0-beta.0 which could be installed at Chrome 67.0.3396.79 fixes the error
* Integrated Lighthouse 3.0.0-beta.0 from Chrome Canary 69.0.3457.0 (Windows) fixes the error

An interessting point is that the Lighthouse extension is tagged as version 2.10.1.3000 and the Lighthouse itself shows version 3.0.0-beta.0.

@wdiechmann
which Lighthouse version do you have at your mac Chrome Canary? I'm on windows here at work and can't check the mac version.
Your PDF report was build with version 2.9.4. You may could try to install the extension?

**Comment by Drag13** [comment] 2018-06-19 09:18
Chrome: Version 67.0.3396.87 (Official Build) (64-bit)
Create-react-app: Version 1.5.2
Integrated Lighthouse: Version 2.9.1

Manifest is present but I got the same error:

![image](https://user-images.githubusercontent.com/8222114/41588235-e228b2da-73b9-11e8-89a7-cb0013ca7ce7.png)

**Comment by patrickhulce** [comment] 2018-06-19 16:44
@Drag13 does using latest LH (3.0.0-beta.0) fix your issue?

**Comment by Drag13** [comment] 2018-06-19 17:31
@patrickhulce  I am sorry, but could you point me where I can get beta-version. On the market, I see only  2.10.1.3000

**Comment by patrickhulce** [comment] 2018-06-19 20:41
@Drag13 that you should be using 3.0.0-beta under the hood :)

**Comment by wardpeet** [comment] 2018-06-19 20:55
@Drag13 @wdiechmann @mrtnmgs 
Chrome 67 (current stable) does not have the latest lighthouse which not holds the fix for this audit.
Chrome 69 (current canary) does has the fix and latest lighthouse. Could you try that one.

You could also try the chrome extension from the chrome store.

it's actually just a @fry2k said :)

**Comment by Drag13** [comment] 2018-06-20 12:10
Chrome: Version 69.0.3466.0 (Official Build) canary (64-bit)
Failures: No manifest was fetched.

![image](https://user-images.githubusercontent.com/8222114/41657399-f5dfdc26-749b-11e8-8399-7e996b859193.png)

Same for the latest official Chrome and LH latest extension. 
Do you need a link to the app?

**Comment by fry2k** [comment] 2018-06-21 09:48
@Drag13 
Yes a link to your app would help me.
In my opinion it seems to be really a problem with fetching the manifest because the brand color is also missing. Or didn't you define the brand color at your manifest?

**Comment by wdiechmann** [comment] 2018-06-21 10:05
would a somewhat clearer error-message aid all of us "earthlings" to squelching your 'in-tray' ?

like:

`parsing manifest.json failed: brand color missing`

Another thing:
When I see a 404 and Lighthouse tells me that a manifest was not fetched, and a manifest.json is in fact present at the correct place - where would I start looking?

Reflexion:
The entire PWA _thing_ seems (to me) to collide with other client strategies, like caching for one. While developing it would be very welcomed to somehow flip-a-switch and suddenly Chrome would load fresh copies of all assets on every reload. No emptying of caches, deleting content, and what-not - just my 2cent

**Comment by Drag13** [comment] 2018-06-21 10:57
App is [here](https://makephoto.azurewebsites.net/)
Manifest is here
```json
{
  "short_name": "Upload",
  "name": "UploadPage",
  "icons": [
    {
      "src": "favicon.ico",
      "sizes": "64x64 32x32 24x24 16x16",
      "type": "image/x-icon"
    }
  ],
  "start_url": "./index.html",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff"
}
```
Could this be connected with no force redirect from http to https?

**Comment by wardpeet** [comment] 2018-06-21 11:05
@wdiechmann
there is such an option in devtools -> application tab. This option is handy while developing and ignoring the Service Worker but it has nothing to do with Lighthouse itself.
![image](https://user-images.githubusercontent.com/1120926/41715272-3375eb72-7553-11e8-9ff9-ee17f3ead271.png)

@Drag13
I get a 404 on http://makephoto.azurewebsites.net/manifest.json or https://makephoto.azurewebsites.net/manifest.json

**Comment by Drag13** [comment] 2018-06-21 11:36
Manifest is definitely there 

![image](https://user-images.githubusercontent.com/8222114/41716875-8718a4d8-7560-11e8-9f06-7e065c7511e5.png)

Seems problem is in hosting permission. I will check later and return. Thanks for the help!

**Comment by wdiechmann** [comment] 2018-06-21 12:49
@wardpeet great! I was of the impression that checkbox would only reload the serviceworker

**Comment by Drag13** [comment] 2018-06-21 12:57
Problem was on the my side. 
Azure doesn't serve static json files without proper web.config.

Chrome 67.0.3396.87 - All works **fine**
Chrome 69.0.3466.0 - All works **fine**

@wardpeet Thanks a lot for the help!

**Comment by wardpeet** [comment] 2018-06-21 16:43
@patrickhulce yeah correct sorry! :)

**Comment by wdiechmann** [comment] 2018-06-22 07:12
@patrickhulce @wardpeet affirmative :)

thx!

**Comment by btaro001234567** [comment] 2018-07-05 02:30
😁😁😁

**Comment by jagaspehar** [comment] 2018-07-05 19:53
FUCK OFF YOU TERRORIST CUNT.

**Comment by wardpeet** [comment] 2018-07-28 11:18
I'm closing this issue, I'm pretty sure this one got fixed.

**Closed by wardpeet** 2018-07-28 11:18 UTC
Labels: needs-investigation, needs-priority

**Comment by AppXprt** [comment] 2019-07-04 11:33
This is back... Light house is broken to hell...

**Comment by AppXprt** [comment] 2019-07-04 12:01
THIS IS BACK AGAIN!!!!!!!!!!!!!!!!

**Comment by AppXprt** [comment] 2019-07-04 12:02
WHAT IN THE HELL ARE YOU ALL DOING THAT KEEPS BREAKING CHROME AND LIGHTHOUSE!!!!!!!!!!!!!!!

**Comment by AppXprt** [comment] 2019-07-04 12:09
Public Service Announcement! If you end up breaking EVERYONE's service workers..

It's not a feature it's a bug!

**Comment by AppXprt** [comment] 2019-07-04 12:25
I have a question... If you know there is a service worker being used, why recommend one??????????
Unable to fetch start URL via service worker.
A service worker enables your web app to be reliable in unpredictable network conditions. Learn more.

Who programmed this crap?
