### ISSUE TITLE
Testing on a mobile device does not work

### ISSUE THREAD

**Issue by matthew-rister** [GoogleChrome/lighthouse#14933] opened 2023-03-28 00:00 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://example.com/

### What happened?

The instructions for [Testing on a mobile device ](https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#testing-on-a-mobile-device) are both outdated and do not work. 

First, the link to **Remote Debugging on Android (Legacy Workflow)** is broken and now directs to the Chrome DevTools homepage. Second, following the instructions _as is_ either throws an exception (see relevant log output) or causes the page to hang.

For what it's worth, I'm specifically trying to test the performance of a locally hosted website on a physical mobile device using port forwarding. Ideally, I'd like to use Lighthouse because it's cross platform and has CI integration but this would be a blocker for adoption.

### What did you expect?

Lighthouse successfully runs on a mobile device as described by the Github README

### What have you tried?

adb kill-server
adb devices -l
adb forward tcp:9222 localabstract:chrome_devtools_remote
lighthouse --port=9222 --screenEmulation.disabled --throttling.cpuSlowdownMultiplier=1 https://example.com

(I have also tried running lighthouse from Chrome DevTools with port forwarding enabled for port 9222)

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

10.1.0

### Chrome Version

111.0.5563.111

### Node Version

18.15.0

### OS

Windows 11 (OS Build 22621.14131)

### Relevant log output

```shell
PS C:\Users\username> lighthouse --port=9222 --screenEmulation.disabled --throttling.cpuSlowdownMultiplier=1 https://example.com
Runtime error encountered: Missing target for page (id = 2680)
Error: Missing target for page (id = 2680)
    at CDPBrowser._createPageInContext (file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Browser.js:275:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/core/gather/navigation-runner.js:357:18
    at async Runner.gather (file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/core/runner.js:212:21)
    at async navigationGather (file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/core/gather/navigation-runner.js:343:21)
    at async navigation (file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/core/index.js:95:24)
    at async runLighthouse (file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/cli/run.js:250:8)
    at async file:///C:/Users/username/AppData/Roaming/npm/node_modules/lighthouse/cli/index.js:10:1
```

**Comment by adamraine** [comment] 2023-03-28 01:15
This looks like a duplicate of https://github.com/GoogleChrome/lighthouse/issues/14746

The workaround is to use the `--legacy-navigation` flag, we can reopen if that doesn't work for you.

**Closed by adamraine** 2023-03-28 01:15 UTC
Labels: bug, needs-priority

**Comment by matthew-rister** [comment] 2023-03-28 17:13
Hi Adam, thank you for the quick response. I can confirm that `--legacy-navigation` does fix the issue. Would it be possible to reopen this as a doc bug? I spent several hours yesterday trying to get this working and this work around is essentially undocumented. Let me know if you would instead like for me to open PR to add a quick blurb about this in the README.

**Comment by adamraine** [comment] 2023-03-28 17:44
https://github.com/GoogleChrome/lighthouse/issues/14746 is marked as a docs issue, you are right that this should be documented.
