### ISSUE TITLE
Changing to HTTP/2 slows site

### ISSUE THREAD

**Issue by Paul-jw** [GoogleChrome/lighthouse#11521] opened 2020-10-06 07:04 UTC
**Summary**

I upgraded to HTTP/2. 
With no changes, this appears to have slowed the site considerably.

Is this possible, or do you think the upgrade was not done correctly?

**Comment by patrickhulce** [comment] 2020-10-06 14:17
Could you be a little more specific? What do you mean by "appears to have slowed"? Are there specific metrics that regressed in Lighthouse? Where are you getting this measurements from?

tl;dr it's [certainly](https://www.webpagetest.org/forums/showthread.php?tid=15679&pid=31537) [possible](https://stackoverflow.com/questions/33658302/why-http-2-is-slower-than-plain-https) that H2 regresses performance for certain resources or the page overall depending on your baseline

**Comment by Paul-jw** [comment] 2020-10-07 07:09
Good morning Patric,

Thank you for your reply.

I should tell you that I am not in any way an expert with this sort of
thing. I made my simple web site with wordpress for my business. I have
learnt a lot over the last seven years but it's only simple things.

Yes, I do have metrics, in the way of screen shots from the
lighthouse tests. One from a couple of days before the HTTP/2 migration and
one from today. No changes were made to the site around the time of the
migration. Even since then, it has been just a few hundred words on the
home page.

  (Please find attached)

I try to keep up with the google requirements. I know there are new things
happening in the new year, especially with regard to site speed. This was
the main reason for moving to HTTP/2.

The server people that did the work get the lightouse score I have
attached. They have told me to see about contacting google to get my ip
changed. This is what they wrote:

* I would suggest contacting Google if you have an account with them and
asking if your Google Lighthouse Audit is tied to a specific IP, reason why
you're seeing a lower score, and if so, if they can allocated a new server
for testing in your case.*

It just does not strike me as logical though. I know there are slight
variations each time a test is run, and  would expect that. However, the
speed, according to the tests now are well in the red. If google's idea is
to get people to speed up site loading time, shouldn't they be seeing the
similar results from whatever ip or location it's coming from?

In any event, I'm not looking for any fuss, I just want to get my site to
load faster. I was just wondering if it was possible that if something went
wrong during the upgrade, that I could find it and put it right.

Thank you for reading this, I'm sure you get hundreds of emails every day.

Best regards,
Paul.






Facebook: https://www.facebook.com/doncastercarpetcleaners

High quality carpet and upholstery cleaners.

01302 874613
075 4488 0558

https://www.doncastercarpetcleaners.co.uk

**Comment by patrickhulce** [comment] 2020-10-07 16:01
FYI @Paul-jw replies to these GitHub notifications become public comments on the GitHub web interface, and not regular emails, so the attachments did not come through.

If you're measuring only using Page Speed Insights score, then https://github.com/GoogleChrome/lighthouse/issues/7326 *might* be the problem here (performance boosts associated with HTTP/2 don't yet show up in PSI, locally your site scores much better for me).

> I would suggest contacting Google if you have an account with them and
asking if your Google Lighthouse Audit is tied to a specific IP, reason why
you're seeing a lower score, and if so, if they can allocated a new server
for testing in your case.

I don't really understand their suggestion either. They might be talking about where the test is being run? In which case, PSI  test location depends on the IP of the person asking for the test. You can read more about how that works in [this great blog post](https://www.debugbear.com/blog/why-is-my-lighthouse-score-different-from-pagespeed-insights).

>  I was just wondering if it was possible that if something went
wrong during the upgrade, that I could find it and put it right.

I can't see what it looked like before, but I think it's unlikely this particular HTTP/2 upgrade was not performed correctly. The biggest performance issues on this page in PSI today all come from YouTube which wouldn't have been affected by the improvements to your site. (Side note, we're building more advice in this sort of case in the future #11290)

**Comment by Paul-jw** [comment] 2020-10-08 06:50
Thanks again for replying.

I would be interested to see the results you are seeing.

These are the screen shots from before and after the HTTP/2 migration, and the screen shot from the hosting people.

Thank you.

![lighthouse 7th August before moving to http 2](https://user-images.githubusercontent.com/72434147/95424696-f0f0d400-093a-11eb-8a50-47c18fb238df.png)
![Lighthouse 7th October 2020](https://user-images.githubusercontent.com/72434147/95424700-f1896a80-093a-11eb-9c8a-c51e9c4208ef.png)
![Lighthouse test by server people](https://user-images.githubusercontent.com/72434147/95424702-f1896a80-093a-11eb-8ebc-95175695e37e.png)

**Comment by patrickhulce** [comment] 2020-10-08 21:44
I think part of this might be the fact that `web.dev` always tests from the United States (PageSpeed Insights should test from something closer to you). This is what I see from the US which is significantly worse than what you're seeing. If your hosting is in the UK that might explain the discrepancies you're seeing. [Variance](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) is a much broader topic though. I wouldn't be concerned about your HTTP/2 integration if your users are in the UK and seeing similar numbers to yours.

![image](https://user-images.githubusercontent.com/2301202/95516711-494cc380-0985-11eb-9c26-7909d3b872e8.png)

**Comment by Paul-jw** [comment] 2020-10-09 06:28
That makes sense, thank you.

My hosting is in the UK. Is there a way that I can get lighthouse to test locally?

Thanks you.

**Comment by patrickhulce** [comment] 2020-10-09 14:51
The other two screenshots you shared are already testing locally using Chrome DevTools or the CLI. You cannot change where web.dev runs your test.

**Comment by patrickhulce** [comment] 2020-10-27 21:36
We're closing this since there isn't a reproducible issue we can see that differs in root cause from the previously linked issues. Best of luck with your site!

**Closed by patrickhulce** 2020-10-27 21:36 UTC
Labels: needs-priority, pending-close, question

**Comment by Paul-jw** [comment] 2020-10-28 08:19
Thank you for your help,
Paul.


Facebook: https://www.facebook.com/doncastercarpetcleaners

High quality carpet and upholstery cleaners.

01302 874613
075 4488 0558

https://www.doncastercarpetcleaners.co.uk
