### ISSUE TITLE
Plots: memory issue after doing many runs

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#1996] opened 2017-04-11 21:02 UTC
I've come across two types of issues in doing a large run with plots (e.g. 70 sites * 20 runs) and haven't actually been able to do all of the runs successfully yet on the entire site set:

1) Out of memory error
2) Segfault

Example of OOM:

```
TODO
```

Example of Segfault (note: I'm logging `process.memoryUsage()`):

```
Measuring site: https://yandex.ru run: 1
Memory usage (in bytes): { rss: 703762432,
  heapTotal: 166494208,
  heapUsed: 22821352,
  external: 72530046 }
Measuring site: https://reddit.com run: 1
[1]    56828 segmentation fault (core dumped)  node --inspect --expose-gc measure.js
```

Possible candidates for memory leak:
* Plots node.js script (https://github.com/GoogleChrome/lighthouse/blob/master/plots/measure.js)
* Lighthouse
* Chrome

Worked with Paul to look at heap snapshots but didn't see a steady increase in heap usage between runs.

**Comment by paulirish** [comment] 2017-09-26 21:33
maybe dupe of #2424

**Closed** 2017-09-26 22:40 UTC
Labels: pending-close
