### ISSUE TITLE
Extension Error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by DanGthatRokGallery** [GoogleChrome/lighthouse#1085] opened 2016-11-30 18:55 UTC
**Lighthouse Version**: 1.2.2
**Chrome Version**: 54.0.2840.99
**Error Message**: Cannot read property 'message' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'message' of undefined
    at collectUsage.then.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:4444:23)```

**Comment by ebidel** [comment] 2016-11-30 18:58
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1082

**Closed by ebidel** 2016-11-30 18:58 UTC
Labels: duplicate
