### ISSUE TITLE
Increased time spent on "Commit" rendering phase in Headless/PSI

### ISSUE THREAD

**Issue by tomasts248** [GoogleChrome/lighthouse#15180] opened 2023-06-16 02:41 UTC
Hello, so basically the website is slow and the indicators associated with PS & Lighthouse are very weird and make it hard to debug and fix it, but maybe it can be an opportunity to further improve PageSpeed and LH since it may happens to other websites. Disclaimer I'm the developer of this site with speed issues and I have asked expert dev (way more experienced than me) as well and he concurs these indicators are indeed strange.

So what make this indicators weird then: 
1. Long tasks without other indicator than the same url, discussed here: 
https://github.com/GoogleChrome/lighthouse/issues/15053
Diving in Performance profiling in Chrome I can see long tasks, but they only indicate a "Expensive function call in third party script."
2. Similar to here/this thread, I got a huge time spent on "other"
https://github.com/GoogleChrome/lighthouse/issues/15083
3. There's no real reason that justifies the TBT though it does happen in practice (that is not in doubt).
4. This started happening two days before migrating of web hosting provider, and despite the similarity with other websites I have built, this is the only one with this speed issue.

What can be done:
1. I do have a staging version of the website, which is simplified and still presents the same speed TBT issue.
url of the staging version: https://www.otzerling.com/staging/wordpress/
2. Perhaps further improve PageSpeed & Lighthouse to easier debug this issues.
3. I'm open to ideas.
4. I'm willing to learn more to debug and resolve this in a definitive way.

**Comment by tomasts248** [comment] 2023-06-18 14:34
> This is a limitation of the Lighthouse report and we are actively working on improvements. The issues you linked to already capture to areas of work related to this UX problem.

Great, thanks!

> Old headless is spending a lot more time on the phase of the rendering pipeline for some reason.

Thanks for the insight.

**Comment by tomasts248** [comment] 2023-06-21 21:30
Ok I seem to have found what was triggering the slow load: in particular removing the following CSS rule inside header.php resulted in good PS Scores/ and restored good performance in mobile and desktop.

`text-shadow: 0px 0px 3px white, 0px 0px 8px white, 0 0 20px white, 0 0 30px white, 0 0 40px white, 0 0 60px white, 0 0 80px white, 0 0 80px white, 0 0 90px white, 0 0 100px white,0 0 1em white,0 0 2em white,0 0 3em white,0 0 4em white, 0 0 5em white;`

**Comment by connorjclark** [comment] 2023-06-21 21:47
In PSI, we run Lighthouse on machines without a consumer graphics card (or any graphics card). It seems likely that text shadow uses hardware graphics acceleration (GPU), and if so that would explain potential discrepancies in PSI.

We only noticed large differences on pages with obviously-high GPU utilization (like webgl or canvas stuff), but text shadow is new (to me, at least). Sadly there's nothing to be done at this point and we're unlikely to improve in this area for PSI any time soon.

**Comment by adamraine** [comment] 2023-06-22 21:04
Related https://github.com/GoogleChrome/lighthouse/issues/8557

**Comment by adamraine** [comment] 2023-06-27 19:37
Closing as dupe of https://github.com/GoogleChrome/lighthouse/issues/8557

**Closed by adamraine** 2023-06-27 19:37 UTC
Labels: needs-priority, needs-investigation, needs-discussion, PSI/LR

**Comment by tomasts248** [comment] 2023-06-27 19:56
> We only noticed large differences on pages with obviously-high GPU utilization (like webgl or canvas stuff), but text shadow is new (to me, at least). Sadly there's nothing to be done at this point and we're unlikely to improve in this area for PSI any time soon.

Oh I see, thanks for explaining. Question so it is more competing to how browsers handle it instead of PSI/Lighthouse?

**Comment by tomasts248** [comment] 2023-06-27 22:43
Sure, What I meant is: is this an area of Google Chrome rather than a problem related to PS or LH?

**Comment by connorjclark** [comment] 2023-06-28 00:20
It's a limitation on how we currently run Lighthouse/Chrome internally for PSI.
