### ISSUE TITLE
SEO audit reports invalid canonical link

### ISSUE THREAD

**Issue by lanceon** [GoogleChrome/lighthouse#5514] opened 2018-06-17 11:12 UTC
#### Provide the steps to reproduce
1. Run LH on http://localhost:8100/ 

Generated page contains the following element:
```
<link rel="canonical" href="http://localhost:8100/" data-react-helmet="true">
```

#### What is the current behavior?
SEO report shows one failed audit:
```
document doesn't have a valid rel=canonical
Points to a different domain (http://localhost:8100/)
```
#### What is the expected behavior?
Audit is passed.

#### Environment Information
* Lighthouse version: 2.9.1
* Operating System: Windows 10
* Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by patrickhulce** [comment] 2018-06-18 16:19
I'm not able to reproduce this behavior on a local server with the same port as the rel=canonical link. Are you sure you're accessing the page through the same origin as the href? A screenshot might help.

**Comment by brendankenny** [comment] 2018-08-10 18:35
Without more information, closing for now. If you're still seeing this issue please comment and we can reopen!

**Closed by brendankenny** 2018-08-10 18:35 UTC
Labels: needs-more-info
