### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by danielmurbach** [GoogleChrome/lighthouse#2777] opened 2017-07-28 13:59 UTC
**Initial URL**: https://gdaenet.edunet.sp.gov.br/
**Chrome Version**: 62.0.3168.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@da2455bea333a5a4bfe61ba1fcfe9e325dc368e1/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```

**Comment by wardpeet** [comment] 2017-07-28 15:39
dupe of #2457

Closing

**Closed by wardpeet** 2017-07-28 15:39 UTC
