### ISSUE TITLE
Unable to download report

### ISSUE THREAD

**Issue by prameetmaan** [GoogleChrome/lighthouse#5047] opened 2018-04-26 10:48 UTC
Unable to download the generated audit report.
When I am clicking the download button at upper left corner, nothing is happening.
Please suggest !!

**Comment by midzer** [comment] 2018-04-26 10:54
Cannot reproduce. Saving JSON and HTML file works for me.

What lighthouse version are you using?

**Comment by prameetmaan** [comment] 2018-04-26 11:09
Lighthouse : 2.8.0

**Comment by midzer** [comment] 2018-04-26 11:33
Okay, so you're probably using lighthouse directly in Chromium via Audit tab.
Just tried again with v65 and it works flawlessly as well.

If you're still having issues, try to install lighthouse extension itself and re-try. This way you can choose from several export options.

**Comment by patrickhulce** [comment] 2018-04-30 16:15
@prameetmaan we're also unable to reproduce is there a particular sequence of steps you're taking to run into this? Has it ever worked for you?

**Comment by ddagino** [comment] 2018-05-30 18:46
I'm seeing this. Details:

OS: Mac OSX High Sierra 10.13.4
Browser(s): Chrome Beta 67.0.3396.62, and Chrome Canary 69.0.3445.0

Steps to reproduce:

1. Navigate to a site (tested on [this money.cnn.com article](http://money.cnn.com/2018/05/30/media/president-trump-roseanne-barr-bob-iger).
2. Open Chrome DevTools > Audits.
3. Click 'Run Audits' with default settings.
4. When audit is complete, click Download Report button in top left.
5. Observe DevTools stall then crash (DevTools window/drawer closes but browser window/tab stays open).
6. Observe no report has been downloaded.

**Comment by dotlouis** [comment] 2018-06-06 15:16
Same here, nothing happens when clicking the download button

**Comment by patrickhulce** [comment] 2018-06-06 17:02
A few updates here folks:

FWIW, I think the UX here is very confusing and I've been burned by it several times. The download report button gives you no feedback that it's been downloaded even when it has, so double check the file system where you tried to save it. We'll fix that UI issue.

I was able to repro @ddagino's money.cnn.com article problem once, but it's highly inconsistent and I haven't been able to track down when it occurs. I haven't been able to get it to happen with 3.0 yet in Canary.

**Comment by jammus** [comment] 2018-06-08 16:12
Having the same problem in Chrome Version 67.0.3396.79 (Official Build) (64-bit) on OSX El Capitan 10.11.6 with built-in Lighthouse (2.9.1)

Clicking download button gives no feedback. Mousing over the download button shows a corrupted icon the right of the button (see attached)

![screen shot 2018-06-08 at 17 08 15](https://user-images.githubusercontent.com/381842/41168751-d118b28e-6b3e-11e8-94c3-44ea610f8d0d.png)

**Comment by ddagino** [comment] 2018-06-08 16:33
@patrickhulce What is the default path where the report would be saved? I ran several `find`s but couldn't find anything.

**Comment by patrickhulce** [comment] 2018-06-08 16:47
@ddagino my default location is with the rest of Chrome downloads `~/Downloads` are you unable to download any reports at all or is it just on certain sites?

@jammus very odd, never seen that one. Just on a particular site or all sites?

**Comment by ddagino** [comment] 2018-06-08 17:32
@patrickhulce I just shut everything down, rebooted, fired up Chrome Beta again, this time with 9GB of memory available, and tested again on a relatively lightweight site: [news.ycombinator.com](https://news.ycombinator.com): success — no lock up and report downloaded to ~/Downloads.

I tested again on a heavier site, [this NYTs article](https://www.nytimes.com/2018/06/08/business/media/anthony-bourdain-dead.html) (RIP Anthony Bordain): again success.

It's looking like this is might be an issue of memory...

**Comment by patrickhulce** [comment] 2018-06-08 17:46
Ah that very well could be, thanks for the extra info! We'll try to dig in with this.

**Comment by latifs** [comment] 2018-07-12 18:57
Hi Guys,
Any updates on that?
Still trying to download an audit and even with memory no dice!
Thanks

**Comment by patrickhulce** [comment] 2018-07-12 19:01
@latifs are you using Chrome canary?

**Comment by ddagino** [comment] 2018-07-12 19:06
@latifs @patrickhulce I'm using Chrome Canary and I recently was able to download an audit report on the site I previously was unable to.

**Comment by latifs** [comment] 2018-07-12 19:09
@patrickhulce, Nope but I just tried it with Canary and it works.

**Comment by patrickhulce** [comment] 2018-07-12 19:42
Cool cool, we think we've fixed these issues with 3.0 and some recent Chrome-side changes, so I'll go ahead and close this. Please file something new with a specific URL and device configuration if you're unable to download in Chrome 69.0.3489.0 or later!

**Closed by patrickhulce** 2018-07-12 19:42 UTC
Labels: DevTools, bug, needs-investigation
