### ISSUE TITLE
Extension Error: Invalid string length when generationg report on mcdcc.org page

### ISSUE THREAD

**Issue by ErstwhileWork** [GoogleChrome/lighthouse#2306] opened 2017-05-19 00:09 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 59.0.3071.47
**URL**: http://mcdcc.org/
**Error Message**: Invalid string length
**Stack Trace**:
 ```RangeError: Invalid string length
    at onChunkRead (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10076:17)
    at <anonymous>```

**Comment by patrickhulce** [comment] 2017-05-19 00:15
dupe of #2305

**Closed by patrickhulce** 2017-05-19 00:15 UTC
Labels: duplicate
