### ISSUE TITLE
Perceptual Speed Index gives an error: Audit error: Images have different sizes

### ISSUE THREAD

**Issue by nicholas-george** [GoogleChrome/lighthouse#5003] opened 2018-04-20 14:34 UTC
I am getting this error: Audit error: Images have different sizes.
Is there anything which needs to be checked to fix this.
Unfortunately, the site I am testing is after login & hence not able to share the site.
Am trying to figure out what needs to be done.

**Comment by patrickhulce** [comment] 2018-04-20 15:45
Thanks for filing @nicholas-george! That usually means something has gone wrong with the load and elements weren't painted. Is it reproducible on every run? If so, is there a subset of the page you can isolate and share for us to take a look?

**Comment by nicholas-george** [comment] 2018-04-21 15:00
Yes. It happens every-time.
An additional piece of information is that, this app uses, work-in-progress service workers.

**Comment by xenon20** [comment] 2018-04-23 14:30
Same problem here, not sure if it's something I have to fix on my page: https://www.gutscheinmail.de/

**Comment by xenon20** [comment] 2018-04-23 18:32
Chrome Version 66.0.3359.117 on macOS 10.13.4 and Lighthouse 2.9.3. Just gave it another try:
![bildschirmfoto 2018-04-23 um 20 31 21](https://user-images.githubusercontent.com/1637686/39145864-5bab25ea-4735-11e8-8c37-74616d6c29b4.png)

**Comment by nicholas-george** [comment] 2018-04-24 08:53
ok. I am able to narrow it a bit in my case.
The same site works in one machine and not in the other
both are imacs with chrome66.0.3359.117 on macos 0.13.4 
The only difference is it works on the machine which has 8GB RAM and not on the one which has 4GB ram.. Or is this caused by a chrome plug-in clash?

**Comment by TristanPeers** [comment] 2018-04-26 07:31
Hi - I'm getting the same error `"Audit error: Images have different sizes"`on my site... but only with the chrome plugin. If I use the in-built Chrome lighthouse audit (dev-tools -> audits) there are no errors in this section.

**Comment by mattwojas** [comment] 2018-04-30 15:32
Hello, we are also experiencing this error, "Audit error: Images have different sizes".  In our case it only appears to be happening on windows machines and cannot be replicated on a mac, and only happens from the plugin not the developer tools.

**Comment by patrickhulce** [comment] 2018-04-30 16:45
Thanks for the additional info folks! Seems like this is extension specific. @mattwojas do your windows and mac machines have same amount of RAM?

**Comment by mattwojas** [comment] 2018-04-30 17:53
@patrickhulce No problem.

There are various amounts of RAM - for windows machines producing the error we have tested 2GB, 3GB, and 12GB machines.  The mac, which does not product the error, has 16GB of RAM.

**Comment by pmerwin** [comment] 2018-07-24 17:22
We are seeing this issue too, anything I can provide to help isolate and fix?

**Comment by patrickhulce** [comment] 2018-07-25 01:30
@pmerwin is it also Windows + extension only for you?

**Comment by pmerwin** [comment] 2018-07-25 17:02
I am actually using webdriverio and the "chromedriver directly via CDP" ... that is in quotes because I am using a sauclabs api that I assume is using CDP.

**Comment by wardpeet** [comment] 2018-10-16 22:10
@patrickhulce can we close this as perceptual speed index has been renamed to speed index?

**Comment by patrickhulce** [comment] 2018-10-16 22:49
It's possible this was "fixed" in v3 in the sense that we're not as strict about the images being exact same dimensions, but it's still a little concerning.


I don't have any idea where we'd start to go about fixing it though without a hard repro, so I'm fine to close until it comes up again in v3 :)

**Closed** 2018-10-16 22:49 UTC
Labels: P1.5, bug, extension, needs-investigation, needs-more-info, pending-close
