### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by carlosraul777** [GoogleChrome/lighthouse#3140] opened 2017-08-25 21:26 UTC
**Initial URL**: https://viera.academy/student/dashboard
**Chrome Version**: 60.0.3112.101
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-09-26 22:55
dupe of #2174

**Closed by patrickhulce** 2017-09-26 22:55 UTC
Labels: pending-close
