### ISSUE TITLE
 ☔️ Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by maulanaahmadarif** [GoogleChrome/lighthouse#1091] opened 2016-12-01 04:57 UTC
**NOTICE FOR DUPLICATE BUG FILERS:** The only known fix for this is usually completely restarting the browser, and sometimes with a completely fresh profile.

**Lighthouse Version**: 1.2.2
**Chrome Version**: 57.0.2937.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7377:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7526:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2016-12-01 05:41
Can you post the URL you're trying? Is this 100℅ reproducible in stable
chrome or just canary?

**Comment by maulanaahmadarif** [comment] 2016-12-01 05:59
I'm using canary right now
https://lab.ydigital.asia/precision/

**Comment by paulirish** [comment] 2016-12-02 18:54
This one is hard to solve. It happens on occasion and the best solution is restarting chrome right now.

If this continues we can look into ways of forcing Chrome to stop tracing even after we've disconnected.

**Comment by brendankenny** [comment] 2016-12-02 19:58
for errors that are causing this, we could add an attempt to stop tracing in the [gather-runner cleanup](https://github.com/GoogleChrome/lighthouse/blob/59f9f4808eb84467d861baf10f3463c0f161f33c/lighthouse-core/gather/gather-runner.js#L272-L276). If the error caused us to lose connection to devtools it won't work, but it may help in some cases

**Comment by paulirish** [comment] 2016-12-03 00:02
@caseq tells me that the tracing backend should stop the trace is the protocol client has disconnected.  So everything is lined up to make this work, though there may be a race condition.

I'm having trouble reproducing this bug (though I have hit it before).

If anyone can find a reliable repro for this, please comment with it.

**Comment by gauntface** [comment] 2017-01-05 23:07
I have a reproducible test case. Will try and reduce so you can either use it for debugging OR add it as part of the integration tests.

**Comment by ebidel** [comment] 2017-04-07 16:14
> Yes, I switched tabs originally and came back and it was still running, then it appeared to be running in all of my tabs, then I closed the window and now clicking the extension button gives me the error here.

**Comment by patrickhulce** [comment] 2017-04-07 16:26
crazy idea: we could always try to stop tracing before doing anything and just throw away any exception that results

**Comment by skylerwshaw** [comment] 2017-07-31 14:36
Posting here instead of falling into the dupe graveyard ☝️ 

**Initial URL**: https://my.mimeo.com/Library/Default.aspx
**Chrome Version**: 60.0.3112.78
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-08-11 23:41
Ok, I got this in DevTools and now I can't get out of this state:

<img width="913" alt="screen shot 2017-08-11 at 4 39 09 pm" src="https://user-images.githubusercontent.com/238208/29235434-9ef120fc-7eb3-11e7-9301-6dc77f89d47f.png">

Ironically, it's ended up on about:blank. So I wonder if that's how a lot of https://github.com/GoogleChrome/lighthouse/issues/2362 is/was happening.

**Comment by patrickhulce** [comment] 2017-08-12 05:00
FWIW @ebidel the running theory for ending up on about:blank with "Unable to load the page" is the bug in DevTools for auditing the URL of an iframe instead of the main page.

**Comment by adavis0000** [comment] 2017-09-08 12:47
Not a fix, but to keep you working... I got back on track after quitting and re-launching Chrome. Not any individual tab or even profile (I usually have a few profiles running with many tabs each). But actually restarting Chrome itself. Then I could audit my site again.

**Comment by tobiastornros** [comment] 2017-09-13 10:19
Can confirm @adavis0000 solution. Chrome needs to restart completely, not just close current profile running in chrome.

**Comment by jontejj** [comment] 2017-09-28 19:56
Seems like it fails if I'm starting two different traces at the same time? I did it from two different tabs.

**Comment by Haroenv** [comment] 2017-11-12 22:01
I had the panel open in another tab, didn't run it, then opened the panel in a second tab and it fails

**Comment by jamesshannon** [comment] 2018-07-31 21:12
Seems like this happens frequently enough. Does it make sense to increase the priority and finally fix this?

**Comment by paulirish** [comment] 2018-09-18 23:57
@jamesshannon it does yes. :)

[chromium location](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/tracing_handler.cc?type=cs&q=f:tracing_handler+%22Tracing+is+already+started%22&sq=package:chromium&g=0&l=378)

**Comment by mssodhi** [comment] 2019-01-24 02:46
Here's an attached screen shot from www.yahoo.com site audit. Tested on Version 73.0.3681.0 (Official Build) canary (64-bit). The error message says "Something went wrong with recording the trace over your page load. Please run Lighthouse again.", in case that helps. I've quit/closed the app, and restarted, and it still happens.
<img width="1920" alt="screen shot 2019-01-23 at 4 49 04 pm" src="https://user-images.githubusercontent.com/8364496/51646811-00de3f80-1f2f-11e9-94dc-3380004fb7c5.png">

**Comment by Hoten** [comment] 2019-01-24 22:36
@mssodhi thanks for reporting. I can share that we are aiming to push 4.0.0 to the next Chrome (not yet in Canary), and in doing so I see that this tracing error no longer happens. Could be that next Canary will have this issue resolved.

**Comment by mssodhi** [comment] 2019-01-24 22:52
@Hoten thanks for the update!

**Comment by patrickhulce** [comment] 2020-08-26 14:56
We believe this is primarily due to Chrome tracing in the background and is fixed with chrome-launcher v0.13.3 (https://github.com/GoogleChrome/chrome-launcher/pull/203). 

If you cannot use that version of chrome-launcher just make sure Chrome is started with the following flag `--force-fieldtrials=*BackgroundTracing/default/`.

**Closed by patrickhulce** 2020-08-26 14:56 UTC
Labels: P1.5, bug

**Comment by paulirish** [comment] 2021-01-06 18:57
Moreover, there are some Chrome changes that happened recently that may have resolved this at the Chrome layer. 

* [services/tracing: Make client priority configurable (I6dc3c92a) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/2404936)
* [BackgroundTracing: Switch to Perfetto client API (I9c35e079) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/2404830)
* [services/tracing: Clean up session priority setting (I0f71edcf) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/2414253)

These changes are in Chrome 88+. googlers, see 🔒  crbug.com/1058632 for discussion. 


status: 

- as [patrick mentioned](https://github.com/GoogleChrome/lighthouse/issues/1091#issuecomment-680932666), we already have flipped off BackgroundTracing with chrome flags, so that was already addressed.
- The above changes should make it so that flag isnt necessary anymore and a new tracing session would prempt an existing bg tracing one.
- we suspect a tracing_already_started case comes from an initiated tracing session that wasn't gracefully completed. the above changes _may_ also solve that case.

so in general we should be good (in Chrome 88+) and any more of these errors can raise eyebrows.

**Comment by Daudxu** [comment] 2023-08-17 02:21
Protocol error (Tracing.start): Tracing has already been started (possibly in another tab).
```
Channel: DevTools
Initial URL: http://127.0.0.1:5173/login
Chrome Version: 116.0.0.0
Stack Trace: w: Protocol error (Tracing.start): Tracing has already been started (possibly in another tab).
    at devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:6938
    at new Promise (<anonymous>)
    at j.send (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:6871)
    at ProtocolSession.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:604:258)
    at Trace.startSensitiveInstrumentation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:152:471)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:610:696
    at async collectPhaseArtifacts (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:610:827)
    at async _navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:623:67)
    at async _navigations (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:625:637)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:625:260

**Comment by neha023** [comment] 2023-10-02 07:06
Protocol error (Tracing.start): Tracing has already been started (possibly in another tab).

Protocol error (Tracing.start): Tracing has already been started (possibly in another tab).
```
Channel: DevTools
Initial URL: https://www.*******machinery.com/admin/catalog/product/edit/id/8565/key/441e91a2d205ac73d47cfcab2cf954c142e0a40a7ce450d74b74366b7fe8d23f/
Chrome Version: 116.0.0.0
Stack Trace: w: Protocol error (Tracing.start): Tracing has already been started (possibly in another tab).
    at devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:6938
    at new Promise (<anonymous>)
    at j.send (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:6871)
    at ProtocolSession.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:604:258)
    at Trace.startSensitiveInstrumentation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:152:471)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:610:696
    at async collectPhaseArtifacts (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:610:827)
    at async _navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:623:67)
    at async _navigations (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:625:637)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:625:260

**Comment by shivamconan** [comment] 2024-03-14 11:35
Facing this issue as well while trying to send CDP command via selenium - 

`selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Tracing has already been started (possibly in another tab)."}
`
