### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by sweetnativedreams** [GoogleChrome/lighthouse#4024] opened 2017-12-10 07:31 UTC
**Initial URL**: https://photos.google.com/
**Chrome Version**: 62.0.3202.94
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-12-15 23:26
thanks for filing @sweetnativedreams! we'll go ahead and close this as a dupe of #2448 but feel free to add any additional info you have over there :)

**Closed by patrickhulce** 2017-12-15 23:26 UTC
Labels: duplicate
