### ISSUE TITLE
Lighthouse extension stops working

### ISSUE THREAD

**Issue by Belchona** [GoogleChrome/lighthouse#4708] opened 2018-03-07 11:08 UTC
Help me pls, lighthouse stops working when it is retrieving scripts.
![2018-03-07 14 04 32](https://user-images.githubusercontent.com/37142767/37089214-d96294fe-2210-11e8-94b1-b7ab99607b36.png)
![2018-03-07 14 04 51](https://user-images.githubusercontent.com/37142767/37089215-d9868dbe-2210-11e8-800f-0a6b98813ccd.png)
This stage never ends, I can't get the report(

I used different wi-fi and different sites to analyze.

**Comment by wardpeet** [comment] 2018-03-07 11:13
could you let us know which version of the extension you're running and on which site?

does it work on some sites?

**Comment by Belchona** [comment] 2018-03-07 18:53
![2018-03-07 21 47 58](https://user-images.githubusercontent.com/37142767/37111664-4a4b4d6a-2251-11e8-874a-39b4469c2a30.png)
I try to run it on https://anketa.alfabank.ru/land/pil-refin/

I've tried another URL - lighthouse works on https://optimize.google.com/optimize/home/#/accounts/2674025900/containers/8567011 for example.
But I can't check our landing(

**Comment by paulirish** [comment] 2018-03-09 07:24
thanks for reporting!  dupe of #4258

**Closed by paulirish** 2018-03-09 07:24 UTC
