### ISSUE TITLE
Service worker runs under different user agent than page being tested

### ISSUE THREAD

**Issue by mattwomple** [GoogleChrome/lighthouse#4556] opened 2018-02-15 23:43 UTC
If a service worker is designed to only operate on mobile devices (consider website owners who outsource the mobile development of their site), then either user agent inspection or feature detection is required to limit the worker's scope. This works fine for mobile devices, but does not play well with the lighthouse test in desktop Chrome Dev Tools.

The lighthouse test in Chrome Dev Tools emulates a mobile device for the page being tested, but the service worker is stuck with the desktop user agent. This causes some PWA tests to fail since the service worker is designed to only operate on mobile devices: e.g. _Does not respond with a 200 when offline_ and _Service worker does not successfully serve the manifest's start_url_.

I realize it is possible to 1) run lighthouse directly on a mobile device, and 2) start chrome with a specific user agent via the `--user-agent` flag, but these solutions are too technical for some website operators that just want to verify lighthouse scores via point-and-click. Would it be possible to emulate a user agent for service workers running on the same domain as the test is being performed?

**Comment by patrickhulce** [comment] 2018-02-16 00:00
Thanks for the thorough report and explanation @mattwomple!

Yes, it is possible, but requires some extra work blocked by #709. Essentially we need to replicate our emulation settings in both page and worker contexts.

**Comment by exterkamp** [comment] 2019-04-25 22:59
Closing as dupe of #709

**Closed by exterkamp** 2019-04-25 22:59 UTC
Labels: bug, needs-priority, pwa
