### ISSUE TITLE
'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by howtoloseweightnow** [GoogleChrome/lighthouse#9635] opened 2019-09-03 07:51 UTC
#### Provide the steps to reproduce
1. Run LH on http://www.howtoloseweightnow.eu/  using Chromium's Developer tools
  

#### What is the current behavior?
Audit has failed 
#### What is the expected behavior?
Audit has succeeded

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System: Debian 10.0 (64-bit)
* Browser: Chromium Version 76.0.3809.100 (Developer Build) built on Debian 10.0

**Related issues**

**Comment by midzer** [comment] 2019-09-03 11:41
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/7246

**Comment by wardpeet** [comment] 2019-09-03 15:36
This is indeed a duplicate, thanks @midzer.

**Closed by wardpeet** 2019-09-03 15:36 UTC
