### ISSUE TITLE
Wrong detection of browser idle in applied vs simulated slowdown which affects TTI

### ISSUE THREAD

**Issue by filrak** [GoogleChrome/lighthouse#9574] opened 2019-08-19 11:59 UTC
Hey! I already had a call with one of your colleagues some time ago where we confirmed the 

The case is - things like https://web.dev/ that have underlyimg lighthouse (probably with applied slowdown) measure TTI wrongly. To be more precise they don't detect browser idle at the right moment therefore things that are prefetched in the background are considered still impacting TTI.

This ends up with a huge difference in real-world performance vs LH result in our product that is highly relying on prefetching. The only "working" configuration is "Simulated  4G" seems to measure it accurately.

Since many clients rely on LH score it's much much harder to properly pitch them and tell that product is fast when the score says something totally different.

#### Provide the steps to reproduce
1. Run LH on https://demo.vuestorefront.io/ locally simulated 4g
2. Run the same audit on applied 4g and web.dev/measure

#### What is the current behavior?

TTI is measured wrongly and LH result highly differs between simulated and applied 4G (usually around 5x vs 8x)

#### What is the expected behavior?
Browser idle should be detected in the right moment before prefetching happens.

#### Environment Information
* Affected Channels:  DevTools and external sources
* Lighthouse version: latest
* Node.js version:
* Operating System: Tested in W10 and MacOS Mojave

**Related issues**

**Comment by filrak** [comment] 2019-08-19 12:08
Might be related to: https://github.com/GoogleChrome/lighthouse/issues/9483

**Comment by patrickhulce** [comment] 2019-08-19 15:03
Thanks for filing @filrak! Would you mind elaborating a bit? Specifically...

> they don't detect browser idle at the right moment

What is the right moment? And who did you speak with that "confirmed" that the current strategy is incorrect?

> LH result highly differs between simulated and applied 4G

The runs I'm seeing differ by about 14 points with TTI varying by ~2 seconds.

![image](https://user-images.githubusercontent.com/2301202/63275470-3352df80-c267-11e9-9ad7-9dbc6d9ac864.png)

![image](https://user-images.githubusercontent.com/2301202/63275489-39e15700-c267-11e9-9736-af5d276f4e8a.png)

While on the high end of score variance, this is relatively within the expected range of volatile performance measurements. You can read more about the factors affecting performance metric variance in our [explainer](https://github.com/GoogleChrome/lighthouse/blob/2e053e1fcabb769bae8d9bf79e06a50556d43465/docs/variability.md).

> properly pitch them and tell that product is fast when the score says something totally different.

The applied throttling performance metrics are what users actually experience on a cold load, slow 4G, mid-tier mobile phone. Speed Index in particular is the worst of the metrics on this page as the images take ~8 seconds to load. Is this the same experience the team is aware of when considering the product to be fast? I ask because if the frustration comes from the usage of a slow 4G, mid-tier mobile phone as our model, that's a very different discussion than "the metrics are computed incorrectly".

**Comment by filrak** [comment] 2019-08-19 15:27
Hey!, Thanks for the answer. I think I need to clarify a few things from my message that may be misleading. Sorry for inconvenience .

First of all I wrongly communicated the thing about difference with "applied" and "sinulated".
The main problem is not a local Lighthouse audit but the one made by your external tools like web.dev 
![image](https://user-images.githubusercontent.com/15185752/63277394-8a77a500-c2a5-11e9-84e1-1e2e2b4d7801.png)
page speed insights
![image](https://user-images.githubusercontent.com/15185752/63277673-070a8380-c2a6-11e9-8bcc-5d09f217247f.png)

The assumption came from a fact that during a call with your friend from Google (which name I forgot because it was some time ago but I'll come back once I find it in a mailbox) we measured it locally and he suspected the problem might be in the applied 4g setting because we spotted a significant difference between those two and he admitted that prefetching might be the reason of this. If you're saying it's an acceptable difference then it's not the case.

Then I would like to know what could case such difference between your external tools and local runs regarding TTI because for me it seems like a bug.

**Comment by connorjclark** [comment] 2019-08-19 17:38
@patrickhulce here's the trace from LR: https://gist.github.com/connorjclark/e9a44c9d3a2434929041034e34e15d30

**Comment by patrickhulce** [comment] 2019-08-19 21:18
Ah thanks for clarifying @filrak! And thanks @connorjclark for the raw data!

The difference between these two environments for your page comes down to the lack of support for HTTP/2 on the infrastructure that web.dev runs on. Because the site delivers lots of files it is particularly punished by the lack of H2 support there. This bug is captured by https://github.com/GoogleChrome/lighthouse/issues/7326 as well as internally assigned to the appropriate team. Feel free to subscribe to that issue for any progress updates, but I'll go ahead and close this one as a duplicate for now.

**Closed by patrickhulce** 2019-08-19 21:18 UTC
Labels: needs-more-info

**Comment by filrak** [comment] 2019-08-20 06:58
Thank you very much for the clarification :)
