### ISSUE TITLE
Extension Error: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache

### ISSUE THREAD

**Issue by Bondifrench** [GoogleChrome/lighthouse#6454] opened 2018-11-02 11:29 UTC
**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: http://localhost:8080/app#!/
**Error Message**: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
**Stack Trace**:
```
LHError: PROTOCOL_TIMEOUT Method: Network.clearBrowserCache
    at _ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:18402:11)
```

**Comment by patrickhulce** [comment] 2018-11-02 14:05
duplicate of #6450

**Closed by patrickhulce** 2018-11-02 14:05 UTC
