### ISSUE TITLE
"Preconnect to required origins" should not come up

### ISSUE THREAD

**Issue by cihati** [GoogleChrome/lighthouse#6676] opened 2018-11-28 20:32 UTC
#### Provide the steps to reproduce
1. Run LH on https://fatllama.com

#### What is the current behavior?
It shows this suggestion.

#### What is the expected behavior?
It doesn't show this suggestion, as I already preconnect to 5 domains in the homepage:
```
    <!-- preconnect 5 most costly connections https://www.webpagetest.org/forums/showthread.php?tid=15317 -->
    <link rel='preconnect' href='//api.segment.io' />
    <link rel='preconnect' href='//stats.pusher.com' />
    <link rel='preconnect' href='//m.stripe.com' />
    <link rel='preconnect' href='//www.google-analytics.com' />
    <link rel='preconnect' href='//js.intercomcdn.com' />
    <!-- preconnect end -->
```

According to #3106 , no more than 5 preconnections should be done for best performance. LH asks me to do a lot more:
![image](https://user-images.githubusercontent.com/461998/49180459-a371ac00-f34c-11e8-839d-d4540656837e.png)

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* Node.js version:
* Operating System: MacOS High Sierra 

**Related issues**
#3106

**Comment by patrickhulce** [comment] 2018-11-28 22:44
Thanks for filing @cihati! Some good news/bad news

Looking at the [webpagetest results](https://www.webpagetest.org/result/181128_97_d27d4f7e6e05affab03e9034a23b2129/1/details/#waterfall_view_step1) for your page, it looks like not all of the preconnect directives are being respected by Chrome. 😢 

In latest version of Lighthouse I just tested though, we're not telling you to preload the ones that are successfully being preloaded in the WPT results though 😃

I think we'll fix this by fetching the `link`s in your HTML to double check 👍

**Comment by cihati** [comment] 2018-11-29 10:02
Thanks for the quick reply, @patrickhulce

**Comment by wardpeet** [comment] 2018-11-29 18:39
it's more or less a duplicate of #5932.

Thanks for filling out!

**Comment by patrickhulce** [comment] 2018-11-29 19:11
Thanks @wardpeet I *thought* I remembered something like this, but I couldn't find it in the moment :)

Closing in favor of #5932

**Closed by patrickhulce** 2018-11-29 19:11 UTC

**Comment by nicolaskopp** [comment] 2019-04-12 11:15
made some more observations here: https://github.com/GoogleChrome/lighthouse/issues/5932?_pjax=%23js-repo-pjax-container#issuecomment-482536051
