### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by zhuangyin8** [GoogleChrome/lighthouse#2435] opened 2017-06-05 01:18 UTC
**Initial URL**: https://www.microsoft.com/en-us/software-download/windows10
**Chrome Version**: 61.0.3119.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@177b9b934d8398dfb0d17b88fd9ff00f3291cca5/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by stramel** [comment] 2017-06-05 02:48
Dupe of #1091

**Closed** 2017-06-05 14:43 UTC
Labels: duplicate
