### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by skylerto** [GoogleChrome/lighthouse#966] opened 2016-11-18 02:40 UTC
**Lighthouse Version**: 1.2.0
**Chrome Version**: 56.0.2924.0
**Error Message**: {"code":-32000,"message":"Result of the evaluation is not a promise"}
**Stack Trace**:
 ```undefined```

**Comment by wardpeet** [comment] 2016-11-18 19:10
can we get a url as well to test on, can not reproduce it at the moment

**Comment by skylerto** [comment] 2016-11-19 02:10
I wish i could but the site is hosted locally, currently developing it.

**Comment by brendankenny** [comment] 2016-11-19 02:15
if you can easily reproduce this, a copy of the lighthouse log near there would be *really* useful.

You can access by going to `about:extensions`, clicking the "Inspect views: background page" link under lighthouse to open up DevTools, going to the console panel, then running the Lighthouse extension as you were.

There should be some `'method => browser'` and `method <= browser ERR` messages before the error happens. The exact method being run and the parameters used should be in those messages.

**Comment by a-xin** [comment] 2016-11-19 11:53
I'm also seeing this issue on a private page, that's the error log I get in "Inspect views":

```
[...]
status Retrieving: EventListeners +201ms     lighthouse-background.js:62169
<= DOM.setChildNodes +5ms Object       lighthouse-background.js:62169
[...]
<= DOM.setChildNodes +0ms Object
status Retrieving: AnchorsWithNoRelNoopener +133ms
status Retrieving: AppCacheManifest +7ms
status Retrieving: ConsoleTimeUsage +7ms
method <= browser ERR:error Runtime.evaluate +2ms 
status Retrieving: DateNowUse +1ms
method <= browser ERR:error Runtime.evaluate +1ms 
status Retrieving: DocWriteUse +1ms
method <= browser ERR:error Runtime.evaluate +3ms 
status Retrieving: GeolocationOnStart +2ms
method <= browser ERR:error Runtime.evaluate +2ms 
status Disconnecting from browser... +1ms

Object
message: "{"code":-32000,"message":"Result of the evaluation is not a promise"}"
__proto__: Object
background.loadSelectedAggregations.then.then.catch.err @ scripts/popup.js:184
```

**Comment by skylerto** [comment] 2016-11-19 15:36
:+1: same log

**Comment by ebidel** [comment] 2016-11-20 04:14
Looks like an error in the protocol, probably from `evaluateAsync. 

https://github.com/GoogleChrome/lighthouse/pull/977 and and https://github.com/GoogleChrome/lighthouse/issues/976 will give us better insight.

**Comment by brendankenny** [comment] 2016-11-20 04:40
so I noticed this yesterday: `geolocation-on-start` is the only gatherer using `evaluateAsync` that [doesn't catch driver errors from it](https://github.com/GoogleChrome/lighthouse/blob/59cef3b7c6a0ea41acbdbe0d8b301c3693494f80/lighthouse-core/gather/gatherers/dobetterweb/geolocation-on-start.js#L45). Should be an easy fix just for this particular error, though that won't fix the artifact produced.

What's really interesting about this log though is that *every* `evaluateAsync` call is failing. With this particular fix the lighthouse run will complete, but all the results will be -1. No idea how that could be happening at this point.

**Comment by wardpeet** [comment] 2016-11-21 18:14
I can not seem to reproduce this.

**Comment by a-xin** [comment] 2016-11-21 18:46
@wardpeet Just realized I can reliably reproduce it on [this demo project](https://rate-axindev.rhcloud.com/). Can you reproduce the issue there?

**Comment by wardpeet** [comment] 2016-11-21 22:10
yes I can.
I think @brendankenny is fixing this in #977

**Closed** 2016-11-22 00:06 UTC
Labels: extension

**Comment by brendankenny** [comment] 2016-11-22 00:07
I opened #1000 to figure out the larger issue of why some sites fail all `evaluateAsync` calls
