### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by agdolla** [GoogleChrome/lighthouse#3147] opened 2017-08-27 08:45 UTC
**Initial URL**: http://localhost:3000/
**Chrome Version**: 60.0.3112.101
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by agdolla** [comment] 2017-08-27 09:18
more info:
git clone https://github.com/react-boilerplate/react-boilerplate
git checkout dev
yarn
npm run start:production
open localhost:3000 and try audit

**Comment by patrickhulce** [comment] 2017-09-01 16:00
dupe of #1733

**Closed by patrickhulce** 2017-09-01 16:00 UTC
Labels: DevTools
