### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by cobusk** [GoogleChrome/lighthouse#2529] opened 2017-06-18 19:48 UTC
**Initial URL**: about:blank
**Chrome Version**: 61.0.3129.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@b7e12bae8572c1ed03d0959ed71df8e4efe2f8ee/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@b7e12bae8572c1ed03d0959ed71df8e4efe2f8ee/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-06-19 15:16
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2362

**Closed by ebidel** 2017-06-19 15:16 UTC
