### ISSUE TITLE
DevTools Error: Unable to load the page: 

### ISSUE THREAD

**Issue by needpower** [GoogleChrome/lighthouse#2789] opened 2017-07-29 09:15 UTC
**Initial URL**: http://learn.javascript.ru/img/sitetoolbar__logo_ru.svg
**Chrome Version**: 60.0.3112.78
**Error Message**: Unable to load the page: 
**Stack Trace**:
```
Error: Unable to load the page: 
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by paulirish** [comment] 2017-08-01 21:57
thanks for reporting. presumably this is a dupe of like the others.

cheers

**Closed by paulirish** 2017-08-01 21:57 UTC
