### ISSUE TITLE
Error: Unknown formatter: url-list

### ISSUE THREAD

**Issue by merlinpatt** [GoogleChrome/lighthouse#2531] opened 2017-06-18 22:46 UTC
```
 Error: Unknown formatter: url-list
    at Function.t.getByName (https://googlechrome.github.io/lighthouse/viewer/src/main.js:2:9830)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12833
    at Array.forEach (native)
    at e._registerFormatters (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12753)
    at e.generateHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:13036)
    at t.replaceReportHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:25936)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:26491
```

Just got this bug after exporting and then importing from the report generated by the Chrome extension.

**Comment by ebidel** [comment] 2017-06-19 00:37
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/2338

**Closed by ebidel** 2017-06-19 00:37 UTC
