### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by seocamo** [GoogleChrome/lighthouse#1007] opened 2016-11-22 06:28 UTC
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: Cannot read property 'filter' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'filter' of undefined
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:793:53)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10959:24)```
i try lighthouse on netflix, and this happen

**Comment by brendankenny** [comment] 2016-11-22 06:42
duplicate of #975

**Closed by brendankenny** 2016-11-22 06:42 UTC
