### ISSUE TITLE
Create a version of ToDoMVC that's good/bad for UX study

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#4456] opened 2018-02-07 22:47 UTC
^^ see above.  todomvc vanilla should be fine.

**Comment by paulirish** [comment] 2018-02-12 22:18
@hwikyounglee does it work for you if we have this ready by Early March?

**Comment by hwikyounglee** [comment] 2018-02-14 05:47
V asked the question to Jason. So we'll confirm soon. (Early March seems right to me)

**Comment by vinamratasingal** [comment] 2018-02-14 23:08
This needs to be in by March 4.

**Comment by hwikyounglee** [comment] 2018-02-14 23:08
March 4 would be a good target so we have time to practice/dryrun. Thanks!

**Comment by patrickhulce** [comment] 2018-02-27 19:16
OK I've two versions, one that's pretty bad everywhere and one that's pretty good with a few intentional regressions. I'm thinking for the good scenario we say that they remember fixing all images and JavaScript; I reintroduced a few of the JavaScript opportunities to the good version which are mixed in with CSS opportunities.

## Bad
![image](https://user-images.githubusercontent.com/2301202/36749363-6699afdc-1baf-11e8-98f1-b0549cecba7f.png)

## Good
![image](https://user-images.githubusercontent.com/2301202/36749384-726cd88e-1baf-11e8-889f-6482edb4cda1.png)


## Report Files

(can just remove .txt extension to open in chrome)
[lighthouse_ux_study_good.html.txt](https://github.com/GoogleChrome/lighthouse/files/1764328/lighthouse_ux_study_good.html.txt)
[lighthouse_ux_study_bad.html.txt](https://github.com/GoogleChrome/lighthouse/files/1764329/lighthouse_ux_study_bad.html.txt)

**Comment by hwikyounglee** [comment] 2018-03-01 18:37
+1. Thanks patrickhulce@!

**Comment by patrickhulce** [comment] 2018-03-12 17:55
seems to be working well so far, so marking this as closed!

**Closed by patrickhulce** 2018-03-12 17:55 UTC
Labels: P1

**Comment by brendankenny** [comment] 2018-03-12 18:37
Would this (or something like this) be worth moving into lighthouse proper with a script to run lh over both? Automate a way to see the comparison between two sites (for the core perf metrics, at least)
