### ISSUE TITLE
Add progress bar for crx/devtools auditing

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#1630] opened 2017-02-03 21:46 UTC
It would be nice to have a progress bar when auditing the page. Similar to PSI and https://testmysite.thinkwithgoogle.com/. As we add more audits, this will become more important.

In the extension, we how the user the list of audits as they run. The progress could be a quick % completed: `(num audits done / total audits) * 100`.

**Comment by paulirish** [comment] 2017-02-04 04:31
Relatedly the progress monitor in #815 was designed for keeping track of tasks, incomplete and complete.

**Comment by pavelfeldman** [comment] 2017-02-06 02:22
Should I resurrect the patch?

**Comment by ebidel** [comment] 2017-02-07 18:16
Sure! Not sure how much has changed since then. Looks like there is a bunch of rebasing that needs to take place.

**Comment by brendankenny** [comment] 2017-09-26 21:23
possible dupe of streaming results

**Closed** 2017-09-27 00:29 UTC
Labels: extension, feature, needs-priority
