### ISSUE TITLE
Redirecting to non-https url then failing. 

### ISSUE THREAD

**Issue by bonpixel** [GoogleChrome/lighthouse#2007] opened 2017-04-13 22:52 UTC
When running Lighthouse the page redirects to non `https` version and then fails to load. I'm not serving anything via http/80 and I'm not redirecting to https/443 but it seems like the plugin should just use the url I gave to it instead of changing it to http.

**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: https://localhost:3000/foo-bar/

**Comment by ebidel** [comment] 2017-04-14 03:23
Probably a dupe of https://github.com/GoogleChrome/lighthouse/issues/1978. Also related: https://github.com/GoogleChrome/lighthouse/issues/1217

**Comment by wardpeet** [comment] 2017-04-21 17:22
yeah it is i'm closing this one :) please refer to #1978

**Closed by wardpeet** 2017-04-21 17:22 UTC
