### ISSUE TITLE
Reality vs. Lighthouse results

### ISSUE THREAD

**Issue by robwatson-intechra** [GoogleChrome/lighthouse#3033] opened 2017-08-18 01:28 UTC
I'm consistently getting 26s site load times in Lighthouse audits. Actually loading the website on a desktop or mobile device only takes 4 seconds. What is it that Lighthouse thinks is going on that it would give a 26s site load time when real users are experiencing nothing of the kind?

**Comment by ebidel** [comment] 2017-08-18 01:46
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2905 with explanation in https://github.com/GoogleChrome/lighthouse/issues/2864#issuecomment-321086040. The solution is to allow customizing the emulation settings (https://github.com/GoogleChrome/lighthouse/issues/2838)

**Closed** 2017-08-18 01:46 UTC
Labels: duplicate
