### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by denov** [GoogleChrome/lighthouse#2079] opened 2017-04-27 05:07 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 57.0.2987.133
**URL**: https://qa.magicapp.org/app

**Comment by stramel** [comment] 2017-04-27 05:12
Dupe of #1091

**Closed** 2017-04-27 06:27 UTC
