### ISSUE TITLE
Performance and pwa not reporting. Also results in others are not correct.

### ISSUE THREAD

**Issue by pushkar-anand** [GoogleChrome/lighthouse#5463] opened 2018-06-09 10:11 UTC
#### Provide the steps to reproduce
1. Run LH on https://omniaparatus.co.in

#### What is the current behavior?
Performance, pwa shows error when reporting.
Other reports are not correct.
My site does not use HTTP/2 but it reports it incorrectly 

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 3.0.0-beta.0
* Operating System: Ubuntu 18.04 LTS

Logs and screenshot are attached.
[bug-report.zip](https://github.com/GoogleChrome/lighthouse/files/2086854/bug-report.zip)

**Comment by patrickhulce** [comment] 2018-06-11 16:10
The error is `NO_NAVSTART` which is a flaky Chrome issue that pops up from time to time. If you hover over the error, it will give you instructions on how to fix it. (in this case just run LH again)

![image](https://user-images.githubusercontent.com/2301202/41243499-27483fa2-6d57-11e8-9908-cfe06bf18f98.png)

Separately, I'm not seeing that your site uses HTTP/2 and several other audit values seem to be different. Is it serving the same page?
![image](https://user-images.githubusercontent.com/2301202/41243352-cd0d8ba0-6d56-11e8-8419-5981d25d5641.png)

![image](https://user-images.githubusercontent.com/2301202/41243569-50827b12-6d57-11e8-9bce-c961e92d8dac.png)

**Comment by pushkar-anand** [comment] 2018-06-11 18:37
Exactly my site uses http/1.1 but lighthouse reports that it using http/2. Several other audits reported are incorrect.

**Comment by patrickhulce** [comment] 2018-06-11 19:00
Hm, I'm not able to reproduce that.

![image](https://user-images.githubusercontent.com/2301202/41251498-f58ee8ae-6d6e-11e8-805f-7d195769419a.png)

**Comment by brendankenny** [comment] 2018-08-10 18:46
Closing for now. If you're still seeing this issue in the latest Lighthouse please comment and we can reopen!

**Closed by brendankenny** 2018-08-10 18:46 UTC
Labels: needs-more-info
