### ISSUE TITLE
Don't break back-compat of the LHR

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2165] opened 2017-05-05 21:58 UTC
We'll have people saving lhr.json files more often now. And if they drag one from folder into devtools audits, they'll expect to see a report.

My proposal to make this easier:

* the LHR gets a `.config` property which is the actual config.
* do the [`generateReportJson()`/etc work](https://github.com/GoogleChrome/lighthouse/blob/581eec37cb08cd9d13be7da4ad41465c70bdd64f/lighthouse-core/runner.js#L136-L150)  inside of the `generateHTML` method
* optional: we could even expose a more static `scoreReport` method in case other modules wanted scores/certifications. (Similar public API-ness makes sense for the pw-metrics-events metric gathering_

But to paraphrase pavel, the sooner you start guaranteeing the backcompat of this API the better.

**Comment by patrickhulce** [comment] 2017-10-13 00:13
dupe of #2668

**Closed by patrickhulce** 2017-10-13 00:13 UTC
Labels: bug, feature, needs-priority
