### ISSUE TITLE
Extension: support disable device emulation flag

### ISSUE THREAD

**Issue by sowmyamanusani** [GoogleChrome/lighthouse#1822] opened 2017-03-06 19:51 UTC
When I do generate report , it is always opening mobile version of the page however I entered page in desktop version. How can I change the settings to open a desktop version but not mobile

**Comment by patrickhulce** [comment] 2017-03-06 19:53
@sowmyamanusani you can use the `--disable-device-emulation` flag on the CLI to run lighthouse without mobile emulation

**Comment by sowmyamanusani** [comment] 2017-03-06 19:56
I am using google chrome plugin. I do not see any option to disable that mobile emulation

**Comment by patrickhulce** [comment] 2017-03-06 23:24
Not all options available on the CLI are available in the extension yet, though it's a good first bug if you're so inclined :)

**Comment by ZZhaoTireless** [comment] 2017-03-17 15:19
I would like to fix this.

**Comment by ZZhaoTireless** [comment] 2017-03-22 05:19
@patrickhulce Could you tell me which file is responsible for the flag in extension folder? I did try to find the way to add flag in extension but I had no clue. I will be glad to help if there is a little hint. Thanks!

**Comment by Pines-Cheng** [comment] 2017-08-15 01:10
That's cool!

**Comment by patrickhulce** [comment] 2017-10-12 22:25
closing as dupe of #2838

**Closed by patrickhulce** 2017-10-12 22:25 UTC
Labels: extension, feature, good first issue, needs-priority
