### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by wendelmoreira** [GoogleChrome/lighthouse#2815] opened 2017-08-01 14:02 UTC
**Lighthouse Version**: 2.3.0
**Chrome Version**: 60.0.3112.78
**Initial URL**: https://chicorei.com/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14109:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14534:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14559:25)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-08-08 21:30
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-08-08 21:30 UTC
