### ISSUE TITLE
Audit without a page refresh?

### ISSUE THREAD

**Issue by NamKot** [GoogleChrome/lighthouse#2332] opened 2017-05-22 18:37 UTC
Hi there! Lighthouse is a great tool that generates a consolidated report of performance, accessibility and best practices report. The webapp we are currently developing is a SPA (single page application) which throws an error on refreshing the page. Due to security concerns (since it is a Test Delivery application), refresh is disallowed. 

It would be a great feature if the report could be generated in a separate tab/window without page reload. 
If the above is supported, it would help to run the tool against multiple sequential webpages (including single page application). 
i did see a few posts on the same lines, but found it helpful to mention the scenario above. 

Thanks! 
Namrata
LinkedIn profile: https://www.linkedin.com/in/namrata-kotha-84b118b7/

**Comment by wardpeet** [comment] 2017-05-22 20:08
The only option I see at the moment is to run multiple lighthouse runs with 3 different configs as they only run 1 pass.

If you need help I'm happy to support you with an example.

**Comment by NamKot** [comment] 2017-05-30 01:02
@wardpeet Please do - would really help. Thanks in advance! 

-Nam

**Comment by paulirish** [comment] 2017-09-26 20:54
@NamKot what details do you want from Lighthouse in this case? PWA? Performance? Best practices?  Accessiblilty? 

In some cases we can provide them without a reload.. However performance requires a load...    What part of the report is your priority?  thanks!

**Comment by paulirish** [comment] 2017-09-26 21:24
Likely a dupe of #1769

**Closed** 2017-09-26 23:00 UTC
Labels: needs-more-info, pending-close, question

**Comment by rageshpayyan** [comment] 2018-09-16 19:49
> The only option I see at the moment is to run multiple lighthouse runs with 3 different configs as they only run 1 pass.
> 
> If you need help I'm happy to support you with an example.

Is there is a way we can audit page flows using lighthouse. example, page1 -> page 2-> page N. If I use lighthouse to audit page N, single page going page1 instead of page N. Is there are any other techniques to achieve this.

**Comment by wardpeet** [comment] 2018-09-17 05:41
lighthouse only supports 1 page. If you need to test for multiple pages you can have a look at https://github.com/github/lightcrawler which hasn't been updated for a while.

There are probably other projects that does something similar.

**Comment by rageshpayyan** [comment] 2018-09-17 17:42
> lighthouse only supports 1 page. If you need to test for multiple pages you can have a look at https://github.com/github/lightcrawler which hasn't been updated for a while.
> 
> There are probably other projects that does something similar.
Can audit page N  using lighthouse without refreshing, in my app if I audit page N, it loses all the browser state and going to the home page. So my question is can be able to use a lighthouse without page reload.
