### ISSUE TITLE
"Registers a Service Worker" failing when on localhost

### ISSUE THREAD

**Issue by jeromecovington** [GoogleChrome/lighthouse#2006] opened 2017-04-13 18:43 UTC
I am registering a service worker, and thus enabling offline loading, with the `offline-plugin` for webpack. I have verified that the service worker is registered, and that offline loading works as I would have expected, but Lighthouse reports a number of failures around the inability to respond with a 200 with no network (offline loading) and the lack of registration of a service worker. I am only developing this particular PWA locally at the moment, and so have only pointed Lighthouse to `localhost`. Is there some issue around Lighthouse's reporting when doing so?

**Comment by JonasBa** [comment] 2017-04-15 09:42
I noticed a similar thing after I moved my service worker registration after the window.load event. Maybe worth checking if that could be the case.

**Comment by stramel** [comment] 2017-04-15 16:10
Maybe similar to #1815

**Comment by ebidel** [comment] 2017-04-15 17:40
@jeromecovington are you able to provide us with the URL of your site?

**Comment by ebidel** [comment] 2017-04-15 18:22
Ah `localhost` :) This looks like a duplicate of https://github.com/GoogleChrome/lighthouse/issues/1815. Are you testing on a slow conncetion or delaying the service worker registration until after `window.onload`?

**Closed** 2018-03-08 23:37 UTC
Labels: pending-close
