### ISSUE TITLE
Fix instrumentation issue with screenshot collection for extension/CLI

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3337] opened 2017-09-14 17:51 UTC
Summary: 
When generating the thumbnails for the screenshot for extension (and possibly for CLI) users, the screenshots come out squished. This could potentially also impact speed index as well. The issue is primarily caused by the way the device is emulated in the Chrome Extension Debugger API 

Potential path forward: 
We can try to work with the DevTools team to fix it, or put together a hacky patch for when we generate the screenshot to avoid this error.

**Comment by paulirish** [comment] 2017-09-26 21:02
dupe of #2287

**Closed by paulirish** 2017-09-26 21:02 UTC
Labels: needs-priority
