### ISSUE TITLE
Accessebility issue when adding extra li or text

### ISSUE THREAD

**Issue by rkhatana001** [GoogleChrome/lighthouse#13039] opened 2021-09-10 09:59 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.aidonis.com

### What happened?

I am running a test to check Accessibility for my website (mobile ver). Lighthouse giving error on Navbar, after some R&D I found a strange behavior.
1.
![image](https://user-images.githubusercontent.com/45754095/132835375-3a403a7e-f0fb-44b5-98c7-98b7068d5008.png)
for above code I get score as you can see in below image
![image](https://user-images.githubusercontent.com/45754095/132835477-9021d3f9-0408-4a2b-870c-325c3a1733b5.png)
2. But As soon I replace ABCD with the original text or add another li (check below code image)
![image](https://user-images.githubusercontent.com/45754095/132834599-9a35c23b-7343-421e-bf61-438ed8d3c378.png)
if I use the above code I get below the score
![image](https://user-images.githubusercontent.com/45754095/132835184-d30918fa-e194-4e33-8ad6-9eb1420df4b5.png)

### What did you expect?

1. By adding new li score should not change
2. How I am getting score for ABCD but error for Treatment

### What have you tried?

1. I have tried a different versions of Chrome.
2. I just debug for this particular div by removing other content from the webpage.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

100.0.0.0

### Chrome Version

93.0.4577.63

### Node Version

na

### Relevant log output

```shell
na
```

**Comment by patrickhulce** [comment] 2021-09-10 13:17
Thanks for filing @rkhatana001!

The `?` score means that the accessibility library threw an exception and we couldn't determine a score. If you hover over one of the accessibility audits that says "Error" it should give you a more detailed exception message.

Would you be able to share a URL that reproduces the `?` case you describe? I'm not able to reproduce this behavior with *just* the snippet of code that you have shared.

**Comment by rkhatana001** [comment] 2021-09-10 13:37
> 
> 
> Thanks for filing @rkhatana001!
> 
> The `?` score means that the accessibility library threw an exception and we couldn't determine a score. If you hover over one of the accessibility audits that says "Error" it should give you a more detailed exception message.
> 
> Would you be able to share a URL that reproduces the `?` case you describe? I'm not able to reproduce this behavior with _just_ the snippet of code that you have shared.

please check https://aidonis.com/ for the mobile version
when I hover on the error, it gives below message

axe-core Error: Cannot read properties of undefined (reading 'cells')
Background and foreground colors have a sufficient contrast ratio Error!

**Comment by patrickhulce** [comment] 2021-09-10 13:47
Thanks @rkhatana001 ! This is a duplicate of https://github.com/GoogleChrome/lighthouse/issues/12039 and axe-core has already been notified :)

**Closed by patrickhulce** 2021-09-10 13:47 UTC
Labels: bug, needs-more-info, needs-priority
