### ISSUE TITLE
Incorrect aspect ratio on map images

### ISSUE THREAD

**Issue by mknwebsolutions** [GoogleChrome/lighthouse#9235] opened 2019-06-19 18:47 UTC
#### Provide the steps to reproduce
1. Run LH on https://www.stockbrokers.com/review/ally-invest
2. Validate scores per image below:
https://imgur.com/a/oUuH8Ox

#### What is the current behavior?
- LH reporting "Displays images with incorrect aspect ratio".
- The two images identified are image maps

#### What is the expected behavior?
- Image maps (or a image sprite containing multiple visuals) should not be reporting as an incorrect aspect ratio

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 4.2.0

**Comment by patrickhulce** [comment] 2019-06-19 19:01
Thanks for filing @mknwebsolutions this was fixed in 4.3.0, #7516. I cannot reproduce on latest Lighthouse version.

**Closed by patrickhulce** 2019-06-19 19:01 UTC
