### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by tyohan** [GoogleChrome/lighthouse#2205] opened 2017-05-10 04:44 UTC
**Lighthouse Version**: 1.6.5
**Chrome Version**: 60.0.3094.0
**URL**: https://shuvayatra.org/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9254:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)```

**Comment by stramel** [comment] 2017-05-10 04:45
Dupe of #1091

**Closed** 2017-05-10 07:33 UTC
