### ISSUE TITLE
Perf Scoring: What does a  "Target" actually mean in relation to scores?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#2020] opened 2017-04-16 22:14 UTC
I've been getting ok and not-ok values for TTI from the node module and after looking at the generate report, I'm not sure what the "target" values mean, if I'm below the target, why am I not getting 100 for the score?

![lighthouse-scoring](https://cloud.githubusercontent.com/assets/139760/25074727/203cd8e4-22b7-11e7-9164-30f46cdf4ef1.png)

**Comment by ebidel** [comment] 2017-04-17 03:06
+1 these are confusing. The perf metrics should really have "target: < TARGET_VAL". 

FWIW, we're planning to make things more clear in the v2 report redesign. You'll see sparklines to see how far of the "target" you ended up.

**Comment by addyosmani** [comment] 2017-04-17 05:18
+1 on it being super hard to reason about with the current presentation. Def on that 96 score.

The current breakdown has otherwise been useful for me in understanding how much of my TTI (target val) "budget" I have left for wiggle room - in case I want to add more functionality or shift more to lazily loaded bundles. I'd want to preserve some notion of that if we can.

**Comment by kosamari** [comment] 2017-04-17 20:46
some-what related (?) https://github.com/google/WebFundamentals/issues/4390
Is there a resources about where 1600/1250/50/5000 number comes from ??

**Comment by paulirish** [comment] 2017-09-26 21:28
@gauntface  Is this a dupe of #2376  ? wdyt

**Comment by gauntface** [comment] 2017-09-29 17:48
I think so. Looks likes the wording / values moved but essentially the same.

**Closed** 2017-09-29 18:06 UTC
Labels: feature, report
