### ISSUE TITLE
Lighthouse keep giving error "No Matching Service Worker" while PWA audit even when an active service worker is registered 

### ISSUE THREAD

**Issue by manusis** [GoogleChrome/lighthouse#13225] opened 2021-10-17 03:06 UTC
Website:  https://furniture-de.mobitual.com/

Browser: Chrome 94

I can see the install icon in the browser and I am able to install the PWA on desktop but when I run the Lighthouse  PWA audit, it keep on giving me this error.

_No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest._

I checked the Application Tab, I could see a valid Manifest and an active service worker registered with the scope at the root level of the site. 

I tried many things but not able to get rid of this error.

**Comment by manusis** [comment] 2021-10-17 07:57
<img width="988" alt="Screen Shot 2021-10-17 at 8 29 44 AM" src="https://user-images.githubusercontent.com/202397/137617618-c19fa541-0b4e-447b-a94b-d7cc5c15d6e8.png">
![Uploading Screen Shot 2021-10-17 at 8.30.00 AM.png…]()
<img width="616" alt="Screen Shot 2021-10-17 at 8 29 52 AM" src="https://user-images.githubusercontent.com/202397/137617630-dfde4290-306c-4c24-8601-0eeba72b6830.png">

**Comment by manusis** [comment] 2021-10-17 07:58
<img width="988" alt="Screen Shot 2021-10-17 at 8 29 44 AM" src="https://user-images.githubusercontent.com/202397/137617646-8bdbc0e0-9900-413e-8e37-5440d916c4f4.png">
<img width="920" alt="Screen Shot 2021-10-17 at 8 30 00 AM" src="https://user-images.githubusercontent.com/202397/137617649-757c1bce-d9b4-48f1-9321-339d9ac74be1.png">
<img width="616" alt="Screen Shot 2021-10-17 at 8 29 52 AM" src="https://user-images.githubusercontent.com/202397/137617658-a82c69dc-c9d9-48e5-95ac-3ad7233068be.png">

**Comment by kleyber-ribeiro** [comment] 2021-11-12 13:21
Hi,
I have the same problem and I would like to have a solution for this.

**Comment by tomyitav** [comment] 2021-11-12 20:31
Same here, Lighthouse is failing but the service worker is registered.

**Comment by adamraine** [comment] 2021-11-24 22:30
Looks like the store on https://furniture-de.mobitual.com/ has been deleted. @manusis @kleyber-ribeiro @tomyitav are you able to provide additional URLs that reproduce this?

**Comment by adamraine** [comment] 2021-12-10 19:18
Without a URL to test there isn't much we can do. Some of these errors may have been resolved with https://github.com/GoogleChrome/lighthouse/issues/13396.

**Closed by adamraine** 2021-12-10 19:18 UTC
Labels: needs-more-info, needs-priority
