### ISSUE TITLE
Extension Error: Protocol error (Storage.clearDataForOrigin): Internal error

### ISSUE THREAD

**Issue by adewalegeorge** [GoogleChrome/lighthouse#1364] opened 2016-12-30 08:29 UTC
**Lighthouse Version**: 1.3.2
**Chrome Version**: 57.0.2966.1
**Error Message**: Protocol error (Storage.clearDataForOrigin): Internal error
**Stack Trace**:
 ```Error: Protocol error (Storage.clearDataForOrigin): Internal error
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7382:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7532:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2016-12-30 17:04
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1353

**Closed by ebidel** 2016-12-30 17:04 UTC
Labels: duplicate
