### ISSUE TITLE
After the lastest release, SEO and Accessibility score is shown as null for mobile strategy

### ISSUE THREAD

**Issue by dshubhamprdxn** [GoogleChrome/lighthouse#12717] opened 2021-06-29 11:50 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://axioned.com/

### What happened?

I'm using pagespeed insights API for fetching data on our site. It works fine for most of the sites but since the new update, we are getting **null** for **SEO** and **Accessibility** for **mobile** strategy. I have tried fetching data multiple times with the API with postman, [API documentation](https://developers.google.com/speed/docs/insights/v5/reference/pagespeedapi/runpagespeed) but still receiving the same result for this website.

When we try to fetch this data with chromes dev tools we were able to get proper results for mobile strategy having a score of around 90 for SEO and accessibility. Not sure why we are not getting proper values from pagespeed insights API
![image](https://user-images.githubusercontent.com/55387913/123785790-8e8b9980-d8f6-11eb-802b-9ba013936c4b.png).

Here is the data where I check the score for fetching SEO and accessibility: 
**mobile['lighthouseResult']['categories']['seo']['score']
mobile['lighthouseResult']['categories']['accessibility']['score']**

### What did you expect?

The expected score here is should be around 90 for SEO and accessibility.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

8

**Comment by adamraine** [comment] 2021-06-29 15:24
Do you have an example query that is returns null SEO and accessibility. Based on the documentation you linked, I think PSI API can only audit one category at a time.

**Comment by dshubhamprdxn** [comment] 2021-06-29 16:55
Thanks @adamraine  for quick response. 

The documentation I linked has an option saying 'try it now' where you can select the URL, multiple categories and strategy. Please refer the screen shot [here](https://paste.pics/fe47140868247a8360261718e1cb0974). Also, to hit the URL with postman with multiple categories, I checked this -> '**https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://axioned.com/&key=YOUR_API_KEY&category=performance&category=seo&category=accessibility&category=best-practices&strategy=mobile**'. 

Also, [here](https://paste.pics/edit/006118ab241aa5b97083a1b06fdbb4f0) is the response of the above api's resulting null values for SEO and accessibility.

**Comment by adamraine** [comment] 2021-06-29 18:09
Ah, you are correct. It looks like the accessibility gatherer is failing. This means some audits in Accessibility and SEO are failing, so we can't compute a score for those categories. This looks like a bug in PSI.

**Comment by patrickhulce** [comment] 2021-06-29 19:06
Thanks for filing @dshubhamprdxn! This appears to be a duplicate of https://github.com/GoogleChrome/lighthouse/issues/12705 which has been fixed and will be published to PSI at the next release.

**Closed by patrickhulce** 2021-06-29 19:06 UTC
Labels: P1.5, PSI/LR, bug, needs-investigation

**Comment by dshubhamprdxn** [comment] 2021-06-30 09:16
Thanks @patrickhulce, hope the new release will be available soon!!
