### ISSUE TITLE
Lighthouse is stuck at retrieving scripts 

### ISSUE THREAD

**Issue by tripti1410** [GoogleChrome/lighthouse#4418] opened 2018-02-04 09:39 UTC
I'm encountering an issue when running Lighthouse at (https://network18.madrid.quintype.io/) app. Its stuck at retrieving scripts. I am attaching a screenshot as well.

<img width="1430" alt="screen shot 2018-02-04 at 3 01 26 pm" src="https://user-images.githubusercontent.com/16831324/35776144-08427a1c-09bd-11e8-98da-ed80e50ae8c5.png">

**Comment by midzer** [comment] 2018-02-04 09:53
I can reproduce this with Lighthouse 2.8.
Site has 600+ kb of JavaScript running. Dunno whether it's too much for LH.

**Comment by patrickhulce** [comment] 2018-02-12 17:50
thanks for filing @tripti1410! this is a dupe of #4258 so we'll discuss over there, it only affects extension so workaround for now is to use the CLI

**Closed by patrickhulce** 2018-02-12 17:50 UTC
