### ISSUE TITLE
Remove unused JavaScript doesn't list any culprit assets

### ISSUE THREAD

**Issue by MrCsabaToth** [GoogleChrome/lighthouse#11771] opened 2020-12-05 01:35 UTC
I was advised by @connorjclark to file an issue.

#### Provide the steps to reproduce
1. Run LH on https://csaba.page/

I'm running Lighthouse in the Developer Tools tab.
Source code of the site: https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/
  
#### What is the current behavior?

Remove unused JavaScript (and also Remove duplicate modules in JavaScript bundles and Avoid serving legacy JavaScript) doesn't provide me a list of which JavaScript assets are unused.

This is an AMP website. I get three errors about JavaScript. I know that some issues have been worked on (https://github.com/ampproject/amphtml/issues/28638).

![Screenshot_2020-12-04_12-50-04](https://user-images.githubusercontent.com/744949/101229814-e14ded00-3656-11eb-8a3a-7bbc26b3dd5d.png)

#### What is the expected behavior?

On other screenshots I saw a list of the JavaScript in violation (example https://github.com/ampproject/amphtml/issues/28638#issuecomment-638473662 https://github.com/ampproject/amphtml/issues/28638#issuecomment-687213259).

#### Environment Information
* Affected Channels: ? Extension ? DevTools ? 
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.27 (Official Build) beta (64-bit), 89.0.4343.0 (Official Build) dev (64-bit)
* Node.js version: v12.19.0
* Operating System: Devuan GNU/Linux 4 (chimaera/ceres) - It's based on Debian unstable/testing

**Comment by connorjclark** [comment] 2020-12-05 03:29
Hover over the error–what does it say?

**Comment by MrCsabaToth** [comment] 2020-12-05 03:34
> Hover over the error–what does it say?

Oh yea! All three says "Cannot read property 'length' of undefined". The beta Chrome has some plugins, but the dev Chrome is pristine, vanilla

**Comment by MrCsabaToth** [comment] 2020-12-05 03:35
![Screenshot_2020-12-04_19-35-31](https://user-images.githubusercontent.com/744949/101232688-e5ced180-3667-11eb-8846-4b5d3ab538ef.png)

**Comment by MrCsabaToth** [comment] 2020-12-05 03:43
To be honest I misinterpreted the UI, I thought the "Error!" referred to the fact that the corresponding rule is violated - kind of a duplicate feedback for the red triangle icon. But now I see that it's the underlying plugin/extension code which shouts there that something was wrong.

**Comment by MrCsabaToth** [comment] 2020-12-05 03:59
This could be a Linux (or even distribution?) specific issue. I had to access a Windows machine by accident for another issue and I ran Lighthouse there for the same URL. The machine runs a Windows 10 Home 19041 build. I ran the test on a vanilla Official Chrome: 87.0.4280.88 (Official Build) (64-bit), Lighthouse version 6.4.0. It only lists Unused JavaScript and duplicate modules and it shows the detailed list for both of those entries.

**Comment by MrCsabaToth** [comment] 2020-12-06 07:52
Today I was using Lighthouse several times. The dev didn't produce the error today, not sure why. The beta still has it though.

**Comment by MrCsabaToth** [comment] 2020-12-12 07:52
Today it worked on the Chrome Dev (89.0.4350.4 (Official Build) dev (64-bit)). Yesterday it errored out. So with the Dev build the reproduction is not 100%, although this is a newer build, so I'll try again later. Ant to make this even weirder I tested now with the Chrome Beta (88.0.4324.41 (Official Build) beta (64-bit)) extension and it didn't error out. So something else affects this in the system. The Lighthouse extension is still 6.4.0.

**Comment by cdeutsch** [comment] 2020-12-15 23:49
FWIW, I'm running into the same issue on Mac 

Chrome Version 87.0.4280.88 (Official Build) (x86_64)

Lighthouse 6.4.0

**Comment by MrCsabaToth** [comment] 2020-12-16 17:00
@cdeutsch thanks, then this not Linux only

**Comment by paulirish** [comment] 2020-12-17 09:08
basically dupe of #11682

and we're 90% confident this was fixed by #10449 which shipped in LH 6.5.0  

sorry this broke on you and please let us know if you still run into this in LH 6.5.0, which is currently in Chrome 89 devtools.

**Closed by paulirish** 2020-12-17 09:08 UTC
Labels: needs-priority

**Comment by MrCsabaToth** [comment] 2020-12-17 19:01
The Dev Chrome now has the 6.5.0 Lighthouse, and a recent scan worked well. However with the 6.4.0 this didn't come 100% deterministically. But the referenced issues are certainly duplicates.
