### ISSUE TITLE
Protocol Error: Could not obtain database names

### ISSUE THREAD

**Issue by LillianWight** [GoogleChrome/lighthouse#11259] opened 2020-08-13 02:48 UTC
#### Provide the steps to reproduce
1. Opened Chrome DevTools, found Lighthouse tab, clicked Generate Report for facesofcovid.net.
  
(The version I loaded is from commit 7601d29 of https://github.com/LillianWight/FacesOfCOVID).

#### What is the current behavior?

First, I got the Protocol Timeout error (I reported the issue in the Pinned section). I cleared the site history, then ran LH again. This time I got the above issue. The full error is:

Protocol error (Network.emulateNetworkConditions): Could not obtain database names.
```
Channel: DevTools
Initial URL: https://facesofcovid.net/
Chrome Version: 84.0.4147.125
Stack Trace: Error: Protocol error (Network.emulateNetworkConditions): Could not obtain database names.
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@d0784639447f2e10d32ebaf9861092b20cfde286/lighthouse_worker/lighthouse_worker_module.js:1898:121)
    at eval (devtools://devtools/remote/serve_file/@d0784639447f2e10d32ebaf9861092b20cfde286/lighthouse_worker/lighthouse_worker_module.js:1417:246)
```

I ran LH again. This time I got:

![Untitled](https://user-images.githubusercontent.com/13643709/90088634-a22d1200-dcdc-11ea-85e9-d2da301b2ebd.png)

#### Environment Information
* Affected Channels: 
* Lighthouse version: n/a - I'm new to development and I just used what was within the DevTools
* Chrome version: Version 84.0.4147.125 (Official Build) (64-bit)
* Node.js version:
* Operating System: Windows 10

**Related issues**

Nothing other than what is described here.

**Comment by patrickhulce** [comment] 2020-08-13 03:03
Thanks for filing @LillianWight!

I'm not sure what is causing `Protocol error (Network.emulateNetworkConditions): Could not obtain database names.`, from Chromium source that message is only raised in connection with IndexedDB which is very unrelated to `Network.emulateNetworkConditions`... I also couldn't reproduce it.

The NO_FCP error is much more common. Did you happen to background the tab while you waited for results? When using the DevTools Lighthouse (or doing any performance profiling really) the tab needs to be visible and kept in the foreground or it will be throttled/prevented from painting.

**Comment by LillianWight** [comment] 2020-08-13 19:58
Hi, Patrick.

I may have backgrounded the tab, yes. I've just tried it again and it seems to work fine.

Thank you!

**Comment by connorjclark** [comment] 2020-08-13 21:11
related #9650

**Comment by patrickhulce** [comment] 2020-08-13 21:12
Great! I'm going to go ahead and close this issue then, but feel free to chime in if it continues to be problematic.

**Closed by patrickhulce** 2020-08-13 21:12 UTC
Labels: needs-more-info, needs-priority
