### ISSUE TITLE
v2.9.0 fails to trace on any site with a redirect

### ISSUE THREAD

**Issue by lastobelus** [GoogleChrome/lighthouse#4499] opened 2018-02-10 00:59 UTC
For example `lighthouse https://www.google.com` in Canada, all performance metrics have the error `Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_TRACING_STARTED)`

Downgrading to v2.8.0 fixes the issue

In my case, it is cumbersome to avoid the initial redirect, as I'm profiling changes to a shopify theme -- their mechanism for previewing themes other than the current live one is you pass a query param with the id of the theme and they set a cookie and redirect, and serve subsequent requests from the theme id stored in the cookie.

**Comment by eskimoblood** [comment] 2018-02-10 20:49
Have the same problem but without redirects, downgrading also solve the problem.

**Comment by patrickhulce** [comment] 2018-02-12 17:16
Oh yikes! Thanks for the report @lastobelus! 

@paulirish and I investigated and think its due to #4310

**Comment by paulirish** [comment] 2018-02-12 18:35
@lastobelus huge thanks for reporting this. and diagnosing it correctly as all redirected URLs. 

we'll get a fix out later today.

----

before relanding #4310 we'll need to make sure we have smoketest coverage for redirects and perf metrics.

**Comment by paulirish** [comment] 2018-02-14 18:11
fixed with 2.9.1

**Closed by paulirish** 2018-02-14 18:11 UTC
Labels: P0, bug

**Comment by markgoho-EDT** [comment] 2018-04-22 14:27
I'm currently experiencing this same issue with an SSO redirect. Should I open a new issue?

**Comment by patrickhulce** [comment] 2018-04-23 18:14
@markgoho-EDT if you're experiencing this on 2.9.1 or later, yes please file a new issue with repro steps as it's a different root cause :)
