### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by shahraship** [GoogleChrome/lighthouse#2340] opened 2017-05-23 15:51 UTC
**Lighthouse Version**: 2.0.0
**Chrome Version**: 58.0.3029.110
**URL**: ***
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11604:25)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by stramel** [comment] 2017-05-23 15:51
Dupe of #1091

**Closed** 2017-05-23 15:57 UTC
