### ISSUE TITLE
Lighthouse reports scripts from installed extensions are issues 

### ISSUE THREAD

**Issue by icantrank** [GoogleChrome/lighthouse#5834] opened 2018-08-14 11:51 UTC
#### Provide the steps to reproduce
1. Run LH on any URL with extensions installed to browsert

#### What is the current behavior?
Lighthouse reports that scripts from installed extensions are an issue and are taking too much time to parse etc, this is not reflective of issues on the site.

#### What is the expected behavior?
Lighthouse to report on issues with the site, and not with browser extensions I have chose to install.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 3.0.0 beta 0
* Node.js version: Not installed, maybe whatever ships with chrome?
* Operating System: Win 10

**Comment by adam-buckley** [comment] 2018-08-14 23:43
Duplicate here #5792

**Comment by wardpeet** [comment] 2018-08-16 13:56
thanks for reporting but as @adam-buckley said it's a duplicate of #5792. You can join the discussion there. I'm closing this one.

**Closed by wardpeet** 2018-08-16 13:56 UTC
Labels: duplicate
