### ISSUE TITLE
No SEO result with Lighthouse 10.1.0 on PageSpeed Insights or Speedlify

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/lighthouse#14972] opened 2023-04-14 17:39 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://nicolas-hoizey.photo

### What happened?

When running PageSpeed Insights on this URL, the report gives "?" on the SEO score, with 2 errors I can't understand:

- `Document has a valid hreflang - Error!`: there is no `hreflang`, why is there this error?
- `Document has a valid rel=canonical Error!`: there is a valid canonical (`<link rel="canonical" href="https://nicolas-hoizey.photo/" itemprop="url">`) 

Here's the test link:
https://pagespeed.web.dev/analysis/https-nicolas-hoizey-photo/l5ikzj2a4m?form_factor=mobile

@zachleat also got a `0` score for SEO for my URL when testing the site with Lighthouse v10.1 (used by https://github.com/zachleat/speedlify ): https://fosstodon.org/@nhoizey@mamot.fr/110192687979273818

### What did you expect?

The SEO score should have been `100`, as in recent tests with previous Lighthouse versions: https://www.11ty.dev/speedlify/nicolas-hoizey-photo/

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

10.1.0

**Comment by adamraine** [comment] 2023-04-14 18:09
This looks like a dupe of https://github.com/GoogleChrome/lighthouse/issues/14934

**Closed by adamraine** 2023-04-14 18:09 UTC
Labels: bug

**Comment by nhoizey** [comment] 2023-04-14 19:16
Oh, sorry, I didn't find it!
