### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by arnav-aggarwal** [GoogleChrome/lighthouse#2365] opened 2017-05-25 18:06 UTC
**Chrome Version**: 60.0.3107.4
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@ffa07b070c2b1dc5dd7c22bc8694f497bee5d538/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>```

**Comment by patrickhulce** [comment] 2017-05-25 20:00
dupe of #1091

**Closed by patrickhulce** 2017-05-25 20:00 UTC
