### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by sankre** [GoogleChrome/lighthouse#8122] opened 2019-04-10 04:13 UTC
**Initial URL**: https://www.akabou-tsubasa.com/
**Chrome Version**: 73.0.3683.103
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:85:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:494:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:182:241)
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:221:381)
    at async Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:214:126)
```

**Comment by paulirish** [comment] 2019-06-25 20:06
dupe of #4330

**Closed** 2019-06-25 22:04 UTC
Labels: needs-priority
