### ISSUE TITLE
NO_SCREENSHOTS error with performance Score 0

### ISSUE THREAD

**Issue by svkrclg** [GoogleChrome/lighthouse#11537] opened 2020-10-08 16:27 UTC
I was trying to run a lighthouse in a remote machine using SSH. I installed lighthouse and Chrome binaries.
But due to some reason, it is giving me performance score 0 and some exception in logs related to screenshot and speedindex.
**I tried both in headless and normal mode.**
Lighthouse Conf: 
```
  const path = "/Applications/GoogleChrome85.app/Contents/MacOS/Google Chrome";
 const chrome = await chromeLauncher.launch({chromeFlag:['--headless', '--disable-gpu'], chromePath : path});
 const options = {logLevel: 'verbose', output: 'json', onlyCategories: ['performance'], port: chrome.port};
```
Error in logs

```
  status Connecting to browser +0ms
  status Resetting state with about:blank +10s
  status Benchmarking machine +33ms
  status Initializing… +1s
  status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, ImageElements, LinkElements, ScriptElements, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint, TraceElements, SourceMaps +16ms
  status Resetting state with about:blank +0ms
  status Setting up network for the pass trace +15ms
  status Cleaning browser cache +2ms
  status Beginning devtoolsLog and trace +35ms
  status Loading page & waiting for onload +59ms
  status Gathering in-page: CSSUsage +7s
  status Gathering in-page: JsUsage +0ms
  status Gathering in-page: ViewportDimensions +0ms
  status Gathering in-page: ConsoleMessages +0ms
  status Gathering in-page: ImageElements +1ms
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: ScriptElements +0ms
  status Gathering in-page: DOMStats +0ms
  status Gathering in-page: OptimizedImages +0ms
  status Gathering in-page: ResponseCompression +0ms
  status Gathering in-page: TagsBlockingFirstPaint +0ms
  status Gathering in-page: TraceElements +0ms
  status Gathering in-page: SourceMaps +0ms
  status Gathering trace +0ms
  status Gathering devtoolsLog & network records +620ms
  status Gathering: CSSUsage +11ms
  status Gathering: JsUsage +157ms
  status Gathering: ViewportDimensions +64ms
  status Gathering: ConsoleMessages +10ms
  status Gathering: ImageElements +6ms
  status Gathering: LinkElements +9ms
  status Gathering: ScriptElements +10ms
  status Gathering: DOMStats +69ms
  status Gathering: OptimizedImages +11ms
  status Gathering: ResponseCompression +2ms
  status Gathering: TagsBlockingFirstPaint +2ms
  status Gathering: TraceElements +4ms
  status Gathering: SourceMaps +55ms
  status Disconnecting from browser... +2s
  status Analyzing and running audits... +33ms
  status Auditing: First Contentful Paint +11ms
  status Auditing: Largest Contentful Paint +67ms
  status Auditing: First Meaningful Paint +5ms
  status Auditing: Speed Index +2ms
  speed-index:warn Caught exception: NO_SCREENSHOTS +6ms
  status Auditing: Screenshot Thumbnails +0ms
  screenshot-thumbnails:warn Caught exception: NO_SCREENSHOTS +1ms
  status Auditing: Final Screenshot +0ms
  final-screenshot:warn Caught exception: NO_SCREENSHOTS +2ms
  status Auditing: Estimated Input Latency +0ms
  status Auditing: Total Blocking Time +4ms
  status Auditing: Max Potential First Input Delay +11ms
  status Auditing: Cumulative Layout Shift +4ms
  status Auditing: Initial server response time was short +3ms
  status Auditing: First CPU Idle +1ms
  status Auditing: Time to Interactive +5ms
  status Auditing: User Timing marks and measures +1ms
  status Auditing: Avoid chaining critical requests +2ms
  status Auditing: Avoid multiple page redirects +2ms
  status Auditing: Minimizes main-thread work +1ms
  status Auditing: JavaScript execution time +4ms
  status Auditing: Preload key requests +1ms
  status Auditing: Preconnect to required origins +2ms
  status Auditing: All text remains visible during webfont loads +1ms
  status Auditing: Diagnostics +2ms
  status Auditing: Network Requests +0ms
  status Auditing: Network Round Trip Times +1ms
  status Auditing: Server Backend Latencies +1ms
  status Auditing: Tasks +1ms
  status Auditing: Metrics +1ms
  metrics:warn Caught exception: NO_SCREENSHOTS +0ms
  status Auditing: Performance budget +1ms
  status Auditing: Timing budget +2ms
  timing-budget:warn Caught exception: NO_SCREENSHOTS +0ms
  status Auditing: Keep request counts low and transfer sizes small +1ms
  status Auditing: Minimize third-party usage +1ms
  status Auditing: Largest Contentful Paint element +1ms
  status Auditing: Avoid large layout shifts +1ms
  status Auditing: Avoid long main-thread tasks +1ms
  status Auditing: Avoid non-composited animations +2ms
  status Auditing: Avoids large JavaScript libraries with smaller alternatives +1ms
  status Auditing: Uses efficient cache policy on static assets +1ms
  status Auditing: Avoids enormous network payloads +2ms
  status Auditing: Defer offscreen images +2ms
  status Auditing: Eliminate render-blocking resources +3ms
  status Auditing: Minify CSS +3ms
  status Auditing: Minify JavaScript +8ms
  status Auditing: Remove unused CSS +111ms
  status Auditing: Remove unused JavaScript +3ms
  status Auditing: Serve images in next-gen formats +42ms
  status Auditing: Efficiently encode images +3ms
  status Auditing: Enable text compression +2ms
  status Auditing: Properly size images +3ms
  status Auditing: Use video formats for animated content +5ms
  status Auditing: Remove duplicate modules in JavaScript bundles +4ms
  status Auditing: Avoid serving legacy JavaScript to modern browsers +4ms
  status Auditing: Avoids an excessive DOM size +245ms
  status Auditing: Avoids `document.write()` +4ms
  status Auditing: Use HTTP/2 +0ms
  status Auditing: Uses passive listeners to improve scrolling performance +3ms
  status Generating results... +0ms
Report is done for https://twitter.com/
Performance score was 0
```
Configuration:
Lighthouse running node: Node module
Lighthouse Version: 6.3.0
Plaftorm: OSX Catalina
Node version: 10.13

Thanks in advance

**Comment by patrickhulce** [comment] 2020-10-08 17:07
Thanks for filing @svkrclg! This error comes straight from Chromium that screenshots were missing from the trace and happens for unknown reasons from time to time. To our knowledge, there's nothing that can be done about it on the Lighthouse side other than run it again (which usually fixes the problem, most Lighthouse integrations rerun up to 3 times before considering a failure).

**Comment by svkrclg** [comment] 2020-10-09 06:39
I tried to run it multiple times but it failed. So basically the issue is at chromium level in getting a screenshot (or any visually related metrics) through command line right?

**Comment by patrickhulce** [comment] 2020-10-09 14:53
> So basically the issue is at chromium level in getting a screenshot (or any visually related metrics) through command line right?

Correct. If you can actually reproduce this in a specific environment (this command works just fine 10/10 times on twitter.com in our infra and locally for me), then you could consider filing the missing screenshots issue at http://crbug.com/ with complete information to reproduce.

**Comment by patrickhulce** [comment] 2020-10-27 21:37
We're closing this out but the course of action described in https://github.com/GoogleChrome/lighthouse/issues/11537#issuecomment-706228332 still applies if it's reproducible I'm sure Chromium devs would appreciate a clear test case :)

**Closed by patrickhulce** 2020-10-27 21:37 UTC
Labels: needs-priority, pending-close

**Comment by ACAHNN** [comment] 2021-03-16 02:28
In case this is helpful for anyone. I was having this issue when driving lighthouse via puppeteer. What fixed it for me was removing an argument that is passed to chromium. Specifically, I was using the --single-process flag. Commenting this out did the trick for me.

[code]
```
await puppeteer.launch({
	    ignoreHTTPSErrors: true,
	    headless: true,
	    args: [//'--single-process',
		   '--no-zygote',
		   '--no-sandbox',
		  ]
	});
```

[configuration]
lighthouse: 7.2.0
puppeteer: 8.0.0
platform(s): macOS Big Sur (local), Ubuntu 20.04 (remote EC2 instance)

**Comment by svenbluege** [comment] 2021-04-29 12:03
Might be just a coincidence, but I fixed the NO_SCREENSHOTS and the resulting missing speedindex issue for me with setting the output to HTML. 

`const options = {logLevel: 'verbose', output: 'html', onlyCategories: ['performance'], port: chrome.port};`

To me, this output format does not matter since you can access the JSON data anyway, but to the magic software below it might make a difference.

**Comment by patrickhulce** [comment] 2021-04-29 14:14
@svenbluege that one is just a coincidence ;) `output: 'html'` only affects what Lighthouse does with results after it gets it back from Chrome, so nothing changed about the screenshot collection process by changing that setting. In general, this error is flaky and we have yet to find an actual reproducible case to file with Chromium.

@ACAHNN 's finding about `--single-process` *might* be related because it does actually change something in Chromium, but it's also possible it was just a flake.

**Comment by jasclarke24** [comment] 2021-10-04 20:06
https://github.com/GoogleChrome/lighthouse/issues/11537#issuecomment-799895027 This --single-process also fixed my issue with screenshots using puppeteer in WLS2/Docker

**Comment by Cokeeeeman** [comment] 2022-05-05 17:57
> @svenbluege that one is just a coincidence ;) `output: 'html'` only affects what Lighthouse does with results after it gets it back from Chrome, so nothing changed about the screenshot collection process by changing that setting. In general, this error is flaky and we have yet to find an actual reproducible case to file with Chromium.
> 
> @ACAHNN 's finding about `--single-process` _might_ be related because it does actually change something in Chromium, but it's also possible it was just a flake.

Seems like `--single-process` is flaky. It doesn't work for me all the time.
