### ISSUE TITLE
Proposal: Add ability to audit 404 pages

### ISSUE THREAD

**Issue by Nooshu** [GoogleChrome/lighthouse#11319] opened 2020-08-26 00:43 UTC
**Feature request summary**
The potential for a '404' mode, maybe a way to force the collection of data for 404 pages. More than happy to help out with this where I am able.

**What is the motivation or use case for changing this?**
At the moment the web performance community has very few ways to actually evaluate / monitor the web performance of 404 pages. Automated services built on both WebPageTest and Lighthouse struggle to collect data because the underlying tools simply abort when a 404 page is encountered. But the size of a 404 page can be really important, especially when requests are being made by a browser and failing without a user even knowing about them (`favicon.ico` is the most common). I've written a blog post with some data from the HTTP Archive [here](https://nooshu.github.io/blog/2020/08/25/you-should-be-testing-your-404-pages-web-performance/) which details a lot of my thoughts all about this issue. 

There is now a way to force WebPageTest to gather 404 page data off the back of [this issue I raised](https://github.com/WPO-Foundation/wptagent/issues/349). It works but it feels like a bit of a workaround.

I'd love for automated monitoring tools built on Lighthouse to have the ability to continuously monitor a sites 404 page, to minimise their impact on users. There's a somewhat related issue already [open here](https://github.com/GoogleChrome/lighthouse/issues/10402), but only related to 404's off the favicon.

**How is this beneficial to Lighthouse?**
As far as I'm aware there are no other synthetic web performance tools that allow you to audit a 404 page (other than the workaround for WebPageTest). Giving Lighthouse the ability to do this will add functionality that no other tools can complete at the moment (as far as I'm aware).

**Comment by stewartmedia-nyoung** [comment] 2020-12-16 23:16
Just would like to add another benefit that I see to including this functionality: 404 pages are typically the barebones template of a website with very few, if any, additional resources needed to be loaded. Auditing these pages would allow us to see and fix performance issues that are likely present site-wide.

**Comment by paulirish** [comment] 2021-03-15 21:49
closing this as a dupe of #10493

**Closed by paulirish** 2021-03-15 21:49 UTC
Labels: needs-discussion, needs-priority
