### ISSUE TITLE
Fails on page with prerender resource hint.

### ISSUE THREAD

**Issue by jdalton** [GoogleChrome/lighthouse#1335] opened 2016-12-28 05:17 UTC
When I try to run the lighthouse extension on https://lodash.com/ I get the following error:
> You probably have multiple tabs open to the same origin. Close the other tabs to use Lighthouse.

If I run it on https://lodash.com/docs/4.17.3 it works. I think the difference is that https://lodash.com/ has a prerender resource hint for the docs page and since prerender uses a hidden tab it's triggering some fail.

**Comment by patrickhulce** [comment] 2016-12-29 00:55
Hm this is interesting I can reproduce with the extension but not the CLI. So must be handled differently.

**Comment by patrickhulce** [comment] 2017-01-04 22:49
Can confirm adding a service worker and prerender hint to any page reliably produces this behavior. CLI workaround seems to be because the clean profile and lack of preregistered service worker avoids the multiple controlled clients issue.

**Comment by wardpeet** [comment] 2019-09-03 17:24
I have a feeling that this got fixed along the way. I can't seem to reproduce this in cli nor extension.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion.

**Closed by wardpeet** 2019-09-03 17:24 UTC
Labels: P3, bug
