### ISSUE TITLE
Lighthouse not taking mobile site version for auditing

### ISSUE THREAD

**Issue by sunrahul8** [GoogleChrome/lighthouse#9630] opened 2019-08-31 17:02 UTC
Open Chrome (mac: Version 76.0.3809.132 (Official Build) (64-bit)) and using developer tool, open m.snapdeal.com (mobile site).
Go to Audit and select deviceType as mobile and click run audit.

Expected - Auditing should be of current site which m.snapdeal.com
Actual - It audits www.snapdeal.com which is desktop version

**Comment by patrickhulce** [comment] 2019-08-31 17:20
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/9476, fixed in Chrome 77 and you can use Chrome Canary as an immediate workaround.

**Closed by patrickhulce** 2019-08-31 17:20 UTC
