### ISSUE TITLE
--chrome-flags user-agent not overriding default

### ISSUE THREAD

**Issue by merj** [GoogleChrome/lighthouse#5562] opened 2018-06-26 20:01 UTC
Running lighthouse version 2.9.4.

#### Provide the steps to reproduce
1. Run `lighthouse` on any local server or domain with logging access setup.

```
lighthouse --chrome-flags="--user-agent=Custom" https://example.com
lighthouse --chrome-flags="--user-agent='Custom'" https://example.com
lighthouse --chrome-flags="--user-agent=\"Custom\"" https://example.com
```

View the access logs on the server and take note of the user-agent column.

#### What is the current behavior?
Showing the Chrome default user-agent in the access log

```
XXX.XXX.XXX.XXX - - [26/Jun/2018:20:53:46 +0100] "GET / HTTP/2.0" 200 6772 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36(KHTML, like Gecko) Chrome/66.0.3359.30 Mobile Safari/537.36"
```

#### What is the expected behavior?
Expecting to see the custom user-agent in the access log.

```
XXX.XXX.XXX.XXX - - [26/Jun/2018:20:53:46 +0100] "GET / HTTP/2.0" 200 6772 "-" "Custom"
```

**Related issues**
[Overriding user agent using --chrome-flags adds additional quotes to user agent ](https://github.com/GoogleChrome/lighthouse/issues/3744)

**Comment by patrickhulce** [comment] 2018-06-26 20:11
Duplicate of #5406, mobile emulation implies setting the user agent to that of a mobile device. You'll need to use `--disable-mobile-emulation` or set the user agent via puppeteer instead of chrome flag.

I believe #5406 ended on an open call for docs on this fact, so if you have ideas, contributions welcome :)

**Closed by patrickhulce** 2018-06-26 20:12 UTC
