### ISSUE TITLE
manifest does not contain a suitable icon

### ISSUE THREAD

**Issue by peterpeterparker** [GoogleChrome/lighthouse#12677] opened 2021-06-19 12:23 UTC
#### Provide the steps to reproduce
1. Run LH on https://tietracker.com
  
#### What is the current behavior?

Lighthouse displays following error regarding the manifest:

> Manifest does not contain a suitable icon - PNG, SVG or WebP format of at least 144 px is required, the sizes attribute must be set, and the purpose attribute, if set, must include "any" or "maskable".

> No supplied icon is at least 144 px square in PNG, SVG or WebP format

[Manifest](https://tietracker.com/manifest.webmanifest) which looks like following and does seem to match expected above description:

```
{
  "name": "Tie Tracker",
  "short_name": "Tie Tracker",
  "icons": [
    {
      "purpose": "maskable",
      "src": "/assets/favicon/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "purpose": "maskable",
      "src": "/assets/favicon/android-chrome-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/",
  "display": "standalone",
  "theme_color": "#230f29",
  "background_color": "#ffffff"
}
```

#### What is the expected behavior?

Either it is an error and the icons of the manifest should be recognized as valid or, the description should be improved to display what's missing.

#### Environment Information
* Chrome version: v91

#### Screenshot

<img width="1171" alt="Capture d’écran 2021-06-19 à 14 21 24" src="https://user-images.githubusercontent.com/16886711/122642237-a51d3e00-d109-11eb-9f5a-bf1fe567a64c.png">

**Comment by adamraine** [comment] 2021-06-21 17:00
Hmm, I think this is an issue with our description. According to the Chrome applications panel, the problem is that ALL your icons have purpose "maskable":

<img width="922" alt="Screen Shot 2021-06-21 at 12 55 36 PM" src="https://user-images.githubusercontent.com/6752989/122799650-fbb48480-d28f-11eb-9ba9-b642b03e8fdd.png">

However, the Lighthouse description indicates this setup would be valid:

<img width="685" alt="Screen Shot 2021-06-21 at 12 57 11 PM" src="https://user-images.githubusercontent.com/6752989/122799820-33bbc780-d290-11eb-8c62-908f9e548cbf.png">

We should update our descriptions to match the Chrome applications panel.

**Comment by peterpeterparker** [comment] 2021-06-21 17:06
Thanks for the answer, I get it now.

Shouldn't be the opposite the correct way to go? Chrome shouldn't be able to accept "maskable" and not only "any" or unset?

**Comment by adamraine** [comment] 2021-06-21 18:51
So the messages in the applications panel are a bit misleading. You can set an icon purpose to `"any maskable"` and have it pass the checks. I have filed upstream about it:

https://bugs.chromium.org/p/chromium/issues/detail?id=1222359

**Comment by peterpeterparker** [comment] 2021-06-21 19:16
that did the trick for the time being, thx @adamraine 🙏

**Comment by adamraine** [comment] 2021-06-25 15:43
So setting the pattern of `"any maskable"` is *discouraged* but not *required*. Unfortunatley, the difference between "must not" and "should not" is a bit subtle in the applications panel message.

The Lighthouse message is now correct, but we removed the part discouraging `"any maskable"` https://github.com/GoogleChrome/lighthouse/pull/12678#discussion_r655596372.

gelnrob@ is open to changing the message, so we can reevaluate what we want to include if that happens.

**Comment by phoglenix** [comment] 2021-07-16 05:08
The issue (see chromium bug linked above) is now fixed at head. It should appear in Chrome 93.
I split the message into two separate warnings (one for "you only have `maskable` icons", one for "avoid having `any maskable` icons")

**Comment by adamraine** [comment] 2021-07-19 15:43
Thanks @phoglenix! The changes to the DT string are the same as we made here, so we can close this.

**Closed by adamraine** 2021-07-19 15:43 UTC
Labels: P2, upstream-action-required
