### ISSUE TITLE
Performance, PWA check broken

### ISSUE THREAD

**Issue by BO41** [GoogleChrome/lighthouse#6185] opened 2018-10-06 14:49 UTC
#### Provide the steps to reproduce
1. Run LH on any URL

#### What is the current behavior?

Performance score ?
PWA score ?

All tests fail: Error!

#### What is the expected behavior?

Test should run

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: Generated by Lighthouse 3.2.1  and some versions before
* Operating System: Linux

**Comment by patrickhulce** [comment] 2018-10-06 19:59
Thanks for reporting @BO41! Seems like a duplicate of #6154, extension currently seems to be broken on Linux :/

**Closed by patrickhulce** 2018-10-06 19:59 UTC
