### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by the7oker** [GoogleChrome/lighthouse#2419] opened 2017-06-01 22:50 UTC
**Initial URL**: http://dev/pakabone2/
**Chrome Version**: 61.0.3117.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@0924893aff1ceb991c789862db5ecff6802330c1/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-01 22:52
dupe of #1091

**Closed by patrickhulce** 2017-06-01 22:52 UTC
