### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by petethumped** [GoogleChrome/lighthouse#2738] opened 2017-07-25 23:01 UTC
**Initial URL**: https://thumped.com/movies/movie-reviews/dunkirk/
**Chrome Version**: 60.0.3112.78
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-08-18 21:40
dupe of #1733

**Closed by patrickhulce** 2017-08-18 21:40 UTC
