### ISSUE TITLE
Device radio buttons show incorrect tool-tips

### ISSUE THREAD

**Issue by simonmurdock** [GoogleChrome/lighthouse#10819] opened 2020-05-20 11:28 UTC
1. Open LH pane in chrome

2. Hover Desktop radio button under device
![image](https://user-images.githubusercontent.com/5403478/82440825-dd7cc380-9a94-11ea-8bbb-e467fbc773b3.png)
![image](https://user-images.githubusercontent.com/5403478/82440921-056c2700-9a95-11ea-9f84-982313d71fea.png)

#### What is the current behavior?
It seems to be showing the mobile tool-tip:
#### What is the expected behavior?
It should show the desktop specific tool-tip:

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: chrome dev tools
* Chrome version: 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)
* Node.js version:N/A
* Operating System: Windows 10

**Comment by patrickhulce** [comment] 2020-05-20 14:36
Thanks for filing @simonmurdock! This is a duplicate of https://github.com/GoogleChrome/lighthouse/issues/5747 so we'll close it for that one.

Explanation:

> the tooltip is for the entire radio set, so the whole input element controls whether to "Apply mobile emulation during auditing"

**Closed by patrickhulce** 2020-05-20 14:36 UTC
Labels: needs-priority
