### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by hlbhariom** [GoogleChrome/lighthouse#969] opened 2016-11-18 13:30 UTC
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: aggregations: expected audit results not found under audit name redirects-http
**Stack Trace**:
 ```Error: aggregations: expected audit results not found under audit name redirects-http
    at expectedNames.forEach.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5535:17)
    at Array.forEach (native)
    at items.map.item (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5519:21)
    at Array.map (native)
    at Function.compare (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5503:18)
    at Function.aggregate (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5577:24)
    at config.aggregations.map.a (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10985:65)
    at Array.map (native)
    at run.then.auditResults (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10985:46)```

**Comment by wardpeet** [comment] 2016-11-18 19:28
Reproduce when you don't select Network connection is secure

Looks like it's related to #921

**Comment by brendankenny** [comment] 2016-11-18 21:23
definitely #921. Closing in favor of that one.

**Closed by brendankenny** 2016-11-18 21:23 UTC
Labels: duplicate, extension
