### ISSUE TITLE
Image no explicit width/height on SVG with dimensions

### ISSUE THREAD

**Issue by BernardA** [GoogleChrome/lighthouse#11631] opened 2020-11-05 17:36 UTC
#### Provide the steps to reproduce
1. Run LH on https://quiamo-client.vercel.app/

See this https://www.webpagetest.org/result/201105_DiRY_c6737940edb79c8e59f605ae6c6b577c/
  

#### What is the current behavior?

![Screenshot 2020-11-05 at 17 04 52](https://user-images.githubusercontent.com/9449665/98275254-c07d7380-1f94-11eb-8c43-c87aa2a23e28.png)

#### What is the expected behavior?
It should work fine as the SVG actually has dimensions. 
To put this into context, the markup in question is the result of the new Next.js `Image` component that , as you may be aware, was developed with collaboration with your team. 
See the docs at https://nextjs.org/docs/basic-features/image-optimization

This is the Next.js/React markup:

                          <Image
                            src="/images/main-logo.png"
                            alt="quiamo logo"
                            className={classes.branding}
                            width="180"
                            height="60"
                            loading="eager"
                            priority
                        />

And the corresponding HTML:

![Screenshot 2020-11-05 at 17 24 12](https://user-images.githubusercontent.com/9449665/98275547-089c9600-1f95-11eb-96cc-48403b183cbe.png)

#### Environment Information
* Affected Channels: webpagetest.org
* Lighthouse version: as per webpagatest.org
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment] 2020-11-05 21:40
Thanks for filing @BernardA!

I'm not sure how we're going to handle this. In practice this particular data SVG will never cause a layout shift, but both SVGs and data URIs can cause layout shifts separately. 

Maybe we'll ignore non-network images with a SVG MIME type.

**Comment by paulirish** [comment] 2020-11-09 22:55
> Maybe we'll ignore non-network images with a SVG MIME type (potential problem what if SVG doesn't have dimensions, invalid, etc it will cause layout shift).

+1. Let's do this and comment it out. It's a compromise solution but works.

**Comment by spanicker** [comment] 2020-12-21 21:40
any ETA on a fix?

**Comment by patrickhulce** [comment] 2021-02-22 15:45
PR is up for this at #12120

**Comment by geisterfurz007** [comment] 2022-05-19 16:09
I might be missing something but is it possible that this may be back again in Lighthouse 9.3.0?

I have this image:

```html
<img style="display:block;max-width:100%;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0" alt="" aria-hidden="true" src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%27339%27%20height=%27221%27/%3e">
```

The decoded SVG is `"<svg xmlns='http://www.w3.org/2000/svg' version='1.1' width='339' height='221'/>"`

The image is part of the output of a next/image component as in the original issue.

Let me know if I can help debug this!

**Comment by styfle** [comment] 2022-05-19 16:29
I believe that was fixed in #13737

**Comment by adamraine** [comment] 2022-05-19 17:09
I reproduced this again on v9.6.1 but not master. Will investigate.

**Comment by adamraine** [comment] 2022-05-19 17:27
Oh yup @styfle was right I saw you linked to a PR and assumed it was https://github.com/GoogleChrome/lighthouse/pull/12120. All good here.

**Closed by adamraine** 2022-05-19 17:27 UTC
Labels: bug, P2, needs-investigation

**Comment by geisterfurz007** [comment] 2022-05-19 18:03
Awesome thanks a lot for the fast response and sorry for missing that PR in my research! Are there any plans as to when the fix will land in a stable version?

**Comment by rckm** [comment] 2022-06-09 14:12
Still waiting for fix 🙏🏻🙏🏻🙏🏻

**Comment by connorjclark** [comment] 2022-06-09 18:41
We have a `@next` nightly release on NPM.

**Comment by tobiasorosa** [comment] 2022-06-25 19:16
Pagespeed is still complaining about no explicit width and height, but this warning is about the empty svg "placeholder" next/image puts before the actual image.

Any way to work around this warning?

![image](https://user-images.githubusercontent.com/68042466/175787529-8ed8c5b5-bab9-44a4-85bd-b55d526a7eda.png)

**Comment by Exchangeico** [comment] 2022-06-25 19:24
Please help me fix my site and my admin panel is not login in because of some errors. thanks
--
Sent from myMail for Android Saturday, 25 June 2022, 08:16PM +01:00 from Tobias Rosa  ***@***.*** :

**Comment by styfle** [comment] 2022-08-10 13:52
@adamraine @connorjclark I would expect this fix (#12120 and #13737) to land before Lighthouse 10 since it can be considered a patch release (its a fix, not a breaking change).

There are [3 million](https://www.npmjs.com/package/next) weekly downloads of Next.js and `next/image` has been using this svg placeholder since since October 2020 when `next/image` was introduced.

This is extremely confusing to users because the error message says to use `next/image` even though the user is already using `next/image`. Here's a screenshot from https://web.dev

<img width="915" alt="image" src="https://user-images.githubusercontent.com/229881/183918186-eb2d27af-b040-49cb-a485-c3b2997f54ca.png">

Please release this fix as soon as possible, thanks!

**Comment by Yan-vibeit** [comment] 2022-08-15 10:39
Confirmed Lighthouse still reporting no size and height are explicit when they are indeed set. 15/08/22.

**Comment by SvenvtH** [comment] 2022-08-16 13:39
> Confirmed Lighthouse still reporting no size and height are explicit when they are indeed set. 15/08/22.

This happens when you try to test your dev version. Try building the site and after that starting the production build.
Then you should no longer have the issue with the height and width not being set.

**Comment by adamraine** [comment] 2022-08-16 20:45
This should be released in 9.6.6

**Comment by vicasas** [comment] 2022-09-10 14:42
This seems to be still a problem, I'm using the latest version of Chrome and the error still persists. (2022/09/10) https://github.com/vercel/next.js/issues/40417#issuecomment-1242743150

![image](https://user-images.githubusercontent.com/57921784/189488369-fb5c6237-948c-4391-8dbc-469da7ebf1b0.png)

**Comment by adamraine** [comment] 2022-09-12 17:43
Chrome M105 ships with Lighthouse version 9.6.2 in DevTools. This issue was fixed in Lighthouse version 9.6.6 which will be shipped with DevTools in M107.

In the meantime, you can use Chrome Canary or the CLI.

**Comment by lhguerra** [comment] 2022-10-20 14:33
![image](https://user-images.githubusercontent.com/4529663/196977674-85e80ded-705b-403d-ac4b-cd1d71385215.png)

I'm just wordless

**Comment by reiv** [comment] 2022-10-23 00:18
For those willing to make the jump -- `next/future/image` does not render any of the "offending" placeholder SVGs.
