### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by NoemiNahomy** [GoogleChrome/lighthouse#7955] opened 2019-04-03 16:33 UTC
**Initial URL**: https://elpais.bo/
**Chrome Version**: 73.0.3683.75
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:995:253)
```

**Comment by himdel** [comment] 2019-05-29 12:00
Same here:

**Initial URL**: http://localhost:3000/vm_infra/explorer#/
**Chrome Version**: 73.0.3683.75
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:995:253)
````

Using chromium - 73.0.3683.75-1 990
        990 http://ftp.cz.debian.org/debian buster/main amd64 Packages

**Comment by patrickhulce** [comment] 2019-05-29 13:42
Yes this is a duplicate of #7246. Debian's version of Chromium doesn't support Lighthouse, workaround is to use Chrome.

**Closed by patrickhulce** 2019-05-29 13:42 UTC
Labels: needs-priority
