### ISSUE TITLE
Fixed media sizes audit

### ISSUE THREAD

**Issue by samccone** [GoogleChrome/lighthouse#802] opened 2016-10-20 20:55 UTC
building off of the work done here
https://github.com/GoogleChrome/lighthouse/pull/511

> This looks at video, image, and SVG elements and ensures that they have width and height dimensions specified in their attributes or via the CSS rules that match to them.

**Comment by ebidel** [comment] 2016-10-20 21:00
DBW!

**Comment by paulirish** [comment] 2020-01-24 21:32
dupe of #10085

**Closed by paulirish** 2020-01-24 21:32 UTC
Labels: P2, needs-complete-audit-proposal, new_audit
