### ISSUE TITLE
DevTools Error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by josedabm** [GoogleChrome/lighthouse#6093] opened 2018-09-22 06:16 UTC
**Initial URL**: https://github.com/GoogleChrome/lighthouse/
**Chrome Version**: 69.0.3497.100
**Error Message**: Cannot read property 'value' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.result (chrome-devtools://devtools/remote/serve_file/@8920e690dd011895672947112477d10d5c8afb09/audits2_worker/audits2_worker_module.js:1008:211)
```

**Comment by exterkamp** [comment] 2018-09-24 15:57
This error is seemingly a duplicate of #6026.  I am closing it as such, but if the problem persists comment and we can reopen.  As always, any additional details of your run leading to this would be appreciated, like the method you used (devtools/extension/cli) run (default/perf only/etc.) and throttling method (simulated/none).  Thanks!

**Closed by exterkamp** 2018-09-24 15:57 UTC
