### ISSUE TITLE
Speed Index impacted by banner on the page

### ISSUE THREAD

**Issue by siteriaitaliana** [GoogleChrome/lighthouse#2607] opened 2017-06-28 08:23 UTC
Speed Index is impacted by the banner scrolling present on the page

**Comment by benschwarz** [comment] 2017-06-28 09:02
@siteriaitaliana Yep. Speed index is calculated by finding a point in time where the page appeared to be 'complete'. 

Animations often throw this metric off, and there isn't a lot that can be done about it pragmatically. (If you were able to disable your banner in certain contexts, you _might_ get more reliable metrics… )

Otherwise, perhaps you could consider using a metric like 'First contentful paint'. Which isn't a 'complete' phase of a user journey, but its definitely one that you could rely on.

**Comment by ebidel** [comment] 2017-06-28 17:32
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2514

**Closed by ebidel** 2017-06-28 17:32 UTC

**Comment by vanux** [comment] 2018-12-05 20:49
Is Speed Index also affected by a toast? We use a toast notification that is present when the page begins to load. with an animated spinner. Based on my calculation of Speed Index and comparing it to Lighthouse, I am finding that the Lighthouse score is really off by 5000ms or more.,

**Comment by patrickhulce** [comment] 2018-12-05 21:36
@vanux speed index will be affected by a toast, yes. By the nature of the metric, it will measure when the page reached its "final" state, if there's no final state because of an animation, then the metric won't have a lot of value.
