### ISSUE TITLE
example.com reports IDB usage

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11920] opened 2021-01-05 20:02 UTC
200 bytes of IDB usage.

![image](https://user-images.githubusercontent.com/39191/103693130-a4bf2b00-4f4d-11eb-99c1-5f70edea70b2.png)

and so the DevTools Lighthouse panel throws up that warning..  

![image](https://user-images.githubusercontent.com/39191/103693188-bb658200-4f4d-11eb-80cd-ca52ec0052d7.png)

but devtools doesnt report any IDB databases.. so the fact that it has quota used seems odd.  

Tested in ToT Chromium 89.0.4367.0

**Comment by adamraine** [comment] 2021-01-05 22:04
Seems like an issue with chromium where data is not properly deleted from IDB. Clicking "Clear site data" does not remove it. Looks like Chrome Dev is giving the same results as Canary but Chrome Beta and Stable are fine, I'll try a bisect.

If this is expected behavior, we could make a special case for IDB where we track the number of entries rather than the usage bytes:
https://chromedevtools.github.io/devtools-protocol/tot/IndexedDB/

**Comment by adamraine** [comment] 2021-01-05 23:59
Looks like this is our guy:
https://chromium-review.googlesource.com/c/chromium/src/+/2557571

Filed upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=1163336

**Comment by adamraine** [comment] 2021-04-05 21:36
Should be fixed upstream.

**Closed** 2021-04-06 18:03 UTC
Labels: DevTools, needs-priority, pending-close
