### ISSUE TITLE
Performance and PWA audits create an error when selected

### ISSUE THREAD

**Issue by henrihelvetica** [GoogleChrome/lighthouse#10558] opened 2020-04-08 04:52 UTC
#### Provide the steps to reproduce
1. Run LH on https://www.espn.com/
  
* Open DevTools in Canary 84.0.4107.0
* A clean profile with no extensions. 
* Proceed to Lighthouse panel to conduct an audit.
* Conduct any audit with either Performance and/or PWA categories selected.

  

#### What is the current behavior?
Any audit conducted with either the Performance and/or PWA categories selected throws an error very shortly after _warming up_. This applies to either the mobile or the desktop devices selected. 

#### What is the expected behavior?
The completion of an audit displaying the score(s). At current we get expected behaviour from:

* Chrome v81.0.4044.92 w/ Lighthouse v5.7.0
* Firefox Nightly v77.0a1 w/ Lighthouse extenion v5.6.0

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 5.7.1
* Chrome version: 84.0.4107.0 
* Node.js version: v10.15.3
* Operating System: macOS v10.14.6 (Build 18G95)

![Screen Shot 2020-04-07 at 23 49 24](https://user-images.githubusercontent.com/50970808/78745133-4834ce00-7931-11ea-8d05-b240b35c241d.png)
**Related issues**

**Comment by patrickhulce** [comment] 2020-04-08 15:52
Thanks for filing @henrihelvetica! :) 

I'm not able to reproduce this message on that URL. Note that this message appears typically when an internal race condition in Chrome prevents DevTools from tracing the page (as Lighthouse does when Performance or PWA category is required). Completely quitting Chrome and restarting typically fixes the problem.

**Comment by henrihelvetica** [comment] 2020-04-08 18:17
Thanks @patrickhulce. I did quit and tried a few more times last night. Did the same moments ago, quit and nothing has changed thus far. I originally took my inquiry to twitter to check and @addyosmani was apparently able to repro and recommended I file it. 

https://twitter.com/addyosmani/status/1247719297054474241

I tend to use espn.com as my test case, but I originally noticed this when doing a trace on https://maskmakers.club/ and after that failed, I then started to poke around. I'll keep investigating on my end. Thanks!

**Comment by patrickhulce** [comment] 2020-04-08 19:11
Hm interesting, I couldn't repro on maskmakers.club either, but I'll keep trying as well.

To confirm which specific error message is appearing you can also try opening DevTools *on DevTools* and check the console for log messages. To open DevTools on DevTools you can undock (Ctrl+P "undock") and inspect the DevTools window (Ctrl+Alt+I) which would help tremendously!

If it's the error I suspect (TRACING_ALREADY_STARTED) then it'd be expected once you see this error occur once on a URL it will continue occurring forever on *any* URL until Chrome has been fully shutdown. 

My best guess so far is that there's been a Chrome regression that makes this suddenly much much more common than it was before.

**Comment by patrickhulce** [comment] 2020-04-08 19:13
Related though:

I'm getting NO_SCREENSHOTS about 25% of the time in canary so that definitely supports this case of a recent regression in Chrome tracing.

![image](https://user-images.githubusercontent.com/2301202/78823871-10ff0500-79a3-11ea-9aee-74c486928a9b.png)

**Comment by paulirish** [comment] 2020-04-28 21:03
Closing as its suspected Tracing_already_start 

also opened https://github.com/GoogleChrome/lighthouse/issues/10659

**Closed by paulirish** 2020-04-28 21:03 UTC
Labels: needs-discussion, needs-more-info, needs-priority
