### ISSUE TITLE
DevTools Error: Cannot read property 'requestAnimationFrame' of null

### ISSUE THREAD

**Issue by DIGITALALEX88** [GoogleChrome/lighthouse#5570] opened 2018-06-27 09:36 UTC
**Initial URL**: https://biospheresrls.com/
**Chrome Version**: 67.0.3396.87
**Error Message**: Cannot read property 'requestAnimationFrame' of null
**Stack Trace**:
```
TypeError: Cannot read property 'requestAnimationFrame' of null
    at Emulation.InspectedPagePlaceholder.onResize (chrome-devtools://devtools/bundled/devtools_app.js:183:96)
    at Emulation.InspectedPagePlaceholder._notify (chrome-devtools://devtools/bundled/shell.js:1033:66)
    at Emulation.InspectedPagePlaceholder._processOnResize (chrome-devtools://devtools/bundled/shell.js:1032:13)
    at Emulation.DeviceModeWrapper._callOnVisibleChildren (chrome-devtools://devtools/bundled/shell.js:1023:8)
    at Emulation.DeviceModeWrapper._processOnResize (chrome-devtools://devtools/bundled/shell.js:1032:41)
    at UI.RootView._callOnVisibleChildren (chrome-devtools://devtools/bundled/shell.js:1023:8)
    at UI.RootView.doResize (chrome-devtools://devtools/bundled/shell.js:1078:6)
    at UI.RootView.doResize (chrome-devtools://devtools/bundled/shell.js:2172:7)
    at UI.RootView.doLayout (chrome-devtools://devtools/bundled/shell.js:1080:41)
    at UI.RootView.invalidateConstraints (chrome-devtools://devtools/bundled/shell.js:1108:6)
```

**Comment by wardpeet** [comment] 2018-06-27 19:11
@DIGITALALEX88 do you have any idea how to reproduce this bug? I couldn't reproduce it right away using chrome version 67.0.3396.99 (Official Build) (64-bit)

**Comment by brendankenny** [comment] 2018-08-10 18:30
closing for now. If you're still seeing this issue, please comment with more details and we can reopen!

**Closed by brendankenny** 2018-08-10 18:30 UTC
Labels: DevTools, bug, needs-investigation

**Comment by paulirish** [comment] 2020-12-21 22:42
duplicate of #5979
