### ISSUE TITLE
Color differences between foreground and background can be dead wrong.

### ISSUE THREAD

**Issue by brokentuskk** [GoogleChrome/lighthouse#13637] opened 2021-11-09 16:51 UTC
**Describe the bug**
In certain spectrums, the penalty for contrast is off.

**To Reproduce**
Use a color with a saturation of 100% and a brightness of around 75%. For example #bf4500, a dark orange. Then place white text on this color. This will fail, most likely due to the brightness of the background being too close to 100%. Black and gray text will pass. In fact the text can be almost completely illegible to the eye, but will pass the test. The highest contrast option possible fails. Stroking the white text in black further reduces the readability, but will also pass.

**Expected behavior**
Expect a pass due to apparent high contrast.

![contrast](https://user-images.githubusercontent.com/49072954/140968140-9075a7b7-e2bf-469b-ae9e-5b2f4db106ff.jpg)

**Comment by adamraine** [comment] 2022-02-07 19:47
I can't reproduce this. Lighthouse only flags the grey text as you expect. For reference I used:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <style>body {background-color: #bf4500;}</style>
  <h1 style="color: white">Text</h1>
  <h1 style="color: black">Text</h1>
  <h1 style="color: grey">Text</h1>
</body>
</html
```

@brokentuskk can you provide an example URL where this is happening?

**Comment by brokentuskk** [comment] 2022-02-07 20:20
I think someone fixed it. We would get dinged on the orange buttons at the bottom of this page every single time. It started passing the audit about a week or so ago.
All Things Barbecue - BBQ Supplies, Smokers, Patio Furniture, Spices & Grills


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
All Things Barbecue - BBQ Supplies, Smokers, Patio Furniture, Spices & G...

The best made smokers & grills, rubs & sauces, gear, outdoor furniture and gear for outdoor kitchens. Shop Ameri...
 |

 |

 |






    On Monday, February 7, 2022, 01:47:30 PM CST, Adam Raine ***@***.***> wrote:  
 
 


I can't reproduce this. Lighthouse only flags the grey text as you expect. For reference I used:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <style>body {background-color: #bf4500;}</style>
  <h1 style="color: white">Text</h1>
  <h1 style="color: black">Text</h1>
  <h1 style="color: grey">Text</h1>
</body>
</html
@brokentuskk can you provide an example URL where this is happening?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adamraine** [comment] 2022-02-07 20:22
Closing this for now

**Closed by adamraine** 2022-02-07 20:22 UTC
Labels: needs-more-info, P2
