### ISSUE TITLE
Lighthouse doesn't exclude Chrome extensions from audit

### ISSUE THREAD

**Issue by MonsieurLeSuisse** [GoogleChrome/lighthouse#6644] opened 2018-11-24 22:09 UTC
#### Provide the steps to reproduce
1. Install/activate Google Dictionary extension in Google Chrome
2. Open Chrome developer tools
3. Run LH on any url, run Audits (_Best Practices_ test is enough)
4. Check result in Best Practices section.
5. See warning "_Uses deprecated API's_" ... "_Element.createShadowRoot is deprecated and will be removed in ..._"
6. Hover over entry in URL column, it reveals: _chrome-extension://xyz/content.min.js_ which belongs to the Google Dictionary extension.

#### What is the current behavior?
LH processes all JS even that of chrome extensions. This falsifies the result of an website audit.

#### What is the expected behavior?
Lighthouse in Chrome Audits is used to check websites. Therefore it must avoid chrome extensions from being included in the audit.

#### Environment Information
* Affected Channels: Extension, DevTools 
* Lighthouse version: Lighthouse 3.0.3
* Operating System: Windows 10
* Chome: Version 70.0.3538.102 (Official Build) (64-Bit)

**Comment by patrickhulce** [comment] 2018-11-25 14:04
Thanks for filing @MonsieurLeSuisse! We consider this a duplicate of #4516, see more discussion in #5792.

**Closed by patrickhulce** 2018-11-25 14:04 UTC
