### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by sunilp** [GoogleChrome/lighthouse#2328] opened 2017-05-22 02:36 UTC
**Initial URL**: https://www.google.com.sg/?gfe_rd=cr
**Chrome Version**: 60.0.3106.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@205e7f909600e889fdb19e31669ef4a570b71391/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>```

**Comment by stramel** [comment] 2017-05-22 04:12
Dupe of #1091

**Comment by sunilp** [comment] 2017-05-22 13:33
yes found it to be similar.. #1091

**Closed** 2017-05-22 13:32 UTC

**Comment by wardpeet** [comment] 2017-05-22 13:39
we will try to fix it asap :)
