### ISSUE TITLE
Site always defaults to mobile version when measuring performance

### ISSUE THREAD

**Issue by mjara74** [GoogleChrome/lighthouse#2916] opened 2017-08-09 16:24 UTC
If you try to measure www.barnesandnoble.com with the lighthouse API, it always measures the performance for m.barnesandnoble.com which is the mobile site. I've tried this using the lighthouse chrome addin and with Chrome's debugging tool's "Audit" feature.

**Comment by patrickhulce** [comment] 2017-08-09 17:23
Thanks for raising this @mjara74. The extension and Audits panel are restricted to mobile emulation/evaluation currently. As a workaround you can use the CLI with the flags `--disable-network-throttling --disable-cpu-throttling --disable-mobile-emulation`

Duplicate of #2838

**Closed by patrickhulce** 2017-08-09 17:23 UTC

**Comment by ashoon** [comment] 2017-11-14 20:14
Hi @patrickhulce - what's the equivalent Node for desktop browsing - in my settings file I have 

module.exports = {
    headless: false,
    args: [
        '--remote-debugging-port=9222',
		'--disable-device-emulation',
		'--disable-network-throttling',
		'--disable-cpu-throttling'
    ]
};

yet when I run lighthouse it returns to the nexus 5x user-agent (and the mobile site version)

var report = await lighthouse (currentPage, settings, null);

**Comment by patrickhulce** [comment] 2017-11-15 00:48
@ashoon that `settings` object looks suspiciously like puppeteer options, not Lighthouse flags :)

you'd need to add `disableDeviceEmulation: true` to your LH flags/settings object to browse as desktop

**Comment by FedericoBiccheddu** [comment] 2021-09-20 16:26
As a @patrickhulce suggests the CLI options are:
 `--disable-network-throttling --disable-cpu-throttling --disable-device-emulation`. 

Just be careful, it is `--disable-device-emulation` not `--disable-mobile-emulation`.

**Comment by olowoseun** [comment] 2025-08-10 08:01
Passing the option --preset=desktop works for me.
