### ISSUE TITLE
Extension Error: Protocol error (Tracing.end): Either tab id or extension id 

### ISSUE THREAD

**Issue by quoccuong1904** [GoogleChrome/lighthouse#4347] opened 2018-01-25 09:34 UTC
**Lighthouse Version**: 2.8.0
**Lighthouse Commit**: 16133efb31b286acfd14cbbe86558577c605dad6
**Chrome Version**: 63.0.3239.132
**Initial URL**: http://bdsnamsaigon.vn/
**Error Message**: Protocol error (Tracing.end): Either tab id or extension id must be specified.
**Stack Trace**:
```
Error: Protocol error (Tracing.end): Either tab id or extension id must be specified.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:13763:15)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by kdzwinel** [comment] 2018-01-25 12:43
Looks like a duplicate of https://github.com/GoogleChrome/lighthouse/issues/4216

**Closed** 2018-01-25 23:05 UTC
Labels: duplicate
