### ISSUE TITLE
lighthouse https://airhorner.com/

### ISSUE THREAD

**Issue by zhaoxi521** [GoogleChrome/lighthouse#1819] opened 2017-03-06 06:33 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 56.0.2924.87
**URL**: https://github.com/GoogleChrome/lighthouse
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13600:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14685:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14711:18)```

**Comment by ebidel** [comment] 2017-04-01 01:02
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-04-01 01:02 UTC
