### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by loneken79** [GoogleChrome/lighthouse#2500] opened 2017-06-14 05:10 UTC
This happens when testing a local preactjs site.
With preact when serving in production mode from localhost an "http" request gives a TLS handshake error. It seems to make the lighthouse test crash.

**Initial URL**: https://127.0.0.1:8080/
**Chrome Version**: 60.0.3112.24
**Error Message**: Unable to load the page: net::ERR_CONNECTION_RESET
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_CONNECTION_RESET
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@16a564bd7c034b8f6e008d0887fc46c7aae48488/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@16a564bd7c034b8f6e008d0887fc46c7aae48488/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by wardpeet** [comment] 2017-07-28 13:34
thanks @loneken79 ! Are you willing to provide the live URL you were testing on and what you observed?

**Comment by patrickhulce** [comment] 2017-07-28 16:53
ah yeah thanks for the report @loneken79 this is a dupe of #1978 but good to know we can expect this signature from DevTools reports!

**Closed by patrickhulce** 2017-07-28 16:53 UTC
Labels: duplicate
