### ISSUE TITLE
Switch DevTools to use emulatedFormFactor for Desktop testing

### ISSUE THREAD

**Issue by halilozanyilmaz** [GoogleChrome/lighthouse#8967] opened 2019-05-16 00:48 UTC
Version: (Please someone P.S me how to find the version of lighhouse. I use chrome audit section)

#### Provide the steps to reproduce
1. Run LH SEO test on the following page:  tisort.ist/buyuk-beden-tisort/ 

#### What is the current behavior?
Gives this message: 
Tap targets are not sized appropriately
62% appropriately sized tap targets
Interactive elements like buttons and links should be large enough (48x48px), and have enough space around them, to be easy enough to tap without overlapping onto other elements. Learn more.

#### What is the expected behavior?
Pass the audit

I don't understand why it gives this message: Here is the screenshot. I am highlighing one of the links that lighhouse compailing about.

**Edit:** I realized that it is doing this on "Desktop" test. Which caused me to be confused. Why would it be testing mobile requirements when "desktop" test is selected?

![image](https://user-images.githubusercontent.com/25062864/57818601-4304e880-778d-11e9-80d6-09afc6d031f7.png)

**Comment by patrickhulce** [comment] 2019-05-16 00:56
Thanks for filing @halilozanyilmaz!

I wonder if we should reword our audit description to be less mobile-only focused if the size of clickable targets is still a UX concern for desktop as well

cc @mattzeunert @AVGP for their take on SEO-impact on desktop of appropriately sized UI targets.

**Comment by halilozanyilmaz** [comment] 2019-05-16 01:45
@patrickhulce ,

This error is for my desktop site:

> Make sure your pages are mobile friendly so users don’t have to pinch or zoom in order to read the content pages.

But my site has mobile view already, I mean instead of chaning the wording, this audit should be canceled.

Because if a website's mobile view passes this audit, then desktop view should not be audited for this item, because it will not be seen by a mobile device. (Of course mobile devices has "view as desktop" for browsing options, but I don't think it should be considered for audit)

**Comment by patrickhulce** [comment] 2019-05-16 01:54
@halilozanyilmaz are you talking about font size now? That should already be marked as not applicable if it was tested as desktop on latest version of lighthouse (not yet in Audits panel, coming soon). If you can reproduce that behavior with the latest version of CLI or Extension please file a separate bug.

**Comment by halilozanyilmaz** [comment] 2019-05-16 02:00
@patrickhulce , no I am not talking abou the font size. I tested my SEO for page in "Desktop" mode, and the error says my pages are not mobile friendly (the above screenshot). However If I would have tested in "Mobile" mode, it would work fine. So in above post I was saying that, maybe for desktop test, this error about if pages are okay for mobile can be canceled. Anyways I fixed my site for this, so it won't be possible to reproduce error on my site. But this is something general I think.

**Comment by patrickhulce** [comment] 2019-05-16 02:10
Oh the Mobile Friendly SEO group as a whole?

Yeah seems fair to make all audits in that group not-applicable when not on mobile or move them into a more generic group @mattzeunert. WDYT?

**Comment by mattzeunert** [comment] 2019-05-16 11:04
Yeah, they should be not applicable, I think it's an issue with how DevTools calls Lighthouse.

DevTools [uses](https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/audits2/Audits2Controller.js?l=240&rcl=c4dd0ee9aebc827a18caa7cb0fdcf7c123d1a29f) `disableDeviceEmulation` rather than `emulatedFormFactor`. (`disableDeviceEmulation` was also [recently removed](https://github.com/GoogleChrome/lighthouse/pull/8289), but Chrome stable is still on 4.2.0.)

`TestedAsMobileDevice` ends up being true – not 100% sure but maybe because `emulatedFormFactor` defaults to `mobile`?

So the solution will be to specify `emulatedFormFactor` in Chrome.

**Comment by connorjclark** [comment] 2020-01-21 22:07
I think this was fixed in Chrome 77. @halilozanyilmaz, can you confirm with your site?

**Comment by patrickhulce** [comment] 2020-01-28 20:49
Confirmed this is fixed for the reported URL in Chrome Canary.

![image](https://user-images.githubusercontent.com/2301202/73304178-5e116e80-41dd-11ea-9c58-86db41552467.png)

**Closed by patrickhulce** 2020-01-28 20:49 UTC
Labels: DevTools, bug, needs-priority, pending-close
