### ISSUE TITLE
Extension Error: Protocol error (Network.emulateNetworkConditions): Unknow...

### ISSUE THREAD

**Issue by zvonkoveljovic2** [GoogleChrome/lighthouse#2028] opened 2017-04-18 14:26 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: https://www.symantec.com/scripts/library/jquery-1.7.2.min.js?20140127
**Error Message**: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
**Stack Trace**:
 ```Error: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by patrickhulce** [comment] 2017-04-18 16:01
@zvonkoveljovic2 it looks like you were trying to audit a javascript file and not the page itself. Lighthouse doesn't support auditing individual source files for violations. You'll have to run it on a particular webpage.

**Comment by patrickhulce** [comment] 2017-09-26 22:46
likely dupe of #1942 comment to reopen if suspected otherwise

**Closed** 2017-09-26 22:45 UTC
Labels: pending-close
