### ISSUE TITLE
Extension Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by apoorvrajsaxena** [GoogleChrome/lighthouse#2389] opened 2017-05-30 07:49 UTC
**Unable to do a test on my angular based web app**
**Lighthouse Version**: 2.0.0
**Chrome Version**: 58.0.3029.110
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
 ```Error: Protocol error (IO.read): Read failed
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11604:25)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ev1stensberg** [comment] 2017-05-30 18:09
Dupe of #1091 , close and let's bring up the discussion there 👍

**Closed** 2017-07-05 05:10 UTC
Labels: duplicate

**Comment by paulirish** [comment] 2017-07-05 15:59
(dupe of #2174, in fact)
