### ISSUE TITLE
`NO_SCREENSHOTS` on Chrome M118+

### ISSUE THREAD

**Issue by pereorga** [GoogleChrome/lighthouse#15460] opened 2023-09-15 17:40 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://pccd.dites.cat/

### What happened?

```
npx lighthouse "https://pccd.dites.cat" --quiet --no-enable-error-reporting --only-categories=performance --view
```

<img width="953" alt="Lighthouse_Report" src="https://github.com/GoogleChrome/lighthouse/assets/919779/a625b746-c733-4b26-a3ce-096682547516">

### What did you expect?

I used to have 100% performance score before, and the screenshots used to not be blank

### What have you tried?

On stable versions of Chrome runs fine. This may be a recent regression.

### How were you running Lighthouse?

node

### Lighthouse Version

11.1.0

### Chrome Version

Chrome Canary 119.0.6010.2

### Node Version

v18.17.1

### OS

Mac

**Comment by adamraine** [comment] 2023-09-15 19:13
I'm able to reproduce, I filed a bug upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=1483420

**Comment by pereorga** [comment] 2023-09-15 21:36
@adamraine thank you. As noted in the Chromium discussion, I've just implemented a workaround on my side. I'm hopeful that the HTTP header I identified might guide you toward a solution.

**Comment by paulirish** [comment] 2023-09-15 23:58
@pereorga yeah isolating that header is super useful. Thank you so much :)

**Comment by adamraine** [comment] 2023-09-18 20:27
A patch has landed, and this issue appears to be fixed on Chromium ToT (but not Canary at time of writing this)

I haven't verified on https://pccd.dites.cat/ since there was a workaround but I did verify on a generic page with the isolated headers set.

Let us know if you still see this on https://pccd.dites.cat/ without the workaround @pereorga.

**Closed by adamraine** 2023-09-18 20:27 UTC
Labels: bug, P1.5, upstream-action-required

**Comment by paulirish** [comment] 2023-10-23 18:18
## Eng-facing
I'm getting other reports of this. 
And we know we've been hitting this exact failure in LR.

[The fix](https://bugs.chromium.org/p/chromium/issues/detail?id=1483420#c4) for the [upstream bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1483420) landed [in m119](https://chromiumdash.appspot.com/commits?commit=3d2d5dc959919ab586ae9c86bf65cacf4fa26d3f&platform=Linux)

Issue #15460 and this were/are reproducible in m118. but not m119.

~Looks like its time to get a merge into stable. :)~ 
[......or not 😞 ](https://bugs.chromium.org/p/chromium/issues/detail?id=1492516#c20)  (rls mgr comment from 1 hour ago):

> we're not planning any further M118 releases.  

## Lighthouse user-facing
Luckily the m119 stable release will [start next Tuesday](https://chromiumdash.appspot.com/schedule) (oct 31). So by Nov 6 hopefully everyone will have the m119 build where this bug is fixed.  Apologies everyone

**Possible workaround** if you're hitting this.  If you have either of these two response headers applied to the test page, try removing them:

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

**Comment by Generosus** [comment] 2023-10-24 00:27
So, we tried the workaround provided above. It works.

Specifically, we commented out the following htaccess rules:

```
#	Header set Cross-Origin-Opener-Policy "same-origin-allow-popups"
#	Header set Cross-Origin-Embedder-Policy "unsafe-none"
```

Thank you guys. We restored our htaccess rules. We'll wait for the fix.

Suggestion: Please publish a temporary notice (banner) on the PSI and Lighthouse websites until this is fixed. We spend numerous hours trying to figure this out. Geez.

Cheers!
