### ISSUE TITLE
DBW: add CLI flag to ignore audits' same origin checks

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#826] opened 2016-10-25 19:27 UTC
Some of the DBW tests filter out audit violations when they occur from code outside the user's control. That is, the user includes a third party script that uses an outdated API and we filter it out ([example](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/uses-http2.js#L63)).

The idea behind this was that users may not have control over this third party code and shouldn't be penalized for it (e.g. they're **DoingGreatWeb** in their own app). 

However, I think should add a toggle for this. Users may want to know when _any_ code in their app is **DoingBadWeb**. Perhaps we can help move the needle a bit on third party libs/scripts that are using old practices, or at the very least, raise attention that something the page is using is bad news bears.

**Comment by ebidel** [comment] 2016-10-25 19:30
Bikeshed: `--audit-remote-urls=true`. This flag would be `false` by default.

**Comment by brendankenny** [comment] 2016-10-25 19:57
Personally I'm of two minds about this: on the one hand, this is a flag very specific to certain audits, so (loathe as I am to add more things to the config file), it may make more sense to add this to the audit declaration in the style of eslint rules or as suggested in #821. This would also help slow CLI flag inflation.

On the other hand, this is an option for a large number of audits, so it does suck to have to repeat it many times. And, as stated, adding more things to the config file should be done reluctantly :)

**Comment by paulirish** [comment] 2016-10-27 01:01
To me this feels like a detail of scoring. Same-origin violations get penalized and cross-origin violations are info-level. (CDNs are hard for us to resolve attribution)

I'm in favor of reporting both violation types from the gatherer. Then, handling scoring for them separately in the audit and formatter.

**Comment by paulirish** [comment] 2018-03-09 00:02
we think this is basically a dupe of #4516  (solved differently)

**Closed by paulirish** 2018-03-09 00:02 UTC
Labels: DoBetterWeb, P2, report
