### ISSUE TITLE
First Contentful Paint ignores opacity: 0 in some situations

### ISSUE THREAD

**Issue by tannerhodges** [GoogleChrome/lighthouse#11603] opened 2020-10-28 02:17 UTC
#### Provide the steps to reproduce
1. Run LH on https://demo.tannerhodges.com/vitals/fcp/opacity.html.
2. Compare to https://demo.tannerhodges.com/vitals/fcp/index.html.

👉 See source code: https://github.com/tannerhodges/core-web-vitals/tree/main/fcp

#### What is the current behavior?
Lighthouse reports that FCP is the same (and sometimes _better_) when the body is hidden with `opacity: 0` and revealed later during page load than when that style is removed and the page renders as quickly as possible.

For example, compare these WebPageTest filmstrips for the files above:

| `opacity.html` | `index.html` |
| -- | -- |
| ![FCP reports times faster when the body has opacity: 0](https://user-images.githubusercontent.com/1619485/97378097-e8375200-1897-11eb-9bd3-cc4b706ac6e0.png) | ![FCP reports slower times when the body renders as soon as possible](https://user-images.githubusercontent.com/1619485/97378100-e8cfe880-1897-11eb-96d7-8d1346edeafc.png) |
| [WebPageTest **video** for `opacity.html`](https://webpagetest.org/video/compare.php?tests=201027_DiRG_c733fc344a126feceec523bcf9a6bb43-r%3A8-c%3A0&thumbSize=200&ival=100&end=visual) | [View WebPageTest  **video** for `index.html`](https://webpagetest.org/video/compare.php?tests=201027_Di5A_e91a35ca7be57980c5e6087495f0e835-r%3A9-c%3A0&thumbSize=200&ival=100&end=visual) |
| [WebPageTest **summary** for `opacity.html`](https://webpagetest.org/result/201027_DiRG_c733fc344a126feceec523bcf9a6bb43/) | [WebPageTest **summary** for `index.html`](https://webpagetest.org/result/201027_Di5A_e91a35ca7be57980c5e6087495f0e835/) |

Lighthouse correctly reports that **LCP** was faster in `index.html`, but incorrectly reports that **FCP** was slower. (Apparently, `opacity.html` rendered even sooner than the page appears in either video… 👀)

This is unexpected, and the effect grows in larger projects with similar code patterns.

In some cases, removing `opacity: 0` from the body can _increase_ FCP by as much as 1 second or more—even though the page is actually rendering much faster. 👇

![Example where FCP reports ≈1s worse, even thought the page renders ≈2s faster](https://user-images.githubusercontent.com/1619485/97374475-bff72580-188e-11eb-821f-5ac9f4169f9c.png)

Unfortunately I can't share the code for this particular project but hopefully the reduced test case replicates the same issues well enough to debug what's going on.

#### What is the expected behavior?
- Per the [Paint Timing spec](https://w3c.github.io/paint-timing/#sec-terminology), elements with `opacity: 0` should not be considered paintable.
- First Contentful Paint should fire later in `opacity.html` than in `index.html`.
- In these examples, FCP and LCP should both match since the `h1` is the first & largest contentful element to render on the page.

#### Environment Information
- Affected Channels: CLI, DevTools, and others. (I've confirmed the same result in PageSpeed Insights and WebPageTest.)
- Lighthouse version: 6.4.1
- Chrome version: 86.0.4240.111
- Node.js version: 14.15.0
- Operating System: macOS 10.15.7

#### Related issues
I'm still trying to get my head around Lighthouse's internals / which issues are actually relevant, but here are some I across while researching this that might (?) help:
- https://github.com/GoogleChrome/lighthouse/issues/2289 DevTools: node revealing is flaky
- https://github.com/GoogleChrome/lighthouse/issues/4139 Differentiate NO_FCP failure cases

I've also experienced similar issues with CLS ignoring `opacity: 0`, so in case the topic of paintable elements overlaps with FCP here are those issues:
- https://github.com/GoogleChrome/lighthouse/issues/10873 High CLS without actual content shifting
- https://github.com/WICG/layout-instability/issues/61 layout instability spec needs to clarify whether (and which) unpainted nodes are considered or not

---

P.S. At this point I'm not sure whether this should be considered a Lighthouse bug or a Chrome bug. Appreciate any insight y'all have as to what's going on here / next steps I should take.

Let me know if there's any additional information I can provide.

🙏 Thanks for the help.

**Comment by patrickhulce** [comment] 2020-10-28 16:33
Thanks for filing with such great detail @tannerhodges! 

Many different issues at play here, some of which have satisfying answers and others less so. I can't spend any more time on this really based on what I saw unfortunately, but I'm flushing what I did find.

> Per the Paint Timing spec, elements with opacity: 0 should not be considered paintable.

I haven't seen or been able to reproduce locally a case where FCP is marked *before* the opacity 0 flips, from my investigation the difference in metric times appears to come from the effect it has on paint scheduling (pushing Chrome to consider pushing a frame earlier, see below). If you find a minimal repro where there are not any other paint-blocking resources or tasks and FCP gets marked on a frame body is opacity 0, we can resume investigating here :)

> First Contentful Paint should fire later in opacity.html than in index.html.

While when isolated this makes sense, there are too many competing factors at play in these examples that affect paint scheduling (multiple other unrelated render-affecting resources), such that I found no statistical significance to  "opacity.html is occurring *earlier* than index.html" (40 runs locally). They appear to be the same on a macro level, which suggests to me that the `opacity: 0` is not what is blocking paint most of the time here. Additionally, all examples I tried that isolate the opacity change, couldn't demonstrate this fact either. 

The most likely explanation I can think of here is that by explicitly scheduling a body opacity change, Chrome considers that moment more important to ship a frame when it would otherwise wait for the webfont/script/etc that is currently being downloaded to finish which is why you occasionally see it taking longer in that case. In general, paint scheduling and coalescing isn't a deterministic or specable thing though and user agents are free to group multiple paints together if they think it will conserve resources or provide a more fluid experience.

> In these examples, FCP and LCP should both match since the h1 is the first & largest contentful element to render on the page.

This is "expected" behavior in the sense that it's working as intended according to the spec, even though it is definitely a bummer that they differ :)

The simplest reproduction of the same concept at play here with the FCP/LCP discrepancy is loading http://melodic-class.glitch.me/fcp-opacity-0.html in the Performance tab in DevTools where you can see that FCP is marked at at time when no content is shipped at all and that LCP waits for the web font to finish downloading.

![image](https://user-images.githubusercontent.com/2301202/97458899-2882e880-1909-11eb-9aad-01a17b97033c.png)

FCP does not wait for text to be visible in user sense of the word (and can therefore pick an invisible looking frame), LCP does wait for text to be visible (and won't pick the invisible text frame) (even under `font-display: swap`, browser will still give a very brief blocking period for the text to be painted if web font is inflight). I agree this isn't necessarily as useful from a developer perspective, so might be worth [filing an issue against the spec](https://github.com/w3c/paint-timing/issues/) with that minimal glitch example or see if it's already been brought up before.

**Comment by tannerhodges** [comment] 2020-11-03 04:11
Interesting!

Yeah, I was definitely under the impression that FCP was (is?) intended to measure paint timing in the _user_ sense of the word. This gives me a much, much better sense of what's happening and some of the results I'm seeing.

Really appreciate you taking the time to share such a thorough answer.

❓ Questions:

1. Where can I learn more about paint scheduling, render-affecting resources, and how/when/why Chrome decides to ship frames?
2. In Dev Tools, how can I find the opacity "flip" in my Performance timeline? (I.e., how can I distinguish the time it was scheduled vs the time it actually rendered?)
3. You mentioned "paint scheduling and coalescing isn't a deterministic or specable thing…" How could I frame my issue in a way that might make it more specable?

Any quick links/tips would be fantastic.

In the meantime, I'll try to whittle this down a bit more and follow-up again by the end of next week.

Thanks again.

**Comment by tannerhodges** [comment] 2020-11-19 05:24
Hey @patrickhulce, thanks for these resources! They've been super helpful.

I've updated the demo: no fonts, no JS, just `opacity` or not (plus a new `visibility` example for comparison).

👀 Now I think this may actually be a Chrome bug…

- ❌ **Opacity** https://demo.tannerhodges.com/vitals/fcp/opacity.html — Should **not** return FCP but does anyway.
- ✅ **Visibility** https://demo.tannerhodges.com/vitals/fcp/visibility.html — Does not return FCP, as expected. _← Lighthouse seems to fail on this one, but if you use DevTools you can confirm there's no FCP event._
- ✅ **Control**: https://demo.tannerhodges.com/vitals/fcp/index.html — Does return FCP, as expected.

Sanity check me here: am I right that this Opacity example should not return any FCP at all?

<img width="1420" alt="Screen Shot 2020-11-19 at 12 14 36 AM" src="https://user-images.githubusercontent.com/1619485/99624472-5933da80-29fc-11eb-9851-edae0735616a.png">

**Comment by tannerhodges** [comment] 2020-11-19 14:11
It seems like this only happens when you have a combination of…

- SVG (maybe because of the parser switching?)
- Flexbox.
- Overflow scrolling containers.

If I remove/change any of those things from the demo then FCP disappears (as it should).

In particular, I think something about overflow scrolling containers is affecting whether FCP is reported for `opacity: 0`. When I run the page through [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.tannerhodges.com%2Fvitals%2Ffcp%2Fopacity.html) it reports an FCP on mobile but **errors on desktop**…

The only difference, as far as I can tell, is whether the list content overflows and makes the container scrollable.

| ❌ Mobile         | ✅ Desktop          |
|----------------|----------------|
| ![](https://user-images.githubusercontent.com/1619485/99676743-e1d76880-2a46-11eb-9bd6-4ac89228359b.png) | ![](https://user-images.githubusercontent.com/1619485/99676746-e26fff00-2a46-11eb-927f-e2d69f450494.png) |

**Comment by patrickhulce** [comment] 2020-11-19 18:10
Thanks very much for that minimal repro and additional investigation @tannerhodges! This is fascinating, to make things even more confusing, I copied the exact source of your page [onto another domain](http://melodic-class.glitch.me/fcp-opacity-0-with-scroll-svg.html) with photos replaced and that produces the expected behavior (NO_FCP) while yours still gives an FCP... 🤯  Can you replicate the same result?

Definitely a Chrome bug, but not even one that makes any sense!  I'll poke around a bit to see if I can find the difference in the hosting, if the specific image matters, etc.

**Comment by patrickhulce** [comment] 2020-11-19 21:46
Wow, OK found the issue and filed https://bugs.chromium.org/p/chromium/issues/detail?id=1151054. Amazing work @tannerhodges hopefully we'll get a fix in Chromium soon :)

**Comment by tannerhodges** [comment] 2020-11-20 01:22
🙌 Fantastic!

I'm so relieved, I can finally take down my conspiracy wall.

<img src="https://user-images.githubusercontent.com/1619485/99743793-66a49f80-2aa4-11eb-9588-7c006e6753d5.jpg" alt="FCP does not exist" width="400" height="310">

Thank you again @patrickhulce for your feedback, resources, and help digging into this.

Excited to see it on its way to getting fixed.

**Comment by paulirish** [comment] 2020-12-17 09:30
CLS w/ opacity:0 is changing: https://chromium-review.googlesource.com/c/chromium/src/+/2591907

not FCP, but worth pointing out...

**Comment by midzer** [comment] 2021-04-27 21:14
Since many LH versions I am experiencing a LCP penalty for having images with opacity animation on page load. Is this intended?

Example: https://feuerwehr-eisolzried.de/

I am unsure whether this fits here. Didn't want to open a new issue...

**Comment by paulirish** [comment] 2021-12-14 21:07
@midzer tbh i'm not sure. check https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/speed/metrics_changelog/lcp.md and try again?

----------

as for @tannerhodges's original report. it appears to be fixed as of m94. see https://bugs.chromium.org/p/chromium/issues/detail?id=1151054#c7

**Closed by paulirish** 2021-12-14 21:07 UTC
Labels: bug, needs-priority, upstream-action-required

**Comment by midzer** [comment] 2021-12-14 23:19
@paulirish Thanks for your message and link. Yeah, the issue is fixed now for me.

**Comment by tannerhodges** [comment] 2021-12-15 00:31
🙌 Fixed at last! Thanks all.
