### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by mgbako** [GoogleChrome/lighthouse#2758] opened 2017-07-27 07:52 UTC
**Initial URL**: http://mathline-electric.com/
**Chrome Version**: 62.0.3164.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@08b90b79808b8a223d6e9fb76c0c05c7a3b0c077/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-07-27 20:09
dupe of #1091

**Closed by patrickhulce** 2017-07-27 20:09 UTC
