### ISSUE TITLE
Extension Error: Protocol error (Network.emulateNetworkConditions): Unknow...

### ISSUE THREAD

**Issue by paidfocusgroups** [GoogleChrome/lighthouse#1950] opened 2017-04-01 18:17 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: http://www.paidfocusgroup.net/nationwide
**Error Message**: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
**Stack Trace**:
 ```Error: Protocol error (Network.emulateNetworkConditions): Unknown debugger protocol error.
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2017-04-01 22:38
Can you add your OS details over on https://github.com/GoogleChrome/lighthouse/issues/1942? This is a dupe of that issue.

**Closed by ebidel** 2017-04-01 22:38 UTC
