### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by helloaliceoh** [GoogleChrome/lighthouse#2573] opened 2017-06-22 21:25 UTC
**Lighthouse Version**: 2.1.0
**Chrome Version**: 58.0.3029.110
**Initial URL**: http://nginx.org/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9893:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
```

**Comment by ebidel** [comment] 2017-06-22 22:04
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2457

**Closed by ebidel** 2017-06-22 22:04 UTC
