### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by EasonRen** [GoogleChrome/lighthouse#2565] opened 2017-06-22 08:11 UTC
**Initial URL**: https://nicecode.win/
**Chrome Version**: 61.0.3135.4
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@8366065c0da06984379f2d39bc85c1067d70d3dd/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-06-22 15:55
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2457

**Closed** 2017-06-22 15:55 UTC
