### ISSUE TITLE
Extension Error: artifacts.ConsoleTimeUsage.usage.filter is not a function

### ISSUE THREAD

**Issue by cnbn96** [GoogleChrome/lighthouse#1055] opened 2016-11-27 02:55 UTC
**Lighthouse Version**: 1.2.1
**Chrome Version**: 52.3.2743.138
**Error Message**: artifacts.ConsoleTimeUsage.usage.filter is not a function
**Stack Trace**:
 ```TypeError: artifacts.ConsoleTimeUsage.usage.filter is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:807:54)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11082:24)```

**Comment by wardpeet** [comment] 2016-11-27 20:02
Dupe of #1031

**Closed** 2016-11-27 20:02 UTC
Labels: duplicate
