### ISSUE TITLE
Extension Error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by gopalindians** [GoogleChrome/lighthouse#1501] opened 2017-01-20 08:56 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: http://demos.codebeing.com/
**Error Message**: Cannot read property 'children' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:560:62)```

**Comment by ebidel** [comment] 2017-01-20 16:58
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1427

**Closed by ebidel** 2017-01-20 16:58 UTC
