### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by prashantpalikhe** [GoogleChrome/lighthouse#2693] opened 2017-07-15 08:00 UTC
**Initial URL**: https://bankieren-acpt3.rabobank.nl/bankierenplus/nl/dashboard.html
**Chrome Version**: 61.0.3158.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@97e40196944c926a7b805cdfe67611832da7d457/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-07-17 17:18
dupe of #1091

**Closed by patrickhulce** 2017-07-17 17:18 UTC
