### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by dinocajic** [GoogleChrome/lighthouse#4450] opened 2018-02-07 14:24 UTC
**Initial URL**: https://americantruxx.com/
**Chrome Version**: 64.0.3282.140
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:957:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:3497:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:3517:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:3515:49)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:2363:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:2361:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:3509:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:960:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@a06bc1d5e8e285c70078802de990c1719ccc75e8/audits2_worker/audits2_worker_module.js:794:8)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2018-02-12 17:20
duplicate of #3306

**Closed by patrickhulce** 2018-02-12 17:20 UTC
