### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#2642] opened 2017-07-05 17:34 UTC
Bug happens after that the page is loaded without javascript.

**Initial URL**: https://www.koolsol.com/?lang=fr
**Chrome Version**: 61.0.3149.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@4485eb651f6f09c3183285927fe82d17fcd7a13e/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@4485eb651f6f09c3183285927fe82d17fcd7a13e/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by wardpeet** [comment] 2017-07-28 13:36
i'm closing this as it's a duplication of other issues. Thanks for the sharing we will look into this

**Closed** 2017-07-28 13:35 UTC
Labels: duplicate

**Comment by wardpeet** [comment] 2017-07-28 17:21
i've tested this on chrome canary (62) and stable chrome (60) could not reproduce
