### ISSUE TITLE
Fetch requests in browser's dev tools but not in Ligthhouse report

### ISSUE THREAD

**Issue by aleksaar** [GoogleChrome/lighthouse#14836] opened 2023-02-28 13:09 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.nytimes.com/ https://www.etuovi.com/

### What happened?

Lighthouse CLI and Chrome’s developer tools, opened during the Lighthouse run, show vastly different total bytes for some pages. Seems like Lighthouse does not show most of the fetch-requests, even though Chrome’s dev tools shows them. 

I am not referring to the variability that comes from different page loads and Lighthouse configuration.

Opening Chrome’s dev tools during a Lighthouse run shows a larger byte amount in the network tab in dev tools (14.3 MB nytimes.com, 18.6 MB etuovi.com), but Lighthouse’s output JSON shows a smaller byte amount (3.7 MB nytimes.com, 4.7 MB etuovi.com) and is missing nearly all fetch-requests of the page in the `network-requests` -audit that contribute the majority of the page size for both pages.

I am using a configuration similiar to the default configuration, but without throttling for Lighthouse. Also, PageSpeed Insights shows similiar results to my Lighthouse runs, so I doubt Lighthouse configuration is the problem.

Below, dev tools data is from the browser windows that Lighthouse opens

https://www.nytimes.com/ Dev tools: 
- Total: 14.3 MB, 386 requests
- Image 1.6 MB, 52 requests
- Script 1.3 MB, 45 requests
- Document 368 kB, 9 requests
- Font 365 kB, 15 requests
- Other 2.8 kB, 8 requests
- Stylesheet 30.5 kB, 13 requests
- Media 0, 0 requests
- Fetch / XHR 10.6 MB, 246 requests

https://www.nytimes.com/ Lighthouse CLI 9.6.2 `resource-summary` -audit
```
{
            "resourceType": "total",
            "label": "Total",
            "requestCount": 162,
            "transferSize": 3745251
          },
          {
            "resourceType": "image",
            "label": "Image",
            "requestCount": 50,
            "transferSize": 1640597
          },
          {
            "resourceType": "script",
            "label": "Script",
            "requestCount": 44,
            "transferSize": 1253580
          },
          {
            "resourceType": "document",
            "label": "Document",
            "requestCount": 7,
            "transferSize": 366943
          },
          {
            "resourceType": "font",
            "label": "Font",
            "requestCount": 15,
            "transferSize": 364728
          },
          {
            "resourceType": "other",
            "label": "Other",
            "requestCount": 33,
            "transferSize": 88864
          },
          {
            "resourceType": "stylesheet",
            "label": "Stylesheet",
            "requestCount": 13,
            "transferSize": 30539
          },
          {
            "resourceType": "media",
            "label": "Media",
            "requestCount": 0,
            "transferSize": 0
          },
          {
            "resourceType": "third-party",
            "label": "Third-party",
            "requestCount": 125,
            "transferSize": 2574040
          }

```
https://www.nytimes.com/ PageSpeed Insights
![image](https://user-images.githubusercontent.com/86832919/221854051-431e165d-a195-4343-956f-03d4bfe28b82.png)

Some of the fetch-requests in dev tools that are missing in Lighthouse https://www.nytimes.com/
![image](https://user-images.githubusercontent.com/86832919/221851381-13357bb4-3ce3-471a-b925-91e4ddf561dc.png)

https://www.etuovi.com/ Dev tools: 
- Total: 18.6 MB 173 requests
- Script 3.5 MB, 21 requests
- Image 591 kB, 12 requests
- Font 352 kB, 7 requests
- Document 124 kB, 5 requests
- Other 65 kB, 11 requests
- Stylesheet 61.3 kB, 2 requests
- Media 0, 0 requests
- Fetch/XHR 13.9 MB, 115 requests

https://www.etuovi.com/ Lighthouse CLI 9.6.2 `resource-summary` -audit
```
{
            "resourceType": "total",
            "label": "Total",
            "requestCount": 59,
            "transferSize": 4699109
          },
          {
            "resourceType": "script",
            "label": "Script",
            "requestCount": 20,
            "transferSize": 3454774
          },
          {
            "resourceType": "image",
            "label": "Image",
            "requestCount": 9,
            "transferSize": 591443
          },
          {
            "resourceType": "font",
            "label": "Font",
            "requestCount": 6,
            "transferSize": 351771
          },
          {
            "resourceType": "document",
            "label": "Document",
            "requestCount": 3,
            "transferSize": 123173
          },
          {
            "resourceType": "other",
            "label": "Other",
            "requestCount": 19,
            "transferSize": 116678
          },
          {
            "resourceType": "stylesheet",
            "label": "Stylesheet",
            "requestCount": 2,
            "transferSize": 61270
          },
          {
            "resourceType": "media",
            "label": "Media",
            "requestCount": 0,
            "transferSize": 0
          },
          {
            "resourceType": "third-party",
            "label": "Third-party",
            "requestCount": 34,
            "transferSize": 820703
          }

```

https://www.etuovi.com/ PageSpeed Insights
![image](https://user-images.githubusercontent.com/86832919/221857932-df2ea22b-8b42-4f1a-b4ec-11c632ce0612.png)

### What did you expect?

Lighthouse should see the same fetch-requests that Chrome’s dev tools see and thus return the same byte and request amounts, when dev tools are opened during a Lighthouse run in the browser that Lighthouse opens.

### What have you tried?

Tried changing the `networkQuietThresholdMs` in the configuration for Lighthouse, but this did not help. Checked the byte amounts and requests in Lighthouse's Chromium window by setting `networkQuietThresholdMs` to 100 seconds.

### How were you running Lighthouse?

CLI, PageSpeed Insights

### Lighthouse Version

CLI 9.6.2

### Chrome Version

Chromium 110.0.5481.100

### Node Version

16.14.2

### OS

Linux

**Comment by adamraine** [comment] 2023-02-28 19:32
I had a hard time testing https://www.etuovi.com/, the page was slow probably because the servers are far from me and I got a 503 error at one point. I'll try and circle back to this though.

On NY times definitely saw some variability in the total transfer size (3.5-6.9 MB on mobile). I couldn't reproduce the huge difference in transfer size between Lighthouse clients, and even if I could I'm skeptical that the site is being consistent about what resources it fetches.

How consistent are these results for you?

**Comment by aleksaar** [comment] 2023-03-01 08:19
Forgot to mention, these were done with desktop configuration. 

But the same thing happens on https://twitter.com/, where opening dev tools network tab for the browser window that Lighthouse opens, shows 4.5 MB with 588 requests and Lighthouse's JSON report show 2.3 MB with 170 requests. Dev tools also shows 428 fetch-requests totaling 2.2 MB, which is the difference between Lighthouse's and dev tools' results. And again, Lighthouse only reports 1 fetch request in the `network-requests` audit. Every other resource images/script/etc. is pretty much the same between Lighthouse and dev tools.

But my entire point is that this is not difference between Lighthouse clients, but the difference between Lighthouse CLI and the browser window that Lighthouse opens.

The way I did it:
- run Lighthouse from terminal
- Lighthouse opens Chromium window
- as soon as browser window opens, press f12 to open dev tools
- look at resources and requests in the network tab (not Lighthouse from dev tools)
- look at results in Lighthouse's JSON file

And every resource seems to be about the same, except almost every request in the Fetch/XHR tab in dev tools is missing from Lighthouse's JSON.

**Comment by adamraine** [comment] 2023-03-07 19:18
Thanks for elaborating on the repro steps, that was helpful. For anyone trying to reproduce this themselves, it helped for me to run Lighthouse with the following command:

```sh
lighthouse https://www.nytimes.com/ -GA --debug-navigation --chrome-flags="--auto-open-devtools-for-tabs"
```

This will open DevTools automatically and pause the page after load so you can pick through the network requests DevTools finds.

This looks like the same issue as https://github.com/GoogleChrome/lighthouse/issues/14211. Lighthouse does not attach to worker targets so any network requests fetched by web workers are not captured in the Lighthouse report. Both https://www.nytimes.com/ and https://twitter.com/ seem to fetch a lot of resources in web workers.

I think we can merge this issue into #14211.

**Comment by paulirish** [comment] 2023-03-07 20:22
Nice. Closing as a dupe of https://github.com/GoogleChrome/lighthouse/issues/14211.

**Closed by paulirish** 2023-03-07 20:22 UTC
Labels: bug, pending-close, needs-priority
