### ISSUE TITLE
How to set output to "html" when use it programmatically?

### ISSUE THREAD

**Issue by ganlanyuan** [GoogleChrome/lighthouse#4357] opened 2018-01-25 20:40 UTC
I use it in this way:
index.js
```javascript
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');
function launchChromeAndRunLighthouse(url, opts, config = null) {
  return chromeLauncher.launch({chromeFlags: opts.chromeFlags}).then(chrome => {
    opts.port = chrome.port;
    return lighthouse(url, opts, config).then(results =>
      chrome.kill().then(() => results));
  });
}

const opts = {
  output: 'html',
  outputpath: './report.html',
  chromeFlags: ['--show-paint-rects']
};

// Usage:
launchChromeAndRunLighthouse('http://google.com/', opts).then(results => {
  // Use results!
  console.log(results);
});
```
```
node index.js
```
But get json format output.

**Comment by patrickhulce** [comment] 2018-01-25 22:53
Hey @ganlanyuan thanks for filing! This seems like a dupe of #3958 and #3587 so you can refer to those on how to get going, but feel free to comment there if you still have questions :)

**Closed by patrickhulce** 2018-01-25 22:53 UTC

**Comment by ganlanyuan** [comment] 2018-01-26 00:11
Thanks

**Comment by Anthodpnt** [comment] 2018-02-17 01:19
Hi guys,

Don't know the best place to drop it but for those of you who want to generate HTML reports when using Lighthouse programatically, here is a workaround using the `lighthouse-cli/printer.js` to get the work done in a couple of lines. It's an example of my workflow but you'll get the idea 😃 .

However, this hack is **not documented** and so your code might fail depending on further releases and core updates I guess. Until then you can give it a try and it should work perfectly.

```javascript
// Require dependencies
const gulp = require('gulp');
const path = require('path');
const open = require('opn');
const logs = require('lighthouse-logger');
const printer = require('lighthouse/lighthouse-cli/printer');
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

// Require configuration file
const config = require(path.resolve('.', 'gulp/config', 'perfs.json'));

/**
 * Lint:
 * Lint method using Chrome and Lighthouse.
 *
 * @param  {String} url - URL to test
 * @return {Object} Lighthoust results
 */
function lint(url) {
  // Launch Chrome in headless mode
  return chromeLauncher.launch(config.flags).then((chrome) => {
    // Add Chrome port in options
    config.flags.port = chrome.port;

    // Setup logs level
    logs.setLevel(config.flags.logLevel);

    // Run Lighthouse on given URL
    return lighthouse(url, config.flags, config.options).then((results) => {
      // Stop Chrome and return results
      return chrome.kill().then(() => results);
    });
  });
}

/**
 * Write:
 * Write HTML reports of Lighthouse results.
 *
 * @param {Object} results - Lighthouse results
 */
function write(results) {
  // Get current date
  const date = new Date();

  // Lead zero method
  const zero = (n) => {
    return n < 10 ? `0${n}` : n;
  };

  // Get date values
  const Y = date.getFullYear();
  const M = zero(date.getUTCMonth() + 1);
  const d = zero(date.getUTCDate());
  const h = zero(date.getHours());
  const m = zero(date.getMinutes());
  const s = zero(date.getSeconds());

  // Build filename
  const filename = `report-${Y}-${M}-${d}-${h}.${m}.${s}.html`;

  // Define output path
  const outputPath = path.resolve('.', 'reports/perfs', filename);

  // Create an HTML report of results
  printer.write(results, 'html', outputPath).then(() => {
    // Open HTML report in browser
    open(outputPath, { wait: false });
  });
}

// Gulp `lint:perfs` Task
// Lint performance issues on the page from configuration.
gulp.task('lint:perfs', () => {
  return lint(config.page)
          .then((results) => write(results))
          .catch((errors) => process.exit(errors));
});
```

Enjoy !
Anthodpnt

**Comment by ganlanyuan** [comment] 2018-02-17 11:17
thanks @Anthodpnt

**Comment by anuragphadke** [comment] 2018-11-17 20:08
@Anthodpnt do you have a sample perfs.json to refer? Mine is here https://gist.github.com/anuragphadke/31914d02094c11321e5cd391a98fb76e, but I am missing some values.
