### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by eguchi3** [GoogleChrome/lighthouse#2492] opened 2017-06-13 02:55 UTC
**Initial URL**: about:blank
**Chrome Version**: 61.0.3124.10
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@ace7df121252a526c7dfe153180c1f974a0462f9/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@ace7df121252a526c7dfe153180c1f974a0462f9/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-06-13 14:59
dupe of #2362

**Closed by patrickhulce** 2017-06-13 14:59 UTC
