### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by rmkpatchaa** [GoogleChrome/lighthouse#2480] opened 2017-06-10 20:54 UTC
**Initial URL**: https://rmkpatchaa.com/
**Chrome Version**: 61.0.3126.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@61b63cbc244f348331c91d78402eb843bd185408/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by ebidel** [comment] 2017-06-10 21:55
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-06-10 21:55 UTC
