### ISSUE TITLE
Testing the entire login route through Lighthouse

### ISSUE THREAD

**Issue by vanyasehgal29** [GoogleChrome/lighthouse#2058] opened 2017-04-24 21:50 UTC
Does lighthouse gives us the flexibility to add login credentials and evaluate the page from login -> adding credentials -> homepage?

**Comment by ebidel** [comment] 2017-04-24 22:48
Unfortunately, there's not a great way for Lighthouse to automate page actions like this. That's more a job for drivers like Selenium. You also might be able to script something yourself. We're limited to testing a page before/during page load. Not what happens after it.

I'm curious: is there a reason you want to test the actual login flow? We have some info on testing against authenticated sites [here](https://github.com/GoogleChrome/lighthouse/issues/1418) and [here](https://github.com/GoogleChrome/lighthouse#testing-on-a-site-with-authentication). Maybe that helps?

**Comment by vanyasehgal29** [comment] 2017-04-24 23:19
Thanks @ebidel for such a quick response. Yeah, I want to calculate the performance for entire flow.

**Comment by paulirish** [comment] 2017-04-25 21:37
@vanyasehgal29 what would be your ideal solution?

1. [login manually first](https://github.com/GoogleChrome/lighthouse#testing-on-a-site-with-authentication), then run LH
1. provide an `Authorization` request header
1. a basic scripting API to navigate, set form values, submit forms, etc
1. provide a cookie value you want set
1. something else?

**Comment by vanyasehgal29** [comment] 2017-04-25 23:12
@paulirish 
I wan't to write a script that performs login, then navigates over a site. So, I would say 5.

**Comment by paulirish** [comment] 2017-04-26 00:26
cool. then we probably will use a phantomium-like API (that doesn't yet exist) for the automation with a handover to lighthouse for the individual pages.

**Comment by abacon** [comment] 2017-04-27 19:04
@paulirish is there anything I can do to help with the phantomium-like API? Fwiw, it may be sufficient to just I've hacked together the following incredibly fragile solution for this:

        return connection.connect()
            .then(() => driver.beginNetworkCollect({url: 'https://www.mysite.com/login'})
                .then(
                    () => driver.gotoURL('https://www.patreon.com/login', {waitForLoad: true})
                )
            ).then(() => {
                return driver.evaluateAsync(`//some login script`)
            })

**Comment by benschwarz** [comment] 2017-04-27 21:56
I've been maintaining a form-based-login extension for Calibre for a couple of years now. Even though it sounds simple — it hasn't been. Many SPAs don't use forms at all, or don't let any events fire, and its a constant source of people messing up the configuration when slightly confused by attribute queries `input[name=foo`, etc.

Basic authentication can work really well, although you need to be sure to catch browser `interstitial` events, or else everything will hang up. 

Cookies or localstorage (for SPAs) are great 👍

**Comment by patrickhulce** [comment] 2017-09-26 22:47
dupe of #1418

**Closed by patrickhulce** 2017-09-26 22:47 UTC
Labels: feature, needs-priority, pending-close
