### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by okonet** [GoogleChrome/lighthouse#1893] opened 2017-03-23 17:19 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 56.0.2924.87
**URL**: https://feedly.com/i/my
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9300:15)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment] 2017-03-23 17:30
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-03-23 17:30 UTC
