### ISSUE TITLE
First meaningful paint is negative

### ISSUE THREAD

**Issue by jessiehan** [GoogleChrome/lighthouse#4654] opened 2018-03-01 09:12 UTC
And no domContentLoaded event in trace
can reproduce with this url: https://m.taobao.com/#index
![2018-03-01 5 09 30](https://user-images.githubusercontent.com/1680909/36836191-a8f28492-1d73-11e8-837b-cf58dac38052.png)

version: 2.5.1

**Comment by patrickhulce** [comment] 2018-03-01 17:56
thanks for filing @jessiehan! this is the same root cause and site as #3838, so we'll close this as a duplicate but feel free to add additional information over there

**Closed by patrickhulce** 2018-03-01 17:56 UTC
