### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by mfiot** [GoogleChrome/lighthouse#6348] opened 2018-10-19 21:40 UTC
**Initial URL**: http://10.20.30.136/dashboard.html#
**Chrome Version**: 70.0.3538.67
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:85:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:490:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:182:241)
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:199:381)
```

**Comment by patrickhulce** [comment] 2018-10-25 14:18
duplicate of #4330

**Closed by patrickhulce** 2018-10-25 14:18 UTC
