### ISSUE TITLE
Video audit: check for correct aspect ratio

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2578] opened 2017-06-23 13:44 UTC
The aspect ratio of a video should match the aspect ratio of a video element used to play it, even if the dimensions are different.

Test by comparing video.videoWidth/video.videoHeight with video element  clientWidth/clientHeight.

Need to ensure video loadedmetadata event has fired before testing.

**Comment by ebidel** [comment] 2017-06-23 15:24
Dupe of https://github.com/GoogleChrome/lighthouse/issues/2579

**Closed by ebidel** 2017-06-23 15:24 UTC
Labels: audit

**Comment by samdutton** [comment] 2017-06-23 15:30
#2579 is for images, this one's for video :).
