### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by mopase** [GoogleChrome/lighthouse#1655] opened 2017-02-07 06:26 UTC
**Lighthouse Version**: 1.4.1
**Chrome Version**: 56.0.2924.87
**URL**: http://patternlab.io/resources.html
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11470:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12474:17)```

**Comment by ebidel** [comment] 2017-02-07 06:50
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1214

**Closed by ebidel** 2017-02-07 06:50 UTC
