### ISSUE TITLE
Weird case where all scores and results are null

### ISSUE THREAD

**Issue by TAnas0** [GoogleChrome/lighthouse#9730] opened 2019-09-24 21:49 UTC
**Summary**

Hey,

I am here to get help understanding the results returned by Lighthouse on the following URL: https://www.massimodutti.com/ma/hommes/nouveaut%C3%A9s/nouveau-c1607006.html

All measurements and audit results are null:

![image](https://user-images.githubusercontent.com/12121506/65552757-2176f300-df1d-11e9-8eb6-2bf100bda883.png)

Note that auditing the home page of the website (https://www.massimodutti.com) is behaving normally.

I am used to seeing a single missing value of the 5 scores, but this is the first time where the audit fails reliably on all 5 scores.

Any help as to why this occurs, or explanations about missing scores, would be greatly appreciated.

Cheers

**Comment by patrickhulce** [comment] 2019-09-24 22:01
That server is responding with a status code of 503 for that page (`Service Unavailable`). This usually indicates that the server is down.

Given that the page is up, this seems like a mistake and it should respond with 200 OK :)

**Comment by TAnas0** [comment] 2019-09-28 15:53
I am having the exact same issue with another website: https://theoasisfest.com/

May be of help if someone is debugging this.

**Comment by patrickhulce** [comment] 2019-09-28 23:56
@TAnas0 I'm not able to reproduce this issue on https://theoasisfest.com/. I get a valid report, perhaps file a new issue if you're able to identify clear reproducible steps?

![image](https://user-images.githubusercontent.com/2301202/65823728-87b38c80-e221-11e9-8853-a132dfe9e984.png)

Also it seems there's some confusion regarding the last comment. It is a mistake of the page/server, Lighthouse is performing as expected and no one is going to be investigating this issue further. Closing for now to reflect that resolution.

**Closed by patrickhulce** 2019-09-28 23:56 UTC
Labels: pending-close

**Comment by TAnas0** [comment] 2019-09-29 17:03
Thank you for your interest @patrickhulce 

The Lighthouse audit for https://theoasisfest.com/ is now working fine for me. I wanted just to add it as an additional example. The audit on the first link () though is still not working and having the same weird behavior.

Anyways, if no one is investigating such cases, this issue is better off closed.

I am really interested in understanding what is going on, but I am running out of leads/pointers to do this.

Cheers

**Comment by patrickhulce** [comment] 2019-09-29 17:06
We already understand and have explained why this is happening to that URL. That is why no one will be investigating.

> That server is responding with a status code of 503 for that page (Service Unavailable). This usually indicates that the server is down.

The server should not be responding with a 503 status code when the page is being served and working as intended. It is a bug on the server. Hope this helps make it clearer!

**Comment by connorjclark** [comment] 2019-09-30 20:00
![image](https://user-images.githubusercontent.com/4071474/65911986-54d4da00-e382-11e9-843e-0966f5673416.png)
