### ISSUE TITLE
Saying we dont use HTTP2 when we do

### ISSUE THREAD

**Issue by Thiploll** [GoogleChrome/lighthouse#6612] opened 2018-11-20 16:29 UTC
#### Provide the steps to reproduce
1. Run LH on: proxyscrape.com

#### What is the current behavior?
It says we arent using http2
#### What is the expected behavior?
We use cloudflare which automatically enables http2 and we also have it enabled on apache, other http2  testing sites say its working fine:  https://http2.pro/check?url=http%3A//proxyscrape.com/

#### Environment Information
* Affected Channels: 
* Lighthouse version: 4.0.0-alpha.0
* Node.js version: /
* Operating System: ubuntu 
we used the new web.dev
**Related issues**

**Comment by patrickhulce** [comment] 2018-11-20 17:56
Thanks for filing @Thiploll! Seems like this is a duplicate of #6539

**Closed by patrickhulce** 2018-11-20 17:56 UTC
