### ISSUE TITLE
Lighthouse 4.2.0 claims site.webmanifest not served via http/2 when all assets are served with that protocol

### ISSUE THREAD

**Issue by tmb-github** [GoogleChrome/lighthouse#8561] opened 2019-04-23 23:26 UTC
OS Windows 8.1
Chrome: Version 74.0.3729.108 (Official Build) (64-bit)
Lighthouse 4.2.0
URL tested: https://ronsanfordproductions.com

HTTP/2 is active for my site, and all assets are being served to the client via that protocol. When loading the page, the Network panel does not show that my site.webmanifest is being fetched at all; it's apparently fetched by Lighthouse when it begins its audit.

However, unlike in previous versions of Chrome or Chrome Canary, Lighthouse in the release of standard Chrome today complains that my autoversioned site.webmanifest (site.20190420160214.webmanifest) is being served via http/1.1, with this report:

Does not use HTTP/2 for all of its resources - 1 request not served via HTTP/2:

URL: https://ronsanfordproductions.com/favicons/site.20190420160214.webmanifest
Protocol: http/1.1

The network tab shows no evidence of the webmanifest file being served during the Lighthouse test, so I cannot determine which protocol was used for fetching it.

Stats:

URL: https://ronsanfordproductions.com/
Fetch time: Apr 23, 2019, 5:49 PM CDT
Device: Emulated Nexus 5X
Network throttling: Provided by environment
CPU throttling: Provided by environment
User agent (host): Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
User agent (network): Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse
CPU/Memory Power: 926

Surely, this is a bug?

**Comment by patrickhulce** [comment] 2019-04-23 23:44
Yes this is a bug, duplicate of https://github.com/GoogleChrome/lighthouse/issues/7158, and should already be fixed in 4.3.0.

**Closed by patrickhulce** 2019-04-23 23:44 UTC
