### ISSUE TITLE
lighthouse audits crash after interacting with "Show audits relevant to" buttons

### ISSUE THREAD

**Issue by jocacadasi** [GoogleChrome/lighthouse#13939] opened 2022-04-28 15:55 UTC
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://anysite.com

### What happened?

After running an audit on ligthhouse, the report crash when we interact with any of the buttons on

Show audits relevant to:

- All 
- FCP
- TBT
- LCP
- CLS

Try to click them several times, and you will see the program going unresponsive. 

The same happens if we download the JSON lighthouse report and then drag the .json file to lighthouse report.

### What did you expect?

I expect lighthouse to work properly.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

Lighthouse 9.4.0

### Chrome Version

Version 100.0.4896.127 (Official Build) (64-bit)

### OS

windows 10

**Comment by adamraine** [comment] 2022-04-28 16:23
https://anysite.com/ isn't loading for me, is the site down at the moment?

**Comment by jocacadasi** [comment] 2022-05-03 10:20
Sorry, any site means, ebay or dell or hp

**Comment by adamraine** [comment] 2022-05-03 16:17
I can't reproduce on PSI with any of those sites either. Like Brendan said, please provide any JSON report that will break our report viewer.

**Comment by adamraine** [comment] 2022-08-23 19:30
Closing for now, we can reopen if you can provide a repro

**Closed by adamraine** 2022-08-23 19:30 UTC
Labels: bug, needs-more-info, needs-priority
