### ISSUE TITLE
Warn that devtools performance trace will not match metrics

### ISSUE THREAD

**Issue by delanotedries** [GoogleChrome/lighthouse#9971] opened 2019-11-14 10:38 UTC
I'm getting very strange results when doing a mobile audit Simulated Slow 4G.
![image](https://user-images.githubusercontent.com/3560936/68849269-0c734080-06d2-11ea-9114-4b8068f13bc2.png)
The report states the FCP is 13.8 seconds.

When I click the view trace to check the performance trace, the FCP is 633.9ms 
![image](https://user-images.githubusercontent.com/3560936/68849550-94594a80-06d2-11ea-8610-426791e16987.png)

When running the Applied Slow 4G audit, the results are actually faster than the Simulated Slow 4G, but they perfectly match the Performance trace:
![image](https://user-images.githubusercontent.com/3560936/68849719-e00bf400-06d2-11ea-9cb0-5d9083dfefa5.png)
![image](https://user-images.githubusercontent.com/3560936/68849790-ff0a8600-06d2-11ea-9843-c0573d4b9e0e.png)

When running the audit without throttling, I get a performance score of 100 and the Performance trace values match the audit report.

I am getting the same result on Pagespeed Insights.
Could this be related to cache?

**Comment by patrickhulce** [comment] 2019-11-14 17:10
Do you have a public URL for us to reproduce? 

I'm guessing that this page has a particularly large root document (MBs not KBs) which is #6867.

**Comment by Lofesa** [comment] 2019-11-15 14:05
Hi @patrickhulce 
I can reproduce this. Chrome 78 LH 5.2 Simulated Slow 4G Performance set at the same options.
In LH I get FCP 1,7s , in Performance 142,1ms. I go to Performance clicking the "View Trace" button.
Seems that both are measuring differents things.

`https://intersindicalrm.org/`

![Captura](https://user-images.githubusercontent.com/22342793/68948620-90075d00-07b8-11ea-9be5-0cf4740b2f98.png)

![Captura1](https://user-images.githubusercontent.com/22342793/68948635-972e6b00-07b8-11ea-84e7-ee91f4441ce0.PNG)

**Comment by patrickhulce** [comment] 2019-11-15 16:32
That FCP timestamp is physically impossible with those throttling settings and the trace looks unthrottled, Fast 3G applies a 500ms *minimum* HTTP RTT. Are you sure you loaded the page *after* changing the settings? This is what I see with those throttling settings on that URL. Subtract the unload handler time and the simulated Lighthouse result is nearly identical.

![image](https://user-images.githubusercontent.com/2301202/68959044-eeb9e000-0792-11ea-9580-aa6da6aa6a68.png)

**Comment by Lofesa** [comment] 2019-11-15 22:04
Hi @patrickhulce 
The step I have done:
1.- Go to Dev Tool performance
2.- Set network and cpu throttling Fast 3G and 4x slowdown
3.- Go to Audits
4.- Set Simulated Slow 4G 4x Slowdown
5.- Run audits for mobile
6.- In Audit Performance, clik on View Trace button, this make go to Dev tools performance
7.- click on FCP label and show time on Summary.

If I clear the Dev Tools Performance w/o touch throttling and make a new record, with a lapse of 8s. the FCP is 2723.6 ms.
So seems that when you click on the View Trace in LH, Dev Tools Performance numbers are similar to when is not throttling.

**Comment by patrickhulce** [comment] 2019-11-15 22:33
> So seems that when you click on the View Trace in LH, Dev Tools Performance numbers are similar to when is not throttling.

Correct when you run with simulated throttling we load the page without throttling and *simulate* what it would have been with throttling. This means that the "View Trace" button will show the unthrottled run.

**Comment by Lofesa** [comment] 2019-11-17 11:51
Hi @patrickhulce @delanotedries 
Well... then the issue is clarified. Maybe a transient solution maybe a note near to the "view trace" button clarifying that the performance result are for unthrottled fecht.

**Comment by delanotedries** [comment] 2019-11-22 10:15
> I'm guessing that this page has a particularly large root document (MBs not KBs) which is #6867.

@patrickhulce this was indeed the case, thx for clarifying.
I agree with @Lofesa that notifying the performance view trace is for an unthrottled fetch would be a good UI improvement for now.

**Comment by patrickhulce** [comment] 2020-08-04 20:26
Plan: View Trace -> View Original Trace + a tooltip that says it's simulated and won't match, uncheck "Simulated throttling" if ya want em to match

**Comment by adamraine** [comment] 2020-08-07 19:58
Working on this over in https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2339861

**Comment by paulirish** [comment] 2020-08-18 19:48
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2339861 was merged

fixed

**Closed by paulirish** 2020-08-18 19:48 UTC
Labels: DevTools, P1

**Comment by paulirish** [comment] 2020-08-18 20:01
Should be in Chrome 86. Hits stable ~ Oct 6th.
