### ISSUE TITLE
Source Map is downloaded during performance audit

### ISSUE THREAD

**Issue by developit** [GoogleChrome/lighthouse#12064] opened 2021-02-08 21:50 UTC
#### Provide the steps to reproduce
1. Run LH on https://preactjs.com
  
#### What is the current behavior?

During the lighthouse Performance audit, Source Map files are downloaded:

https://user-images.githubusercontent.com/105127/107285782-a937a180-6a2d-11eb-8e3a-44a222ecf4ab.mov

#### What is the expected behavior?

No downloads are triggered during Lighthouse execution.

#### Environment Information
* Affected Channels: Extension (did not test others)
* Lighthouse version: 7.0.0
* Chrome version:  89.0.4389.40 (Official Build) beta (x86_64)
* Node.js version: 12.9
* Operating System: MacOS

**Related issues**

https://support.google.com/webmasters/thread/86647663?hl=en

**Comment by paulirish** [comment] 2021-02-08 22:02
Since we're a diagnostic tool, I think it's totally fair for Lighthouse to attempt these downloads. We do it to provide better detail and actionability in the opportunities.

Similarly, chrome devtools makes the same network requests if JS sourcemaps are enabled (the default).


I see the webmasters support thread.... but it's unclear how this is a problem for site owners... perhaps it's unexpected to see them in request logs?

**Comment by patrickhulce** [comment] 2021-02-08 22:22
I think think the issue in the video that's valid is that it prompts Chrome's download UI. DevTools doesn't trigger Chrome's download UI. Probably to do with our weird iframe fetcher?

**Comment by brendankenny** [comment] 2021-02-09 17:04
ah, yeah, I didn't spot that in the video either :) In theory the request should be cancelled and never download:

https://github.com/GoogleChrome/lighthouse/blob/aaf136519ce726e4a0e85cf256de110849fa5a6f/lighthouse-core/gather/fetcher.js#L135-L136

Can't repro in CLI but I can in DevTools.

**Comment by brendankenny** [comment] 2021-02-09 19:58
Since we last discussed protocol support for fetching resources, the protocol method has landed ([`Network.loadNetworkResource`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-loadNetworkResource)), though I believe it still blocks the CORS case. Its options object does optimistically mention it "may be extended later to better support CORS, CORB and streaming", though.

**Comment by paulirish** [comment] 2021-02-09 22:01
> Since we last discussed protocol support for fetching resources, the protocol method has landed ([`Network.loadNetworkResource`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-loadNetworkResource)), though I believe it still blocks the CORS case. Its options object does optimistically mention it "may be extended later to better support CORS, CORB and streaming", though.

i looked into this stuff a bit and filed a new issue: [Improve generalized/sourcemap fetcher #12070](https://github.com/GoogleChrome/lighthouse/issues/12070)

**Comment by paulirish** [comment] 2021-02-09 22:04
I was looking as to why one would use octet-stream as the mimetype for sourcemaps... Looks like [some bozo confirmed it was fine 8 years ago](https://stackoverflow.com/a/19912684/89484).  😳

 But yes unfortunately that mimetype + how lighthouse fetches == a download. We can [change this in Lighthouse](https://github.com/GoogleChrome/lighthouse/issues/12070) but, @developit, in the meantime..  serving sourcemaps as `application/json` would be the workaround.

**Comment by adamraine** [comment] 2021-03-02 00:32
Should we close this in favor of https://github.com/GoogleChrome/lighthouse/issues/12070? The current fetcher is also [incompatible with some CSPs](https://github.com/GoogleChrome/lighthouse/pull/12044#issuecomment-788274938).

Considering there are two issues breaking the current fetcher, we should probably seek a different implementation that uses `Network.loadNetworkResource`.

**Comment by paulirish** [comment] 2021-03-31 20:25
> Should we close this in favor of #12070?

good call. sg

**Closed by paulirish** 2021-03-31 20:25 UTC
Labels: needs-investigation, needs-priority
