### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by fakoua** [GoogleChrome/lighthouse#2748] opened 2017-07-26 19:49 UTC
**Lighthouse Version**: 2.3.0
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://www.qalamoun.org/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14109:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14534:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14559:25)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-07-26 20:42
dupe of #1834

**Closed by patrickhulce** 2017-07-26 20:42 UTC
