### ISSUE TITLE
Google Chrome Audits Always crashes

### ISSUE THREAD

**Issue by rameshguthulakkd** [GoogleChrome/lighthouse#9331] opened 2019-07-07 00:37 UTC
I am trying to us Google chrome Devtool Audits, but when I try to use, it always shows me an error and the Audits are not working. The error message is
"Ah, sorry! We ran into an error. Try to navigate to the URL in a fresh Chrome profile without any other tabs or extensions open and try again". I tried disabling the extensions and new profile, but the error remains same.

OS:- Ubuntu 18.04
Chrome version:- Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by Remexllee** [comment] 2019-07-07 02:12
@rameshguthulakkd 
I suggest you to open an issue in `devtools-frontend` too
https://github.com/ChromeDevTools/devtools-frontend

From your description, the error comes from the code below:
https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/audits/AuditsStatusView.js#L223

**Comment by connorjclark** [comment] 2019-07-08 17:29
> I suggest you to open an issue in devtools-frontend too

We're the same people and this is the right place to post bugs re: Lighthouse in DevTools :)

@rameshguthulakkd please provide a URL.

**Comment by Remexllee** [comment] 2019-07-08 18:11
> We're the same people and this is the right place to post bugs re: Lighthouse in DevTools :)

Thanks for your info. I am thinking this issue may be caused by DevTools without arriving at Lighthouse.
As you labeled here, needs more info to reproduce this issue.

**Comment by hnordberg** [comment] 2019-07-15 18:27
For us it happens for _any local URL_. Non-local sites work fine.
Tested with **Version 75.0.3770.100 (Official Build) (64-bit)** and **Version 77.0.3850.0 (Official Build) canary (64-bit)**

**Comment by hnordberg** [comment] 2019-07-23 17:06
It is now working for me (before I updated Chrome). It would be nice if Lighthouse would log its error to the console or another location that is visible when you run into trouble. This would help when you look for solutions as a user and would presumably help the devs too.

**Comment by nikitas** [comment] 2019-07-24 10:46
Mac os 10.14.3 / Chrome Version 75.0.3770.142 (Official Build) (64-bit)
also having crash on localhost only

**Comment by mattpass** [comment] 2019-07-26 11:41
Found the same - starting an Audit on Mac OS against local sites throws this error up. Runs fine against non local sites.

Extra note: I can start an Audit against local sites on Chrome on Ubuntu fine, it's a Mac specific problem of audits on local hosted site.

**Comment by patrickhulce** [comment] 2019-07-26 14:54
Folks with local issues is there anything specific about your local environment you can share? We run hundreds of tests against localhost servers on Mac everyday without issue, so it's likely something else in the environment that's causing this. 

When you say "crash" are you referring to `Ah, sorry! We ran into an error. Try to navigate to the URL in a fresh Chrome profile without any other tabs or extensions open and try again`?

**Comment by nikitas** [comment] 2019-07-26 15:08
@patrickhulce yes, this error. But I tried in an incognito tab, same result, as well as on different mac computers of colleagues.  local nodejs server on 4001 port

**Comment by patrickhulce** [comment] 2019-07-26 18:39
Thanks @nikitas!

Is there a particular nodejs server you're using? https://webpack.js.org/configuration/dev-server/ perhaps?

**Comment by hnordberg** [comment] 2019-08-03 00:03
@patrickhulce Yup, that's the one. Why? Did you find an issue with it? Is there anyway to tell why lighthouse is failing? (e.g., stack trace)

**Comment by patrickhulce** [comment] 2019-08-03 20:43
It's one of these errors.
![image](https://user-images.githubusercontent.com/2301202/62416689-11b9ed00-b605-11e9-89d1-cb4f233f5f5c.png)

I'm not able to reproduce this with Chrome Canary and just the webpack development server. Is anyone here able to give their page a try with the CLI or extension and report back?

**Comment by hnordberg** [comment] 2019-08-05 20:10
It works for me in Chrome Version 76.0.3809.87 (Official Build) (64-bit). Seems like it would be a good idea to have an option to log errors to the console.

**Comment by mattpass** [comment] 2019-08-09 14:19
Our developer informs me the Lighthouse extension is working fine but not via Audits tab in devtools if this helps in some way.

**Comment by patrickhulce** [comment] 2019-08-09 14:48
@hnordberg they are logged if you inspect the DevTools window itself. i.e. undock DevTools into a separate window and hit `CmdOrCtrl+Alt+I`. Maybe someone could give that a try in DevTools that can reproduce this?

Thanks for the extra info @mattpass!

**Comment by hnordberg** [comment] 2019-08-09 17:24
It was working when I tried it a couple of days ago (as noted above). It is currently not working. Here's the Lighthouse log that I got from inspecting the DevTools window (CmdOrCtrl+Alt+J).

`status Connecting to browser +0ms
10:18:57.491 audits2_worker_module.js:2394 status Resetting state with about:blank +1ms
10:18:57.567 audits2_worker_module.js:2394 status Benchmarking machine +76ms
10:18:58.071 audits2_worker_module.js:2394 status Initializing… +503ms
10:18:58.104 audits2_worker_module.js:2394 status Resetting state with about:blank +34ms
10:18:58.134 audits2_worker_module.js:2394 status Setting up network for the pass trace +30ms
10:18:58.139 audits2_worker_module.js:2394 status Cleaning browser cache +5ms
10:18:58.231 audits2_worker_module.js:2394 status Beginning devtoolsLog and trace +92ms
10:18:58.239 audits2_worker_module.js:2394 status Loading page & waiting for onload +8ms CSSUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility
10:18:58.590 audits2_worker_module.js:2394 status Disconnecting from browser... +351ms
10:18:59.272 audits2_module.js:480 LHError: INSECURE_DOCUMENT_REQUEST
    at eval (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1275:585)
    at Driver._waitForFullyLoaded (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1275:1784)
    at async Driver.gotoURL (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1284:1250)
    at async Function.loadPage (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1328:294)
    at async Function.runPass (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1360:452)
    at async Function.run (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1357:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1862:151)
    at async Function.run (devtools://devtools/remote/serve_file/@111fe1e15d5ced26080a7dc239bcfe70f6c49aad/audits2_worker/audits2_worker_module.js:1854:11)
renderBugReport @ audits2_module.js:480
_startAudit @ audits2_module.js:324
async function (async)
_startAudit @ audits2_module.js:321
dispatchEventToListeners @ shell.js:500
(anonymous) @ audits2_module.js:391
10:18:59.435 shell.js:5219 Cannot find context with specified id
_evaluateGlobal @ shell.js:5219
async function (async)
_evaluateGlobal @ shell.js:5219
evaluate @ shell.js:5214
evaluate @ shell.js:7988
_onEvaluateOnInspectedPage @ shell.js:7904
_onmessage @ shell.js:7956
10:18:59.436 shell.js:7991 Extension server error: Inspector protocol error: Cannot find context with specified id`
That's hard to ready (but easy to copy+paste). Here's a pic: 
![image](https://user-images.githubusercontent.com/1466683/62797178-e1080680-ba8f-11e9-8a39-015ae0c8a209.png)

**Comment by patrickhulce** [comment] 2019-08-09 18:43
Oh @hnordberg that should have been fixed long ago! Is it at least working for you in Chrome Canary?

**Comment by hnordberg** [comment] 2019-08-09 19:13
Yes! Version 78.0.3878.0 (Official Build) canary (64-bit) works against local server.

**Comment by Techassi** [comment] 2019-08-17 12:44
I am using Version `Version 78.0.3886.0` on Canary and if I try to audit via the `Audits` tab the only thing I get is:
![image](https://user-images.githubusercontent.com/16667167/63211862-45187380-c0fd-11e9-8725-3bf716ee29da.png)

This keeps going until I cancel it. There is no audit being started. I can provide some logs if needed.

**Comment by maxbloch** [comment] 2019-08-20 08:33
I was having the same [original](https://github.com/GoogleChrome/lighthouse/issues/9331#issue-464902219) issue as @rameshguthulakkd for a local developement website and it was being caused by an untrusted Let's Encrypt HTTPS/SSL-certificate. Simply adding a security exception was not sufficient and the solution was to import the certificate via Chrome > Settings > Manage Certificates > Autorities > Import.

**Comment by buttflattery** [comment] 2019-08-21 10:53
@maxbloch saved the day, thanks alot.

**Comment by Sanabria** [comment] 2019-08-22 01:39
@maxbloch thank you, this worked for me after a lot of frustration trying other things.

**Comment by mattpass** [comment] 2019-08-22 08:04
Ahhh, this would be the case for us too, we have no SSL cert on localhost testing, thanks @maxbloch.

Still, it's pretty commonplace not to have SSL cert locally for websites you're testing. So still an issue to have fixed in Lighthouse as IMO as it's not clear what the error is plus works fine on other OS's (I'm on Ubuntu and works great, only errors this way on Mac).

At least the problem has been found now! :-)

**Comment by buttflattery** [comment] 2019-08-22 09:54
Guys who are still having problem with the latest chrome on ubuntu they must follow the steps for the config file to be used with a little change and you can get it working on the latest `Version 76.0.3809.100 (Official Build) (64-bit)`

## openssl Configuration

The trick to this whole thing lies in the `openssl.cnf` file. Set up a temporary directory to work in at `~/tmp/ssl` just too keep all these files together. Then, after generating the cert and key files, we’ll move them to where they need to be.

So… make a copy of your main `openssl.cnf` file to work with:

```
cp /etc/ssl/openssl.cnf ~/tmp/ssl/custom-openssl.cnf
```

Now, open the copy of openssl.cnf and add (or uncomment) this line from the `[v3_req]` section of the file:

```
[v3_req]
...
x509_extensions = v3_ca
```
Then, add this section to the end of the `[v3_req] `section:

```
[v3_ca]
...
subjectAltName = @alt_names
[alt_names]
DNS.1 = *.mydomain.dev
DNS.2 = mydomain.dev
```

Now use the following command to generate the certificate 

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mycert.key -out mycert.crt -config custom-openssl.cnf
```

Now once you generate the files successfully update your virtual host with the configurations that are commonly used for providing the certificate file in every other aticle


## Getting Google Chrome To Accept Your Self-Signed Certificate on `Ubuntu 14.* ~ 16.*`

This is done differently on different platforms. I am working on Ubuntu 16.04. If you are using any linux based setup you will need to use the certutil command line tool for this. If you don’t have that command line tool, run this:

```
sudo apt-get install libnss3-tools
```
Now, navigate to your development website in your Google Chrome browser. You will see that the https: part of the URL is all red-X-ed out. Now we want to add our self-signed SSL certificate to Google Chrome so we can trust ourselves and not see the annoying security warnings for our local development.

Here’s what to do:

- click the lock icon with an X,
- choose Certificate Information
- go to Details tab
- Click on Export… (save as a file)

Doesn’t matter what the file name is, but try not to have spaces in the file name, just make note of what the file name is so you can use it in the next command.

The following command will add the certificate (where YOUR_FILE is your exported file):
```
certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n YOUR_FILE -i YOUR_FILE
```

To see if it actually worked, you can list all of your certificates with this command:

```
certutil -d sql:$HOME/.pki/nssdb -L
```

Now, when you go to your site you should see that Google Chrome trusts your self-signed SSL certificate best to relaunch the browser.


## Removing A Certificate

If you need to delete a certificate do the following:
```
certutil -D -d sql:$HOME/.pki/nssdb -n YOUR_FILE
```

where `YOUR_FILE` is the name of your certificate that you recently saved. To see a list of all your certificates and their names use this command:

```
certutil -d sql$HOME/.pki/nssdb -L
```

**Comment by patrickhulce** [comment] 2019-08-22 14:34
@mattpass @buttflattery this *is* fixed in latest Lighthouse and Chrome Canary AFAIK. 

If you're wanting to ignore security errors you'll just need to launch Chrome with `--ignore-certificate-errors` if you're using Lighthouse CLI that means `--chrome-flags='--ignore-certificate-errors'`

**Comment by Techassi** [comment] 2019-08-26 23:20
@maxbloch I can confirm. Adding the certificate resolves the problem. Great hint! 😃

**Comment by jameswilson** [comment] 2019-09-11 01:36
> Do self-signed certs cause this issue too?

Yes. Self-signed certs are affected. I'm getting the INSECURE_DOCUMENT_REQUEST with a self-signed cert on local environment using `mydomain.test` (with an entry in /etc/hosts for this domain) on Mac OS Mojave with Google Chrome Version 76.0.3809.132 (Official Build) (64-bit).

**Comment by peshoicov** [comment] 2020-06-25 11:12
For me the issue was the old version of Google Chrome (at this moment I have 74 and the latest stable is 83). Updating it made the audit work.

**Comment by patrickhulce** [comment] 2020-10-27 21:11
We believe this is fixed in recent Chrome versions. If anyone can reproduce this issue in Chrome 83 or later while using the correct flags referenced in https://github.com/GoogleChrome/lighthouse/issues/9331#issuecomment-523933114 then please feel free to chime in to reopen.

**Closed by patrickhulce** 2020-10-27 21:11 UTC
Labels: needs-priority, pending-close

**Comment by barbaracabralTL** [comment] 2020-11-20 16:43
I'm having this on Chrome 87:
`    "chromedriver": "^87.0.0", "lighthouse": "^6.4.1",    "@lhci/cli": "^0.6.1",`


<img width="952" alt="Captura de Tela 2020-11-20 às 13 41 16" src="https://user-images.githubusercontent.com/61509300/99825674-18d87780-2b36-11eb-9f5d-2e8293f21530.png">
