### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by goyalmunish85** [GoogleChrome/lighthouse#7646] opened 2019-03-23 02:46 UTC
**Initial URL**: http://localhost:8000/
**Chrome Version**: 72.0.3626.96
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by cixtor** [comment] 2019-04-02 01:24
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/1091 and also https://github.com/GoogleChrome/lighthouse/issues/7246

> Tracing is disabled in Debian starting with 72.0.3626.81-1.
> Its implementation relies on many sourceless javascript files.
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922431

**Comment by patrickhulce** [comment] 2019-04-02 02:18
#7246 is indeed the correct duplicate here, Debian ships with partial Chromium. Install real Chrome as a workaround.

**Closed by patrickhulce** 2019-04-02 02:18 UTC
