### ISSUE TITLE
Problem with Auto Ads -[Anchor]

### ISSUE THREAD

**Issue by coolguruji** [GoogleChrome/lighthouse#11004] opened 2020-06-22 14:32 UTC
**Summary**
Hey, I am preparing my site for Core Web Vitals. I am using Adsense for monetizing my site. What i saw when i was fixing my CLS score that is Auto Ads [Anchor ads] solution given by Adsense is increasing my CLS score because it shifts my layout from the top to show sliding ads. 

What is Anchor Ads?
Anchor ads stick to the edge of the user's screen and are easily dismissible. These ads mainly serve on mobile but can appear on desktop too.

They appear at the top of the user's screen unless we determine that this would negatively affect the user experience, in which case we show them at the bottom. When shown at the top, anchor ads only appear after the user has scrolled down far enough, so that they never cover your site's branding or navigation.

What's the issue?
 When you scroll from bottom to top that sliding ads will appear on top of the mobile screen. They just add style="padding: 124px 0px 0px;" in my body tag and this is increasing CLS score. Only that's issue that i cant fix because Adsense ads is dynamically inserting it. 

This issue is happening with all Adsense users because its a kind of setting provided by default from the Adsense team.

Now what we can do?

Thanks

**Comment by patrickhulce** [comment] 2020-06-22 14:43
Thanks for filing @coolguruji! A few clarifying questions for you

> They appear at the top of the user's screen unless we determine that this would negatively affect the user experience

This "we" sounds like it is Adsense and not you, correct? (from https://support.google.com/adsense/answer/9305577?hl=en)

> They just add style="padding: 124px 0px 0px;" in my body tag and this is increasing CLS score. Only that's issue that i cant fix because Adsense ads is dynamically inserting it.

Do I understand the problem correctly that the CLS increase comes from Adsense adding padding to the body tag once it is loaded and *not* from any sort of scroll-related ads? Can you preemptively add the padding in preparation for the ads loading?

**Comment by coolguruji** [comment] 2020-06-24 11:46
1) Yeah that "we" is for Adsense! Actually Algorithm is deciding where to put that Anchor Ads in the bottom or at the top. Most of time its at the top.

2) When page loads on the mobile screen and user scrolls down, at that time that Anchor Ads will appear and i have used Web Vitals Plugin on my Chrome browser to find out this issue because it's field data issue. It cant be traced at Pagespeed because its happening on scrolling down. That advertisement is appearing in that manner.  So basically my Layout is shifting without users action from top around 124px to show that Anchor ads. 

I am using this plugin - https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma
Anchor ads preview - https://youtu.be/-273QPh0g-0?t=71
Open the given youtube link and within few seconds you will see an advertisement at the top of the mobile screen in that video. Then you'll have a better idea.

In my Search Console at Core Web Vitals, Google is reporting me "CLS issue: more than 0.25 (mobile)" Agg CLS is 0.53.

3) That CLS increases after Adsense adding padding to the body tag when user scrolling down. I can add padding on the body tag but it will make my user experience worst because on tiny mobile screen all content will get padded approx 124px from the top. That cant be a solution at all.

This issue will be not happening only with me its a issue for all Page-level Ads user's who is using Anchor ads.

**Comment by patrickhulce** [comment] 2020-06-24 15:34
> it will make my user experience worst because on tiny mobile screen all content will get padded approx 124px from the top. That cant be a solution at all.

If this only happens on scroll, then perhaps animate in the padding as they scroll for a seamless experience.


> I have used Web Vitals Plugin on my Chrome browser to find out this issue because it's field data issue. It cant be traced at Pagespeed because its happening on scrolling from down to top

Ah OK. Sorry to hear that @coolguruji! However, this forum is for issues with Lighthouse. Since this is a field data issue caused by adsense we're not really able to help much here.

Maybe you can try contacting them to get through to the [known issues](https://support.google.com/adsense/answer/1067521?hl=en)?

We're going to close this as there's no action for Lighthouse to take with regard to reporting CLS. Best of luck to you though!

**Closed by patrickhulce** 2020-06-24 15:34 UTC
Labels: needs-more-info, needs-priority, question

**Comment by b21946606** [comment] 2020-11-29 13:08
Hello, @coolguruji i have same issue too. Did you find a solution?

**Comment by micmue70** [comment] 2021-01-29 09:20
Are there any solutions for this problem? We have it, too!

**Comment by b21946606** [comment] 2021-02-05 07:28
@micmue70 Only solution is: just disable them and wait 28 days.

**Comment by imtheu** [comment] 2021-08-15 06:20
Hey, I don't know if this is a bad practice regarding adsense policies, but apparently you can fix the CLS by removing these styles as soon as they are inserted:

```javascript
document.addEventListener("DOMContentLoaded", function() { 
	const body = document.body;
	const observer = new MutationObserver(function (_, observer) {
		body.style.padding = "";
	});
	observer.observe(body, {
		attributes: true,
		attributeFilter: ['style']
	});
});
```

**Comment by MVinhas** [comment] 2023-03-24 17:12
You can simply add this CSS:
```body {
	padding-top:0px !important;
}```

Anchor ad will cut a bit your header, it's only you who can decide if that's worth it.

**Comment by ActualMediaNetwork** [comment] 2025-08-26 13:47
I have the same issue in my site [Actualapp.com](https://www.actualapp.com)

As you can see I have the low score for the CLS. Is the only issue related with the performance that I have and I don't know how to solve it. I have tried a lot of things but always I have the same issue because I don't know how to fix the space for the ads because they are auto. Some ideas? Thanks in advance
