### ISSUE TITLE
Lighthouse 6 - Chrome Developer Tools - Always displays Light House is Warming Up

### ISSUE THREAD

**Issue by Mavrick2020** [GoogleChrome/lighthouse#11369] opened 2020-09-02 13:45 UTC
#### Provide the steps to reproduce
1. Steps to Reproduce 
Go to secure intranet site
login and access a page after login
open chrome developer tool
navigate to lighthouse tab and click on generate report. Chrome developer tools always shows message - Light House is Warming Up.

#### What is the current behavior?
On intranet site it always shows message "Light House is Warming Up". The site requires authentication to access a page.
![image](https://user-images.githubusercontent.com/68216830/91991452-869faf00-ed50-11ea-8fa4-14498bc2fe7b.png)

#### What is the expected behavior?
Lighthouse analysis

#### Environment Information
* Lighthouse version: 6
* Chrome version: 85
* Operating System: Windows 10

**Comment by patrickhulce** [comment] 2020-09-02 15:11
Thanks for filing @Mavrick2020! This is a duplicate of https://github.com/GoogleChrome/lighthouse/issues/9484 which it seems like you've already found. All known workarounds are already documented there, and we'll leave that issue open for a better explanation message.

**Closed by patrickhulce** 2020-09-02 15:11 UTC
Labels: needs-priority
