### ISSUE TITLE
Console stuck at first run on ErrorReporting prompt

### ISSUE THREAD

**Issue by dima-horror** [GoogleChrome/lighthouse#8319] opened 2019-04-16 10:08 UTC
#### Provide the steps to reproduce
1. Run LH on https://example.com

#### What is the current behavior?
Console not response after prompt

> We're constantly trying to improve Lighthouse and its reliability.
> May we anonymously report runtime exceptions to improve the tool over time?  (y/N)

#### What is the expected behavior?
After asking permission of error reporting lighthouse audit will need to continue

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 4.3.0
* Node.js version: v10.13.0
* Operating System: Windows 10 Home

![2019-04-16_12h57_49](https://user-images.githubusercontent.com/13537063/56201022-a7c30b00-6048-11e9-83ed-2bb6830eadc3.gif)

**Comment by patrickhulce** [comment] 2019-04-22 14:49
@wardpeet any chance you'd be able to help repro this on Windows? I can't seem to repro on Mac. The logs not showing up might be Windows-specific.

@dima-horror would you mind sharing your Chrome version and trying with latest Chrome Canary? From the GIF I suspect the root error is with Chrome not moving on rather than any Lighthouse issue. If Chrome opened at all that means LH has already moved on from the runtime exceptions bit.

**Comment by dima-horror** [comment] 2019-05-05 14:36
@patrickhulce , I have the latest version of Chrome.

![2019-05-05_17h24_56](https://user-images.githubusercontent.com/13537063/57195409-c0915300-6f5a-11e9-9748-eb4d8ef1f6d0.png)

I tried to launch with latest Chrome Canary, result is the same.

> _Google Chrome is up to date_
> _Version 76.0.3785.0 (Official Build) canary (64-bit)_

![2019-05-05_17h23_34](https://user-images.githubusercontent.com/13537063/57195438-2978cb00-6f5b-11e9-9c29-835e58b88780.gif)

Note that the problem is only on first LH run. All next launches LH working correctly.

To emulate first run of LH I manually clean configstore of LH.
```js
    const configstore = new Configstore('lighthouse');
    configstore.delete('isErrorReportingEnabled');
```

I think that the problem is with senty-prompt

https://github.com/GoogleChrome/lighthouse/blob/4308d6666e6f3912c9a87e36dfbeb377cf54d2bc/lighthouse-cli/sentry-prompt.js#L63-L78

**Comment by patrickhulce** [comment] 2019-05-05 15:40
Thanks for the extra info and debugging help @dima-horror! 

The reason I'm skeptical this has anything to do with the error reporting is that the line to open Chrome runs *after* that promise has resolved.

https://github.com/GoogleChrome/lighthouse/blob/ec08e7b9375d3cbe38938b95a0dadfd8287d532e/lighthouse-cli/bin.js#L142-L147

vs.

https://github.com/GoogleChrome/lighthouse/blob/ec08e7b9375d3cbe38938b95a0dadfd8287d532e/lighthouse-cli/run.js#L205-L209

Because your screenshot shows Chrome opening, that means we've already moved on from the error reporting code. This behavior is exactly what is observed by the user in #6512 conditions, but I'm not sure what circumstances would lead it to be so reproducible for you. 

I'm still not able to reproduce this behavior on Mac (after clearing the prompt setting) :(

@wardpeet friendly ping to see if you can reproduce this on windows perhaps?

**Comment by brendankenny** [comment] 2019-06-25 23:56
Closing since there hasn't been any movement here, but if you're still seeing a problem please comment and we can reopen.

**Closed by brendankenny** 2019-06-25 23:56 UTC
Labels: needs-more-info
