### ISSUE TITLE
Ligthouse test never completes execution

### ISSUE THREAD

**Issue by oliverfernandez** [GoogleChrome/lighthouse#4615] opened 2018-02-23 19:01 UTC
Site: https://mejorconsalud.com/

Executing Ligthouse test using Chrome plugin, execution never completes, but I use Dev Tools Audits it works

**Comment by patrickhulce** [comment] 2018-02-23 19:05
thanks for reporting @oliverfernandez! this seems to be a dupe of #4258 so we'll go ahead and close this one out.

**Closed by patrickhulce** 2018-02-23 19:05 UTC
Labels: duplicate
