### ISSUE TITLE
feature: Measure a warm load

### ISSUE THREAD

**Issue by kscm** [GoogleChrome/lighthouse#2325] opened 2017-05-21 21:21 UTC
It may be useful to separate performance testing in two:

1) when the web-app is "first run" (before/when Service Worker is registered)
2) repeated run, after Service Worker registration (all resources are cached by the service worker in the first run)

**Comment by paulirish** [comment] 2017-10-12 23:55
closing as dupe of #585

**Closed by paulirish** 2017-10-12 23:55 UTC
Labels: audit, feature, P2
