### ISSUE TITLE
404 in Lighthouse when analyzing site

### ISSUE THREAD

**Issue by nikpage** [GoogleChrome/lighthouse#2391] opened 2017-05-30 13:22 UTC
I ran Lighthouse against uxstrategy.eu. 

A "Debugging Chrome" flag kept blinking and then I got this.

No webpage was found for the web address: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/307c3fbd-92e9-4423-961f-88e853ec0ab6
HTTP ERROR 404

**Comment by ebidel** [comment] 2017-05-30 18:05
I'm not able to repro this. I navigated to uxstrategy.eu, ended up on https://www.uxstrategy.eu/, and ran the 2.0 extension against that URL.

Can you provide reliable steps that reproduce the error?

**Comment by frankludriks** [comment] 2017-08-09 05:17
I got an error the same as @nikpage 

I was using incognito tab at the time though

**Comment by brendankenny** [comment] 2017-09-28 22:33
This is the same as #1177. Basically, Chrome can't open the report in an incognito tab since it's a blob url.

This is fixed by #2734 but we haven't pushed out an extension version with the fix yet.

**Closed by brendankenny** 2017-09-28 22:33 UTC
Labels: pending-close
