### ISSUE TITLE
Issue encountered while performing the SEO audit from the Lighthouse extension!

### ISSUE THREAD

**Issue by AsmaMohd** [GoogleChrome/lighthouse#4467] opened 2018-02-08 08:39 UTC
Hi,

![check](https://user-images.githubusercontent.com/36260045/35963112-22baa71c-0ccd-11e8-9527-b5282a867de5.png)
I am reaching out to you because I was trying to assess the features of a Lighthouse Chrome extension and I want to conduct an SEO audit of my webpage but all in vain. I am unable to see any reports or prompts on my screen after selecting the SEO audit option on the installed chrome extension. 

Please let me know what could be the possible issue and How can I fix it? 

I have attached the screenshot for you to review.

Waiting for your positive response.

Cheers,
Asma.

**Comment by AsmaMohd** [comment] 2018-02-08 08:41
URL: http://zoetalentsolutions.com/hr-courses/

**Comment by tvld** [comment] 2018-02-08 10:28
Seems duplicate of  #4466

**Comment by wardpeet** [comment] 2018-02-08 16:14
closing :) duplicate of #4466

**Closed by wardpeet** 2018-02-08 16:14 UTC
Labels: bug, duplicate, extension
