### ISSUE TITLE
Should icons audit check that icon actually exists?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#684] opened 2016-09-21 20:12 UTC
I noticed that the audit that makes sure the manifest references a 192-pixel icon doesn't actually check if the icon exists in the cache. It just parses the manifest and makes sure that it defines a 192x192 size icon.

**Comment by brendankenny** [comment] 2016-09-22 00:08
@paulirish you mentioned devtools has to do some tricky thing to get these in the application panel. Worth doing?

**Comment by ebidel** [comment] 2017-04-19 15:52
Marking as dupe of https://github.com/GoogleChrome/lighthouse/issues/789.

**Closed by ebidel** 2017-04-19 15:52 UTC
