### ISSUE TITLE
link rel=preload warning, but link exists

### ISSUE THREAD

**Issue by liorg2** [GoogleChrome/lighthouse#6417] opened 2018-10-28 08:18 UTC
i get link rel=preload warning, but link exists in the head section
can you please assist ?

report is attached

analyzed page: https://www.terminalx.com/
version: Lighthouse 3.0.3
generated with chrome developers tools > audit
chrome version: Version 70.0.3538.67 (Official Build) (64-bit)
**REPORT:**

![image](https://user-images.githubusercontent.com/1691647/47613555-0516d000-da9a-11e8-9026-3005432f8681.png)

**source**
![image](https://user-images.githubusercontent.com/1691647/47613567-7787b000-da9a-11e8-92a5-0b0f27305b4e.png)

**full json**
[www.terminalx.com-20181028T100755.json.zip](https://github.com/GoogleChrome/lighthouse/files/2522584/www.terminalx.com-20181028T100755.json.zip)

**Comment by midzer** [comment] 2018-10-28 08:28
Hi @liorg2 
Thanks for your report. Without running LH on your site, I got two (possible relevant) warnings in console:

> The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

> A preload for '<URL>' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

Consider running a more recent LH version as well. If i remember correctly, there has been some changes concerning `rel=preload` lately.

Have a nice day
midzer

**Comment by paulirish** [comment] 2018-12-17 20:36
We need to do https://github.com/GoogleChrome/lighthouse/pull/6694 but for the preload audit. 

The link rel=preload directive should have `crossorigin` in them.
https://www.zachleat.com/web/preload/

**Comment by patrickhulce** [comment] 2018-12-19 14:33
I'm not able to reproduce this specific error, but I've found some interesting things in my investigation.

1. The initiators don't seem to be tracked properly on latest Chrome Canary (#6843). Fonts loaded through a stylesheet show up as being initiated by the root document. This effectively means we shouldn't be able to encounter this case at the moment since all fonts that need `crossorigin` won't be suggested for preload anyway due to an incorrect depth.
2. Our audit skips *URLs* that are already preloaded instead of network request IDs which means I'm actually seeing the opposite occur if I force the issue with a script instead. i.e. when a URL is requested to be preloaded and it isn't being used (so the request is issued a second time) the audit still passes, even though it's double bad for performance!

It's difficult to take action on 2, without taking action on 1. I'll try and track down the last Chrome version where it worked.

**Comment by patrickhulce** [comment] 2019-01-03 16:55
Marking this as closed, #6849 addresses what we can right now and #6843 tracks the remainder.

**Closed by patrickhulce** 2019-01-03 16:55 UTC
Labels: P1, bug
