### ISSUE TITLE
Zero performance on a valid page

### ISSUE THREAD

**Issue by bancer** [GoogleChrome/lighthouse#2928] opened 2017-08-10 10:39 UTC
Running audits on http://dinnerbooking.com results with an empty page and 0 performance
![screenshot from 2017-08-10 12 36 12](https://user-images.githubusercontent.com/3830106/29166909-941197b6-7dc8-11e7-8c8a-a62a8714cf58.png)

Chrome Version 60.0.3112.78 (Official Build) (64-bit)
OS Ubuntu 14.04 LTS

**Comment by ebidel** [comment] 2017-08-10 16:15
I'm not able to reproduce this by running LH in the DevTools. When I hit http://dinnerbooking.com/, I end up on http://dinnerbooking.com/dk/en-US and there aren't any issues auditing that page. 

It's curious that you end up on a different page (google.com/dk/ads...). Do you have any developer or ad blocking extensions that could be getting in the way?

**Comment by patrickhulce** [comment] 2017-08-10 17:14
This is a known issue that due to a race condition, an iframe URL can be audited instead of the intended page. Should be fixed in m61 by https://chromium-review.googlesource.com/c/570921, sorry for the inconvenience @bancer! You can use Chrome Canary, extension, or CLI as a workaround.

**Closed by patrickhulce** 2017-08-10 17:14 UTC

**Comment by bancer** [comment] 2017-08-11 07:26
@patrickhulce 
![screenshot from 2017-08-11 09 25 05](https://user-images.githubusercontent.com/3830106/29204391-010c8318-7e77-11e7-911d-646d9393a0c6.png)
Where can I find instructions on how to run audits from CLI?

**Comment by patrickhulce** [comment] 2017-08-11 17:19
@bancer [README](https://github.com/GoogleChrome/lighthouse#using-the-node-cli) is a pretty good place to start.
