### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by b11n** [GoogleChrome/lighthouse#1983] opened 2017-04-08 15:30 UTC
**Lighthouse Version**: 1.6.0
**Chrome Version**: 57.0.2987.133
**URL**: https://m.redbus.in/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13600:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14685:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14711:18)```

**Comment by ebidel** [comment] 2017-04-08 17:12
dupe of https://github.com/GoogleChrome/lighthouse/issues/1834

**Closed by ebidel** 2017-04-08 17:12 UTC
