### ISSUE TITLE
CLS caused by sticky sidebars

### ISSUE THREAD

**Issue by pacifier007** [GoogleChrome/lighthouse#12243] opened 2021-03-13 17:36 UTC
First of all, sorry I don't know if this is correct place for this. Should I post this to Chrome issues instead or somewhere else? Please let me know.

Almost all the sticky sidebars, done in a smarter way than the naive position: sticky solution, use the trick where they transition from position: absolute to position: fixed and back depending on scroll. However they don't really cause layout shifts.

For example a popular sticky solution here: https://somewebmedia.github.io/hc-sticky/demo_1.html (it's the same with every solution/library out there, but I just found this example first)

You can see that while scrolling whenever they sidebar gets sticky it's staying in the view and causes no real layout shift, yet it's detected as a layout shift. The readability of content isn't affected in any way, and the sidebar content is staying in view without being shifted.

I believe this should get the same treatment is using position: sticky.

**Comment by brendankenny** [comment] 2021-03-23 21:45
Looks like you already found https://github.com/WICG/layout-instability, but that's generally the better place for bugs in how CLS is defined (vs implementations measuring it).

I can confirm this is fixed in Chrome 90+ after the change in http://crrev.com/849650 and no longer registers any layout shifts.

**Closed by brendankenny** 2021-03-23 21:45 UTC
Labels: needs-priority
