### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by cheerly** [GoogleChrome/lighthouse#3391] opened 2017-09-22 04:02 UTC
**Initial URL**: chrome-extension://dbebidibfabmempkkbhabeehoncoaphf/_generated_background_page.html
**Chrome Version**: 61.0.3163.91
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@2f544949507dc5330b714cb017e3f584e791a1bf/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-09-26 22:55
dupe of #2174

**Closed by patrickhulce** 2017-09-26 22:55 UTC
Labels: pending-close
