### ISSUE TITLE
Always switches to mobile phone preview and reports impossibly low performance

### ISSUE THREAD

**Issue by jkavalik** [GoogleChrome/lighthouse#2905] opened 2017-08-09 09:04 UTC
Wanted to check something with devtools->audit and found out it was changed to lighthouse since I last used it. It did not work most of the time ("unable to load page" as reported many times) and when it works, it forces mobile phone emulation and reports wrong times (or slows things down itself) - for example 25s for a localhost load (which works well under a second according to both the Network tab and my perception).

**Comment by ebidel** [comment] 2017-08-09 17:21
There's a related discussion on https://github.com/GoogleChrome/lighthouse/issues/2864.

Not sure which version you were running, but Lighthouse has always emulated a mobile device with a throttled connection.

**Comment by ebidel** [comment] 2017-08-09 17:24
Marking this as a duplicate of https://github.com/GoogleChrome/lighthouse/issues/2838.

**Comment by patrickhulce** [comment] 2017-08-09 17:25
> Not sure which version you were running, but Lighthouse has always emulated a mobile device with a throttled connection.

I believe @jkavalik was referring to the original Audits panel in DevTools, not a prior version of Lighthouse.

**Closed by ebidel** 2017-08-09 17:25 UTC

**Comment by jkavalik** [comment] 2017-08-09 18:36
@ebidel yes, as @patrickhulce noted, it is about Chrome v60 dev tools panel called Audit, sorry for not stating it more precisely.

> ... but Lighthouse has always emulated a mobile device with a throttled connection.

well, nice in theory but thats not what I want from the Audit panel - I wanted it to just analyze with the settings I provide, as the mobile version of the page might be substantially different from the desktop one. It worked that way before Lighthouse integration so I would be glad if it were possible to do that now too. Hope that might get resolved in #2838, thank you.
