### ISSUE TITLE
Does not use HTTP/2 for all of its resources

### ISSUE THREAD

**Issue by dmitriytretyakov** [GoogleChrome/lighthouse#7593] opened 2019-03-20 09:51 UTC
#### Provide the steps to reproduce
1. Run LH on https://sticker.plus/

#### What is the current behavior?

Problem: Does not use HTTP/2 for all of its resources

/manifest.json(sticker.plus) | http/1.1
…icons/icon-144x144.png(sticker.plus) | http/1.1

#### What is the expected behavior?

In network tab this files loaded with h2 protocol, why LH think that is http/1.1?

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 4.0.0
* Operating System: Windows 10

**Comment by patrickhulce** [comment] 2019-03-20 14:38
I believe this is a duplicate of #7158

**Closed** 2019-04-10 14:01 UTC
