### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by petethumped** [GoogleChrome/lighthouse#2689] opened 2017-07-13 22:52 UTC
**Initial URL**: https://thumped.com/music/events/the-jimmy-cake-tough-love-album-launch/
**Chrome Version**: 60.0.3112.50
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@1b8bb7c2c2f4bd3a42ec5a63db827ad9930f2536/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by patrickhulce** [comment] 2017-08-18 21:40
dupe of #1733

**Closed by patrickhulce** 2017-08-18 21:40 UTC
