### ISSUE TITLE
Wrong CLS for a sticky positioned element

### ISSUE THREAD

**Issue by davidramosmrf** [GoogleChrome/lighthouse#11619] opened 2020-11-02 16:21 UTC
#### Provide the steps to reproduce
1. Access to https://6rl03.csb.app/ using https://github.com/GoogleChrome/web-vitals-extension 

#### What is the current behaviour?
The CLS metric is increased by changing the margin-top of a sticky positioned element that doesn't have any visual impact.

#### What is the expected behaviour?
There should be no CLS if there is no Layout Shift.

#### Environment Information
* Affected Channels:  DevTools, web.dev
* Lighthouse version: v6.4.1
* Chrome version: 86.0.4240.111 (Official Build) (x86_64)
* Node.js version:  v12.16.3
* Operating System:  macOS Version 10.15.7 

P.S. I am not sure if this should be considered a Lighthouse or Chrome bug. I appreciate any ideas you could have.

Let me know if you need any other details that I can give you in order to reproduce the error.

Many thanks for your help ✌️

**Comment by patrickhulce** [comment] 2020-11-02 17:00
Thanks for filing @davidramosmrf!

I can't reproduce this in Lighthouse or PSI and given your repro is with another tool, Chromium would likely be the place you want to go to discuss this.

Before you get there though, I'm seeing a different cause than what you described (which also explains why Lighthouse gives 0). The only layout shift I see is coming from an iframe where it looks like the default margin is asynchronously removed (which does shift the layout of its tiny contents, even if those contents aren't yet visible)

![image](https://user-images.githubusercontent.com/2301202/97896185-5e094680-1cfa-11eb-8cd7-0a8f353bd69b.png)

Lighthouse doesn't currently count the layout shift of iframes, and I would expect Chromium to close any issue like this with "working as intended"/wontfix.

**Comment by davidramosmrf** [comment] 2020-11-02 17:14
Thanks for your quick reply @patrickhulce .

I will open an issue to Chromium then, using a static HTML place in a gh-page.

**Comment by davidramosmrf** [comment] 2020-11-02 17:19
Find it [here](https://marfeel.github.io/use-cases/CLS/index.html) in case you can take a look

**Comment by patrickhulce** [comment] 2020-11-02 22:30
@davidramosmrf is there a chance what you're observing falls into [this case](https://chromium.googlesource.com/chromium/src/+/master/docs/speed/metrics_changelog/2020_10_cls.md#problem-in-chrome-86)?

I was testing with Chrome Canary which would've fixed it already.

**Comment by davidramosmrf** [comment] 2020-11-03 08:59
Thanks again for your reply @patrickhulce .

I think it should be related somehow, as we discover recently this issue with CLS. 

We think that this should be fix because it's not correct, but let's see what's the output.

**Comment by davidramosmrf** [comment] 2020-11-06 07:51
HI @patrickhulce, 

Just to let you know, finally they fixed the [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1145078#c10).

**Comment by patrickhulce** [comment] 2020-11-06 15:49
🎉 thanks for improving Chromium @davidramosmrf! :) This means we should pick up the fix as well, so I'll go ahead and close  👍

**Closed by patrickhulce** 2020-11-06 15:49 UTC
Labels: metrics-cwv, needs-priority, pending-close, question
