### ISSUE TITLE
Incorrect Tooltip Information in Audits Tab

### ISSUE THREAD

**Issue by nurul3101** [GoogleChrome/lighthouse#6137] opened 2018-09-28 13:00 UTC
In the device section of Audit tab, there are two options Mobile and Desktop. When you hover over **Desktop** it says *"**Apply mobile emulation during auditing**"* which shouldn't be the case. That message should be specified when hovered over Mobile options only. For Desktop option there should be a different tooltip.

**Comment by patrickhulce** [comment] 2018-09-28 14:30
Thanks for reporting @nurul3101. I believe this is a duplicate of #5747. @paulirish's explanation there is still solid 👍

**Closed by patrickhulce** 2018-09-28 14:30 UTC
