### ISSUE TITLE
GatherRunner:error no document request found

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [GoogleChrome/lighthouse#3816] opened 2017-11-13 08:59 UTC
ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +2ms
  ChromeLauncher Waiting for browser...v +506ms
  status Initializing… +520ms
  status Loading page & waiting for onload URL, Viewport, ViewportDimensions, ThemeColor, Manifest, ChromeConsoleMessage
s, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, Optimiz
edImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL +333ms
  statusEnd Loading page & waiting for onload +11s
  status Retrieving trace +3ms
  status Retrieving devtoolsLog and network records +2s
  status Retrieving: URL +11ms
  status Retrieving: Viewport +1ms
  status Retrieving: ViewportDimensions +4ms
  status Retrieving: ThemeColor +2ms
  status Retrieving: Manifest +1ms
  status Retrieving: ChromeConsoleMessages +1ms
  status Retrieving: ImageUsage +1ms
  status Retrieving: Accessibility +6ms
  status Retrieving: EventListeners +100ms
  status Retrieving: AnchorsWithNoRelNoopener +100ms
  status Retrieving: AppCacheManifest +3ms
  status Retrieving: DOMStats +3ms
  status Retrieving: JSLibraries +5ms
  status Retrieving: OptimizedImages +8ms
  status Retrieving: PasswordInputsWithPreventedPaste +334ms
  status Retrieving: ResponseCompression +2ms
  status Retrieving: TagsBlockingFirstPaint +4ms
  status Retrieving: WebSQL +4ms
  status Loading page & waiting for onload ServiceWorker, Offline, StartUrl +808ms
  statusEnd Loading page & waiting for onload +47ms
  status Retrieving devtoolsLog and network records +6ms
  status Retrieving: ServiceWorker +3ms
  status Retrieving: Offline +2ms
  status Retrieving: StartUrl +13ms
  status Loading page & waiting for onload HTTPRedirect, HTMLWithoutJavaScript +310ms
  Driver:warn Timed out waiting for page load. Moving on... +30s
  statusEnd Loading page & waiting for onload +3ms
  status Retrieving devtoolsLog and network records +1ms
  GatherRunner:error no document request found http://<url>/#/login +1ms
  status Disconnecting from browser... +1ms
  ChromeLauncher Killing Chrome instance 26120 +1ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)

**Comment by JyotiPrakashMallick** [comment] 2017-11-13 09:01
Question is I started my query as PS C:\Users\jmallick> lighthouse https://<url>/#/login --disable-device-emulation --disable-network-throttling
And I gave it is **"https"** but in the error console I can see "GatherRunner:error no document request found **http:///#/login +1ms**". How this redirection happened ?

**Comment by patrickhulce** [comment] 2017-11-13 17:16
@JyotiPrakashMallick this is a duplicate of #1978, so I'm going to go ahead and close this issue.

The problem is that you do not have a server also listening over http. Our bug of failing the run instead of the audit is to be addressed by @brendankenny shortly

**Closed by patrickhulce** 2017-11-13 17:16 UTC
