### ISSUE TITLE
Performance Audit is way off!

### ISSUE THREAD

**Issue by jap777** [GoogleChrome/lighthouse#2864] opened 2017-08-07 16:17 UTC
The performance audit runs at 120% CPU, and then says my website takes 6.5sec to load.  When in reality it's solid at ~465ms.  It makes no sense.

**Comment by ebidel** [comment] 2017-08-07 17:25
Can you provide more information on how you're running Lighthouse? CLI/devtools/extension? What settings? An example report would be useful for us.

Keep in mind that when Lighthouse audits the page, it throttles the CPU and network connection to emulate a nexus 5x device. So your perf numbers will be worse than loading the page directly in the browser.

**Comment by noahbenham** [comment] 2017-08-07 17:39
Are there any plans to allow other device type emulation during audits? We're not targeting nexus 5x devices; would be nice to have an audit more applicable to our target devices.

**Comment by patrickhulce** [comment] 2017-08-07 18:01
@noahbenham you can use the CLI with the `--disable-cpu-throttling --disable-network-throttling --disable-device-emulation` flags if you're only concerned with desktop performance.

You can find the settings we use for emulation here (https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/emulation.js)

**Comment by jap777** [comment] 2017-08-07 18:26
Thanks for the quick turnaround!  :-)

I’m running devtools in Chrome 60.0.3112.78  (Fedora 26)

I’m in development running gulp-connect-php as the webserver.  I also ran it with the testing apache web server, but with similar results.  

Settings?  I don’t see a means to tweak anything with the audits.  

I primarily run aria audits, but after my chrome upgrade, I thought I’d try a performance audit.  

Someone just mentioned the use of emulating a Nexus 5.  Are not sensible performance techniques pertinent to all devices?  So, I too wonder about pretending we’re a handheld device, when my audience is very clearly desktop and handheld use would be <5%??

Also for me both DEV and TEST environments are not compressed, but production will incorporate these things.  The time to fix performance issues would be now I suspect.

Another odd thing: During audits, (all of them actually), my backend’s app-sensor detects tampering of the input and clobbers the session which forces the UI to do likewise.  I can only get audits on the login page.  That’s not the most helpful.  ;-)

Anyway, I don’t want to sound overly critical.  I like what you’ve done with the tools.  They look nicer, they seem like they’re more in-depth.  

-Joseph

**Comment by ebidel** [comment] 2017-08-08 21:24
One of the goals of Lighthouse is to make sure sites are prioritizing mobile performance. We've intentionally set the emulation settings to mimic a mobile device on a reasonable 3g connection. If your performance numbers are good on mobile, they'll be even better on desktop :) Your users will be happy.

Marking this as a dupe of https://github.com/GoogleChrome/lighthouse/issues/2838 (ability to customize throttling settings).

**Closed by ebidel** 2017-08-08 21:24 UTC
