### ISSUE TITLE
Enable running lighthouse on device via chrome://inspect.

### ISSUE THREAD

**Issue by tdresser** [GoogleChrome/lighthouse#6667] opened 2018-11-27 16:21 UTC
If I connect devtools to a tab via chrome://inspect, and then try to use the audits tab, it doesn't work.
I should be able to run lighthouse audits on device in this context.

**Comment by brendankenny** [comment] 2019-06-26 00:06
Duplicate of #4212

since that one has nice screenshots

**Closed by brendankenny** 2019-06-26 00:06 UTC
Labels: P1.5
