### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by orfeu-negro** [GoogleChrome/lighthouse#2884] opened 2017-08-08 16:17 UTC
**Lighthouse Version**: 2.3.0
**Chrome Version**: 60.0.3112.90
**Initial URL**: https://developers.google.com/web/tools/lighthouse/
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:9907:25)
    at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
    at handleResponse (extensions::sendRequest:67:7)
```

**Comment by ebidel** [comment] 2017-08-08 18:46
Dupe of https://github.com/GoogleChrome/lighthouse/issues/1091

**Closed by ebidel** 2017-08-08 18:46 UTC
