### ISSUE TITLE
Byte-efficiency audits can dominate the opportunities but have small impact on metrics

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3558] opened 2017-10-14 04:51 UTC
Relevant reddit comment: https://www.reddit.com/r/webdev/comments/75w7t0/so_exactly_what_do_i_do_google_put_my_css_in_js/doax8ub/

Our image optimization items can end up topping the opportunities section, but they may not have a big impact on FCP/FMP. 

Perhaps we can downplay their significance if their impact is later in the load..

**Comment by patrickhulce** [comment] 2017-10-16 15:55
My preference here would be to re-orient the time savings around the predictive perf models. There are plenty of cases where lazy loading offscreen images like in the post actually doesn't do anything at all since there's nothing after them that needed network bandwidth.

**Comment by patrickhulce** [comment] 2017-11-01 20:07
Let's mark this as a dupe of #3618, sg @paulirish?

**Closed** 2018-03-08 23:40 UTC
Labels: duplicate, pending-close
