### ISSUE TITLE
Runtime Settings

### ISSUE THREAD

**Issue by maurocarrero** [GoogleChrome/lighthouse#2761] opened 2017-07-27 13:16 UTC
First of all, thanks for this great tool.
What I am trying to achieve is to emulate the same **Throttling configuration** from Dev Tools' Network Tab into the Lighthouse **Runtime Settings** in order to understand how measures as Finish, DOMContentLoad, Load, Requests, relates with Lighthouse results and combine information in order to have a stable first measurement (as a starting point for further optimizations).

So, from **Lighthouse**:
``` 
Network Throttling 562.5ms RTT, 1.4Mbps down, 0.7Mbps up: Enabled
CPU Throttling 4x slowdown: Enabled
```
I can configure custom **Network Conditions** from Chrome Dev Tools, but instead of RTT value, I can set there a Latency value, and cannot set a CPU slowdown (this can be done from Performance tab though), furthermore Chrome Canary provides less detailed Throttling configurations (Fast 3G, Slow 3G, etc.).

Wrapping up, my idea is to have the same runtime configuration in every measurement feature.
I suspect that this could be configurable somewhere, but cannot find it.
Does this make sense? Thanks.

**Comment by ebidel** [comment] 2017-08-08 21:25
Not sure I completely follow the request. Perhaps this is a dupe of https://github.com/GoogleChrome/lighthouse/issues/2838? Being able to customize the runtime settings for a lighthouse run?

**Comment by maurocarrero** [comment] 2017-08-09 12:56
Sure, that issue summarizes better what I clumsily tried to explain, will follow that instead. Thanks.

**Closed** 2017-08-09 14:51 UTC
Labels: feature, question
